define({
  "common": {
    "apply": "Į_Apply___š",
    "ok": "Gerai",
    "cancel": "Atšaukti",
    "yes": "Į_Yes__š",
    "no": "Į_No__š",
    "next": "Kitas",
    "back": "Atgal",
    "selected": "Į_selected___š",
    "name": "Pavadinimas",
    "usage": "Į_Usage___š",
    "settings": "Į_Settings___š",
    "home": "Į_Home__š",
    "link": "Į_Link__š",
    "messages": "Į_Messages___š",
    "outputs": "Į_Outputs___š",
    "title": "Pavadinimas",
    "thumbnail": "Į_Thumbnail____š",
    "url": "Į_URL__š",
    "actions": "Veiksmai",
    "layer": "Sluoksnis",
    "action": "Į_Action___š",
    "input": "Į_Input___š",
    "output": "Į_Output___š",
    "type": "Į_Type__š",
    "required": "Į_Required___š",
    "options": "Į_Options___š",
    "label": "Žymė",
    "tooltip": "Į_Tooltip___š",
    "visible": "Į_Visible___š",
    "symbol": "Į_Symbol___š",
    "popup": "Į_Popup___š",
    "upload": "Į_Upload___š",
    "execute": "Į_Execute___š",
    "help": "Į_Help__š",
    "executing": "Į_Executing____š",
    "clear": "Valyti",
    "error": "Į_Error___š",
    "zoomTo": "Parodyti visą",
    "attribute": "Į_Attribute____š",
    "exports": "Į_Export___š",
    "check": "Į_Check___š",
    "save": "Į_Save__š",
    "close": "Į_Close___š",
    "deleteText": "Į_Delete___š",
    "map": "Žemėlapis",
    "scene": "Į_Scene___š",
    "reset": "Į_Reset___š",
    "icon": "Į_Icon__š",
    "share": "Į_Share___š"
  },
  "errorCode": "Kodas",
  "errorMessage": "Pranešimas",
  "errorDetail": "Išsamiau",
  "widgetPlaceholderTooltip": "Norėdami nustatyti, eikite į valdiklių dalį ir spustelėkite atitinkamą vietą",
  "fieldStatistics": {
    "statistics": "Į_Statistics____š",
    "field": "Laukas",
    "count": "Į_Number of Values______š",
    "sum": "Į_Sum of Values_____š",
    "min": "Į_Minimum___š",
    "max": "Į_Maximum___š",
    "ave": "Į_Average___š",
    "stddev": "Į_Standard Deviation______š"
  },
  "symbolChooser": {
    "preview": "Peržiūra",
    "basic": "Bazinis",
    "arrows": "Rodyklės",
    "business": "Verslas",
    "cartographic": "Kartografijos",
    "nationalParkService": "Nacionalinių parkų tarnyba",
    "outdoorRecreation": "Pramogos lauke",
    "peoplePlaces": "Žmonių susibūrimo vietos",
    "safetyHealth": "Sauga ir sveikata",
    "shapes": "Formos",
    "transportation": "Transportas",
    "symbolSize": "Simbolio dydis",
    "color": "Spalva",
    "alpha": "Alfa",
    "outlineColor": "Kontūro spalva",
    "outlineWidth": "Kontūro plotis",
    "style": "Stilius",
    "width": "Plotis",
    "text": "Tekstas",
    "fontColor": "Šrifto spalva",
    "fontSize": "Šrifto dydis",
    "transparency": "Permatomumas",
    "solid": "Vientisas",
    "dash": "Brūkšnys",
    "dot": "Taškas",
    "dashDot": "Brūkšnys taškas",
    "dashDotDot": "Brūkšnys taškas taškas"
  },
  "transparency": {
    "opaque": "Nepermatomas",
    "transparent": "Permatomas"
  },
  "rendererChooser": {
    "domain": "Domenas",
    "use": "Naudoti",
    "singleSymbol": "Vieną simbolį",
    "uniqueSymbol": "Skirtingus simbolius",
    "color": "Spalva",
    "size": "Dydis",
    "toShow": "Rodyti",
    "colors": "Spalvos",
    "classes": "Klasės",
    "symbolSize": "Simbolio dydis",
    "addValue": "Pridėti reikšmę",
    "setDefaultSymbol": "Nustatyti numatytąjį simbolį",
    "defaultSymbol": "Numatytasis simbolis",
    "selectedSymbol": "Pasirinktas simbolis",
    "value": "Reikšmė",
    "label": "Į_Label___š",
    "range": "Intervalas"
  },
  "drawBox": {
    "point": "Taškas",
    "line": "Linija",
    "polyline": "Kreivė",
    "freehandPolyline": "Laisvai piešiama kreivė",
    "triangle": "Trikampis",
    "extent": "Aprėptis",
    "circle": "Apskritimas",
    "ellipse": "Elipsė",
    "polygon": "Poligonas",
    "freehandPolygon": "Laisvai piešiamas poligonas",
    "text": "Tekstas",
    "clear": "Į_Clear___š"
  },
  "popupConfig": {
    "title": "Į_Title___š",
    "add": "Pridėti",
    "fields": "Laukai",
    "noField": "Lauko nėra",
    "visibility": "Matoma",
    "name": "Į_Name__š",
    "alias": "Pseudonimas",
    "actions": "Į_Actions___š"
  },
  "includeButton": {
    "include": "Įtraukti"
  },
  "loadingShelter": {
    "loading": "Kraunama"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Paslaugų nerasta.",
    "unableConnectTo": "Nepavyksta prisijungti prie",
    "invalidUrlTip": "URL, kurį nurodėte yra arba neteisingas, arba nepasiekiamas."
  },
  "serviceBrowser": {
    "noGpFound": "Geoduomenų apdorojimo paslaugų nerasta.",
    "unableConnectTo": "Nepavyksta prisijungti prie"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Žemėlapių paslaugų arba elementų paslaugų nerasta.",
    "unableConnectTo": "Nepavyksta prisijungti prie"
  },
  "basicServiceChooser": {
    "validate": "Tikrinti",
    "example": "Pavyzdys",
    "set": "Grupė"
  },
  "urlInput": {
    "invalidUrl": "Neleistinas URL."
  },
  "urlComboBox": {
    "invalidUrl": "Neleistinas URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Pridėti filtro sąlygą",
    "addSet": "Pridėti išraiškų rinkinį",
    "matchMsg": "Gauti elementus sluoksnyje, kurie atitinka šias sąlygas: ${any_or_all}",
    "matchMsgSet": "${any_or_all} iš grupėje esančių sąlygų yra teisinga (-os)",
    "all": "Viskas",
    "any": "Bet kuri",
    "value": "Reikšmė",
    "field": "Į_Field___š",
    "unique": "Unikalios",
    "none": "Nėra",
    "and": "ir",
    "valueTooltip": "Įveskite reikšmę",
    "fieldTooltip": "Pasirinkite iš esamo lauko",
    "uniqueValueTooltip": "Pažymėtame lauke pasirinkite unikalias reikšmes",
    "stringOperatorIs": "yra",
    "stringOperatorIsNot": "nėra",
    "stringOperatorStartsWith": "prasideda su",
    "stringOperatorEndsWith": "baigiasi su",
    "stringOperatorContains": "įraše yra",
    "stringOperatorDoesNotContain": "įraše nėra",
    "stringOperatorIsBlank": "yra tuščias",
    "stringOperatorIsNotBlank": "nėra tuščias",
    "dateOperatorIsOn": "yra ant",
    "dateOperatorIsNotOn": "yra ne ant",
    "dateOperatorIsBefore": "yra prieš",
    "dateOperatorIsAfter": "yra po",
    "dateOperatorDays": "dienos",
    "dateOperatorWeeks": "savaitės",
    "dateOperatorMonths": "mėnesiai",
    "dateOperatorInTheLast": "yra paskutinis",
    "dateOperatorNotInTheLast": "nėra paskutinis",
    "dateOperatorIsBetween": "yra tarp",
    "dateOperatorIsNotBetween": "nėra tarp",
    "dateOperatorIsBlank": "yra tuščias",
    "dateOperatorIsNotBlank": "nėra tuščias",
    "numberOperatorIs": "yra",
    "numberOperatorIsNot": "nėra",
    "numberOperatorIsAtLeast": "yra mažiausia (bent)",
    "numberOperatorIsLessThan": "yra mažiau nei",
    "numberOperatorIsAtMost": "yra daugiausia",
    "numberOperatorIsGreaterThan": "yra daugiau nei",
    "numberOperatorIsBetween": "yra tarp",
    "numberOperatorIsNotBetween": "nėra tarp",
    "numberOperatorIsBlank": "yra tuščias",
    "numberOperatorIsNotBlank": "nėra tuščias",
    "string": "Eilutė",
    "number": "Skaičius",
    "date": "Data",
    "askForValues": "Klausti reikšmių",
    "prompt": "Įveskite",
    "hint": "Užuomina",
    "error": {
      "invalidParams": "Neleistini parametrai.",
      "invalidUrl": "Neleistinas URL.",
      "noFilterFields": "Sluoksnyje nėra laukų, kurie gali būti naudojami filtravimui.",
      "invalidSQL": "Neleistina SQL sąlyga.",
      "cantParseSQL": "Nepavyksta išanalizuoti SQL sąlygos."
    },
    "caseSensitive": "Didžiosios ir mažosios raidės skirtingos",
    "notSupportCaseSensitiveTip": "Patalpintos paslaugos nepalaiko užklausos, kurioje skiriamos didžiosios ir mažosios raidės."
  },
  "featureLayerSource": {
    "layer": "Sluoksnis",
    "browse": "Parinkti",
    "selectFromMap": "Pasirinkti iš žemėlapio",
    "selectFromPortal": "Pridėti iš Portal for ArcGIS",
    "addServiceUrl": "Pridėti paslaugos URL",
    "inputLayerUrl": "Įvesties sluoksnio URL",
    "selectLayer": "Pasirinkite elementų sluoksnį iš dabartinio žemėlapio.",
    "chooseItem": "Pasirinkite elementų sluoksnio elementą.",
    "setServiceUrl": "Įveskite elementų paslaugos arba žemėlapių paslaugos URL.",
    "selectFromOnline": "Pridėti iš ArcGIS Online",
    "chooseLayer": "Pasirinkite elementų sluoksnį."
  },
  "queryableLayerSource": {
    "layer": "Į_Layer___š",
    "browse": "Parinkti",
    "selectFromMap": "Pasirinkti iš žemėlapio",
    "selectFromPortal": "Pridėti iš Portal for ArcGIS",
    "addServiceUrl": "Pridėti paslaugos URL",
    "inputLayerUrl": "Įvesties sluoksnio URL",
    "selectLayer": "Pasirinkite sluoksnį iš esamo žemėlapio.",
    "chooseItem": "Pasirinkite elementą.",
    "setServiceUrl": "Įveskite paslaugos URL.",
    "selectFromOnline": "Pridėti iš ArcGIS Online",
    "chooseLayer": "Pasirinkite sluoksnį."
  },
  "gpSource": {
    "selectFromPortal": "Pridėti iš Portal for ArcGIS",
    "addServiceUrl": "Pridėti paslaugos URL",
    "selectFromOnline": "Pridėti iš ArcGIS Online",
    "setServiceUrl": "Įveskite geoduomenų apdorojimo paslaugos URL.",
    "chooseItem": "Pasirinkite geoduomenų apdorojimo paslaugos elementą.",
    "chooseTask": "Pasirinkite geoduomenų apdorojimo užduotį."
  },
  "itemSelector": {
    "map": "Į_Map__š",
    "selectWebMap": "Pasirinkti žemėlapį",
    "addMapFromOnlineOrPortal": "ArcGIS Online viešuosiuose ištekliuose arba privačiame turinyje, esančiame ArcGIS Online arba Portal, raskite ir pridėkite aplikacijoje interneto žemėlapį.",
    "searchMapName": "Ieškoti pagal žemėlapio pavadinimą...",
    "searchNone": "Nepavyko rasti jūsų ieškomo elemento. Bandykite dar kartą.",
    "groups": "Grupės",
    "noneGroups": "Grupių nėra",
    "signInTip": "Baigėsi prisijungimo laikas, atnaujinkite naršyklės langą, kad vėl prisijungtumėte prie portalo.",
    "signIn": "Prisijunkite",
    "publicMap": "Vieša",
    "myOrganization": "Organizacija",
    "myGroup": "Mano Grupės",
    "myContent": "Turinys",
    "count": "Į_Count___š",
    "fromPortal": "iš portalo",
    "fromOnline": "iš ArcGIS.com",
    "noneThumbnail": "Miniatiūros nėra",
    "owner": "savininkas",
    "signInTo": "Prisijungti į",
    "lastModified": "Pakeitimo data",
    "moreDetails": "Išsamiau"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Paslauga nepalaiko užklausos."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Žemėlapyje tinkamų sluoksnių nėra."
  },
  "layerInfosMenu": {
    "titleBasemap": "Pagrindo žemėlapiai",
    "titleLayers": "Darbiniai sluoksniai",
    "labelLayer": "Sluoksnio pavadinimas",
    "itemZoomTo": "Parodyti visą",
    "itemTransparency": "Permatomumas",
    "itemTransparent": "Permatomas",
    "itemOpaque": "Nepermatomas",
    "itemMoveUp": "Pakelti aukštyn",
    "itemMoveDown": "Nuleisti žemyn",
    "itemDesc": "Aprašas",
    "itemDownload": "Atsiųsti",
    "itemToAttributeTable": "Atidaryti atributų lentelę"
  },
  "imageChooser": {
    "unsupportReaderAPI": "UŽDUOTIS: naršyklė nepalaiko failo skaitytuvo API",
    "readError": "Nepavyko nuskaityti failo.",
    "unknowError": "nepavyko įvykdyti operacijų",
    "invalidType": "Neleistinas failo tipas.",
    "cropImage": "Į_Crop Image____š",
    "exceed": "Failo dydis negali viršyti 1024 KB",
    "enableFlash": "UŽDUOTIS: įjunkite „flash“.",
    "cropWaining": "Pasirinkite bent ${width} x ${height} pikselių dydžio nuotrauką.",
    "toolTip": "Geriausiam rezultatui naudokite paveikslėlį, kuris būtų ${width} piks. pločio ${height} piks. ilgio. Kitų išmatavimų paveikslėliai talpinimo metu bus automatiškai pakoreguoti. Tinkami paveikslėlių formatai: PNG, GIF ir JPEG."
  },
  "simpleTable": {
    "moveUp": "Pakelti aukštyn",
    "moveDown": "Nuleisti žemyn",
    "deleteRow": "Ištrinti",
    "edit": "Redaguoti"
  },
  "urlParams": {
    "invalidToken": "Netinkamas prieigos raktas",
    "validateTokenError": "Netinkamas prieigos raktas arba tinklo klaida"
  },
  "exportTo": {
    "exportTo": "Eksportuoti",
    "toCSV": "Eksportuoti į CSV formato failą",
    "toFeatureCollection": "Eksportuoti į elementų rinkinį",
    "toGeoJSON": "Eksportuoti į GeoJSON"
  },
  "appState": {
    "title": "Į_App State____š",
    "restoreMap": "Spustelėkite, kad atkurtumėte naudotą žemėlapio aprėptį ir matomus sluoksnius"
  },
  "featureActions": {
    "ZoomTo": "Į_Zoom to___š",
    "PanTo": "Į_Pan to___š",
    "Flash": "Į_Flash___š",
    "ShowPopup": "Į_Show Pop-up____š",
    "CreateLayer": "Į_Create Layer_____š",
    "ShowStatistics": "Į_Statistics_____š...",
    "ClearSelection": "Į_Clear Selection______š",
    "ExportToCSV": "Į_Export to CSV file______š",
    "ExportToFeatureCollection": "Į_Export to Feature Collection_________š",
    "ExportToGeoJSON": "Į_Export to GeoJSON______š"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Į_Related layer_____š",
    "selectedFeatures": "Į_Selected features______š",
    "drawShapesTip": "Į_Draw shapes to select features__________š",
    "pleaseDrawShapesTip": "Į_Please draw shapes to select features____________š",
    "allFeaturesTip": "Į_All features in the layer_________š",
    "selectFeaturesOrDrawShapesTip": "Į_Please use selected features in this layer or draw shapes on map to limit features__________________________š."
  },
  "searchDistance": {
    "applySearchDistance": "Į_Apply a search distance________š",
    "applySearchDistanceToFeatures": "Į_Apply a search distance to selected features______________š"
  },
  "units": {
    "miles": "Į_Miles___š",
    "kilometers": "Į_Kilometers____š",
    "feet": "Į_Feet__š",
    "meters": "Į_Meters___š",
    "yards": "Į_Yards___š",
    "nauticalMiles": "Į_Nautical Miles_____š"
  },
  "featureSetChooser": {
    "select": "Į_Select___š",
    "dragBox": "Į_Drag__š",
    "dragMouse": "Į_Darg the mouse_____š",
    "selectByRectangle": "Į_Select By Rectangle_______š",
    "selectFeaturesTip": "Į_Select features by dragging box around them on map________________š",
    "newSelectionTip": "Į_Create a new selection________š",
    "addSelectionTip": "Į_Add to the current selection_________š",
    "removeSelectionTip": "Į_Remove from the current selection___________š",
    "selectFromCurrentSelectionTip": "Į_Select from the current selection___________š",
    "unselectAllSelectionTip": "Į_Unselect all currently selected features_____________š"
  },
  "widgetManager": {
    "createWidgetError": "Į_Create widget error_______š",
    "createWidgetSettingPageError": "Į_Create widget setting page error___________š",
    "loadWidgetResourceError": "Į_Load widget resouce error_________š"
  },
  "shareOptions": {
    "shareMap": "Į_Choose who can view this app_________š",
    "shareMapTips": "Į_Your map is currentlt shared with these people_______________š",
    "everyone": "Į_everyone___š",
    "theseGroups": "Į_theseGroups____š"
  },
  "shareLink": {
    "email": "Į_email___š",
    "shareEmail": "Į_Email___š",
    "facebook": "Į_facebook___š",
    "shareFacebook": "Į_Facebook___š",
    "twitter": "Į_twitter___š",
    "shareTwitter": "Į_Twitter___š",
    "googlePlus": "Į_googlePlus____š",
    "shareGooglePlus": "Į_GooglePlus____š",
    "EmbedTips": "Į_Embed this scene in a website__________š",
    "shareEmailTxt1": "Į_Have a look at this Web Scene__________š:",
    "shareEmailTxt2": "Į_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________š.",
    "smallSize": "Į_Small___š",
    "mediumSize": "Į_Medium___š",
    "largeSize": "Į_Large___š",
    "customSize": "Į_Custom___š",
    "embed": "Į_Embed this scene in a website__________š",
    "more": "Į_Embed Options_____š",
    "changeShareSettings": "Į_Change Share Settings_______š",
    "shareLinkText": "Į_Choose who can view Copy________š",
    "linkOptions": "Į_Link Options_____š",
    "linkOptionsUrlParameters": "Į_Select URL parameters included in the link______________š",
    "currentMapExtent": "Į_Current map extent______š",
    "chooseCenterWithLevel": "Į_Click the map to define the center of the map with scale level____________________š",
    "chooseCenterWithScale": "Į_Click the map to define the center of the map with map scale___________________š",
    "findLocation": "Į_Find the location or feature and zoom to it______________š",
    "findLocation_inputPlaceholder": "Į_Your place or feature_______š",
    "queryFeature": "Į_Query a feature and zoom to it__________š",
    "addMarker": "Į_Add a marker on the map________š",
    "addMarker_titlePlaceholder": "Į_Title of the marker pop-up_________š",
    "addMarker_symbolURL": "Į_Marker symbol URL______š",
    "addMarker_label": "Į_Marker label_____š",
    "overwirteMobileLayout": "Į_Overwrite default mobile layout__________š",
    "language": "Į_Set the app language_______š",
    "auth": "Į_Authenticate a user automatically___________š",
    "linkPreview": "Į_Link Preview_____š",
    "useShortenLink": "Į_Short Link____š",
    "shareMapUrlExtent": "Į_shareMapUrlExtent______š"
  },
  "webSceneLoader": {
    "webglSupportTip": "Į_3D web apps aren't supported in your browser_______________š."
  }
});