define({
  "common": {
    "apply": "Ř_Apply___ů",
    "ok": "OK",
    "cancel": "Storno",
    "yes": "Ř_Yes__ů",
    "no": "Ř_No__ů",
    "next": "Další",
    "back": "Zpět",
    "selected": "Ř_selected___ů",
    "name": "Název",
    "usage": "Ř_Usage___ů",
    "settings": "Ř_Settings___ů",
    "home": "Ř_Home__ů",
    "link": "Ř_Link__ů",
    "messages": "Ř_Messages___ů",
    "outputs": "Ř_Outputs___ů",
    "title": "Nadpis",
    "thumbnail": "Ř_Thumbnail____ů",
    "url": "Ř_URL__ů",
    "actions": "Akce",
    "layer": "Vrstva",
    "action": "Ř_Action___ů",
    "input": "Ř_Input___ů",
    "output": "Ř_Output___ů",
    "type": "Ř_Type__ů",
    "required": "Ř_Required___ů",
    "options": "Ř_Options___ů",
    "label": "Štítek",
    "tooltip": "Ř_Tooltip___ů",
    "visible": "Ř_Visible___ů",
    "symbol": "Ř_Symbol___ů",
    "popup": "Ř_Popup___ů",
    "upload": "Ř_Upload___ů",
    "execute": "Ř_Execute___ů",
    "help": "Ř_Help__ů",
    "executing": "Ř_Executing____ů",
    "clear": "Vyprázdnit",
    "error": "Ř_Error___ů",
    "zoomTo": "Zaostřit",
    "attribute": "Ř_Attribute____ů",
    "exports": "Ř_Export___ů",
    "check": "Ř_Check___ů",
    "save": "Ř_Save__ů",
    "close": "Ř_Close___ů",
    "deleteText": "Ř_Delete___ů",
    "map": "Mapa",
    "scene": "Ř_Scene___ů",
    "reset": "Ř_Reset___ů",
    "icon": "Ř_Icon__ů",
    "share": "Ř_Share___ů"
  },
  "errorCode": "Kód",
  "errorMessage": "Zpráva",
  "errorDetail": "Podrobnosti",
  "widgetPlaceholderTooltip": "Chcete-li jej nastavit, přejděte do nabídky Widgety a klikněte na odpovídající zástupný znak.",
  "fieldStatistics": {
    "statistics": "Ř_Statistics____ů",
    "field": "Pole",
    "count": "Ř_Number of Values______ů",
    "sum": "Ř_Sum of Values_____ů",
    "min": "Ř_Minimum___ů",
    "max": "Ř_Maximum___ů",
    "ave": "Ř_Average___ů",
    "stddev": "Ř_Standard Deviation______ů"
  },
  "symbolChooser": {
    "preview": "Náhled",
    "basic": "Základní",
    "arrows": "Šipky",
    "business": "Obchod",
    "cartographic": "Kartografický",
    "nationalParkService": "úřad National Park Service",
    "outdoorRecreation": "Rekreace ve volné přírodě",
    "peoplePlaces": "Lidé a místa",
    "safetyHealth": "Bezpečnost a zdraví",
    "shapes": "Tvary",
    "transportation": "Doprava",
    "symbolSize": "Velikost symbolu",
    "color": "Barva",
    "alpha": "Alfa",
    "outlineColor": "Barva obrysu",
    "outlineWidth": "Šířka obrysu",
    "style": "Styl",
    "width": "Šířka",
    "text": "Text",
    "fontColor": "Barva písma",
    "fontSize": "Velikost písma",
    "transparency": "Průhlednost",
    "solid": "Plná",
    "dash": "Přerušovaná",
    "dot": "Tečkovaná",
    "dashDot": "Čerchovaná",
    "dashDotDot": "Dvojčerchovaná"
  },
  "transparency": {
    "opaque": "Neprůhledná",
    "transparent": "Průhledná"
  },
  "rendererChooser": {
    "domain": "Doména",
    "use": "Použít",
    "singleSymbol": "Jeden symbol",
    "uniqueSymbol": "Unikátní symboly",
    "color": "Barva",
    "size": "Velikost",
    "toShow": "Zobrazit",
    "colors": "Barvy",
    "classes": "třídami",
    "symbolSize": "Velikost symbolu",
    "addValue": "Přidat hodnotu",
    "setDefaultSymbol": "Nastavit výchozí symbol",
    "defaultSymbol": "Výchozí symbol",
    "selectedSymbol": "Vybraný symbol",
    "value": "Hodnota",
    "label": "Ř_Label___ů",
    "range": "Rozmezí"
  },
  "drawBox": {
    "point": "Bod",
    "line": "Linie",
    "polyline": "Polylinie",
    "freehandPolyline": "Polylinie od ruky",
    "triangle": "Trojúhelník",
    "extent": "Rozsah",
    "circle": "Kruh",
    "ellipse": "Elipsa",
    "polygon": "Polygon",
    "freehandPolygon": "Polygon od ruky",
    "text": "Text",
    "clear": "Ř_Clear___ů"
  },
  "popupConfig": {
    "title": "Ř_Title___ů",
    "add": "Přidat",
    "fields": "Pole",
    "noField": "Žádná pole",
    "visibility": "Viditelná",
    "name": "Ř_Name__ů",
    "alias": "Přezdívka",
    "actions": "Ř_Actions___ů"
  },
  "includeButton": {
    "include": "Zahrnutí"
  },
  "loadingShelter": {
    "loading": "Načítání"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nebyly nalezeny žádné služby.",
    "unableConnectTo": "Nelze se připojit k",
    "invalidUrlTip": "Zadaná adresa URL je neplatná nebo nepřístupná."
  },
  "serviceBrowser": {
    "noGpFound": "Nebyly nalezeny žádné geoprocessingové služby",
    "unableConnectTo": "Nelze se připojit k"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nebyly nalezeny žádné mapové služby ani služby prvků.",
    "unableConnectTo": "Nelze se připojit k"
  },
  "basicServiceChooser": {
    "validate": "Ověřit",
    "example": "Příklad",
    "set": "Nastavit"
  },
  "urlInput": {
    "invalidUrl": "Neplatná adresa URL"
  },
  "urlComboBox": {
    "invalidUrl": "Neplatná adresa URL"
  },
  "filterBuilder": {
    "addAnotherExpression": "Přidat výraz filtru",
    "addSet": "Přidat sadu výrazů",
    "matchMsg": "Získat prvky vrstvy, které odpovídají ${any_or_all} z následujících výrazů.",
    "matchMsgSet": "${any_or_all} z následujících výrazů v této sadě platí.",
    "all": "Všechny",
    "any": "Libovolný",
    "value": "Hodnota",
    "field": "Ř_Field___ů",
    "unique": "Unikátní",
    "none": "Žádné",
    "and": "a",
    "valueTooltip": "Vložit hodnotu",
    "fieldTooltip": "Vybrat z existujícího pole",
    "uniqueValueTooltip": "Vybrat z unikátních hodnot ve vybraném poli",
    "stringOperatorIs": "je",
    "stringOperatorIsNot": "není",
    "stringOperatorStartsWith": "začíná na",
    "stringOperatorEndsWith": "končí na",
    "stringOperatorContains": "obsahuje",
    "stringOperatorDoesNotContain": "neobsahuje",
    "stringOperatorIsBlank": "je prázdný",
    "stringOperatorIsNotBlank": "není prázdný",
    "dateOperatorIsOn": "je na",
    "dateOperatorIsNotOn": "není na",
    "dateOperatorIsBefore": "je před",
    "dateOperatorIsAfter": "je za",
    "dateOperatorDays": "dní",
    "dateOperatorWeeks": "týdnů",
    "dateOperatorMonths": "měsíců",
    "dateOperatorInTheLast": "za posledních",
    "dateOperatorNotInTheLast": "ne za posledních",
    "dateOperatorIsBetween": "je mezi",
    "dateOperatorIsNotBetween": "není mezi",
    "dateOperatorIsBlank": "je prázdný",
    "dateOperatorIsNotBlank": "není prázdný",
    "numberOperatorIs": "je",
    "numberOperatorIsNot": "není",
    "numberOperatorIsAtLeast": "je alespoň",
    "numberOperatorIsLessThan": "je menší než",
    "numberOperatorIsAtMost": "je nejvýše",
    "numberOperatorIsGreaterThan": "je větší než",
    "numberOperatorIsBetween": "je mezi",
    "numberOperatorIsNotBetween": "není mezi",
    "numberOperatorIsBlank": "je prázdný",
    "numberOperatorIsNotBlank": "není prázdný",
    "string": "Řetězec",
    "number": "Číslo",
    "date": "Datum",
    "askForValues": "Interaktivní dotaz na hodnoty",
    "prompt": "Dotaz",
    "hint": "Text nápovědy",
    "error": {
      "invalidParams": "Neplatné parametry.",
      "invalidUrl": "Neplatná adresa URL",
      "noFilterFields": "Ve vrstvě nejsou žádná pole, která by bylo možno využít k filtrování.",
      "invalidSQL": "Neplatný výraz SQL.",
      "cantParseSQL": "SQL výraz nelze analyzovat."
    },
    "caseSensitive": "Rozlišovat malá a velká písmena",
    "notSupportCaseSensitiveTip": "Hostované služby nepodporují dotazy rozlišující velikost písmen."
  },
  "featureLayerSource": {
    "layer": "Vrstva",
    "browse": "Procházet",
    "selectFromMap": "Vybrat z mapy",
    "selectFromPortal": "Přidat z Portal for ArcGIS",
    "addServiceUrl": "Přidat adresu URL služby",
    "inputLayerUrl": "Adresa URL vstupní vrstvy",
    "selectLayer": "Zvolte vrstvu prvků z aktuální mapy.",
    "chooseItem": "Zvolte položku vrstvy prvků.",
    "setServiceUrl": "Zadejte adresu URL služby prvků nebo mapové služby.",
    "selectFromOnline": "Přidat z ArcGIS Online",
    "chooseLayer": "Zvolte vrstvu prvků."
  },
  "queryableLayerSource": {
    "layer": "Ř_Layer___ů",
    "browse": "Procházet",
    "selectFromMap": "Vybrat z mapy",
    "selectFromPortal": "Přidat z Portal for ArcGIS",
    "addServiceUrl": "Přidat adresu URL služby",
    "inputLayerUrl": "Adresa URL vstupní vrstvy",
    "selectLayer": "Zvolte vrstvu ze současné mapy.",
    "chooseItem": "Zvolte položku.",
    "setServiceUrl": "Zadejte adresu URL služby.",
    "selectFromOnline": "Přidat z ArcGIS Online",
    "chooseLayer": "Zvolte vrstvu."
  },
  "gpSource": {
    "selectFromPortal": "Přidat z Portal for ArcGIS",
    "addServiceUrl": "Přidat URL adresu služby",
    "selectFromOnline": "Přidat z ArcGIS Online",
    "setServiceUrl": "Zadejte adresu URL geoprocessingové služby.",
    "chooseItem": "Zvolte položku geoprocessingové služby.",
    "chooseTask": "Zvolte geoprocessingovou úlohu."
  },
  "itemSelector": {
    "map": "Ř_Map__ů",
    "selectWebMap": "Zvolit webovou mapu",
    "addMapFromOnlineOrPortal": "Umožňuje vyhledat a přidat webovou mapu, kterou bude aplikace používat. Může jít o mapu z veřejných zdrojů služby ArcGIS Online či ze soukromého obsahu ve službě ArcGIS Online nebo na portálu.",
    "searchMapName": "Vyhledávat podle názvu mapy…",
    "searchNone": "Nepodařilo se nám najít to, co hledáte. Zkuste to prosím znovu.",
    "groups": "Skupiny",
    "noneGroups": "Žádné skupiny",
    "signInTip": "Vaše přihlašovací relace vypršela. Chcete-li se k portálu znovu přihlásit, obnovte zobrazení stránky v prohlížeči.",
    "signIn": "Přihlásit se",
    "publicMap": "Veřejné",
    "myOrganization": "Moje organizace",
    "myGroup": "Moje skupiny",
    "myContent": "Můj obsah",
    "count": "Ř_Count___ů",
    "fromPortal": "z portálu",
    "fromOnline": "z webu ArcGIS.com",
    "noneThumbnail": "Miniatura není k dispozici.",
    "owner": "vlastník",
    "signInTo": "Přihlásit se do",
    "lastModified": "Naposledy upraveno",
    "moreDetails": "Další podrobnosti"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Tato služba nepodporuje dotazování."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "V mapě není k dispozici žádná vhodná vrstva."
  },
  "layerInfosMenu": {
    "titleBasemap": "Podkladové mapy",
    "titleLayers": "Operační vrstvy",
    "labelLayer": "Název vrstvy",
    "itemZoomTo": "Přiblížit na",
    "itemTransparency": "Průhlednost",
    "itemTransparent": "Průhledná",
    "itemOpaque": "Neprůhledná",
    "itemMoveUp": "Přesunout nahoru",
    "itemMoveDown": "Přesunout dolů",
    "itemDesc": "Popis",
    "itemDownload": "Stáhnout",
    "itemToAttributeTable": "Otevřít atributovou tabulku"
  },
  "imageChooser": {
    "unsupportReaderAPI": "ÚKOL: Prohlížeč nepodporuje API průzkumníka souborů.",
    "readError": "Soubor se nepodařilo načíst.",
    "unknowError": "Operace nelze dokončit",
    "invalidType": "Neplatný typ souboru.",
    "cropImage": "Ř_Crop Image____ů",
    "exceed": "Velikost souboru nesmí překročit 1024 KB.",
    "enableFlash": "ÚKOL: Povolit Flash.",
    "cropWaining": "Zvolte prosím fotografii s rozměry alespoň ${width}×${height} pixelů.",
    "toolTip": "V zájmu dosažení nejlepších výsledků by měl být obrázek ${width} pixelů široký a ${height} pixelů vysoký. Obrázky jiných rozměrů budou upraveny. Lze použít následující formáty: PNG, GIF a JPEG."
  },
  "simpleTable": {
    "moveUp": "Přesunout nahoru",
    "moveDown": "Přesunout dolů",
    "deleteRow": "Odstranit",
    "edit": "Upravit"
  },
  "urlParams": {
    "invalidToken": "Neplatný token",
    "validateTokenError": "Neplatný token nebo chyba sítě"
  },
  "exportTo": {
    "exportTo": "Exportovat",
    "toCSV": "Exportovat do souboru CSV",
    "toFeatureCollection": "Exportovat do sbírky prvků",
    "toGeoJSON": "Exportovat do GeoJSON"
  },
  "appState": {
    "title": "Ř_App State____ů",
    "restoreMap": "Kliknutím obnovíte rozsah mapy a viditelnost vrstvy tam, kde jste skončili."
  },
  "featureActions": {
    "ZoomTo": "Ř_Zoom to___ů",
    "PanTo": "Ř_Pan to___ů",
    "Flash": "Ř_Flash___ů",
    "ShowPopup": "Ř_Show Pop-up____ů",
    "CreateLayer": "Ř_Create Layer_____ů",
    "ShowStatistics": "Ř_Statistics_____ů...",
    "ClearSelection": "Ř_Clear Selection______ů",
    "ExportToCSV": "Ř_Export to CSV file______ů",
    "ExportToFeatureCollection": "Ř_Export to Feature Collection_________ů",
    "ExportToGeoJSON": "Ř_Export to GeoJSON______ů"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Ř_Related layer_____ů",
    "selectedFeatures": "Ř_Selected features______ů",
    "drawShapesTip": "Ř_Draw shapes to select features__________ů",
    "pleaseDrawShapesTip": "Ř_Please draw shapes to select features____________ů",
    "allFeaturesTip": "Ř_All features in the layer_________ů",
    "selectFeaturesOrDrawShapesTip": "Ř_Please use selected features in this layer or draw shapes on map to limit features__________________________ů."
  },
  "searchDistance": {
    "applySearchDistance": "Ř_Apply a search distance________ů",
    "applySearchDistanceToFeatures": "Ř_Apply a search distance to selected features______________ů"
  },
  "units": {
    "miles": "Ř_Miles___ů",
    "kilometers": "Ř_Kilometers____ů",
    "feet": "Ř_Feet__ů",
    "meters": "Ř_Meters___ů",
    "yards": "Ř_Yards___ů",
    "nauticalMiles": "Ř_Nautical Miles_____ů"
  },
  "featureSetChooser": {
    "select": "Ř_Select___ů",
    "dragBox": "Ř_Drag__ů",
    "dragMouse": "Ř_Darg the mouse_____ů",
    "selectByRectangle": "Ř_Select By Rectangle_______ů",
    "selectFeaturesTip": "Ř_Select features by dragging box around them on map________________ů",
    "newSelectionTip": "Ř_Create a new selection________ů",
    "addSelectionTip": "Ř_Add to the current selection_________ů",
    "removeSelectionTip": "Ř_Remove from the current selection___________ů",
    "selectFromCurrentSelectionTip": "Ř_Select from the current selection___________ů",
    "unselectAllSelectionTip": "Ř_Unselect all currently selected features_____________ů"
  },
  "widgetManager": {
    "createWidgetError": "Ř_Create widget error_______ů",
    "createWidgetSettingPageError": "Ř_Create widget setting page error___________ů",
    "loadWidgetResourceError": "Ř_Load widget resouce error_________ů"
  },
  "shareOptions": {
    "shareMap": "Ř_Choose who can view this app_________ů",
    "shareMapTips": "Ř_Your map is currentlt shared with these people_______________ů",
    "everyone": "Ř_everyone___ů",
    "theseGroups": "Ř_theseGroups____ů"
  },
  "shareLink": {
    "email": "Ř_email___ů",
    "shareEmail": "Ř_Email___ů",
    "facebook": "Ř_facebook___ů",
    "shareFacebook": "Ř_Facebook___ů",
    "twitter": "Ř_twitter___ů",
    "shareTwitter": "Ř_Twitter___ů",
    "googlePlus": "Ř_googlePlus____ů",
    "shareGooglePlus": "Ř_GooglePlus____ů",
    "EmbedTips": "Ř_Embed this scene in a website__________ů",
    "shareEmailTxt1": "Ř_Have a look at this Web Scene__________ů:",
    "shareEmailTxt2": "Ř_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ů.",
    "smallSize": "Ř_Small___ů",
    "mediumSize": "Ř_Medium___ů",
    "largeSize": "Ř_Large___ů",
    "customSize": "Ř_Custom___ů",
    "embed": "Ř_Embed this scene in a website__________ů",
    "more": "Ř_Embed Options_____ů",
    "changeShareSettings": "Ř_Change Share Settings_______ů",
    "shareLinkText": "Ř_Choose who can view Copy________ů",
    "linkOptions": "Ř_Link Options_____ů",
    "linkOptionsUrlParameters": "Ř_Select URL parameters included in the link______________ů",
    "currentMapExtent": "Ř_Current map extent______ů",
    "chooseCenterWithLevel": "Ř_Click the map to define the center of the map with scale level____________________ů",
    "chooseCenterWithScale": "Ř_Click the map to define the center of the map with map scale___________________ů",
    "findLocation": "Ř_Find the location or feature and zoom to it______________ů",
    "findLocation_inputPlaceholder": "Ř_Your place or feature_______ů",
    "queryFeature": "Ř_Query a feature and zoom to it__________ů",
    "addMarker": "Ř_Add a marker on the map________ů",
    "addMarker_titlePlaceholder": "Ř_Title of the marker pop-up_________ů",
    "addMarker_symbolURL": "Ř_Marker symbol URL______ů",
    "addMarker_label": "Ř_Marker label_____ů",
    "overwirteMobileLayout": "Ř_Overwrite default mobile layout__________ů",
    "language": "Ř_Set the app language_______ů",
    "auth": "Ř_Authenticate a user automatically___________ů",
    "linkPreview": "Ř_Link Preview_____ů",
    "useShortenLink": "Ř_Short Link____ů",
    "shareMapUrlExtent": "Ř_shareMapUrlExtent______ů"
  },
  "webSceneLoader": {
    "webglSupportTip": "Ř_3D web apps aren't supported in your browser_______________ů."
  }
});