define({
  "common": {
    "apply": "é_Apply___È",
    "ok": "OK",
    "cancel": "Annulla",
    "yes": "é_Yes__È",
    "no": "é_No__È",
    "next": "Avanti",
    "back": "Indietro",
    "selected": "é_selected___È",
    "name": "Nome",
    "usage": "é_Usage___È",
    "settings": "é_Settings___È",
    "home": "é_Home__È",
    "link": "é_Link__È",
    "messages": "é_Messages___È",
    "outputs": "é_Outputs___È",
    "title": "Titolo",
    "thumbnail": "é_Thumbnail____È",
    "url": "é_URL__È",
    "actions": "Azioni",
    "layer": "Layer",
    "action": "é_Action___È",
    "input": "é_Input___È",
    "output": "é_Output___È",
    "type": "é_Type__È",
    "required": "é_Required___È",
    "options": "é_Options___È",
    "label": "Etichetta",
    "tooltip": "é_Tooltip___È",
    "visible": "é_Visible___È",
    "symbol": "é_Symbol___È",
    "popup": "é_Popup___È",
    "upload": "é_Upload___È",
    "execute": "é_Execute___È",
    "help": "é_Help__È",
    "executing": "é_Executing____È",
    "clear": "Cancella",
    "error": "é_Error___È",
    "zoomTo": "Zoom a",
    "attribute": "é_Attribute____È",
    "exports": "é_Export___È",
    "check": "é_Check___È",
    "save": "é_Save__È",
    "close": "é_Close___È",
    "deleteText": "é_Delete___È",
    "map": "Mappa",
    "scene": "é_Scene___È",
    "reset": "é_Reset___È",
    "icon": "é_Icon__È",
    "share": "é_Share___È"
  },
  "errorCode": "Codice",
  "errorMessage": "Messaggio",
  "errorDetail": "Dettagli",
  "widgetPlaceholderTooltip": "Per configurarlo, passare a Widget e fare clic sul segnaposto corrispondente",
  "fieldStatistics": {
    "statistics": "é_Statistics____È",
    "field": "Campo",
    "count": "é_Number of Values______È",
    "sum": "é_Sum of Values_____È",
    "min": "é_Minimum___È",
    "max": "é_Maximum___È",
    "ave": "é_Average___È",
    "stddev": "é_Standard Deviation______È"
  },
  "symbolChooser": {
    "preview": "Anteprima",
    "basic": "Base",
    "arrows": "Frecce",
    "business": "Aziende",
    "cartographic": "Cartografico",
    "nationalParkService": "Parco nazionale",
    "outdoorRecreation": "Attività ricreative all'aperto",
    "peoplePlaces": "Luoghi e persone",
    "safetyHealth": "Sicurezza e salute",
    "shapes": "Forme",
    "transportation": "Trasporti",
    "symbolSize": "Dimensioni simbolo",
    "color": "Colore",
    "alpha": "Alfa",
    "outlineColor": "Colore contorno",
    "outlineWidth": "Spessore contorno",
    "style": "Stile",
    "width": "Larghezza",
    "text": "Testo",
    "fontColor": "Colore carattere",
    "fontSize": "Dimensione carattere",
    "transparency": "Trasparenza",
    "solid": "Continua",
    "dash": "Tratteggiata",
    "dot": "Punteggiata",
    "dashDot": "Linea punto",
    "dashDotDot": "Linea punto punto"
  },
  "transparency": {
    "opaque": "Opaco",
    "transparent": "Trasparente"
  },
  "rendererChooser": {
    "domain": "Dominio",
    "use": "Utilizzare",
    "singleSymbol": "Singolo simbolo",
    "uniqueSymbol": "Simboli univoci",
    "color": "Colore",
    "size": "Dimensione",
    "toShow": "Da mostrare",
    "colors": "Colori",
    "classes": "Classi",
    "symbolSize": "Dimensioni simbolo",
    "addValue": "Aggiungi valore",
    "setDefaultSymbol": "Imposta simbolo predefinito",
    "defaultSymbol": "Simbolo predefinito",
    "selectedSymbol": "Simbolo selezionato",
    "value": "Valore",
    "label": "é_Label___È",
    "range": "Intervallo"
  },
  "drawBox": {
    "point": "Punto",
    "line": "Linea",
    "polyline": "Polilinea",
    "freehandPolyline": "Polilinea a mano libera",
    "triangle": "Triangolo",
    "extent": "Estensione",
    "circle": "Cerchio",
    "ellipse": "Ellisse",
    "polygon": "Poligono",
    "freehandPolygon": "Poligono a mano libera",
    "text": "Testo",
    "clear": "é_Clear___È"
  },
  "popupConfig": {
    "title": "é_Title___È",
    "add": "Aggiungi",
    "fields": "Campi",
    "noField": "Campi non disponibili",
    "visibility": "Visibile",
    "name": "é_Name__È",
    "alias": "Alias",
    "actions": "é_Actions___È"
  },
  "includeButton": {
    "include": "Includi"
  },
  "loadingShelter": {
    "loading": "Caricamento in corso"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nessun servizio trovato.",
    "unableConnectTo": "Impossibile connettersi a",
    "invalidUrlTip": "L'URL immesso non è valido o non è accessibile."
  },
  "serviceBrowser": {
    "noGpFound": "Non sono stati trovati servizi di geoprocessing.",
    "unableConnectTo": "Impossibile connettersi a"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Non sono stati trovati servizi mappe o servizi feature",
    "unableConnectTo": "Impossibile connettersi a"
  },
  "basicServiceChooser": {
    "validate": "Convalida",
    "example": "Esempio",
    "set": "Imposta"
  },
  "urlInput": {
    "invalidUrl": "URL non valido."
  },
  "urlComboBox": {
    "invalidUrl": "URL non valido."
  },
  "filterBuilder": {
    "addAnotherExpression": "Aggiungi un'espressione di filtro",
    "addSet": "Aggiungi un set di espressioni",
    "matchMsg": "Ottieni le feature nel layer corrispondenti a ${any_or_all} tra le seguenti espressioni",
    "matchMsgSet": "In questo set ${any_or_all} seguenti espressioni sono vere",
    "all": "tutte le",
    "any": "una qualsiasi delle",
    "value": "Valore",
    "field": "é_Field___È",
    "unique": "Univoci",
    "none": "Nessuno",
    "and": "e",
    "valueTooltip": "Immetti valore",
    "fieldTooltip": "Seleziona da campo esistente",
    "uniqueValueTooltip": "Seleziona da valori univoci nel campo selezionato",
    "stringOperatorIs": "è",
    "stringOperatorIsNot": "non è",
    "stringOperatorStartsWith": "inizia con",
    "stringOperatorEndsWith": "termina con",
    "stringOperatorContains": "contiene",
    "stringOperatorDoesNotContain": "non contiene",
    "stringOperatorIsBlank": "è vuoto",
    "stringOperatorIsNotBlank": "non è vuoto",
    "dateOperatorIsOn": "ricorre il giorno",
    "dateOperatorIsNotOn": "non ricorre il giorno",
    "dateOperatorIsBefore": "ricorre prima del giorno",
    "dateOperatorIsAfter": "ricorre dopo il giorno",
    "dateOperatorDays": "giorni",
    "dateOperatorWeeks": "settimane",
    "dateOperatorMonths": "mesi",
    "dateOperatorInTheLast": "negli ultimi/nelle ultime",
    "dateOperatorNotInTheLast": "non negli ultimi/nelle ultime",
    "dateOperatorIsBetween": "è compreso tra",
    "dateOperatorIsNotBetween": "non è compreso tra",
    "dateOperatorIsBlank": "è vuoto",
    "dateOperatorIsNotBlank": "non è vuoto",
    "numberOperatorIs": "è",
    "numberOperatorIsNot": "non è",
    "numberOperatorIsAtLeast": "è almeno",
    "numberOperatorIsLessThan": "è minore di",
    "numberOperatorIsAtMost": "è al massimo",
    "numberOperatorIsGreaterThan": "è maggiore di",
    "numberOperatorIsBetween": "è compreso tra",
    "numberOperatorIsNotBetween": "non è compreso tra",
    "numberOperatorIsBlank": "è vuoto",
    "numberOperatorIsNotBlank": "non è vuoto",
    "string": "Stringa",
    "number": "Numero",
    "date": "Data",
    "askForValues": "Richiedi valori",
    "prompt": "Prompt",
    "hint": "Suggerimento",
    "error": {
      "invalidParams": "Parametri non validi.",
      "invalidUrl": "URL non valido.",
      "noFilterFields": "Il layer non contiene campi utilizzabili per il filtro.",
      "invalidSQL": "Espressione SQL non valida.",
      "cantParseSQL": "Impossibile analizzare l'espressione SQL."
    },
    "caseSensitive": "Maiuscole/minuscole",
    "notSupportCaseSensitiveTip": "I servizi ospitati non supportano query con distinzione tra maiuscole e minuscole."
  },
  "featureLayerSource": {
    "layer": "Layer",
    "browse": "Sfoglia",
    "selectFromMap": "Seleziona da mappa",
    "selectFromPortal": "Aggiungi da Portal for ArcGIS",
    "addServiceUrl": "Aggiungi URL del servizio",
    "inputLayerUrl": "URL layer di input",
    "selectLayer": "Seleziona un layer feature dalla mappa corrente.",
    "chooseItem": "Scegli un elemento layer feature.",
    "setServiceUrl": "Immetti l'URL del servizio feature o del servizio mappe.",
    "selectFromOnline": "Aggiungi da ArcGIS Online",
    "chooseLayer": "Scegliere un feature layer."
  },
  "queryableLayerSource": {
    "layer": "é_Layer___È",
    "browse": "Esplora",
    "selectFromMap": "Seleziona da mappa",
    "selectFromPortal": "Aggiungi da Portal for ArcGIS",
    "addServiceUrl": "Aggiungi URL del servizio",
    "inputLayerUrl": "URL layer di input",
    "selectLayer": "Selezionare un layer dalla mappa corrente.",
    "chooseItem": "Scegliere un elemento.",
    "setServiceUrl": "Immettere l'URL del servizio.",
    "selectFromOnline": "Aggiungi da ArcGIS Online",
    "chooseLayer": "Selezionare un layer."
  },
  "gpSource": {
    "selectFromPortal": "Aggiungi da Portal for ArcGIS",
    "addServiceUrl": "Aggiungi URL del servizio",
    "selectFromOnline": "Aggiungi da ArcGIS Online",
    "setServiceUrl": "Immettere l'URL del servizio di geoprocessing.",
    "chooseItem": "Scegliere un elemento del servizio di geoprocessing.",
    "chooseTask": "Scegliere un'attività di geoprocessing."
  },
  "itemSelector": {
    "map": "é_Map__È",
    "selectWebMap": "Scegli mappa Web",
    "addMapFromOnlineOrPortal": "Cercare e aggiungere una mappa Web nell'applicazione da risorse pubbliche di ArcGIS Online o da contenuti privati disponibili in ArcGIS Online o nel portale.",
    "searchMapName": "Cerca per nome applicazione...",
    "searchNone": "Impossibile trovare l'elemento cercato. Riprovare.",
    "groups": "Gruppi",
    "noneGroups": "Gruppi non disponibili",
    "signInTip": "La sessione di accesso è scaduta. Aggiornare il browser per accedere nuovamente al portale.",
    "signIn": "Accedi",
    "publicMap": "Pubblico",
    "myOrganization": "La mia organizzazione",
    "myGroup": "I miei gruppi",
    "myContent": "I miei contenuti",
    "count": "é_Count___È",
    "fromPortal": "da portale",
    "fromOnline": "da ArcGIS.com",
    "noneThumbnail": "Anteprima non disponibile",
    "owner": "proprietario",
    "signInTo": "Accedi a",
    "lastModified": "Data ultima modifica",
    "moreDetails": "Altri dettagli"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Il servizio non supporta la query."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Nessun layer appropriato disponibile nella mappa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mappe di base",
    "titleLayers": "Layer operativi",
    "labelLayer": "Nome layer",
    "itemZoomTo": "Zoom a",
    "itemTransparency": "Trasparenza",
    "itemTransparent": "Trasparente",
    "itemOpaque": "Opaco",
    "itemMoveUp": "Sposta su",
    "itemMoveDown": "Sposta giù",
    "itemDesc": "Descrizione",
    "itemDownload": "Download",
    "itemToAttributeTable": "Apri tabella attributi"
  },
  "imageChooser": {
    "unsupportReaderAPI": "DA FARE: Il browser non supporta lettore di file API",
    "readError": "Lettura del file non riuscita.",
    "unknowError": "impossibile completare le operazioni",
    "invalidType": "Tipo di file non valido.",
    "cropImage": "é_Crop Image____È",
    "exceed": "Le dimensioni del file non possono superare 1024 KB",
    "enableFlash": "TODO: abilitare Flash.",
    "cropWaining": "Scegliere una foto di almeno ${width} x ${height} pixel.",
    "toolTip": "Per ottimizzare i risultati, l'immagine deve avere una larghezza pari a ${width} pixel e un'altezza pari a ${height} pixel. Dimensioni diverse verranno adattate. I formati di immagine supportati sono PNG, GIF e JPEG."
  },
  "simpleTable": {
    "moveUp": "Sposta su",
    "moveDown": "Sposta giù",
    "deleteRow": "Elimina",
    "edit": "Modifica"
  },
  "urlParams": {
    "invalidToken": "Token non valido",
    "validateTokenError": "Token non valido o errore di rete"
  },
  "exportTo": {
    "exportTo": "Esporta",
    "toCSV": "Esporta in file CSV",
    "toFeatureCollection": "Esporta in raccolta feature",
    "toGeoJSON": "Esporta in GeoJSON"
  },
  "appState": {
    "title": "é_App State____È",
    "restoreMap": "Fare clic per ripristinare l'estensione mappa e la visibilità dei layer dove si era rimasti."
  },
  "featureActions": {
    "ZoomTo": "é_Zoom to___È",
    "PanTo": "é_Pan to___È",
    "Flash": "é_Flash___È",
    "ShowPopup": "é_Show Pop-up____È",
    "CreateLayer": "é_Create Layer_____È",
    "ShowStatistics": "é_Statistics_____È...",
    "ClearSelection": "é_Clear Selection______È",
    "ExportToCSV": "é_Export to CSV file______È",
    "ExportToFeatureCollection": "é_Export to Feature Collection_________È",
    "ExportToGeoJSON": "é_Export to GeoJSON______È"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "é_Related layer_____È",
    "selectedFeatures": "é_Selected features______È",
    "drawShapesTip": "é_Draw shapes to select features__________È",
    "pleaseDrawShapesTip": "é_Please draw shapes to select features____________È",
    "allFeaturesTip": "é_All features in the layer_________È",
    "selectFeaturesOrDrawShapesTip": "é_Please use selected features in this layer or draw shapes on map to limit features__________________________È."
  },
  "searchDistance": {
    "applySearchDistance": "é_Apply a search distance________È",
    "applySearchDistanceToFeatures": "é_Apply a search distance to selected features______________È"
  },
  "units": {
    "miles": "é_Miles___È",
    "kilometers": "é_Kilometers____È",
    "feet": "é_Feet__È",
    "meters": "é_Meters___È",
    "yards": "é_Yards___È",
    "nauticalMiles": "é_Nautical Miles_____È"
  },
  "featureSetChooser": {
    "select": "é_Select___È",
    "dragBox": "é_Drag__È",
    "dragMouse": "é_Darg the mouse_____È",
    "selectByRectangle": "é_Select By Rectangle_______È",
    "selectFeaturesTip": "é_Select features by dragging box around them on map________________È",
    "newSelectionTip": "é_Create a new selection________È",
    "addSelectionTip": "é_Add to the current selection_________È",
    "removeSelectionTip": "é_Remove from the current selection___________È",
    "selectFromCurrentSelectionTip": "é_Select from the current selection___________È",
    "unselectAllSelectionTip": "é_Unselect all currently selected features_____________È"
  },
  "widgetManager": {
    "createWidgetError": "é_Create widget error_______È",
    "createWidgetSettingPageError": "é_Create widget setting page error___________È",
    "loadWidgetResourceError": "é_Load widget resouce error_________È"
  },
  "shareOptions": {
    "shareMap": "é_Choose who can view this app_________È",
    "shareMapTips": "é_Your map is currentlt shared with these people_______________È",
    "everyone": "é_everyone___È",
    "theseGroups": "é_theseGroups____È"
  },
  "shareLink": {
    "email": "é_email___È",
    "shareEmail": "é_Email___È",
    "facebook": "é_facebook___È",
    "shareFacebook": "é_Facebook___È",
    "twitter": "é_twitter___È",
    "shareTwitter": "é_Twitter___È",
    "googlePlus": "é_googlePlus____È",
    "shareGooglePlus": "é_GooglePlus____È",
    "EmbedTips": "é_Embed this scene in a website__________È",
    "shareEmailTxt1": "é_Have a look at this Web Scene__________È:",
    "shareEmailTxt2": "é_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________È.",
    "smallSize": "é_Small___È",
    "mediumSize": "é_Medium___È",
    "largeSize": "é_Large___È",
    "customSize": "é_Custom___È",
    "embed": "é_Embed this scene in a website__________È",
    "more": "é_Embed Options_____È",
    "changeShareSettings": "é_Change Share Settings_______È",
    "shareLinkText": "é_Choose who can view Copy________È",
    "linkOptions": "é_Link Options_____È",
    "linkOptionsUrlParameters": "é_Select URL parameters included in the link______________È",
    "currentMapExtent": "é_Current map extent______È",
    "chooseCenterWithLevel": "é_Click the map to define the center of the map with scale level____________________È",
    "chooseCenterWithScale": "é_Click the map to define the center of the map with map scale___________________È",
    "findLocation": "é_Find the location or feature and zoom to it______________È",
    "findLocation_inputPlaceholder": "é_Your place or feature_______È",
    "queryFeature": "é_Query a feature and zoom to it__________È",
    "addMarker": "é_Add a marker on the map________È",
    "addMarker_titlePlaceholder": "é_Title of the marker pop-up_________È",
    "addMarker_symbolURL": "é_Marker symbol URL______È",
    "addMarker_label": "é_Marker label_____È",
    "overwirteMobileLayout": "é_Overwrite default mobile layout__________È",
    "language": "é_Set the app language_______È",
    "auth": "é_Authenticate a user automatically___________È",
    "linkPreview": "é_Link Preview_____È",
    "useShortenLink": "é_Short Link____È",
    "shareMapUrlExtent": "é_shareMapUrlExtent______È"
  },
  "webSceneLoader": {
    "webglSupportTip": "é_3D web apps aren't supported in your browser_______________È."
  }
});