define({
	addAChartSource: "ก้_Add a Chart Source_ษฺ",
	sourceLabel: "ก้_Source label_ษฺ",
	labelField: "ก้_Label field_ษฺ",
	actions: "ก้_Actions_ษฺ",
	hightLightColor: "ก้_Highlight color_ษฺ",
	urlChartSource: "ก้_URL Chart Source_ษฺ",
	layerChartSource: "ก้_Layer Chart Source_ษฺ",
	searchUrl: "ก้_Search URL_ษฺ",
	browse: "ก้_Browse_ษฺ",
	layers: "ก้_Layers_ษฺ",
	availableFields: "ก้_Available Fields_ษฺ",
	charts: "ก้_Charts_ษฺ",
	chartField: "ก้_Chart field_ษฺ",
	description: "ก้_Description_ษฺ",
	title: "ก้_Title_ษฺ",
	type: "ก้_Type_ษฺ",
	cancel: "ก้_Cancel_ษฺ",
	addChartSource: "ก้_Add Chart Source_ษฺ",
	updateChartSource: "ก้_Update Chart Source_ษฺ",
	chartSources: "ก้_Chart Sources_ษฺ",
	chartSource: "ก้_Chart Source_ษฺ",
	general: "ก้_General_ษฺ"
});