define({
	addAChartSource: "כן_Add a Chart Source_ש",
	sourceLabel: "כן_Source label_ש",
	labelField: "כן_Label field_ש",
	actions: "כן_Actions_ש",
	hightLightColor: "כן_Highlight color_ש",
	urlChartSource: "כן_URL Chart Source_ש",
	layerChartSource: "כן_Layer Chart Source_ש",
	searchUrl: "כן_Search URL_ש",
	browse: "כן_Browse_ש",
	layers: "כן_Layers_ש",
	availableFields: "כן_Available Fields_ש",
	charts: "כן_Charts_ש",
	chartField: "כן_Chart field_ש",
	description: "כן_Description_ש",
	title: "כן_Title_ש",
	type: "כן_Type_ש",
	cancel: "כן_Cancel_ש",
	addChartSource: "כן_Add Chart Source_ש",
	updateChartSource: "כן_Update Chart Source_ש",
	chartSources: "כן_Chart Sources_ש",
	chartSource: "כן_Chart Source_ש",
	general: "כן_General_ש"
});