define({
	addAChartSource: "بيت_Add a Chart Source_لاحقة",
	sourceLabel: "بيت_Source label_لاحقة",
	labelField: "بيت_Label field_لاحقة",
	actions: "بيت_Actions_لاحقة",
	hightLightColor: "بيت_Highlight color_لاحقة",
	urlChartSource: "بيت_URL Chart Source_لاحقة",
	layerChartSource: "بيت_Layer Chart Source_لاحقة",
	searchUrl: "بيت_Search URL_لاحقة",
	browse: "بيت_Browse_لاحقة",
	layers: "بيت_Layers_لاحقة",
	availableFields: "بيت_Available Fields_لاحقة",
	charts: "بيت_Charts_لاحقة",
	chartField: "بيت_Chart field_لاحقة",
	description: "بيت_Description_لاحقة",
	title: "بيت_Title_لاحقة",
	type: "بيت_Type_لاحقة",
	cancel: "بيت_Cancel_لاحقة",
	addChartSource: "بيت_Add Chart Source_لاحقة",
	updateChartSource: "بيت_Update Chart Source_لاحقة",
	chartSources: "بيت_Chart Sources_لاحقة",
	chartSource: "بيت_Chart Source_لاحقة",
	general: "بيت_General_لاحقة"
});