define({
	addAChartSource: "æ_Add a Chart Source_Â",
	sourceLabel: "æ_Source label_Â",
	labelField: "æ_Label field_Â",
	actions: "æ_Actions_Â",
	hightLightColor: "æ_Highlight color_Â",
	urlChartSource: "æ_URL Chart Source_Â",
	layerChartSource: "æ_Layer Chart Source_Â",
	searchUrl: "æ_Search URL_Â",
	browse: "æ_Browse_Â",
	layers: "æ_Layers_Â",
	availableFields: "æ_Available Fields_Â",
	charts: "æ_Charts_Â",
	chartField: "æ_Chart field_Â",
	description: "æ_Description_Â",
	title: "æ_Title_Â",
	type: "æ_Type_Â",
	cancel: "æ_Cancel_Â",
	addChartSource: "æ_Add Chart Source_Â",
	updateChartSource: "æ_Update Chart Source_Â",
	chartSources: "æ_Chart Sources_Â",
	chartSource: "æ_Chart Source_Â",
	general: "æ_General_Â"
});