define({
  "common": {
    "apply": "ø_Apply___å",
    "ok": "OK",
    "cancel": "Annuller",
    "yes": "ø_Yes__å",
    "no": "ø_No__å",
    "next": "Næste",
    "back": "Tilbage",
    "selected": "ø_selected___å",
    "name": "Navn",
    "usage": "ø_Usage___å",
    "settings": "ø_Settings___å",
    "home": "ø_Home__å",
    "link": "ø_Link__å",
    "messages": "ø_Messages___å",
    "outputs": "ø_Outputs___å",
    "title": "Titel",
    "thumbnail": "ø_Thumbnail____å",
    "url": "ø_URL__å",
    "actions": "Handlinger",
    "layer": "Lag",
    "action": "ø_Action___å",
    "input": "ø_Input___å",
    "output": "ø_Output___å",
    "type": "ø_Type__å",
    "required": "ø_Required___å",
    "options": "ø_Options___å",
    "label": "Mærke",
    "tooltip": "ø_Tooltip___å",
    "visible": "ø_Visible___å",
    "symbol": "ø_Symbol___å",
    "popup": "ø_Popup___å",
    "upload": "ø_Upload___å",
    "execute": "ø_Execute___å",
    "help": "ø_Help__å",
    "executing": "ø_Executing____å",
    "clear": "Ryd",
    "error": "ø_Error___å",
    "zoomTo": "Zoom til",
    "attribute": "ø_Attribute____å",
    "exports": "ø_Export___å",
    "check": "ø_Check___å",
    "save": "ø_Save__å",
    "close": "ø_Close___å",
    "deleteText": "ø_Delete___å",
    "map": "Kort",
    "scene": "ø_Scene___å",
    "reset": "ø_Reset___å",
    "icon": "ø_Icon__å",
    "share": "ø_Share___å"
  },
  "errorCode": "Kode",
  "errorMessage": "Meddelelse",
  "errorDetail": "Detalje",
  "widgetPlaceholderTooltip": "Gå til Widgets. og klik på den tilhørende pladsholder, for at oprette den",
  "fieldStatistics": {
    "statistics": "ø_Statistics____å",
    "field": "Felt",
    "count": "ø_Number of Values______å",
    "sum": "ø_Sum of Values_____å",
    "min": "ø_Minimum___å",
    "max": "ø_Maximum___å",
    "ave": "ø_Average___å",
    "stddev": "ø_Standard Deviation______å"
  },
  "symbolChooser": {
    "preview": "Forhåndsvisning",
    "basic": "Grundlæggende principper",
    "arrows": "Pile",
    "business": "Forretning",
    "cartographic": "Kartografisk",
    "nationalParkService": "Nationalparkforvaltning (NPF)",
    "outdoorRecreation": "Udendørs rekreation",
    "peoplePlaces": "Offentlige steder",
    "safetyHealth": "Sikkerhed og sundhed",
    "shapes": "Former",
    "transportation": "Transport",
    "symbolSize": "Symbolstørrelse",
    "color": "Farve",
    "alpha": "Alfa",
    "outlineColor": "Konturfarve",
    "outlineWidth": "Kantbredde",
    "style": "Typografi",
    "width": "Bredde",
    "text": "Tekst",
    "fontColor": "Skriftfarve",
    "fontSize": "Skriftstørrelse",
    "transparency": "Gennemsigtighed",
    "solid": "Udfyldt",
    "dash": "Streg",
    "dot": "Punktum",
    "dashDot": "Streg-prik",
    "dashDotDot": "Streg-prik-prik"
  },
  "transparency": {
    "opaque": "Uigennemsigtig",
    "transparent": "Gennemsigtig"
  },
  "rendererChooser": {
    "domain": "Domæne",
    "use": "Brug",
    "singleSymbol": "Et enkelt symbol",
    "uniqueSymbol": "Entydige symboler",
    "color": "Farve",
    "size": "Størrelse",
    "toShow": "Som viser",
    "colors": "Farver",
    "classes": "Klasser",
    "symbolSize": "Symbolstørrelse",
    "addValue": "Tilføj værdi",
    "setDefaultSymbol": "Indstil standardsymbol",
    "defaultSymbol": "Standardsymbol",
    "selectedSymbol": "Valgt symbol",
    "value": "Værdi",
    "label": "ø_Label___å",
    "range": "Interval"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihåndspolylinje",
    "triangle": "Triangel",
    "extent": "Område",
    "circle": "Cirkel",
    "ellipse": "Ellipse",
    "polygon": "Polygon",
    "freehandPolygon": "Frihåndspolygon",
    "text": "Tekst",
    "clear": "ø_Clear___å"
  },
  "popupConfig": {
    "title": "ø_Title___å",
    "add": "Tilføj",
    "fields": "Felter",
    "noField": "Intet felt",
    "visibility": "Synlig",
    "name": "ø_Name__å",
    "alias": "Alias",
    "actions": "ø_Actions___å"
  },
  "includeButton": {
    "include": "Medtag"
  },
  "loadingShelter": {
    "loading": "Indlæser"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Der blev ingen tjenester fundet.",
    "unableConnectTo": "Der kunne ikke oprettes forbindelse til",
    "invalidUrlTip": "Den URL, du har angivet, er ugyldig eller utilgængelig."
  },
  "serviceBrowser": {
    "noGpFound": "Der blev ingen geoprocesseringstjenester fundet.",
    "unableConnectTo": "Der kunne ikke oprettes forbindelse til"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Der blev ingen kort- eller featuretjeneste fundet",
    "unableConnectTo": "Der kunne ikke oprettes forbindelse til"
  },
  "basicServiceChooser": {
    "validate": "Bekræft",
    "example": "Eksempel",
    "set": "Indstil"
  },
  "urlInput": {
    "invalidUrl": "Ugyldig URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ugyldig URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Tilføj et filterudtryk",
    "addSet": "Tilføj et udtrykssæt",
    "matchMsg": "Hent objekter i det lag, der passer til ${any_or_all} af følgende udtryk",
    "matchMsgSet": "${any_or_all} af følgende udtryk i dette sæt er sande",
    "all": "Alle",
    "any": "Hvilket som helst",
    "value": "Værdi",
    "field": "ø_Field___å",
    "unique": "Unik",
    "none": "Ingen",
    "and": "og",
    "valueTooltip": "Angiv værdi",
    "fieldTooltip": "Pluk fra eksisterende felt",
    "uniqueValueTooltip": "Pluk fra unikke værdier i det valgte felt",
    "stringOperatorIs": "er",
    "stringOperatorIsNot": "er ikke",
    "stringOperatorStartsWith": "starter med",
    "stringOperatorEndsWith": "slutter med",
    "stringOperatorContains": "indeholder",
    "stringOperatorDoesNotContain": "indeholder ikke",
    "stringOperatorIsBlank": "er tomt",
    "stringOperatorIsNotBlank": "er ikke tomt",
    "dateOperatorIsOn": "er d.",
    "dateOperatorIsNotOn": "er ikke d.",
    "dateOperatorIsBefore": "er før",
    "dateOperatorIsAfter": "er efter",
    "dateOperatorDays": "dage",
    "dateOperatorWeeks": "uger",
    "dateOperatorMonths": "måneder",
    "dateOperatorInTheLast": "i de seneste",
    "dateOperatorNotInTheLast": "ikke i de seneste",
    "dateOperatorIsBetween": "er mellem",
    "dateOperatorIsNotBetween": "er ikke mellem",
    "dateOperatorIsBlank": "er tomt",
    "dateOperatorIsNotBlank": "er ikke tomt",
    "numberOperatorIs": "er",
    "numberOperatorIsNot": "er ikke",
    "numberOperatorIsAtLeast": "er mindst",
    "numberOperatorIsLessThan": "er mindre end",
    "numberOperatorIsAtMost": "er højest",
    "numberOperatorIsGreaterThan": "er større end",
    "numberOperatorIsBetween": "er mellem",
    "numberOperatorIsNotBetween": "er ikke mellem",
    "numberOperatorIsBlank": "er tomt",
    "numberOperatorIsNotBlank": "er ikke tomt",
    "string": "Streng",
    "number": "Nummer",
    "date": "Dato",
    "askForValues": "Spørg efter værdier",
    "prompt": "Prompt",
    "hint": "Tip",
    "error": {
      "invalidParams": "Ugyldige parametre.",
      "invalidUrl": "Ugyldig URL.",
      "noFilterFields": "Laget har ingen felter, der kan anvendes til filtrering.",
      "invalidSQL": "Ugyldigt SQL-udtryk.",
      "cantParseSQL": "SQL-udtrykket kan ikke parses."
    },
    "caseSensitive": "Skelner mellem store og små bogstaver",
    "notSupportCaseSensitiveTip": "\"Hostede\" tjenester understøtter ikke forespørgsler, der skelner mellem store og små bogstaver."
  },
  "featureLayerSource": {
    "layer": "Lag",
    "browse": "Gennemse",
    "selectFromMap": "Vælg fra kort",
    "selectFromPortal": "Tilføj fra Portal for ArcGIS",
    "addServiceUrl": "Tilføj tjeneste-URL",
    "inputLayerUrl": "Inputlagets URL",
    "selectLayer": "Vælg et vektorlag fra det aktuelle kort.",
    "chooseItem": "Vælg et vektorlagelement.",
    "setServiceUrl": "Angiv URL-adressen på en feature- eller korttjeneste.",
    "selectFromOnline": "Tilføj fra ArcGIS Online",
    "chooseLayer": "Vælg et vektorlag."
  },
  "queryableLayerSource": {
    "layer": "ø_Layer___å",
    "browse": "Gennemse",
    "selectFromMap": "Vælg fra kort",
    "selectFromPortal": "Tilføj fra Portal for ArcGIS",
    "addServiceUrl": "Tilføj tjeneste-URL",
    "inputLayerUrl": "Inputlagets URL",
    "selectLayer": "Vælg et lag fra det aktuelle kort.",
    "chooseItem": "Vælg et element.",
    "setServiceUrl": "Indtast URL'en til tjenesten.",
    "selectFromOnline": "Tilføj fra ArcGIS Online",
    "chooseLayer": "Vælg et lag."
  },
  "gpSource": {
    "selectFromPortal": "Tilføj fra Portal for ArcGIS",
    "addServiceUrl": "Tilføj tjeneste-URL",
    "selectFromOnline": "Tilføj fra ArcGIS Online",
    "setServiceUrl": "Indtast URL til geoprocesseringstjenesten.",
    "chooseItem": "Vælg et geoprocesseringstjenesteelement.",
    "chooseTask": "Vælg en geoprocesseringsopgave."
  },
  "itemSelector": {
    "map": "ø_Map__å",
    "selectWebMap": "Vælg webkort",
    "addMapFromOnlineOrPortal": "Find og tilføj et webkort i applikationen fra offentlige ArcGIS Online-ressourcer eller dit private indhold i ArcGIS Online eller Portal.",
    "searchMapName": "Søg efter kortnavn...",
    "searchNone": "Vi kan ikke finde det, du søger. Prøv igen.",
    "groups": "Grupper",
    "noneGroups": "Ingen grupper",
    "signInTip": "Din login-session er udløbet. Opdater browseren for at logge på portalen igen.",
    "signIn": "Log ind",
    "publicMap": "Offentlig",
    "myOrganization": "Min organisation",
    "myGroup": "Mine grupper",
    "myContent": "Mit indhold",
    "count": "ø_Count___å",
    "fromPortal": "fra Portal",
    "fromOnline": "fra ArcGIS.com",
    "noneThumbnail": "Miniaturen er ikke tilgængelig",
    "owner": "ejer",
    "signInTo": "Log ind på",
    "lastModified": "Sidst ændret",
    "moreDetails": "Flere oplysninger"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Tjenesten understøtter ikke forespørgsler."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Der er intet passende lag tilgængeligt i kortet."
  },
  "layerInfosMenu": {
    "titleBasemap": "Baggrundskort",
    "titleLayers": "Operationelle lag",
    "labelLayer": "Navn på lag",
    "itemZoomTo": "Zoom til",
    "itemTransparency": "Gennemsigtighed",
    "itemTransparent": "Gennemsigtig",
    "itemOpaque": "Uigennemsigtig",
    "itemMoveUp": "Flyt op",
    "itemMoveDown": "Flyt ned",
    "itemDesc": "Beskrivelse",
    "itemDownload": "Hent",
    "itemToAttributeTable": "Åbn attributtabel"
  },
  "imageChooser": {
    "unsupportReaderAPI": "OPGAVE: Browseren understøtter ikke fillæser-API",
    "readError": "Kunne ikke læse filen.",
    "unknowError": "kan ikke fuldføre handlinger",
    "invalidType": "Ugyldig filtype.",
    "cropImage": "ø_Crop Image____å",
    "exceed": "Filstørrelsen må ikke være over 1.024 KB",
    "enableFlash": "OPGAVE: Aktivér flash.",
    "cropWaining": "Vælg et foto, der er mindst ${width} x ${height} pixels.",
    "toolTip": "For at opnå det bedste resultat bør billedet være ${width} pixels bredt x ${height} pixels højt. Andre størrelser tilpasses, så de passer. Acceptable billedformater er: PNG, GIF og JPEG."
  },
  "simpleTable": {
    "moveUp": "Flyt op",
    "moveDown": "Flyt ned",
    "deleteRow": "Slet",
    "edit": "Redigér"
  },
  "urlParams": {
    "invalidToken": "Ugyldigt token",
    "validateTokenError": "Ugyldigt token eller netværksfejl"
  },
  "exportTo": {
    "exportTo": "Eksportér",
    "toCSV": "Eksportér til CSV-fil",
    "toFeatureCollection": "Eksportér til objektsamling",
    "toGeoJSON": "Eksportér til GeoJSON"
  },
  "appState": {
    "title": "ø_App State____å",
    "restoreMap": "Klik for at gendanne kortudstrækningen og lagenes synlighed dér, hvor du var nået til."
  },
  "featureActions": {
    "ZoomTo": "ø_Zoom to___å",
    "PanTo": "ø_Pan to___å",
    "Flash": "ø_Flash___å",
    "ShowPopup": "ø_Show Pop-up____å",
    "CreateLayer": "ø_Create Layer_____å",
    "ShowStatistics": "ø_Statistics_____å...",
    "ClearSelection": "ø_Clear Selection______å",
    "ExportToCSV": "ø_Export to CSV file______å",
    "ExportToFeatureCollection": "ø_Export to Feature Collection_________å",
    "ExportToGeoJSON": "ø_Export to GeoJSON______å"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ø_Related layer_____å",
    "selectedFeatures": "ø_Selected features______å",
    "drawShapesTip": "ø_Draw shapes to select features__________å",
    "pleaseDrawShapesTip": "ø_Please draw shapes to select features____________å",
    "allFeaturesTip": "ø_All features in the layer_________å",
    "selectFeaturesOrDrawShapesTip": "ø_Please use selected features in this layer or draw shapes on map to limit features__________________________å."
  },
  "searchDistance": {
    "applySearchDistance": "ø_Apply a search distance________å",
    "applySearchDistanceToFeatures": "ø_Apply a search distance to selected features______________å"
  },
  "units": {
    "miles": "ø_Miles___å",
    "kilometers": "ø_Kilometers____å",
    "feet": "ø_Feet__å",
    "meters": "ø_Meters___å",
    "yards": "ø_Yards___å",
    "nauticalMiles": "ø_Nautical Miles_____å"
  },
  "featureSetChooser": {
    "select": "ø_Select___å",
    "dragBox": "ø_Drag__å",
    "dragMouse": "ø_Darg the mouse_____å",
    "selectByRectangle": "ø_Select By Rectangle_______å",
    "selectFeaturesTip": "ø_Select features by dragging box around them on map________________å",
    "newSelectionTip": "ø_Create a new selection________å",
    "addSelectionTip": "ø_Add to the current selection_________å",
    "removeSelectionTip": "ø_Remove from the current selection___________å",
    "selectFromCurrentSelectionTip": "ø_Select from the current selection___________å",
    "unselectAllSelectionTip": "ø_Unselect all currently selected features_____________å"
  },
  "widgetManager": {
    "createWidgetError": "ø_Create widget error_______å",
    "createWidgetSettingPageError": "ø_Create widget setting page error___________å",
    "loadWidgetResourceError": "ø_Load widget resouce error_________å"
  },
  "shareOptions": {
    "shareMap": "ø_Choose who can view this app_________å",
    "shareMapTips": "ø_Your map is currentlt shared with these people_______________å",
    "everyone": "ø_everyone___å",
    "theseGroups": "ø_theseGroups____å"
  },
  "shareLink": {
    "email": "ø_email___å",
    "shareEmail": "ø_Email___å",
    "facebook": "ø_facebook___å",
    "shareFacebook": "ø_Facebook___å",
    "twitter": "ø_twitter___å",
    "shareTwitter": "ø_Twitter___å",
    "googlePlus": "ø_googlePlus____å",
    "shareGooglePlus": "ø_GooglePlus____å",
    "EmbedTips": "ø_Embed this scene in a website__________å",
    "shareEmailTxt1": "ø_Have a look at this Web Scene__________å:",
    "shareEmailTxt2": "ø_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________å.",
    "smallSize": "ø_Small___å",
    "mediumSize": "ø_Medium___å",
    "largeSize": "ø_Large___å",
    "customSize": "ø_Custom___å",
    "embed": "ø_Embed this scene in a website__________å",
    "more": "ø_Embed Options_____å",
    "changeShareSettings": "ø_Change Share Settings_______å",
    "shareLinkText": "ø_Choose who can view Copy________å",
    "linkOptions": "ø_Link Options_____å",
    "linkOptionsUrlParameters": "ø_Select URL parameters included in the link______________å",
    "currentMapExtent": "ø_Current map extent______å",
    "chooseCenterWithLevel": "ø_Click the map to define the center of the map with scale level____________________å",
    "chooseCenterWithScale": "ø_Click the map to define the center of the map with map scale___________________å",
    "findLocation": "ø_Find the location or feature and zoom to it______________å",
    "findLocation_inputPlaceholder": "ø_Your place or feature_______å",
    "queryFeature": "ø_Query a feature and zoom to it__________å",
    "addMarker": "ø_Add a marker on the map________å",
    "addMarker_titlePlaceholder": "ø_Title of the marker pop-up_________å",
    "addMarker_symbolURL": "ø_Marker symbol URL______å",
    "addMarker_label": "ø_Marker label_____å",
    "overwirteMobileLayout": "ø_Overwrite default mobile layout__________å",
    "language": "ø_Set the app language_______å",
    "auth": "ø_Authenticate a user automatically___________å",
    "linkPreview": "ø_Link Preview_____å",
    "useShortenLink": "ø_Short Link____å",
    "shareMapUrlExtent": "ø_shareMapUrlExtent______å"
  },
  "webSceneLoader": {
    "webglSupportTip": "ø_3D web apps aren't supported in your browser_______________å."
  }
});