define({
  "common": {
    "apply": "Å_Apply___ö",
    "ok": "OK",
    "cancel": "Peruuta",
    "yes": "Å_Yes__ö",
    "no": "Å_No__ö",
    "next": "Seuraava",
    "back": "Takaisin",
    "selected": "Å_selected___ö",
    "name": "Nimi",
    "usage": "Å_Usage___ö",
    "settings": "Å_Settings___ö",
    "home": "Å_Home__ö",
    "link": "Å_Link__ö",
    "messages": "Å_Messages___ö",
    "outputs": "Å_Outputs___ö",
    "title": "Otsikko",
    "thumbnail": "Å_Thumbnail____ö",
    "url": "Å_URL__ö",
    "actions": "Toimet",
    "layer": "Karttataso",
    "action": "Å_Action___ö",
    "input": "Å_Input___ö",
    "output": "Å_Output___ö",
    "type": "Å_Type__ö",
    "required": "Å_Required___ö",
    "options": "Å_Options___ö",
    "label": "Tunnusteksti",
    "tooltip": "Å_Tooltip___ö",
    "visible": "Å_Visible___ö",
    "symbol": "Å_Symbol___ö",
    "popup": "Å_Popup___ö",
    "upload": "Å_Upload___ö",
    "execute": "Å_Execute___ö",
    "help": "Å_Help__ö",
    "executing": "Å_Executing____ö",
    "clear": "Tyhjennä",
    "error": "Å_Error___ö",
    "zoomTo": "Tarkenna kohteeseen",
    "attribute": "Å_Attribute____ö",
    "exports": "Å_Export___ö",
    "check": "Å_Check___ö",
    "save": "Å_Save__ö",
    "close": "Å_Close___ö",
    "deleteText": "Å_Delete___ö",
    "map": "Kartta",
    "scene": "Å_Scene___ö",
    "reset": "Å_Reset___ö",
    "icon": "Å_Icon__ö",
    "share": "Å_Share___ö"
  },
  "errorCode": "Koodi",
  "errorMessage": "Viesti",
  "errorDetail": "Yksityiskohta",
  "widgetPlaceholderTooltip": "Kun haluat asettaa tähän pienoisohjelman, mene Pienoisohjelmat-välilehdelle ja napsauta vastaavaa paikkamerkkiä",
  "fieldStatistics": {
    "statistics": "Å_Statistics____ö",
    "field": "Kenttä",
    "count": "Å_Number of Values______ö",
    "sum": "Å_Sum of Values_____ö",
    "min": "Å_Minimum___ö",
    "max": "Å_Maximum___ö",
    "ave": "Å_Average___ö",
    "stddev": "Å_Standard Deviation______ö"
  },
  "symbolChooser": {
    "preview": "Esikatselu",
    "basic": "Perus",
    "arrows": "Nuolet",
    "business": "Yritystoiminta",
    "cartographic": "Kartografinen",
    "nationalParkService": "puistolaitos",
    "outdoorRecreation": "Ulkovirkistys",
    "peoplePlaces": "Ihmiset Paikat",
    "safetyHealth": "Turv., terveys",
    "shapes": "Muodot",
    "transportation": "Kuljetus",
    "symbolSize": "Symbolin koko",
    "color": "Väri",
    "alpha": "Alfa",
    "outlineColor": "Reunaviivan väri",
    "outlineWidth": "Ääriviivan leveys",
    "style": "Tyyli",
    "width": "Leveys",
    "text": "Teksti",
    "fontColor": "Fontin väri",
    "fontSize": "Fontin koko",
    "transparency": "Läpinäkyvyys",
    "solid": "Yhtenäinen",
    "dash": "Viiva",
    "dot": "Piste",
    "dashDot": "Viiva-piste",
    "dashDotDot": "Viiva-piste-piste"
  },
  "transparency": {
    "opaque": "Läpinäkymätön",
    "transparent": "Läpinäkyvä"
  },
  "rendererChooser": {
    "domain": "Arvoalue",
    "use": "Käytä",
    "singleSymbol": "Yksi symboli",
    "uniqueSymbol": "Yksilölliset symbolit",
    "color": "Väri",
    "size": "Koko",
    "toShow": "Näytä",
    "colors": "Värit",
    "classes": "Luokkaa",
    "symbolSize": "Symbolin koko",
    "addValue": "Lisää arvo",
    "setDefaultSymbol": "Aseta oletussymboli",
    "defaultSymbol": "Oletussymboli",
    "selectedSymbol": "Valittu symboli",
    "value": "Arvo",
    "label": "Å_Label___ö",
    "range": "Vaihteluväli"
  },
  "drawBox": {
    "point": "Piste",
    "line": "Viiva",
    "polyline": "Taiteviiva",
    "freehandPolyline": "Vapaakädenpiirto, viiva",
    "triangle": "Kolmio",
    "extent": "Laajuus",
    "circle": "Ympyrä",
    "ellipse": "Ellipsi",
    "polygon": "Alue",
    "freehandPolygon": "Vapaankäden alue",
    "text": "Teksti",
    "clear": "Å_Clear___ö"
  },
  "popupConfig": {
    "title": "Å_Title___ö",
    "add": "Lisää",
    "fields": "Kentät",
    "noField": "Ei kenttää",
    "visibility": "Näkyvä",
    "name": "Å_Name__ö",
    "alias": "Alias",
    "actions": "Å_Actions___ö"
  },
  "includeButton": {
    "include": "Sisällytä"
  },
  "loadingShelter": {
    "loading": "Ladataan"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Palvelua ei löytynyt.",
    "unableConnectTo": "Yhteyttä kohteeseen ei voi muodostaa.",
    "invalidUrlTip": "Syötetty URL on virheellinen, tai se ei ole käytettävissä."
  },
  "serviceBrowser": {
    "noGpFound": "Geoprosessointipalvelua ei löytynyt.",
    "unableConnectTo": "Yhteyttä kohteeseen ei voi muodostaa"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Karttapalvelua tai kohdepalvelua ei löytynyt.",
    "unableConnectTo": "Yhteyttä kohteeseen ei voi muodostaa"
  },
  "basicServiceChooser": {
    "validate": "Vahvista",
    "example": "Esimerkki",
    "set": "Aseta"
  },
  "urlInput": {
    "invalidUrl": "Virheellinen URL-osoite."
  },
  "urlComboBox": {
    "invalidUrl": "Virheellinen URL-osoite."
  },
  "filterBuilder": {
    "addAnotherExpression": "Lisää suodatinlauseke",
    "addSet": "Lisää lausekesarja",
    "matchMsg": "Nouda sellaiset karttatason kohteet, jotka vastaavat ${any_or_all} seuraavia ehtolausekkeita",
    "matchMsgSet": "${any_or_all} seuraavista ehtolausekkeista ovat tosia",
    "all": "Kaikki",
    "any": "Mikä tahansa",
    "value": "Arvo",
    "field": "Å_Field___ö",
    "unique": "Yksilöllinen",
    "none": "Ei mitään",
    "and": "ja",
    "valueTooltip": "Syötä arvo",
    "fieldTooltip": "Poimi olemassa olevasta kentästä",
    "uniqueValueTooltip": "Poimi valitun kentän yksilöllisistä arvoista",
    "stringOperatorIs": "on",
    "stringOperatorIsNot": "ei ole",
    "stringOperatorStartsWith": "alkaa merkillä",
    "stringOperatorEndsWith": "päättyy merkkiin",
    "stringOperatorContains": "sisältää",
    "stringOperatorDoesNotContain": "ei sisällä",
    "stringOperatorIsBlank": "on tyhjä",
    "stringOperatorIsNotBlank": "ei ole tyhjä",
    "dateOperatorIsOn": "on päällä",
    "dateOperatorIsNotOn": "ei ole päällä",
    "dateOperatorIsBefore": "on ennen",
    "dateOperatorIsAfter": "on jälkeen",
    "dateOperatorDays": "päivää",
    "dateOperatorWeeks": "viikkoa",
    "dateOperatorMonths": "kuukautta",
    "dateOperatorInTheLast": "viimeisessä",
    "dateOperatorNotInTheLast": "ei viimeisessä",
    "dateOperatorIsBetween": "on välillä",
    "dateOperatorIsNotBetween": "ei ole välillä",
    "dateOperatorIsBlank": "on tyhjä",
    "dateOperatorIsNotBlank": "ei ole tyhjä",
    "numberOperatorIs": "on",
    "numberOperatorIsNot": "ei ole",
    "numberOperatorIsAtLeast": "on vähintään",
    "numberOperatorIsLessThan": "on vähemmän kuin",
    "numberOperatorIsAtMost": "on enintään",
    "numberOperatorIsGreaterThan": "on suurempi kuin",
    "numberOperatorIsBetween": "on välillä",
    "numberOperatorIsNotBetween": "ei ole välillä",
    "numberOperatorIsBlank": "on tyhjä",
    "numberOperatorIsNotBlank": "ei ole tyhjä",
    "string": "Merkkijono",
    "number": "Numero",
    "date": "Päivämäärä",
    "askForValues": "Pyydä arvoja",
    "prompt": "Kehote",
    "hint": "Vihje",
    "error": {
      "invalidParams": "Virheelliset parametrit.",
      "invalidUrl": "Virheellinen URL-osoite.",
      "noFilterFields": "Karttatasolla ei ole suodatukseen soveltuvia kenttiä.",
      "invalidSQL": "Virheellinen SQL-lauseke.",
      "cantParseSQL": "SQL-lauseketta ei voi jäsentää."
    },
    "caseSensitive": "Kirjainkoolla on merkitystä",
    "notSupportCaseSensitiveTip": "Isännöidyt palvelut eivät tue kirjainkoon tunnistavaa kyselyä."
  },
  "featureLayerSource": {
    "layer": "Karttataso",
    "browse": "Selaa",
    "selectFromMap": "Valitse kartasta",
    "selectFromPortal": "Lisää Portal for ArcGIS:stä",
    "addServiceUrl": "Lisää palvelun URL-osoite",
    "inputLayerUrl": "Anna karttatason URL-osoite",
    "selectLayer": "Valitse kohteen karttataso nykyisestä kartasta.",
    "chooseItem": "Valitse kohteen karttataso",
    "setServiceUrl": "Anna kohdepalvelun tai karttapalvelun URL-osoite.",
    "selectFromOnline": "Lisää ArcGIS Online -palvelusta",
    "chooseLayer": "Valitse kohdekarttataso."
  },
  "queryableLayerSource": {
    "layer": "Å_Layer___ö",
    "browse": "Selaa",
    "selectFromMap": "Valitse kartasta",
    "selectFromPortal": "Lisää Portal for ArcGIS:stä",
    "addServiceUrl": "Lisää palvelun URL-osoite",
    "inputLayerUrl": "Anna karttatason URL-osoite",
    "selectLayer": "Valitse karttataso nykyisestä kartasta.",
    "chooseItem": "Valitse kohde.",
    "setServiceUrl": "Anna palvelun URL-osoite.",
    "selectFromOnline": "Lisää ArcGIS Online -palvelusta",
    "chooseLayer": "Valitse karttataso."
  },
  "gpSource": {
    "selectFromPortal": "Lisää Portal for ArcGIS:stä",
    "addServiceUrl": "Lisää palvelun URL-osoite",
    "selectFromOnline": "Lisää ArcGIS Online -palvelusta",
    "setServiceUrl": "Anna geoprosessointipalvelun URL-osoite.",
    "chooseItem": "Valitse geoprosessointipalvelun kohde.",
    "chooseTask": "Valitse geoprosessointipalvelun tehtävä."
  },
  "itemSelector": {
    "map": "Å_Map__ö",
    "selectWebMap": "Valitse Web-kartta",
    "addMapFromOnlineOrPortal": "Etsi ja lisää sovelluksen Web-kartta ArcGIS Onlinen julkisista lähteistä tai ArcGIS Onlinen tai portaalin yksityisestä sisällöstäsi.",
    "searchMapName": "Hae kartan nimellä...",
    "searchNone": "Emme löytäneet etsimääsi. Kokeile uudelleen.",
    "groups": "Ryhmät",
    "noneGroups": "Ei ryhmiä",
    "signInTip": "Istuntosi on vanhentunut. Päivitä selain ja kirjaudu uudelleen portaaliin.",
    "signIn": "Kirjaudu sisään",
    "publicMap": "Julkinen",
    "myOrganization": "Organisaationi",
    "myGroup": "Omat ryhmät",
    "myContent": "Oma sisältö",
    "count": "Å_Count___ö",
    "fromPortal": "Portaalista",
    "fromOnline": "ArcGIS.comista",
    "noneThumbnail": "Pikkukuva ei ole käytettävissä",
    "owner": "omistaja",
    "signInTo": "Kirjaudu palveluun",
    "lastModified": "Muokattu viimeksi",
    "moreDetails": "Lisää tietoja"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Palvelu ei tue kyselyä."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Kartassa ei ole käytettävissä soveltuvaa karttatasoa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Taustakartat",
    "titleLayers": "Toiminnalliset karttatasot",
    "labelLayer": "Karttatason nimi",
    "itemZoomTo": "Tarkenna kohteeseen",
    "itemTransparency": "Läpinäkyvyys",
    "itemTransparent": "Läpinäkyvä",
    "itemOpaque": "Läpinäkymätön",
    "itemMoveUp": "Siirrä ylös",
    "itemMoveDown": "Siirrä alas",
    "itemDesc": "Kuvaus",
    "itemDownload": "Lataa",
    "itemToAttributeTable": "Avaa ominaisuustietotaulu"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TEHTÄVÄT: Selain ei tue tiedoston lukuohjelman ohjelmointirajapintaa",
    "readError": "Tiedoston luku epäonnistui.",
    "unknowError": "toimintoja ei voi suorittaa loppuun",
    "invalidType": "Invalid file type.",
    "cropImage": "Å_Crop Image____ö",
    "exceed": "Tiedoston koko ei saa ylittää 1024 kt",
    "enableFlash": "TODO: Ota käyttöön Flash.",
    "cropWaining": "Valitse valokuva, joka on kooltaan vähintään ${width} x ${height} pikseliä.",
    "toolTip": "Parhaan tuloksen saamiseksi kuvan tulisi olla leveydeltään ${width} pikseliä ja korkeudeltaan ${height} pikseliä. Muut koot säädetään sopivaksi. Hyväksyttyjä kuvamuotoja ovat PNG, GIF ja JPEG."
  },
  "simpleTable": {
    "moveUp": "Siirrä ylös",
    "moveDown": "Siirrä alas",
    "deleteRow": "Poista",
    "edit": "Muokkaa"
  },
  "urlParams": {
    "invalidToken": "Virheellinen tunnus",
    "validateTokenError": "Virheellinen tunnus tai verkkovirhe"
  },
  "exportTo": {
    "exportTo": "Vie",
    "toCSV": "Vie CSV-tiedostoksi",
    "toFeatureCollection": "Vie kohdekokoelmaan",
    "toGeoJSON": "Vie GeoJSON-muotoon"
  },
  "appState": {
    "title": "Å_App State____ö",
    "restoreMap": "Palauta karttalaajuus ja karttatasojen näkyvyys tilaan, jossa ne olivat alun perin."
  },
  "featureActions": {
    "ZoomTo": "Å_Zoom to___ö",
    "PanTo": "Å_Pan to___ö",
    "Flash": "Å_Flash___ö",
    "ShowPopup": "Å_Show Pop-up____ö",
    "CreateLayer": "Å_Create Layer_____ö",
    "ShowStatistics": "Å_Statistics_____ö...",
    "ClearSelection": "Å_Clear Selection______ö",
    "ExportToCSV": "Å_Export to CSV file______ö",
    "ExportToFeatureCollection": "Å_Export to Feature Collection_________ö",
    "ExportToGeoJSON": "Å_Export to GeoJSON______ö"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Å_Related layer_____ö",
    "selectedFeatures": "Å_Selected features______ö",
    "drawShapesTip": "Å_Draw shapes to select features__________ö",
    "pleaseDrawShapesTip": "Å_Please draw shapes to select features____________ö",
    "allFeaturesTip": "Å_All features in the layer_________ö",
    "selectFeaturesOrDrawShapesTip": "Å_Please use selected features in this layer or draw shapes on map to limit features__________________________ö."
  },
  "searchDistance": {
    "applySearchDistance": "Å_Apply a search distance________ö",
    "applySearchDistanceToFeatures": "Å_Apply a search distance to selected features______________ö"
  },
  "units": {
    "miles": "Å_Miles___ö",
    "kilometers": "Å_Kilometers____ö",
    "feet": "Å_Feet__ö",
    "meters": "Å_Meters___ö",
    "yards": "Å_Yards___ö",
    "nauticalMiles": "Å_Nautical Miles_____ö"
  },
  "featureSetChooser": {
    "select": "Å_Select___ö",
    "dragBox": "Å_Drag__ö",
    "dragMouse": "Å_Darg the mouse_____ö",
    "selectByRectangle": "Å_Select By Rectangle_______ö",
    "selectFeaturesTip": "Å_Select features by dragging box around them on map________________ö",
    "newSelectionTip": "Å_Create a new selection________ö",
    "addSelectionTip": "Å_Add to the current selection_________ö",
    "removeSelectionTip": "Å_Remove from the current selection___________ö",
    "selectFromCurrentSelectionTip": "Å_Select from the current selection___________ö",
    "unselectAllSelectionTip": "Å_Unselect all currently selected features_____________ö"
  },
  "widgetManager": {
    "createWidgetError": "Å_Create widget error_______ö",
    "createWidgetSettingPageError": "Å_Create widget setting page error___________ö",
    "loadWidgetResourceError": "Å_Load widget resouce error_________ö"
  },
  "shareOptions": {
    "shareMap": "Å_Choose who can view this app_________ö",
    "shareMapTips": "Å_Your map is currentlt shared with these people_______________ö",
    "everyone": "Å_everyone___ö",
    "theseGroups": "Å_theseGroups____ö"
  },
  "shareLink": {
    "email": "Å_email___ö",
    "shareEmail": "Å_Email___ö",
    "facebook": "Å_facebook___ö",
    "shareFacebook": "Å_Facebook___ö",
    "twitter": "Å_twitter___ö",
    "shareTwitter": "Å_Twitter___ö",
    "googlePlus": "Å_googlePlus____ö",
    "shareGooglePlus": "Å_GooglePlus____ö",
    "EmbedTips": "Å_Embed this scene in a website__________ö",
    "shareEmailTxt1": "Å_Have a look at this Web Scene__________ö:",
    "shareEmailTxt2": "Å_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ö.",
    "smallSize": "Å_Small___ö",
    "mediumSize": "Å_Medium___ö",
    "largeSize": "Å_Large___ö",
    "customSize": "Å_Custom___ö",
    "embed": "Å_Embed this scene in a website__________ö",
    "more": "Å_Embed Options_____ö",
    "changeShareSettings": "Å_Change Share Settings_______ö",
    "shareLinkText": "Å_Choose who can view Copy________ö",
    "linkOptions": "Å_Link Options_____ö",
    "linkOptionsUrlParameters": "Å_Select URL parameters included in the link______________ö",
    "currentMapExtent": "Å_Current map extent______ö",
    "chooseCenterWithLevel": "Å_Click the map to define the center of the map with scale level____________________ö",
    "chooseCenterWithScale": "Å_Click the map to define the center of the map with map scale___________________ö",
    "findLocation": "Å_Find the location or feature and zoom to it______________ö",
    "findLocation_inputPlaceholder": "Å_Your place or feature_______ö",
    "queryFeature": "Å_Query a feature and zoom to it__________ö",
    "addMarker": "Å_Add a marker on the map________ö",
    "addMarker_titlePlaceholder": "Å_Title of the marker pop-up_________ö",
    "addMarker_symbolURL": "Å_Marker symbol URL______ö",
    "addMarker_label": "Å_Marker label_____ö",
    "overwirteMobileLayout": "Å_Overwrite default mobile layout__________ö",
    "language": "Å_Set the app language_______ö",
    "auth": "Å_Authenticate a user automatically___________ö",
    "linkPreview": "Å_Link Preview_____ö",
    "useShortenLink": "Å_Short Link____ö",
    "shareMapUrlExtent": "Å_shareMapUrlExtent______ö"
  },
  "webSceneLoader": {
    "webglSupportTip": "Å_3D web apps aren't supported in your browser_______________ö."
  }
});