define({
  "common": {
    "apply": "Č_Apply___ž",
    "ok": "U redu",
    "cancel": "Odustani",
    "yes": "Č_Yes__ž",
    "no": "Č_No__ž",
    "next": "Sljedeće",
    "back": "Natrag",
    "selected": "Č_selected___ž",
    "name": "Naziv",
    "usage": "Č_Usage___ž",
    "settings": "Č_Settings___ž",
    "home": "Č_Home__ž",
    "link": "Č_Link__ž",
    "messages": "Č_Messages___ž",
    "outputs": "Č_Outputs___ž",
    "title": "Naslov",
    "thumbnail": "Č_Thumbnail____ž",
    "url": "Č_URL__ž",
    "actions": "Radnje",
    "layer": "Sloj",
    "action": "Č_Action___ž",
    "input": "Č_Input___ž",
    "output": "Č_Output___ž",
    "type": "Č_Type__ž",
    "required": "Č_Required___ž",
    "options": "Č_Options___ž",
    "label": "Oznaka",
    "tooltip": "Č_Tooltip___ž",
    "visible": "Č_Visible___ž",
    "symbol": "Č_Symbol___ž",
    "popup": "Č_Popup___ž",
    "upload": "Č_Upload___ž",
    "execute": "Č_Execute___ž",
    "help": "Č_Help__ž",
    "executing": "Č_Executing____ž",
    "clear": "Očisti",
    "error": "Č_Error___ž",
    "zoomTo": "Povećaj na",
    "attribute": "Č_Attribute____ž",
    "exports": "Č_Export___ž",
    "check": "Č_Check___ž",
    "save": "Č_Save__ž",
    "close": "Č_Close___ž",
    "deleteText": "Č_Delete___ž",
    "map": "Karta",
    "scene": "Č_Scene___ž",
    "reset": "Č_Reset___ž",
    "icon": "Č_Icon__ž",
    "share": "Č_Share___ž"
  },
  "errorCode": "Kod",
  "errorMessage": "Poruka",
  "errorDetail": "Pojedinost",
  "widgetPlaceholderTooltip": "Za postavljanje idite u Widgete i kliknite na odgovarajuće mjesto",
  "fieldStatistics": {
    "statistics": "Č_Statistics____ž",
    "field": "Polje",
    "count": "Č_Number of Values______ž",
    "sum": "Č_Sum of Values_____ž",
    "min": "Č_Minimum___ž",
    "max": "Č_Maximum___ž",
    "ave": "Č_Average___ž",
    "stddev": "Č_Standard Deviation______ž"
  },
  "symbolChooser": {
    "preview": "Pretpregled",
    "basic": "Osnovno",
    "arrows": "Strelice",
    "business": "Poduzeće",
    "cartographic": "Kartografsko",
    "nationalParkService": "Nacionalni park",
    "outdoorRecreation": "Vanjska rekreacija",
    "peoplePlaces": "Ljudi Mjesta",
    "safetyHealth": "Sigurnost Zdravlje",
    "shapes": "Oblici",
    "transportation": "Prijevoz",
    "symbolSize": "Veličina simbola",
    "color": "Boja",
    "alpha": "Alfa",
    "outlineColor": "Boja obrisa",
    "outlineWidth": "Širina obrisa",
    "style": "Stil",
    "width": "Širina",
    "text": "Tekst",
    "fontColor": "Boja fonta",
    "fontSize": "Veličina fonta",
    "transparency": "Prozirnost",
    "solid": "Puna linija",
    "dash": "Linija s crticom",
    "dot": "Točka",
    "dashDot": "Linija s crticom i točkom",
    "dashDotDot": "Linija s crticom i dvije točke"
  },
  "transparency": {
    "opaque": "Neprozirno",
    "transparent": "Transparentno"
  },
  "rendererChooser": {
    "domain": "Domena",
    "use": "Upotrijebi",
    "singleSymbol": "Jedan simbol",
    "uniqueSymbol": "Jedinstveni simbol",
    "color": "Boja",
    "size": "Veličina",
    "toShow": "Za prikaz",
    "colors": "Boje",
    "classes": "Razredi",
    "symbolSize": "Veličina simbola",
    "addValue": "Dodaj vrijednost",
    "setDefaultSymbol": "Postavi zadani simbol",
    "defaultSymbol": "Zadani simbol",
    "selectedSymbol": "Odabrani simbol",
    "value": "Vrijednost",
    "label": "Č_Label___ž",
    "range": "Raspon"
  },
  "drawBox": {
    "point": "Točka",
    "line": "Linija",
    "polyline": "Polilinija",
    "freehandPolyline": "Prostoručna polilinija",
    "triangle": "Trokut",
    "extent": "Obuhvat",
    "circle": "Krug",
    "ellipse": "Elipsa",
    "polygon": "Poligon",
    "freehandPolygon": "Prostoručni poligon",
    "text": "Tekst",
    "clear": "Č_Clear___ž"
  },
  "popupConfig": {
    "title": "Č_Title___ž",
    "add": "Dodaj",
    "fields": "Polja",
    "noField": "Nema polja",
    "visibility": "Vidljivo",
    "name": "Č_Name__ž",
    "alias": "Alias",
    "actions": "Č_Actions___ž"
  },
  "includeButton": {
    "include": "Uključi"
  },
  "loadingShelter": {
    "loading": "Učitavanje"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nema usluge.",
    "unableConnectTo": "Nije moguće povezivanje na",
    "invalidUrlTip": "URL koji ste unijeli nije valjan ili dostupan."
  },
  "serviceBrowser": {
    "noGpFound": "Nema usluge geoprocesiranja.",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nema usluge karte ili usluge geoobjekta",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "basicServiceChooser": {
    "validate": "Provjera",
    "example": "Primjer",
    "set": "Postavi"
  },
  "urlInput": {
    "invalidUrl": "Nevažeći URL."
  },
  "urlComboBox": {
    "invalidUrl": "Nevažeći URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Dodaj izraz filtra",
    "addSet": "Dodaj niz izraza",
    "matchMsg": "Pribavite geoobjekte u sloju koji odgovaraju ${any_or_all} sljedećim izrazima",
    "matchMsgSet": "${any_or_all} od sljedećih izraza u ovom nizu jesu istiniti",
    "all": "Sve",
    "any": "Bilo koji",
    "value": "Vrijednost",
    "field": "Č_Field___ž",
    "unique": "Jedinstveno",
    "none": "Nema",
    "and": "i",
    "valueTooltip": "Unesite vrijednost",
    "fieldTooltip": "Izaberite iz postojećih polja",
    "uniqueValueTooltip": "Izaberite iz jedinstvenih vrijednosti u odabranom polju",
    "stringOperatorIs": "je",
    "stringOperatorIsNot": "nije",
    "stringOperatorStartsWith": "počinje s",
    "stringOperatorEndsWith": "završava s",
    "stringOperatorContains": "sadrži",
    "stringOperatorDoesNotContain": "ne sadrži",
    "stringOperatorIsBlank": "prazno je",
    "stringOperatorIsNotBlank": "nije prazno",
    "dateOperatorIsOn": "je na",
    "dateOperatorIsNotOn": "nije na",
    "dateOperatorIsBefore": "je prije",
    "dateOperatorIsAfter": "je poslije",
    "dateOperatorDays": "dani",
    "dateOperatorWeeks": "tjedni",
    "dateOperatorMonths": "mjeseci",
    "dateOperatorInTheLast": "u posljednjem",
    "dateOperatorNotInTheLast": "nije u posljednjem",
    "dateOperatorIsBetween": "jest između",
    "dateOperatorIsNotBetween": "nije između",
    "dateOperatorIsBlank": "prazno je",
    "dateOperatorIsNotBlank": "nije prazno",
    "numberOperatorIs": "je",
    "numberOperatorIsNot": "nije",
    "numberOperatorIsAtLeast": "barem je",
    "numberOperatorIsLessThan": "manje je od",
    "numberOperatorIsAtMost": "najviše je",
    "numberOperatorIsGreaterThan": "veće je od",
    "numberOperatorIsBetween": "jest između",
    "numberOperatorIsNotBetween": "nije između",
    "numberOperatorIsBlank": "prazno je",
    "numberOperatorIsNotBlank": "nije prazno",
    "string": "Tekst",
    "number": "Broj",
    "date": "Datum",
    "askForValues": "Zatražite vrijednosti",
    "prompt": "Pitanje",
    "hint": "Podsjetnik",
    "error": {
      "invalidParams": "Nevažeći parametri.",
      "invalidUrl": "Nevažeći URL.",
      "noFilterFields": "Sloj nema polja koja se mogu upotrijebiti za filtar.",
      "invalidSQL": "Nevažeći SQL izraz.",
      "cantParseSQL": "Ne može analizirati SQL izraz."
    },
    "caseSensitive": "Osjetljivo na velika i mala slova",
    "notSupportCaseSensitiveTip": "Hostirane usluge ne podržavaju upit osjetljiv na velika i mala slova."
  },
  "featureLayerSource": {
    "layer": "Sloj",
    "browse": "Pregledaj",
    "selectFromMap": "Odaberi s karte",
    "selectFromPortal": "Dodaj s Portal for ArcGIS",
    "addServiceUrl": "Dodaj URL usluge",
    "inputLayerUrl": "Unesite URL sloja",
    "selectLayer": "Odaberite sloj geoobjekta s trenutačne karte.",
    "chooseItem": "Izaberite stavku sloja geoobjekata.",
    "setServiceUrl": "Unesite URL usluge geoobjekata ili usluge karte.",
    "selectFromOnline": "Dodaj iz ArcGIS Online",
    "chooseLayer": "Odaberite sloj geoobjekata."
  },
  "queryableLayerSource": {
    "layer": "Č_Layer___ž",
    "browse": "Pregledaj",
    "selectFromMap": "Odaberi s karte",
    "selectFromPortal": "Dodaj s Portal for ArcGIS",
    "addServiceUrl": "Dodaj URL usluge",
    "inputLayerUrl": "Unesite URL sloja",
    "selectLayer": "Odaberite sloj s trenutačne karte.",
    "chooseItem": "Odaberite stavku.",
    "setServiceUrl": "Unesite URL usluge.",
    "selectFromOnline": "Dodaj iz ArcGIS Online",
    "chooseLayer": "Izaberite sloj."
  },
  "gpSource": {
    "selectFromPortal": "Dodaj s Portal for ArcGIS",
    "addServiceUrl": "Dodaj URL usluge",
    "selectFromOnline": "Dodaj iz ArcGIS Online",
    "setServiceUrl": "Unesite URL usluge geoprocesiranja.",
    "chooseItem": "Izaberite stavku usluge geoprocesiranja.",
    "chooseTask": "Izaberite zadatak geoprocesiranja."
  },
  "itemSelector": {
    "map": "Č_Map__ž",
    "selectWebMap": "Izaberi web-kartu",
    "addMapFromOnlineOrPortal": "Pronađite i dodajte web-kartu iz aplikacije iz javnih resursa ArcGIS Onlinea ili iz vašeg privatnog sadržaja u ArcGIS Onlineu ili Portalu.",
    "searchMapName": "Pretraži prema nazivu karte...",
    "searchNone": "Nismo mogli pronaći to što tražite. Pokušajte ponovno.",
    "groups": "Grupe",
    "noneGroups": "Nema grupa",
    "signInTip": "Istekla je vaša sesija prijave pa osvježite svoj preglednik kako biste se ponovno prijavili na portal.",
    "signIn": "Prijava",
    "publicMap": "Javno",
    "myOrganization": "Moja organizacija",
    "myGroup": "Moje grupe",
    "myContent": "Moj sadržaj",
    "count": "Č_Count___ž",
    "fromPortal": "s Portala",
    "fromOnline": "sa stranice ArcGIS.com",
    "noneThumbnail": "Sličica nije dostupna",
    "owner": "vlasnik",
    "signInTo": "Prijavi se u",
    "lastModified": "Posljednja izmjena",
    "moreDetails": "Više pojedinosti"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Usluga ne podržava upit."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Nema odgovarajućeg sloja dostupnog na karti."
  },
  "layerInfosMenu": {
    "titleBasemap": "Kartografske podloge",
    "titleLayers": "Operativni slojevi",
    "labelLayer": "Naziv sloja",
    "itemZoomTo": "Povećaj na",
    "itemTransparency": "Prozirnost",
    "itemTransparent": "Transparentno",
    "itemOpaque": "Neprozirno",
    "itemMoveUp": "Premjesti gore",
    "itemMoveDown": "Premjesti dolje",
    "itemDesc": "Opis",
    "itemDownload": "Preuzmi",
    "itemToAttributeTable": "Otvori atributnu tablicu"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Obveza: preglednik ne podržava čitač datoteka API",
    "readError": "Nije uspjelo čitanje datoteke.",
    "unknowError": "nije moguće dovršiti radnje",
    "invalidType": "Nevažeća vrsta datoteke.",
    "cropImage": "Č_Crop Image____ž",
    "exceed": "Veličina datoteke ne može premašiti 1024 KB",
    "enableFlash": "Obveza: omogućite bljeskanje.",
    "cropWaining": "Izaberite fotografiju koja je barem ${width} x ${height} piksela.",
    "toolTip": "Za najbolje rezultate slika bi trebala imati ${width} piksela u širini i ${height} piksela u visini. Ostale će se veličine prilagoditi kako bi odgovarale. Prihvatljivi formati slika: PNG, GIF i JPEG."
  },
  "simpleTable": {
    "moveUp": "Premjesti gore",
    "moveDown": "Premjesti dolje",
    "deleteRow": "Izbriši",
    "edit": "Uredi"
  },
  "urlParams": {
    "invalidToken": "Nevažeći token",
    "validateTokenError": "Nevažeći token ili mrežna pogreška"
  },
  "exportTo": {
    "exportTo": "Izvezi",
    "toCSV": "Izvezi u CSV datoteku",
    "toFeatureCollection": "Izvezi u kolekciju geoobjekata",
    "toGeoJSON": "Izvezi u GeoJSON"
  },
  "appState": {
    "title": "Č_App State____ž",
    "restoreMap": "Kliknite da biste vratili obuhvat karte i vidljivost slojeva na posljednju vrijednost."
  },
  "featureActions": {
    "ZoomTo": "Č_Zoom to___ž",
    "PanTo": "Č_Pan to___ž",
    "Flash": "Č_Flash___ž",
    "ShowPopup": "Č_Show Pop-up____ž",
    "CreateLayer": "Č_Create Layer_____ž",
    "ShowStatistics": "Č_Statistics_____ž...",
    "ClearSelection": "Č_Clear Selection______ž",
    "ExportToCSV": "Č_Export to CSV file______ž",
    "ExportToFeatureCollection": "Č_Export to Feature Collection_________ž",
    "ExportToGeoJSON": "Č_Export to GeoJSON______ž"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Č_Related layer_____ž",
    "selectedFeatures": "Č_Selected features______ž",
    "drawShapesTip": "Č_Draw shapes to select features__________ž",
    "pleaseDrawShapesTip": "Č_Please draw shapes to select features____________ž",
    "allFeaturesTip": "Č_All features in the layer_________ž",
    "selectFeaturesOrDrawShapesTip": "Č_Please use selected features in this layer or draw shapes on map to limit features__________________________ž."
  },
  "searchDistance": {
    "applySearchDistance": "Č_Apply a search distance________ž",
    "applySearchDistanceToFeatures": "Č_Apply a search distance to selected features______________ž"
  },
  "units": {
    "miles": "Č_Miles___ž",
    "kilometers": "Č_Kilometers____ž",
    "feet": "Č_Feet__ž",
    "meters": "Č_Meters___ž",
    "yards": "Č_Yards___ž",
    "nauticalMiles": "Č_Nautical Miles_____ž"
  },
  "featureSetChooser": {
    "select": "Č_Select___ž",
    "dragBox": "Č_Drag__ž",
    "dragMouse": "Č_Darg the mouse_____ž",
    "selectByRectangle": "Č_Select By Rectangle_______ž",
    "selectFeaturesTip": "Č_Select features by dragging box around them on map________________ž",
    "newSelectionTip": "Č_Create a new selection________ž",
    "addSelectionTip": "Č_Add to the current selection_________ž",
    "removeSelectionTip": "Č_Remove from the current selection___________ž",
    "selectFromCurrentSelectionTip": "Č_Select from the current selection___________ž",
    "unselectAllSelectionTip": "Č_Unselect all currently selected features_____________ž"
  },
  "widgetManager": {
    "createWidgetError": "Č_Create widget error_______ž",
    "createWidgetSettingPageError": "Č_Create widget setting page error___________ž",
    "loadWidgetResourceError": "Č_Load widget resouce error_________ž"
  },
  "shareOptions": {
    "shareMap": "Č_Choose who can view this app_________ž",
    "shareMapTips": "Č_Your map is currentlt shared with these people_______________ž",
    "everyone": "Č_everyone___ž",
    "theseGroups": "Č_theseGroups____ž"
  },
  "shareLink": {
    "email": "Č_email___ž",
    "shareEmail": "Č_Email___ž",
    "facebook": "Č_facebook___ž",
    "shareFacebook": "Č_Facebook___ž",
    "twitter": "Č_twitter___ž",
    "shareTwitter": "Č_Twitter___ž",
    "googlePlus": "Č_googlePlus____ž",
    "shareGooglePlus": "Č_GooglePlus____ž",
    "EmbedTips": "Č_Embed this scene in a website__________ž",
    "shareEmailTxt1": "Č_Have a look at this Web Scene__________ž:",
    "shareEmailTxt2": "Č_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ž.",
    "smallSize": "Č_Small___ž",
    "mediumSize": "Č_Medium___ž",
    "largeSize": "Č_Large___ž",
    "customSize": "Č_Custom___ž",
    "embed": "Č_Embed this scene in a website__________ž",
    "more": "Č_Embed Options_____ž",
    "changeShareSettings": "Č_Change Share Settings_______ž",
    "shareLinkText": "Č_Choose who can view Copy________ž",
    "linkOptions": "Č_Link Options_____ž",
    "linkOptionsUrlParameters": "Č_Select URL parameters included in the link______________ž",
    "currentMapExtent": "Č_Current map extent______ž",
    "chooseCenterWithLevel": "Č_Click the map to define the center of the map with scale level____________________ž",
    "chooseCenterWithScale": "Č_Click the map to define the center of the map with map scale___________________ž",
    "findLocation": "Č_Find the location or feature and zoom to it______________ž",
    "findLocation_inputPlaceholder": "Č_Your place or feature_______ž",
    "queryFeature": "Č_Query a feature and zoom to it__________ž",
    "addMarker": "Č_Add a marker on the map________ž",
    "addMarker_titlePlaceholder": "Č_Title of the marker pop-up_________ž",
    "addMarker_symbolURL": "Č_Marker symbol URL______ž",
    "addMarker_label": "Č_Marker label_____ž",
    "overwirteMobileLayout": "Č_Overwrite default mobile layout__________ž",
    "language": "Č_Set the app language_______ž",
    "auth": "Č_Authenticate a user automatically___________ž",
    "linkPreview": "Č_Link Preview_____ž",
    "useShortenLink": "Č_Short Link____ž",
    "shareMapUrlExtent": "Č_shareMapUrlExtent______ž"
  },
  "webSceneLoader": {
    "webglSupportTip": "Č_3D web apps aren't supported in your browser_______________ž."
  }
});