define({
		addAChartSource: "添加Chart数据源",
		sourceLabel: "数据源名称",
		labelField: "标记字段",
		actions: "操作",
		hightLightColor: "高亮颜色",
		urlChartSource: "URL Chart数据源",
		layerChartSource: "图层Chart数据源",
		searchUrl: "搜索的URL",
		browse: "浏览",
		layers: "图层",
		availableFields: "可选字段",
		charts: "Charts",
		chartField: "Chart字段",
		description: "描述",
		title: "名称",
		type: "类型",
		cancel: "取消",
		addChartSource: "添加Chart数据源",
		updateChartSource: "更新Chart数据源",
		chartSources: "Chart数据源",
		chartSource: "Chart数据源",
		general: "通用",
		setSource: "设置数据源",
		setSourceTip: "请设置chart数据源",
		setLabelFieldTip: "请选择标记字段。",
		setMediaTip: "请至少设置一种chart类型。"
	});