define({
  root: ({
    rdoLayer: "Feature Layer",
    txtLayerLabel: "Layer Name",
    layerSettingLabel: "Layer Settings",
    locationSettingLabel: "Location Settings",
    actionsLabel: "Fields",
    locatorUrl: "Geocoder URL",
    set: "Set",
    locatorName: "Geocoder Name",
    placeholder: "Placeholder Text",
    countryCode: "Country or Region Code(s)",
    countryCodeEg: "e.g. ",
    countryCodeHint: "Leaving this value blank will search all countries and regions",
    maxSuggestions: "Maximum Suggestions",
    maxResults: "Maximum Results",
    enableLocalSearch: "Enable local search",
    minScale: "Min Scale",
    minScaleHint: "When the map scale is larger than this scale, local search will be applied",
    radius: "Radius",
    radiusHint: "Specifies the radius of an area around current map center that is used to boost the rank of geocoding candidates so that candidates closest to the location are returned first",
    meters: "Meters",
    instructionGeocode: "Add and configure geocode services.",
    instructionLayers: "Choose layer and configure fields.",
    locatorTips: "Suggestions are not available because the geocoding service doesn't support suggest capability.",
    zoomScale: "Zoom Scale",
    invalidUrlTip: "The URL ${URL} is invalid or inaccessible.",
    name: "Name",
    add: "Add",
    layerTab: {
      layerTabLabel: "Layer Settings"
    },
    geocodeTab: {
      geocodeTabLabel: "Location Settings",
      enableDisableXY: "Allow input from XY",
      enableDisableGeocode: "Allow batch geocoding"
    },
    lookupList: "Field Names to Recognize",
    isRecognized: "Field names in the table below are automatically recognized for this field",
    needsEditablePointLayers: "The webmap must contain at least 1 editable point layer.",
    actions: "Actions",
    editpageName: "Name",
    editpageAlias: "Alias",
    configureFields: "Configure Layer Fields",
    display: "Display",
    noSelectField: "Please select the Feature Layer option first",
    newNamePlaceholder: "Double-click the row to edit"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "hr": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sr": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});