define({
  root: ({
    rdoLayer: "Feature Layer",
    txtLayerLabel: "Layer Name",
    layerSettingLabel: "Layer Settings",
    locationSettingLabel: "Location Settings",
    actionsLabel: "Fields",
    locatorUrl: "Geocoder URL",
    set: "Set",
    locatorName: "Geocoder Name",
    placeholder: "Placeholder Text",
    countryCode: "Country or Region Code(s)",
    countryCodeEg: "e.g. ",
    countryCodeHint: "Leaving this value blank will search all countries and regions",
    maxSuggestions: "Maximum Suggestions",
    maxResults: "Maximum Results",
    enableLocalSearch: "Enable local search",
    minScale: "Min Scale",
    minScaleHint: "When the map scale is larger than this scale, local search will be applied",
    radius: "Radius",
    radiusHint: "Specifies the radius of an area around current map center that is used to boost the rank of geocoding candidates so that candidates closest to the location are returned first",
    meters: "Meters",
    instructionGeocode: "Add and configure geocode services.",
    instructionLayers: "Choose layer and configure fields.",
    locatorTips: "Suggestions are not available because the geocoding service doesn't support suggest capability.",
    zoomScale: "Zoom Scale",
    invalidUrlTip: "The URL ${URL} is invalid or inaccessible.",
    searchInCurrentMapExtent: "Only search in current map extent",
    name: "Name",
    add: "Add",
    layerTab: {
      layerTabLabel: "Layer Settings"
    },
    geocodeTab: {
      geocodeTabLabel: "Location Settings",
      enableDisableXY: "Allow input from XY",
      enableDisableGeocode: "Allow batch geocoding"
    },
    lookupList: "Is recognized if named",
    needsEditableLayers: "The webmap must contain at least 1 editable layer.",
    actions: "Actions",
    editpageName: "Name",
    editpageAlias: "Alias",
    configureFields: "Configure Layer Fields",
    display: "Display"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});