define({
	addAChartSource: "須_Add a Chart Source_鷗",
	sourceLabel: "須_Source label_鷗",
	labelField: "須_Label field_鷗",
	actions: "須_Actions_鷗",
	hightLightColor: "須_Highlight color_鷗",
	urlChartSource: "須_URL Chart Source_鷗",
	layerChartSource: "須_Layer Chart Source_鷗",
	searchUrl: "須_Search URL_鷗",
	browse: "須_Browse_鷗",
	layers: "須_Layers_鷗",
	availableFields: "須_Available Fields_鷗",
	charts: "須_Charts_鷗",
	chartField: "須_Chart field_鷗",
	description: "須_Description_鷗",
	title: "須_Title_鷗",
	type: "須_Type_鷗",
	cancel: "須_Cancel_鷗",
	addChartSource: "須_Add Chart Source_鷗",
	updateChartSource: "須_Update Chart Source_鷗",
	chartSources: "須_Chart Sources_鷗",
	chartSource: "須_Chart Source_鷗",
	general: "須_General_鷗"
});