define({
  "common": {
    "apply": "כן_Apply___ש",
    "ok": "אישור",
    "cancel": "ביטול",
    "yes": "כן_Yes__ש",
    "no": "כן_No__ש",
    "next": "הבא",
    "back": "חזור",
    "selected": "כן_selected___ש",
    "name": "שם",
    "usage": "כן_Usage___ש",
    "settings": "כן_Settings___ש",
    "home": "כן_Home__ש",
    "link": "כן_Link__ש",
    "messages": "כן_Messages___ש",
    "outputs": "כן_Outputs___ש",
    "title": "כותרת",
    "thumbnail": "כן_Thumbnail____ש",
    "url": "כן_URL__ש",
    "actions": "פעולות",
    "layer": "שכבה",
    "action": "כן_Action___ש",
    "input": "כן_Input___ש",
    "output": "כן_Output___ש",
    "type": "כן_Type__ש",
    "required": "כן_Required___ש",
    "options": "כן_Options___ש",
    "label": "תווית",
    "tooltip": "כן_Tooltip___ש",
    "visible": "כן_Visible___ש",
    "symbol": "כן_Symbol___ש",
    "popup": "כן_Popup___ש",
    "upload": "כן_Upload___ש",
    "execute": "כן_Execute___ש",
    "help": "כן_Help__ש",
    "executing": "כן_Executing____ש",
    "clear": "נקה",
    "error": "כן_Error___ש",
    "zoomTo": "התמקד אל",
    "attribute": "כן_Attribute____ש",
    "exports": "כן_Export___ש",
    "check": "כן_Check___ש",
    "save": "כן_Save__ש",
    "close": "כן_Close___ש",
    "deleteText": "כן_Delete___ש",
    "map": "מפה",
    "scene": "כן_Scene___ש",
    "reset": "כן_Reset___ש",
    "icon": "כן_Icon__ש",
    "share": "כן_Share___ש"
  },
  "errorCode": "קוד",
  "errorMessage": "הודעה",
  "errorDetail": "פרט",
  "widgetPlaceholderTooltip": "כדי להגדיר זאת, עבור לוידג'טים ולחץ על ממלא המקום המתאים",
  "fieldStatistics": {
    "statistics": "כן_Statistics____ש",
    "field": "שדה",
    "count": "כן_Number of Values______ש",
    "sum": "כן_Sum of Values_____ש",
    "min": "כן_Minimum___ש",
    "max": "כן_Maximum___ש",
    "ave": "כן_Average___ש",
    "stddev": "כן_Standard Deviation______ש"
  },
  "symbolChooser": {
    "preview": "תצוגה מקדימה",
    "basic": "בסיסי",
    "arrows": "חיצים",
    "business": "עסקים",
    "cartographic": "קרטוגרפיה",
    "nationalParkService": "שירות הפארקים הלאומיים",
    "outdoorRecreation": "נופש בטבע",
    "peoplePlaces": "מקומות של אנשים",
    "safetyHealth": "בטחון הציבור",
    "shapes": "צורות",
    "transportation": "תחבורה",
    "symbolSize": "גודל סמל",
    "color": "צבע",
    "alpha": "אלפא",
    "outlineColor": "צבע קו תוחם",
    "outlineWidth": "רוחב קו תוחם",
    "style": "סגנון",
    "width": "רוחב",
    "text": "טקסט",
    "fontColor": "צבע גופן",
    "fontSize": "גודל גופן",
    "transparency": "שקיפות",
    "solid": "מלא",
    "dash": "מקווקו",
    "dot": "נקודה",
    "dashDot": "קו נקודה",
    "dashDotDot": "קו נקודה נקודה"
  },
  "transparency": {
    "opaque": "אטום",
    "transparent": "שקוף"
  },
  "rendererChooser": {
    "domain": "דומיין",
    "use": "עם",
    "singleSymbol": "סמל יחיד",
    "uniqueSymbol": "סמלים ייחודיים",
    "color": "צבע",
    "size": "גודל",
    "toShow": "להציג",
    "colors": "צבעים",
    "classes": "קבוצות",
    "symbolSize": "גודל סמל",
    "addValue": "הוסף ערך",
    "setDefaultSymbol": "הגדר סמל ברירת מחדל",
    "defaultSymbol": "סימבול ברירת מחדל",
    "selectedSymbol": "בחר סמל",
    "value": "ערך",
    "label": "כן_Label___ש",
    "range": "טווח"
  },
  "drawBox": {
    "point": "נקודה",
    "line": "קו",
    "polyline": "קו",
    "freehandPolyline": "קו בשרטוט חופשי",
    "triangle": "משולש",
    "extent": "תיחום",
    "circle": "מעגל",
    "ellipse": "אליפסה",
    "polygon": "פוליגון",
    "freehandPolygon": "פוליגון בשרטוט חופשי",
    "text": "טקסט",
    "clear": "כן_Clear___ש"
  },
  "popupConfig": {
    "title": "כן_Title___ש",
    "add": "הוסף",
    "fields": "שדות",
    "noField": "אין שדה",
    "visibility": "ניראה",
    "name": "כן_Name__ש",
    "alias": "שם נוסף",
    "actions": "כן_Actions___ש"
  },
  "includeButton": {
    "include": "כלול"
  },
  "loadingShelter": {
    "loading": "טוען"
  },
  "basicServiceBrowser": {
    "noServicesFound": "לא נמצא שירות:",
    "unableConnectTo": "לא יכול להתחבר",
    "invalidUrlTip": "ה-URL שהזנת לא חוקי או שלא ניתן לגשת אליו."
  },
  "serviceBrowser": {
    "noGpFound": "לא נמצא שרות geoprocessing.",
    "unableConnectTo": "לא יכול להתחבר"
  },
  "layerServiceBrowser": {
    "noServicesFound": "לא נמצאו שירותי מפה או שירותי ישויות",
    "unableConnectTo": "לא יכול להתחבר"
  },
  "basicServiceChooser": {
    "validate": "אימות",
    "example": "דוגמא",
    "set": "הגדר"
  },
  "urlInput": {
    "invalidUrl": "URL לא חוקי."
  },
  "urlComboBox": {
    "invalidUrl": "URL לא חוקי."
  },
  "filterBuilder": {
    "addAnotherExpression": "הוסף ביטוי לסינון",
    "addSet": "הוסף קבוצת ביטויים",
    "matchMsg": "קבל ישויות בשכבה שתואמת ${any_or_all} מהביטויים הבאים",
    "matchMsgSet": "${any_or_all} מהביטויים הבאים בסט זה הם נכונים",
    "all": "הכל",
    "any": "כלשהו",
    "value": "ערך",
    "field": "כן_Field___ש",
    "unique": "ייחודי",
    "none": "ללא",
    "and": "וגם",
    "valueTooltip": "הכנס ערך",
    "fieldTooltip": "בחר מתוך שדה קיים",
    "uniqueValueTooltip": "בחר מתוך ערכים ייחודיים בשדה נבחר",
    "stringOperatorIs": "הוא",
    "stringOperatorIsNot": "אינו",
    "stringOperatorStartsWith": "מתחיל עם",
    "stringOperatorEndsWith": "מסתיים ב",
    "stringOperatorContains": "מכיל",
    "stringOperatorDoesNotContain": "לא מכיל",
    "stringOperatorIsBlank": "ריק",
    "stringOperatorIsNotBlank": "אינו ריק",
    "dateOperatorIsOn": "הוא ב-",
    "dateOperatorIsNotOn": "אינו ב-",
    "dateOperatorIsBefore": "הוא לפני",
    "dateOperatorIsAfter": "הוא אחרי",
    "dateOperatorDays": "ימים",
    "dateOperatorWeeks": "שבועות",
    "dateOperatorMonths": "חודשים",
    "dateOperatorInTheLast": "בסוף",
    "dateOperatorNotInTheLast": "לא בסוף",
    "dateOperatorIsBetween": "בין",
    "dateOperatorIsNotBetween": "לא נמצא בין",
    "dateOperatorIsBlank": "ריק",
    "dateOperatorIsNotBlank": "אינו ריק",
    "numberOperatorIs": "הוא",
    "numberOperatorIsNot": "אינו",
    "numberOperatorIsAtLeast": "הוא לפחות",
    "numberOperatorIsLessThan": "הוא פחות מ-",
    "numberOperatorIsAtMost": "הוא לכל היותר",
    "numberOperatorIsGreaterThan": "הוא גדול מ-",
    "numberOperatorIsBetween": "בין",
    "numberOperatorIsNotBetween": "לא נמצא בין",
    "numberOperatorIsBlank": "ריק",
    "numberOperatorIsNotBlank": "אינו ריק",
    "string": "מחרוזת",
    "number": "מספר",
    "date": "תאריך",
    "askForValues": "בקש ערכים",
    "prompt": "בקשה להזנה",
    "hint": "רמז",
    "error": {
      "invalidParams": "פרמטרים לא חוקיים.",
      "invalidUrl": "URL לא חוקי.",
      "noFilterFields": "לשכבוה אין שדות בהם ניתן להשתמש לסינון.",
      "invalidSQL": "ביטוי SQL לא חוקי.",
      "cantParseSQL": "לא ניתן לפענח את ביטוי ה-SQL."
    },
    "caseSensitive": "תלוי רישיות",
    "notSupportCaseSensitiveTip": "השירותים המתארחים אינם תומכים בשאילתא תלויית רישיות."
  },
  "featureLayerSource": {
    "layer": "שכבה",
    "browse": "דפדף",
    "selectFromMap": "בחר ממפה",
    "selectFromPortal": "הוסף מ- Portal for ArcGIS",
    "addServiceUrl": "הוסף כתובת URL של שירות",
    "inputLayerUrl": "URL של שכבת הקלט",
    "selectLayer": "בחר שכבת ישויות מהמפה הנוכחית.",
    "chooseItem": "בחר פריט שכבת ישויות.",
    "setServiceUrl": "הזן את כתובת ה-URL של שירות הישויות או שירות המפות.",
    "selectFromOnline": "הוסף  מ-ArcGIS Online",
    "chooseLayer": "בחר שכבת ישויות."
  },
  "queryableLayerSource": {
    "layer": "כן_Layer___ש",
    "browse": "נתב",
    "selectFromMap": "בחר ממפה",
    "selectFromPortal": "הוסף מ- Portal for ArcGIS",
    "addServiceUrl": "הוסף כתובת URL של שירות",
    "inputLayerUrl": "URL של שכבת הקלט",
    "selectLayer": "בחר שכבה מהמפה הנוכחית.",
    "chooseItem": "בחר פריט.",
    "setServiceUrl": "הזן את כתובת ה-URL של השירות.",
    "selectFromOnline": "הוסף  מ-ArcGIS Online",
    "chooseLayer": "בחר שכבה."
  },
  "gpSource": {
    "selectFromPortal": "הוסף מ- Portal for ArcGIS",
    "addServiceUrl": "הוסף כתובת URL של שירות",
    "selectFromOnline": "הוסף  מ-ArcGIS Online",
    "setServiceUrl": "הזן את כתובת ה- URL של שירות העיבוד הגיאוגרפי.",
    "chooseItem": "בחר פריט שירות של עיבוד גיאוגרפי.",
    "chooseTask": "בחר משימת עיבוד גיאוגרפי."
  },
  "itemSelector": {
    "map": "כן_Map__ש",
    "selectWebMap": "בחר Web Map",
    "addMapFromOnlineOrPortal": "מצא והוסף Web Map מתוך המקורות הציבוריים של ArcGIS Online, התוכן הפרטי שלך בתוך ArcGIS Online או הפורטל.",
    "searchMapName": "חפש לפי שם מפה...",
    "searchNone": "לא מצאנו את מה שחיפשת. נסה בבקשה שנית.",
    "groups": "קבוצות",
    "noneGroups": "אין קבוצות",
    "signInTip": "פג תוקף משך זמן ההתחברות. רענן בבקשה את הדפדפן שלך בשביל להתחבר לפורטל שלך שוב.",
    "signIn": "התחבר",
    "publicMap": "כללי",
    "myOrganization": "הארגון שלי",
    "myGroup": "הקבוצות שלי",
    "myContent": "התוכן שלי",
    "count": "כן_Count___ש",
    "fromPortal": "מהפורטל",
    "fromOnline": "מתוך ArcGIS.com",
    "noneThumbnail": "תמונה ממוזערת אינה זמינה",
    "owner": "יוצר",
    "signInTo": "התחבר אל",
    "lastModified": "שונה לאחרונה",
    "moreDetails": "פרטים נוספים"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "השירות אינו תומך בשאילתה."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "אין שכבה מתאימה זמינה במפה."
  },
  "layerInfosMenu": {
    "titleBasemap": "מפות בסיס",
    "titleLayers": "שכבות תפעוליות",
    "labelLayer": "שם שכבה",
    "itemZoomTo": "התמקד אל",
    "itemTransparency": "שקיפות",
    "itemTransparent": "שקוף",
    "itemOpaque": "אטום",
    "itemMoveUp": "הזז למעלה",
    "itemMoveDown": "הזז למטה",
    "itemDesc": "תיאור",
    "itemDownload": "הורד",
    "itemToAttributeTable": "פתח טבלת מאפיינים"
  },
  "imageChooser": {
    "unsupportReaderAPI": "לביצוע: הדפדפן לא תומך ב-API של קריאת קבצים",
    "readError": "קריאת הקובץ נכשלה.",
    "unknowError": "לא ניתן להשלים את ביצוע הפעולות.",
    "invalidType": "סוג קובץ לא חוקי.",
    "cropImage": "כן_Crop Image____ש",
    "exceed": "גודל הקובץ אינו יכול להיות יותר מ-‎1024 KB",
    "enableFlash": "לביצוע: הפעל Flash.",
    "cropWaining": "בחר תמונה שגודלה לפחות ${width}‏ x‏ ${height} פיקסלים.",
    "toolTip": "לקבלת תוצאות מיטביות, הקובץ צריך להיות ברוחב של ${width} פיקסלים ובגובה של ${height} פיקסלים. גדלים אחרים יותאמו. פורמטים של תמונות שיתקבלו הם: PNG,‏ GIF ו-JPEG."
  },
  "simpleTable": {
    "moveUp": "הזז למעלה",
    "moveDown": "הזז למטה",
    "deleteRow": "מחק",
    "edit": "עריכה"
  },
  "urlParams": {
    "invalidToken": "קוד גישה לא חוקי",
    "validateTokenError": "קוד גישה לא חוקי או שגיאה ברשת"
  },
  "exportTo": {
    "exportTo": "יצוא",
    "toCSV": "ייצא לקובץ CSV",
    "toFeatureCollection": "ייצא לאוסף ישויות",
    "toGeoJSON": "ייצא אל GeoJSON"
  },
  "appState": {
    "title": "כן_App State____ש",
    "restoreMap": "לחץ כדי לשחזר את תיחום המפה וניראות השכבות היכן שהפסקת."
  },
  "featureActions": {
    "ZoomTo": "כן_Zoom to___ש",
    "PanTo": "כן_Pan to___ש",
    "Flash": "כן_Flash___ש",
    "ShowPopup": "כן_Show Pop-up____ש",
    "CreateLayer": "כן_Create Layer_____ש",
    "ShowStatistics": "כן_Statistics_____ש...",
    "ClearSelection": "כן_Clear Selection______ש",
    "ExportToCSV": "כן_Export to CSV file______ש",
    "ExportToFeatureCollection": "כן_Export to Feature Collection_________ש",
    "ExportToGeoJSON": "כן_Export to GeoJSON______ש"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "כן_Related layer_____ש",
    "selectedFeatures": "כן_Selected features______ש",
    "drawShapesTip": "כן_Draw shapes to select features__________ש",
    "pleaseDrawShapesTip": "כן_Please draw shapes to select features____________ש",
    "allFeaturesTip": "כן_All features in the layer_________ש",
    "selectFeaturesOrDrawShapesTip": "כן_Please use selected features in this layer or draw shapes on map to limit features__________________________ש."
  },
  "searchDistance": {
    "applySearchDistance": "כן_Apply a search distance________ש",
    "applySearchDistanceToFeatures": "כן_Apply a search distance to selected features______________ש"
  },
  "units": {
    "miles": "כן_Miles___ש",
    "kilometers": "כן_Kilometers____ש",
    "feet": "כן_Feet__ש",
    "meters": "כן_Meters___ש",
    "yards": "כן_Yards___ש",
    "nauticalMiles": "כן_Nautical Miles_____ש"
  },
  "featureSetChooser": {
    "select": "כן_Select___ש",
    "dragBox": "כן_Drag__ש",
    "dragMouse": "כן_Darg the mouse_____ש",
    "selectByRectangle": "כן_Select By Rectangle_______ש",
    "selectFeaturesTip": "כן_Select features by dragging box around them on map________________ש",
    "newSelectionTip": "כן_Create a new selection________ש",
    "addSelectionTip": "כן_Add to the current selection_________ש",
    "removeSelectionTip": "כן_Remove from the current selection___________ש",
    "selectFromCurrentSelectionTip": "כן_Select from the current selection___________ש",
    "unselectAllSelectionTip": "כן_Unselect all currently selected features_____________ש"
  },
  "widgetManager": {
    "createWidgetError": "כן_Create widget error_______ש",
    "createWidgetSettingPageError": "כן_Create widget setting page error___________ש",
    "loadWidgetResourceError": "כן_Load widget resouce error_________ש"
  },
  "shareOptions": {
    "shareMap": "כן_Choose who can view this app_________ש",
    "shareMapTips": "כן_Your map is currentlt shared with these people_______________ש",
    "everyone": "כן_everyone___ש",
    "theseGroups": "כן_theseGroups____ש"
  },
  "shareLink": {
    "email": "כן_email___ש",
    "shareEmail": "כן_Email___ש",
    "facebook": "כן_facebook___ש",
    "shareFacebook": "כן_Facebook___ש",
    "twitter": "כן_twitter___ש",
    "shareTwitter": "כן_Twitter___ש",
    "googlePlus": "כן_googlePlus____ש",
    "shareGooglePlus": "כן_GooglePlus____ש",
    "EmbedTips": "כן_Embed this scene in a website__________ש",
    "shareEmailTxt1": "כן_Have a look at this Web Scene__________ש:",
    "shareEmailTxt2": "כן_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ש.",
    "smallSize": "כן_Small___ש",
    "mediumSize": "כן_Medium___ש",
    "largeSize": "כן_Large___ש",
    "customSize": "כן_Custom___ש",
    "embed": "כן_Embed this scene in a website__________ש",
    "more": "כן_Embed Options_____ש",
    "changeShareSettings": "כן_Change Share Settings_______ש",
    "shareLinkText": "כן_Choose who can view Copy________ש",
    "linkOptions": "כן_Link Options_____ש",
    "linkOptionsUrlParameters": "כן_Select URL parameters included in the link______________ש",
    "currentMapExtent": "כן_Current map extent______ש",
    "chooseCenterWithLevel": "כן_Click the map to define the center of the map with scale level____________________ש",
    "chooseCenterWithScale": "כן_Click the map to define the center of the map with map scale___________________ש",
    "findLocation": "כן_Find the location or feature and zoom to it______________ש",
    "findLocation_inputPlaceholder": "כן_Your place or feature_______ש",
    "queryFeature": "כן_Query a feature and zoom to it__________ש",
    "addMarker": "כן_Add a marker on the map________ש",
    "addMarker_titlePlaceholder": "כן_Title of the marker pop-up_________ש",
    "addMarker_symbolURL": "כן_Marker symbol URL______ש",
    "addMarker_label": "כן_Marker label_____ש",
    "overwirteMobileLayout": "כן_Overwrite default mobile layout__________ש",
    "language": "כן_Set the app language_______ש",
    "auth": "כן_Authenticate a user automatically___________ש",
    "linkPreview": "כן_Link Preview_____ש",
    "useShortenLink": "כן_Short Link____ש",
    "shareMapUrlExtent": "כן_shareMapUrlExtent______ש"
  },
  "webSceneLoader": {
    "webglSupportTip": "כן_3D web apps aren't supported in your browser_______________ש."
  }
});