define({
	addAChartSource: "å_Add a Chart Source_ø",
	sourceLabel: "å_Source label_ø",
	labelField: "å_Label field_ø",
	actions: "å_Actions_ø",
	hightLightColor: "å_Highlight color_ø",
	urlChartSource: "å_URL Chart Source_ø",
	layerChartSource: "å_Layer Chart Source_ø",
	searchUrl: "å_Search URL_ø",
	browse: "å_Browse_ø",
	layers: "å_Layers_ø",
	availableFields: "å_Available Fields_ø",
	charts: "å_Charts_ø",
	chartField: "å_Chart field_ø",
	description: "å_Description_ø",
	title: "å_Title_ø",
	type: "å_Type_ø",
	cancel: "å_Cancel_ø",
	addChartSource: "å_Add Chart Source_ø",
	updateChartSource: "å_Update Chart Source_ø",
	chartSources: "å_Chart Sources_ø",
	chartSource: "å_Chart Source_ø",
	general: "å_General_ø"
});