define({
	addAChartSource: "한_Add a Chart Source_빠",
	sourceLabel: "한_Source label_빠",
	labelField: "한_Label field_빠",
	actions: "한_Actions_빠",
	hightLightColor: "한_Highlight color_빠",
	urlChartSource: "한_URL Chart Source_빠",
	layerChartSource: "한_Layer Chart Source_빠",
	searchUrl: "한_Search URL_빠",
	browse: "한_Browse_빠",
	layers: "한_Layers_빠",
	availableFields: "한_Available Fields_빠",
	charts: "한_Charts_빠",
	chartField: "한_Chart field_빠",
	description: "한_Description_빠",
	title: "한_Title_빠",
	type: "한_Type_빠",
	cancel: "한_Cancel_빠",
	addChartSource: "한_Add Chart Source_빠",
	updateChartSource: "한_Update Chart Source_빠",
	chartSources: "한_Chart Sources_빠",
	chartSource: "한_Chart Source_빠",
	general: "한_General_빠"
});