define({
  "common": {
    "apply": "Å_Apply___ö",
    "ok": "OK",
    "cancel": "Avbryt",
    "yes": "Å_Yes__ö",
    "no": "Å_No__ö",
    "next": "Nästa",
    "back": "Bakåt",
    "selected": "Å_selected___ö",
    "name": "Namn",
    "usage": "Å_Usage___ö",
    "settings": "Å_Settings___ö",
    "home": "Å_Home__ö",
    "link": "Å_Link__ö",
    "messages": "Å_Messages___ö",
    "outputs": "Å_Outputs___ö",
    "title": "Titel",
    "thumbnail": "Å_Thumbnail____ö",
    "url": "Å_URL__ö",
    "actions": "Åtgärder",
    "layer": "Lager",
    "action": "Å_Action___ö",
    "input": "Å_Input___ö",
    "output": "Å_Output___ö",
    "type": "Å_Type__ö",
    "required": "Å_Required___ö",
    "options": "Å_Options___ö",
    "label": "Etikett",
    "tooltip": "Å_Tooltip___ö",
    "visible": "Å_Visible___ö",
    "symbol": "Å_Symbol___ö",
    "popup": "Å_Popup___ö",
    "upload": "Å_Upload___ö",
    "execute": "Å_Execute___ö",
    "help": "Å_Help__ö",
    "executing": "Å_Executing____ö",
    "clear": "Rensa",
    "error": "Å_Error___ö",
    "zoomTo": "Zooma till",
    "attribute": "Å_Attribute____ö",
    "exports": "Å_Export___ö",
    "check": "Å_Check___ö",
    "save": "Å_Save__ö",
    "close": "Å_Close___ö",
    "deleteText": "Å_Delete___ö",
    "map": "Karta",
    "scene": "Å_Scene___ö",
    "reset": "Å_Reset___ö",
    "icon": "Å_Icon__ö",
    "share": "Å_Share___ö"
  },
  "errorCode": "Kod",
  "errorMessage": "Meddelande",
  "errorDetail": "Information",
  "widgetPlaceholderTooltip": "Ställ in detta genom att gå till Widgetar och klicka på motsvarande platshållare",
  "fieldStatistics": {
    "statistics": "Å_Statistics____ö",
    "field": "Fält",
    "count": "Å_Number of Values______ö",
    "sum": "Å_Sum of Values_____ö",
    "min": "Å_Minimum___ö",
    "max": "Å_Maximum___ö",
    "ave": "Å_Average___ö",
    "stddev": "Å_Standard Deviation______ö"
  },
  "symbolChooser": {
    "preview": "Förhandsgranska",
    "basic": "Grundläggande",
    "arrows": "Pilar",
    "business": "Företag",
    "cartographic": "Kartografisk",
    "nationalParkService": "National Park Service",
    "outdoorRecreation": "Utomhusrekreation",
    "peoplePlaces": "Personplatser",
    "safetyHealth": "Säkerhet och hälsa",
    "shapes": "Objekt",
    "transportation": "Transport",
    "symbolSize": "Symbolstorlek",
    "color": "Färg",
    "alpha": "Alfa",
    "outlineColor": "Konturfärg",
    "outlineWidth": "Konturbredd",
    "style": "Format",
    "width": "Bredd",
    "text": "Text",
    "fontColor": "Teckenfärg",
    "fontSize": "Teckenstorlek",
    "transparency": "Transparens",
    "solid": "Heldragen",
    "dash": "Streck",
    "dot": "Punkt",
    "dashDot": "Streck punkt",
    "dashDotDot": "Streck punkt punkt"
  },
  "transparency": {
    "opaque": "Opak",
    "transparent": "Transparent"
  },
  "rendererChooser": {
    "domain": "Värdemängd",
    "use": "Använda",
    "singleSymbol": "En symbol",
    "uniqueSymbol": "Unika symboler",
    "color": "Färg",
    "size": "Storlek",
    "toShow": "För att visa",
    "colors": "Färger",
    "classes": "Klasser",
    "symbolSize": "Symbolstorlek",
    "addValue": "Lägg till värde",
    "setDefaultSymbol": "Ange standardsymbol",
    "defaultSymbol": "Standardsymbol",
    "selectedSymbol": "Vald symbol",
    "value": "Värde",
    "label": "Å_Label___ö",
    "range": "Intervall"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihandspolylinje",
    "triangle": "Triangel",
    "extent": "Utbredning",
    "circle": "Cirkel",
    "ellipse": "Ellips",
    "polygon": "Polygon",
    "freehandPolygon": "Frihandspolygon",
    "text": "Text",
    "clear": "Å_Clear___ö"
  },
  "popupConfig": {
    "title": "Å_Title___ö",
    "add": "Lägg till",
    "fields": "Fält",
    "noField": "Inget fält",
    "visibility": "Synlig",
    "name": "Å_Name__ö",
    "alias": "Alias",
    "actions": "Å_Actions___ö"
  },
  "includeButton": {
    "include": "Ta med"
  },
  "loadingShelter": {
    "loading": "Läser in"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Ingen tjänst hittades.",
    "unableConnectTo": "Det gick inte att ansluta till",
    "invalidUrlTip": "Den URL du har angett är ogiltig eller går inte att komma åt."
  },
  "serviceBrowser": {
    "noGpFound": "Ingen geobearbetningstjänst hittades.",
    "unableConnectTo": "Det gick inte att ansluta till"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Inga karttjänster eller geoobjekttjänster hittades",
    "unableConnectTo": "Det gick inte att ansluta till"
  },
  "basicServiceChooser": {
    "validate": "Validera",
    "example": "Exempel",
    "set": "Ange"
  },
  "urlInput": {
    "invalidUrl": "Ogiltig URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ogiltig URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Lägg till ett filteruttryck",
    "addSet": "Lägg till en uttrycksuppsättning",
    "matchMsg": "Hämta geoobjekt i lagret som matchar ${any_or_all} av följande uttryck",
    "matchMsgSet": "${any_or_all} av följande uttryck i uppsättningen är sanna",
    "all": "Alla",
    "any": "Något",
    "value": "Värde",
    "field": "Å_Field___ö",
    "unique": "Unik",
    "none": "Ingen",
    "and": "och",
    "valueTooltip": "Ange värde",
    "fieldTooltip": "Välj i befintligt fält",
    "uniqueValueTooltip": "Välj bland unika värden i det valda fältet",
    "stringOperatorIs": "är",
    "stringOperatorIsNot": "är inte",
    "stringOperatorStartsWith": "börjar med",
    "stringOperatorEndsWith": "slutar med",
    "stringOperatorContains": "innehåller",
    "stringOperatorDoesNotContain": "innehåller inte",
    "stringOperatorIsBlank": "är tomt",
    "stringOperatorIsNotBlank": "är inte tomt",
    "dateOperatorIsOn": "är",
    "dateOperatorIsNotOn": "är inte",
    "dateOperatorIsBefore": "är före",
    "dateOperatorIsAfter": "är efter",
    "dateOperatorDays": "dagar",
    "dateOperatorWeeks": "veckor",
    "dateOperatorMonths": "månader",
    "dateOperatorInTheLast": "i den sista",
    "dateOperatorNotInTheLast": "inte i den sista",
    "dateOperatorIsBetween": "är mellan",
    "dateOperatorIsNotBetween": "är inte mellan",
    "dateOperatorIsBlank": "är tomt",
    "dateOperatorIsNotBlank": "är inte tomt",
    "numberOperatorIs": "är",
    "numberOperatorIsNot": "är inte",
    "numberOperatorIsAtLeast": "är minst",
    "numberOperatorIsLessThan": "är mindre än",
    "numberOperatorIsAtMost": "är som mest",
    "numberOperatorIsGreaterThan": "är större än",
    "numberOperatorIsBetween": "är mellan",
    "numberOperatorIsNotBetween": "är inte mellan",
    "numberOperatorIsBlank": "är tomt",
    "numberOperatorIsNotBlank": "är inte tomt",
    "string": "Sträng",
    "number": "Nummer",
    "date": "Datum",
    "askForValues": "Fråga efter värden",
    "prompt": "Fråga",
    "hint": "Tips",
    "error": {
      "invalidParams": "Ogiltiga parametrar.",
      "invalidUrl": "Ogiltig URL.",
      "noFilterFields": "Lagret innehåller inga fält som kan användas för filter.",
      "invalidSQL": "Ogiltigt SQL-uttryck.",
      "cantParseSQL": "Det går inte att tolka SQL-uttrycket."
    },
    "caseSensitive": "Skiftlägeskänsligt",
    "notSupportCaseSensitiveTip": "Värdbaserade tjänster stöder inte skiftlägeskänsliga frågor."
  },
  "featureLayerSource": {
    "layer": "Lager",
    "browse": "Bläddra",
    "selectFromMap": "Välj från karta",
    "selectFromPortal": "Lägg till från Portal for ArcGIS",
    "addServiceUrl": "Lägg till tjänst-URL",
    "inputLayerUrl": "Indatalager-URL",
    "selectLayer": "Välj ett geoobjektlager i den aktuella kartan.",
    "chooseItem": "Välj ett objekt i geoobjektlagret.",
    "setServiceUrl": "Ange URL till karttjänsten eller geoobjekttjänsten.",
    "selectFromOnline": "Lägg till från ArcGIS Online",
    "chooseLayer": "Välj ett geoobjektslager."
  },
  "queryableLayerSource": {
    "layer": "Å_Layer___ö",
    "browse": "Bläddra",
    "selectFromMap": "Välj från karta",
    "selectFromPortal": "Lägg till från Portal for ArcGIS",
    "addServiceUrl": "Lägg till tjänst-URL",
    "inputLayerUrl": "Indatalager-URL",
    "selectLayer": "Välj ett lager i den aktuella kartan.",
    "chooseItem": "Välj ett objekt.",
    "setServiceUrl": "Ange webbadressen till tjänsten.",
    "selectFromOnline": "Lägg till från ArcGIS Online",
    "chooseLayer": "Välj ett lager."
  },
  "gpSource": {
    "selectFromPortal": "Lägg till från Portal for ArcGIS",
    "addServiceUrl": "Lägg till tjänst-URL",
    "selectFromOnline": "Lägg till från ArcGIS Online",
    "setServiceUrl": "Ange webbadressen till geobearbetningstjänsten.",
    "chooseItem": "Välj ett objekt från geobearbetningstjänsten.",
    "chooseTask": "Välj en geobearbetningsåtgärd."
  },
  "itemSelector": {
    "map": "Å_Map__ö",
    "selectWebMap": "Välj webbkarta",
    "addMapFromOnlineOrPortal": "Hitta och lägg till en webbkarta i applikationen från offentliga ArcGIS Online-resurser eller ditt privata innehåll i ArcGIS Online eller Portal.",
    "searchMapName": "Sök efter kartnamn ...",
    "searchNone": "Vi kunde inte hitta det du söker. Försök igen.",
    "groups": "Grupper",
    "noneGroups": "Inga grupper",
    "signInTip": "Din inloggningssession har gått ut. Uppdatera webbläsaren om du vill logga in på portalen igen.",
    "signIn": "Logga in",
    "publicMap": "Publik",
    "myOrganization": "Min organisation",
    "myGroup": "Mina grupper",
    "myContent": "Mitt innehåll",
    "count": "Å_Count___ö",
    "fromPortal": "från Portal",
    "fromOnline": "från ArcGIS.com",
    "noneThumbnail": "Ingen miniatyrbild finns tillgänglig",
    "owner": "ägare",
    "signInTo": "Logga in på",
    "lastModified": "Senast ändrad",
    "moreDetails": "Mer information"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Tjänsten stöder inte frågor."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Det finns inget lämpligt lager tillgängligt i kartan."
  },
  "layerInfosMenu": {
    "titleBasemap": "Baskartor",
    "titleLayers": "Funktionslager",
    "labelLayer": "Lagernamn",
    "itemZoomTo": "Zooma till",
    "itemTransparency": "Transparens",
    "itemTransparent": "Transparent",
    "itemOpaque": "Opak",
    "itemMoveUp": "Flytta uppåt",
    "itemMoveDown": "Flytta nedåt",
    "itemDesc": "Beskrivning",
    "itemDownload": "Hämta",
    "itemToAttributeTable": "Öppna attributtabell"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: webbläsaren har inte stöd för filläsnings-API",
    "readError": "Det gick inte att läsa filen.",
    "unknowError": "det gick inte att slutföra åtgärderna",
    "invalidType": "Ogiltig filtyp.",
    "cropImage": "Å_Crop Image____ö",
    "exceed": "Filstorleken får inte överskrida 1 024 KB",
    "enableFlash": "TODO: aktivera flash.",
    "cropWaining": "Välj ett foto som är på minst ${width} x ${height} pixlar.",
    "toolTip": "För bästa resultat ska bilden vara ${width} bildpunkter bred och ${height} bildpunkter hög. Andra storlekar justeras för att passa in. Tillåtna bildformat är: PNG, GIF och JPEG."
  },
  "simpleTable": {
    "moveUp": "Flytta uppåt",
    "moveDown": "Flytta nedåt",
    "deleteRow": "Ta bort",
    "edit": "Redigera"
  },
  "urlParams": {
    "invalidToken": "Ogiltig token",
    "validateTokenError": "Ogiltig token eller nätverksfel"
  },
  "exportTo": {
    "exportTo": "Exportera",
    "toCSV": "Exportera till CSV-fil",
    "toFeatureCollection": "Exportera till geoobjektssamling",
    "toGeoJSON": "Exportera till GeoJSON"
  },
  "appState": {
    "title": "Å_App State____ö",
    "restoreMap": "Klicka om du vill återställa kartutbredningen och lagrens synlighet där du slutade."
  },
  "featureActions": {
    "ZoomTo": "Å_Zoom to___ö",
    "PanTo": "Å_Pan to___ö",
    "Flash": "Å_Flash___ö",
    "ShowPopup": "Å_Show Pop-up____ö",
    "CreateLayer": "Å_Create Layer_____ö",
    "ShowStatistics": "Å_Statistics_____ö...",
    "ClearSelection": "Å_Clear Selection______ö",
    "ExportToCSV": "Å_Export to CSV file______ö",
    "ExportToFeatureCollection": "Å_Export to Feature Collection_________ö",
    "ExportToGeoJSON": "Å_Export to GeoJSON______ö"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Å_Related layer_____ö",
    "selectedFeatures": "Å_Selected features______ö",
    "drawShapesTip": "Å_Draw shapes to select features__________ö",
    "pleaseDrawShapesTip": "Å_Please draw shapes to select features____________ö",
    "allFeaturesTip": "Å_All features in the layer_________ö",
    "selectFeaturesOrDrawShapesTip": "Å_Please use selected features in this layer or draw shapes on map to limit features__________________________ö."
  },
  "searchDistance": {
    "applySearchDistance": "Å_Apply a search distance________ö",
    "applySearchDistanceToFeatures": "Å_Apply a search distance to selected features______________ö"
  },
  "units": {
    "miles": "Å_Miles___ö",
    "kilometers": "Å_Kilometers____ö",
    "feet": "Å_Feet__ö",
    "meters": "Å_Meters___ö",
    "yards": "Å_Yards___ö",
    "nauticalMiles": "Å_Nautical Miles_____ö"
  },
  "featureSetChooser": {
    "select": "Å_Select___ö",
    "dragBox": "Å_Drag__ö",
    "dragMouse": "Å_Darg the mouse_____ö",
    "selectByRectangle": "Å_Select By Rectangle_______ö",
    "selectFeaturesTip": "Å_Select features by dragging box around them on map________________ö",
    "newSelectionTip": "Å_Create a new selection________ö",
    "addSelectionTip": "Å_Add to the current selection_________ö",
    "removeSelectionTip": "Å_Remove from the current selection___________ö",
    "selectFromCurrentSelectionTip": "Å_Select from the current selection___________ö",
    "unselectAllSelectionTip": "Å_Unselect all currently selected features_____________ö"
  },
  "widgetManager": {
    "createWidgetError": "Å_Create widget error_______ö",
    "createWidgetSettingPageError": "Å_Create widget setting page error___________ö",
    "loadWidgetResourceError": "Å_Load widget resouce error_________ö"
  },
  "shareOptions": {
    "shareMap": "Å_Choose who can view this app_________ö",
    "shareMapTips": "Å_Your map is currentlt shared with these people_______________ö",
    "everyone": "Å_everyone___ö",
    "theseGroups": "Å_theseGroups____ö"
  },
  "shareLink": {
    "email": "Å_email___ö",
    "shareEmail": "Å_Email___ö",
    "facebook": "Å_facebook___ö",
    "shareFacebook": "Å_Facebook___ö",
    "twitter": "Å_twitter___ö",
    "shareTwitter": "Å_Twitter___ö",
    "googlePlus": "Å_googlePlus____ö",
    "shareGooglePlus": "Å_GooglePlus____ö",
    "EmbedTips": "Å_Embed this scene in a website__________ö",
    "shareEmailTxt1": "Å_Have a look at this Web Scene__________ö:",
    "shareEmailTxt2": "Å_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ö.",
    "smallSize": "Å_Small___ö",
    "mediumSize": "Å_Medium___ö",
    "largeSize": "Å_Large___ö",
    "customSize": "Å_Custom___ö",
    "embed": "Å_Embed this scene in a website__________ö",
    "more": "Å_Embed Options_____ö",
    "changeShareSettings": "Å_Change Share Settings_______ö",
    "shareLinkText": "Å_Choose who can view Copy________ö",
    "linkOptions": "Å_Link Options_____ö",
    "linkOptionsUrlParameters": "Å_Select URL parameters included in the link______________ö",
    "currentMapExtent": "Å_Current map extent______ö",
    "chooseCenterWithLevel": "Å_Click the map to define the center of the map with scale level____________________ö",
    "chooseCenterWithScale": "Å_Click the map to define the center of the map with map scale___________________ö",
    "findLocation": "Å_Find the location or feature and zoom to it______________ö",
    "findLocation_inputPlaceholder": "Å_Your place or feature_______ö",
    "queryFeature": "Å_Query a feature and zoom to it__________ö",
    "addMarker": "Å_Add a marker on the map________ö",
    "addMarker_titlePlaceholder": "Å_Title of the marker pop-up_________ö",
    "addMarker_symbolURL": "Å_Marker symbol URL______ö",
    "addMarker_label": "Å_Marker label_____ö",
    "overwirteMobileLayout": "Å_Overwrite default mobile layout__________ö",
    "language": "Å_Set the app language_______ö",
    "auth": "Å_Authenticate a user automatically___________ö",
    "linkPreview": "Å_Link Preview_____ö",
    "useShortenLink": "Å_Short Link____ö",
    "shareMapUrlExtent": "Å_shareMapUrlExtent______ö"
  },
  "webSceneLoader": {
    "webglSupportTip": "Å_3D web apps aren't supported in your browser_______________ö."
  }
});