define({
	addAChartSource: "ı_Add a Chart Source_İ",
	sourceLabel: "ı_Source label_İ",
	labelField: "ı_Label field_İ",
	actions: "ı_Actions_İ",
	hightLightColor: "ı_Highlight color_İ",
	urlChartSource: "ı_URL Chart Source_İ",
	layerChartSource: "ı_Layer Chart Source_İ",
	searchUrl: "ı_Search URL_İ",
	browse: "ı_Browse_İ",
	layers: "ı_Layers_İ",
	availableFields: "ı_Available Fields_İ",
	charts: "ı_Charts_İ",
	chartField: "ı_Chart field_İ",
	description: "ı_Description_İ",
	title: "ı_Title_İ",
	type: "ı_Type_İ",
	cancel: "ı_Cancel_İ",
	addChartSource: "ı_Add Chart Source_İ",
	updateChartSource: "ı_Update Chart Source_İ",
	chartSources: "ı_Chart Sources_İ",
	chartSource: "ı_Chart Source_İ",
	general: "ı_General_İ"
});