define({
  "common": {
    "apply": "Č_Apply___ž",
    "ok": "U redu",
    "cancel": "Otkaži",
    "yes": "Č_Yes__ž",
    "no": "Č_No__ž",
    "next": "Sledeće",
    "back": "Nazad",
    "selected": "Č_selected___ž",
    "name": "Naziv",
    "usage": "Č_Usage___ž",
    "settings": "Č_Settings___ž",
    "home": "Č_Home__ž",
    "link": "Č_Link__ž",
    "messages": "Č_Messages___ž",
    "outputs": "Č_Outputs___ž",
    "title": "Naslov",
    "thumbnail": "Č_Thumbnail____ž",
    "url": "Č_URL__ž",
    "actions": "Radnje",
    "layer": "Sloj",
    "action": "Č_Action___ž",
    "input": "Č_Input___ž",
    "output": "Č_Output___ž",
    "type": "Č_Type__ž",
    "required": "Č_Required___ž",
    "options": "Č_Options___ž",
    "label": "Oznaka",
    "tooltip": "Č_Tooltip___ž",
    "visible": "Č_Visible___ž",
    "symbol": "Č_Symbol___ž",
    "popup": "Č_Popup___ž",
    "upload": "Č_Upload___ž",
    "execute": "Č_Execute___ž",
    "help": "Č_Help__ž",
    "executing": "Č_Executing____ž",
    "clear": "Izbriši",
    "error": "Č_Error___ž",
    "zoomTo": "Uveličaj na",
    "attribute": "Č_Attribute____ž",
    "exports": "Č_Export___ž",
    "check": "Č_Check___ž",
    "save": "Č_Save__ž",
    "close": "Č_Close___ž",
    "deleteText": "Č_Delete___ž",
    "map": "Mapa",
    "scene": "Č_Scene___ž",
    "reset": "Č_Reset___ž",
    "icon": "Č_Icon__ž",
    "share": "Č_Share___ž"
  },
  "errorCode": "Kôd",
  "errorMessage": "Poruka",
  "errorDetail": "Detalj",
  "widgetPlaceholderTooltip": "Da biste postavili, idite na „Vidžet“ i kliknite na odgovarajućeg čuvara mesta",
  "fieldStatistics": {
    "statistics": "Č_Statistics____ž",
    "field": "Polje",
    "count": "Č_Number of Values______ž",
    "sum": "Č_Sum of Values_____ž",
    "min": "Č_Minimum___ž",
    "max": "Č_Maximum___ž",
    "ave": "Č_Average___ž",
    "stddev": "Č_Standard Deviation______ž"
  },
  "symbolChooser": {
    "preview": "Pregledaj",
    "basic": "Osnovna verzija",
    "arrows": "Strelice",
    "business": "Privreda",
    "cartographic": "Kartografija",
    "nationalParkService": "Servis nacionalnih parkova u SAD (National Park Service)",
    "outdoorRecreation": "Rekreacija napolju",
    "peoplePlaces": "Ljudi i mesta",
    "safetyHealth": "Bezbednost i zdravlje",
    "shapes": "Oblici",
    "transportation": "Transport",
    "symbolSize": "Veličina simbola",
    "color": "Boja",
    "alpha": "Alpha",
    "outlineColor": "Boja konture",
    "outlineWidth": "Širina konture",
    "style": "Stil",
    "width": "Širina",
    "text": "Tekst",
    "fontColor": "Boja fonta",
    "fontSize": "Veličina fonta",
    "transparency": "Prozirnost",
    "solid": "Neprozirno",
    "dash": "Crta",
    "dot": "Tačka",
    "dashDot": "Crta tačka",
    "dashDotDot": "Crta tačka tačka"
  },
  "transparency": {
    "opaque": "Neprozirno",
    "transparent": "Prozirno"
  },
  "rendererChooser": {
    "domain": "Domen",
    "use": "Koristi",
    "singleSymbol": "Pojedinačan simbol",
    "uniqueSymbol": "Jedinstveni simbol",
    "color": "Boja",
    "size": "Veličina",
    "toShow": "Za prikaz",
    "colors": "Boje",
    "classes": "Klase",
    "symbolSize": "Veličina simbola",
    "addValue": "Dodaj vrednost",
    "setDefaultSymbol": "Postavi podrazumevani simbol",
    "defaultSymbol": "Podrazumevani simbol",
    "selectedSymbol": "Izabrani simbol",
    "value": "Vrednost",
    "label": "Č_Label___ž",
    "range": "Opseg"
  },
  "drawBox": {
    "point": "Tačka",
    "line": "Linija",
    "polyline": "Poligon",
    "freehandPolyline": "Poligon slobodnom rukom",
    "triangle": "Trougao",
    "extent": "Obuhvat",
    "circle": "Krug",
    "ellipse": "Elipsa",
    "polygon": "Polilinija",
    "freehandPolygon": "Polilinija slobodnom rukom",
    "text": "Tekst",
    "clear": "Č_Clear___ž"
  },
  "popupConfig": {
    "title": "Č_Title___ž",
    "add": "Dodaj",
    "fields": "Polja",
    "noField": "Nema polja",
    "visibility": "Vidljivo",
    "name": "Č_Name__ž",
    "alias": "Pseudonim",
    "actions": "Č_Actions___ž"
  },
  "includeButton": {
    "include": "Uključi"
  },
  "loadingShelter": {
    "loading": "Učitavanje"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nema pronađenog servisa.",
    "unableConnectTo": "Nije moguće povezivanje na",
    "invalidUrlTip": "Uneta URL adresa je nevažeća ili nedostupna."
  },
  "serviceBrowser": {
    "noGpFound": "Nema pronađenog servisa geoprocesiranja.",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nema pronađenog servisa mape ili servisa geoobjekata",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "basicServiceChooser": {
    "validate": "Proveri valjanost",
    "example": "Primer",
    "set": "Postavi"
  },
  "urlInput": {
    "invalidUrl": "Nevažeća URL adresa."
  },
  "urlComboBox": {
    "invalidUrl": "Nevažeća URL adresa."
  },
  "filterBuilder": {
    "addAnotherExpression": "Dodaj izraz filtera",
    "addSet": "Dodaj set izraza",
    "matchMsg": "Ubaci u sloj geoobjekte koji se podudaraju sa ${any_or_all} od sledećih izraza",
    "matchMsgSet": "${any_or_all} sledeći izrazi u ovom setu su istiniti",
    "all": "Sve",
    "any": "Bilo koje",
    "value": "Vrednost",
    "field": "Č_Field___ž",
    "unique": "Jedinstveno",
    "none": "Ništa",
    "and": "i",
    "valueTooltip": "Unesite vrednost",
    "fieldTooltip": "Izaberi iz postojećeg polja",
    "uniqueValueTooltip": "Izaberi iz jedinstvenih vrednosti u izabranom polju",
    "stringOperatorIs": "je",
    "stringOperatorIsNot": "nije",
    "stringOperatorStartsWith": "počinje sa",
    "stringOperatorEndsWith": "završava se sa",
    "stringOperatorContains": "sadrži",
    "stringOperatorDoesNotContain": "ne sadrži",
    "stringOperatorIsBlank": "je prazno",
    "stringOperatorIsNotBlank": "nije prazno",
    "dateOperatorIsOn": "je na",
    "dateOperatorIsNotOn": "nije na",
    "dateOperatorIsBefore": "je ispred",
    "dateOperatorIsAfter": "je iza",
    "dateOperatorDays": "dani",
    "dateOperatorWeeks": "sedmice",
    "dateOperatorMonths": "meseci",
    "dateOperatorInTheLast": "u poslednjih",
    "dateOperatorNotInTheLast": "nije u poslednjih",
    "dateOperatorIsBetween": "je između",
    "dateOperatorIsNotBetween": "nije između",
    "dateOperatorIsBlank": "je prazno",
    "dateOperatorIsNotBlank": "nije prazno",
    "numberOperatorIs": "je",
    "numberOperatorIsNot": "nije",
    "numberOperatorIsAtLeast": "je najmanje",
    "numberOperatorIsLessThan": "je manje od",
    "numberOperatorIsAtMost": "je najviše",
    "numberOperatorIsGreaterThan": "je veće od",
    "numberOperatorIsBetween": "je između",
    "numberOperatorIsNotBetween": "nije između",
    "numberOperatorIsBlank": "je prazno",
    "numberOperatorIsNotBlank": "nije prazno",
    "string": "Niska",
    "number": "Broj",
    "date": "Datum",
    "askForValues": "Traži vrednosti",
    "prompt": "Odziv",
    "hint": "Napomena",
    "error": {
      "invalidParams": "Nevažeći parametri.",
      "invalidUrl": "Nevažeća URL adresa.",
      "noFilterFields": "Sloj nema polja koja mogu da budu korišćena za filter.",
      "invalidSQL": "Nevažeći SQL izraz.",
      "cantParseSQL": "Parsiranje SQL izraza nije moguće."
    },
    "caseSensitive": "Razlikuje velika i mala slova",
    "notSupportCaseSensitiveTip": "Hostovani servisi ne podržavaju upite koji razlikuju velika i mala slova."
  },
  "featureLayerSource": {
    "layer": "Sloj",
    "browse": "Pretraži",
    "selectFromMap": "Izaberi iz mape",
    "selectFromPortal": "Dodaj iz Portal for ArcGIS",
    "addServiceUrl": "Dodaj URL adresu servisa",
    "inputLayerUrl": "URL adresa ulaznog sloja",
    "selectLayer": "Izaberite sloj geoobjekata iz trenutne mape.",
    "chooseItem": "Odaberite stavku sloja geoobjekata.",
    "setServiceUrl": "Unesite URL adresu servisa geoobjekata ili servisa mape.",
    "selectFromOnline": "Dodaj iz ArcGIS Online",
    "chooseLayer": "Odaberite sloj geoobjekata."
  },
  "queryableLayerSource": {
    "layer": "Č_Layer___ž",
    "browse": "Pretraži",
    "selectFromMap": "Izaberi iz mape",
    "selectFromPortal": "Dodaj iz Portal for ArcGIS",
    "addServiceUrl": "Dodaj URL adresu servisa",
    "inputLayerUrl": "URL adresa ulaznog sloja",
    "selectLayer": "Izaberi sloj iz trenutne mape.",
    "chooseItem": "Odaberite stavku.",
    "setServiceUrl": "Unesite URL adresu servisa.",
    "selectFromOnline": "Dodaj iz ArcGIS Online",
    "chooseLayer": "Odaberite sloj."
  },
  "gpSource": {
    "selectFromPortal": "Dodaj iz Portal for ArcGIS",
    "addServiceUrl": "Dodaj URL adresu servisa",
    "selectFromOnline": "Dodaj iz ArcGIS Online",
    "setServiceUrl": "Unesite URL adresu servisa geoprocesiranja.",
    "chooseItem": "Odaberite stavku servisa geoprocesiranja.",
    "chooseTask": "Odaberite zadatak geoprocesiranja."
  },
  "itemSelector": {
    "map": "Č_Map__ž",
    "selectWebMap": "Odaberite veb mapu",
    "addMapFromOnlineOrPortal": "Pronađite i dodajte veb mapu u aplikaciju sa ArcGIS Online javnih resursa ili vašeg privatnog sadržaja u ArcGIS Online ili na Portalu.",
    "searchMapName": "Pretraži po imenu mape...",
    "searchNone": "Nismo uspeli da nađemo ono što tražite. Pokušajte ponovo.",
    "groups": "Grupe",
    "noneGroups": "Nema grupa",
    "signInTip": "Vaša sesija prijavljivanja je istekla, osvežite pregledač da biste se ponovo prijavili u portal.",
    "signIn": "Prijavite se",
    "publicMap": "Javni",
    "myOrganization": "Moja organizacija",
    "myGroup": "Moje grupe",
    "myContent": "Moj sadržaj",
    "count": "Č_Count___ž",
    "fromPortal": "sa portala",
    "fromOnline": "sa ArcGIS.com",
    "noneThumbnail": "Sličica nije dostupna",
    "owner": "vlasnik",
    "signInTo": "Prijavite se na",
    "lastModified": "Poslednja izmena",
    "moreDetails": "Više detalja"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Servis ne podržava upit."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Nema odgovarajućeg sloja dostupnog u mapi."
  },
  "layerInfosMenu": {
    "titleBasemap": "Pozadinske mape",
    "titleLayers": "Operativni slojevi",
    "labelLayer": "Ime sloja",
    "itemZoomTo": "Uveličaj na",
    "itemTransparency": "Prozirnost",
    "itemTransparent": "Prozirno",
    "itemOpaque": "Neprozirno",
    "itemMoveUp": "Pomeri se na gore",
    "itemMoveDown": "Pomeri se na dole",
    "itemDesc": "Opis",
    "itemDownload": "Preuzmi",
    "itemToAttributeTable": "Otvori tabelu atributa"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Zaduženja: pregledač ne podržava API čitač podataka",
    "readError": "Čitanje datoteke nije uspelo.",
    "unknowError": "završetak operacija nije moguć",
    "invalidType": "Nevažeći tip datoteke.",
    "cropImage": "Č_Crop Image____ž",
    "exceed": "Veličina datoteke ne može da premaši 1024 KB",
    "enableFlash": "Zaduženja: aktivirajte flash.",
    "cropWaining": "Odaberite fotografiju čije su dimenzije najmanje ${width} x ${height} piksela.",
    "toolTip": "Za najbolje rezultate, snimak treba da bude ${width} piksela širok i ${height} piksela visok. Ostale veličine će biti prilagođene da se uklope. Prihvatljivi formati snimaka su: PNG, GIF i JPEG."
  },
  "simpleTable": {
    "moveUp": "Pomeri se na gore",
    "moveDown": "Pomeri se na dole",
    "deleteRow": "Obriši",
    "edit": "Izmeni"
  },
  "urlParams": {
    "invalidToken": "Nevažeći token",
    "validateTokenError": "Nevažeći token ili greška na mreži"
  },
  "exportTo": {
    "exportTo": "Izvezi",
    "toCSV": "Izvezi u CSV datoteku",
    "toFeatureCollection": "Izvezi u kolekciju geoobjekata",
    "toGeoJSON": "Izvezi u GeoJSON"
  },
  "appState": {
    "title": "Č_App State____ž",
    "restoreMap": "Kliknite da biste vratili obuhvat mape i vidljivost slojeva gde ste stali."
  },
  "featureActions": {
    "ZoomTo": "Č_Zoom to___ž",
    "PanTo": "Č_Pan to___ž",
    "Flash": "Č_Flash___ž",
    "ShowPopup": "Č_Show Pop-up____ž",
    "CreateLayer": "Č_Create Layer_____ž",
    "ShowStatistics": "Č_Statistics_____ž...",
    "ClearSelection": "Č_Clear Selection______ž",
    "ExportToCSV": "Č_Export to CSV file______ž",
    "ExportToFeatureCollection": "Č_Export to Feature Collection_________ž",
    "ExportToGeoJSON": "Č_Export to GeoJSON______ž"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Č_Related layer_____ž",
    "selectedFeatures": "Č_Selected features______ž",
    "drawShapesTip": "Č_Draw shapes to select features__________ž",
    "pleaseDrawShapesTip": "Č_Please draw shapes to select features____________ž",
    "allFeaturesTip": "Č_All features in the layer_________ž",
    "selectFeaturesOrDrawShapesTip": "Č_Please use selected features in this layer or draw shapes on map to limit features__________________________ž."
  },
  "searchDistance": {
    "applySearchDistance": "Č_Apply a search distance________ž",
    "applySearchDistanceToFeatures": "Č_Apply a search distance to selected features______________ž"
  },
  "units": {
    "miles": "Č_Miles___ž",
    "kilometers": "Č_Kilometers____ž",
    "feet": "Č_Feet__ž",
    "meters": "Č_Meters___ž",
    "yards": "Č_Yards___ž",
    "nauticalMiles": "Č_Nautical Miles_____ž"
  },
  "featureSetChooser": {
    "select": "Č_Select___ž",
    "dragBox": "Č_Drag__ž",
    "dragMouse": "Č_Darg the mouse_____ž",
    "selectByRectangle": "Č_Select By Rectangle_______ž",
    "selectFeaturesTip": "Č_Select features by dragging box around them on map________________ž",
    "newSelectionTip": "Č_Create a new selection________ž",
    "addSelectionTip": "Č_Add to the current selection_________ž",
    "removeSelectionTip": "Č_Remove from the current selection___________ž",
    "selectFromCurrentSelectionTip": "Č_Select from the current selection___________ž",
    "unselectAllSelectionTip": "Č_Unselect all currently selected features_____________ž"
  },
  "widgetManager": {
    "createWidgetError": "Č_Create widget error_______ž",
    "createWidgetSettingPageError": "Č_Create widget setting page error___________ž",
    "loadWidgetResourceError": "Č_Load widget resouce error_________ž"
  },
  "shareOptions": {
    "shareMap": "Č_Choose who can view this app_________ž",
    "shareMapTips": "Č_Your map is currentlt shared with these people_______________ž",
    "everyone": "Č_everyone___ž",
    "theseGroups": "Č_theseGroups____ž"
  },
  "shareLink": {
    "email": "Č_email___ž",
    "shareEmail": "Č_Email___ž",
    "facebook": "Č_facebook___ž",
    "shareFacebook": "Č_Facebook___ž",
    "twitter": "Č_twitter___ž",
    "shareTwitter": "Č_Twitter___ž",
    "googlePlus": "Č_googlePlus____ž",
    "shareGooglePlus": "Č_GooglePlus____ž",
    "EmbedTips": "Č_Embed this scene in a website__________ž",
    "shareEmailTxt1": "Č_Have a look at this Web Scene__________ž:",
    "shareEmailTxt2": "Č_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ž.",
    "smallSize": "Č_Small___ž",
    "mediumSize": "Č_Medium___ž",
    "largeSize": "Č_Large___ž",
    "customSize": "Č_Custom___ž",
    "embed": "Č_Embed this scene in a website__________ž",
    "more": "Č_Embed Options_____ž",
    "changeShareSettings": "Č_Change Share Settings_______ž",
    "shareLinkText": "Č_Choose who can view Copy________ž",
    "linkOptions": "Č_Link Options_____ž",
    "linkOptionsUrlParameters": "Č_Select URL parameters included in the link______________ž",
    "currentMapExtent": "Č_Current map extent______ž",
    "chooseCenterWithLevel": "Č_Click the map to define the center of the map with scale level____________________ž",
    "chooseCenterWithScale": "Č_Click the map to define the center of the map with map scale___________________ž",
    "findLocation": "Č_Find the location or feature and zoom to it______________ž",
    "findLocation_inputPlaceholder": "Č_Your place or feature_______ž",
    "queryFeature": "Č_Query a feature and zoom to it__________ž",
    "addMarker": "Č_Add a marker on the map________ž",
    "addMarker_titlePlaceholder": "Č_Title of the marker pop-up_________ž",
    "addMarker_symbolURL": "Č_Marker symbol URL______ž",
    "addMarker_label": "Č_Marker label_____ž",
    "overwirteMobileLayout": "Č_Overwrite default mobile layout__________ž",
    "language": "Č_Set the app language_______ž",
    "auth": "Č_Authenticate a user automatically___________ž",
    "linkPreview": "Č_Link Preview_____ž",
    "useShortenLink": "Č_Short Link____ž",
    "shareMapUrlExtent": "Č_shareMapUrlExtent______ž"
  },
  "webSceneLoader": {
    "webglSupportTip": "Č_3D web apps aren't supported in your browser_______________ž."
  }
});