define({
	addAChartSource: "Ă_Add a Chart Source_ș",
	sourceLabel: "Ă_Source label_ș",
	labelField: "Ă_Label field_ș",
	actions: "Ă_Actions_ș",
	hightLightColor: "Ă_Highlight color_ș",
	urlChartSource: "Ă_URL Chart Source_ș",
	layerChartSource: "Ă_Layer Chart Source_ș",
	searchUrl: "Ă_Search URL_ș",
	browse: "Ă_Browse_ș",
	layers: "Ă_Layers_ș",
	availableFields: "Ă_Available Fields_ș",
	charts: "Ă_Charts_ș",
	chartField: "Ă_Chart field_ș",
	description: "Ă_Description_ș",
	title: "Ă_Title_ș",
	type: "Ă_Type_ș",
	cancel: "Ă_Cancel_ș",
	addChartSource: "Ă_Add Chart Source_ș",
	updateChartSource: "Ă_Update Chart Source_ș",
	chartSources: "Ă_Chart Sources_ș",
	chartSource: "Ă_Chart Source_ș",
	general: "Ă_General_ș"
});