define({
  "common": {
    "apply": "å_Apply___ø",
    "ok": "OK",
    "cancel": "Avbryt",
    "yes": "å_Yes__ø",
    "no": "å_No__ø",
    "next": "Neste",
    "back": "Bak",
    "selected": "å_selected___ø",
    "name": "Navn",
    "usage": "å_Usage___ø",
    "settings": "å_Settings___ø",
    "home": "å_Home__ø",
    "link": "å_Link__ø",
    "messages": "å_Messages___ø",
    "outputs": "å_Outputs___ø",
    "title": "Tittel",
    "thumbnail": "å_Thumbnail____ø",
    "url": "å_URL__ø",
    "actions": "Handlinger",
    "layer": "Lag",
    "action": "å_Action___ø",
    "input": "å_Input___ø",
    "output": "å_Output___ø",
    "type": "å_Type__ø",
    "required": "å_Required___ø",
    "options": "å_Options___ø",
    "label": "Etikett",
    "tooltip": "å_Tooltip___ø",
    "visible": "å_Visible___ø",
    "symbol": "å_Symbol___ø",
    "popup": "å_Popup___ø",
    "upload": "å_Upload___ø",
    "execute": "å_Execute___ø",
    "help": "å_Help__ø",
    "executing": "å_Executing____ø",
    "clear": "Fjern",
    "error": "å_Error___ø",
    "zoomTo": "Zoom til",
    "attribute": "å_Attribute____ø",
    "exports": "å_Export___ø",
    "check": "å_Check___ø",
    "save": "å_Save__ø",
    "close": "å_Close___ø",
    "deleteText": "å_Delete___ø",
    "map": "Kart",
    "scene": "å_Scene___ø",
    "reset": "å_Reset___ø",
    "icon": "å_Icon__ø",
    "share": "å_Share___ø"
  },
  "errorCode": "Kode",
  "errorMessage": "Melding",
  "errorDetail": "Detaljer",
  "widgetPlaceholderTooltip": "For å konfigurere går du til Widgeter og klikker på tilsvarende plassholder",
  "fieldStatistics": {
    "statistics": "å_Statistics____ø",
    "field": "Felt",
    "count": "å_Number of Values______ø",
    "sum": "å_Sum of Values_____ø",
    "min": "å_Minimum___ø",
    "max": "å_Maximum___ø",
    "ave": "å_Average___ø",
    "stddev": "å_Standard Deviation______ø"
  },
  "symbolChooser": {
    "preview": "Forhåndsvisning",
    "basic": "Grunnleggende",
    "arrows": "Piler",
    "business": "Næringsliv",
    "cartographic": "Kartografisk",
    "nationalParkService": "National Park Service",
    "outdoorRecreation": "Utendørsaktiviteter",
    "peoplePlaces": "Folk og steder",
    "safetyHealth": "Helse og sikkerhet",
    "shapes": "Former",
    "transportation": "Transport",
    "symbolSize": "Symbolstørrelse",
    "color": "Farge",
    "alpha": "Alfa",
    "outlineColor": "Omrissfarge",
    "outlineWidth": "Omrissbredde",
    "style": "Stil",
    "width": "Bredde",
    "text": "Tekst",
    "fontColor": "Skriftfarge",
    "fontSize": "Skriftstørrelse",
    "transparency": "Gjennomsiktighet",
    "solid": "Heltrukket",
    "dash": "Strek",
    "dot": "Prikk",
    "dashDot": "Strek prikk",
    "dashDotDot": "Strek prikk prikk"
  },
  "transparency": {
    "opaque": "Ugjennomsiktig",
    "transparent": "Gjennomsiktighet"
  },
  "rendererChooser": {
    "domain": "Domene",
    "use": "Bruke",
    "singleSymbol": "Et enkeltsymbol",
    "uniqueSymbol": "Unike symboler",
    "color": "Farge",
    "size": "Størrelse",
    "toShow": "Å vise",
    "colors": "Farger",
    "classes": "Klasser:",
    "symbolSize": "Symbolstørrelse",
    "addValue": "Legg til verdi",
    "setDefaultSymbol": "Angi standardsymbol",
    "defaultSymbol": "Standardsymbol",
    "selectedSymbol": "Valgt symbol",
    "value": "Verdi",
    "label": "å_Label___ø",
    "range": "Område"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihåndspolylinje",
    "triangle": "Trekant",
    "extent": "Utstrekning",
    "circle": "Sirkel",
    "ellipse": "Ellipse",
    "polygon": "Polygon",
    "freehandPolygon": "Frihåndspolygon",
    "text": "Tekst",
    "clear": "å_Clear___ø"
  },
  "popupConfig": {
    "title": "å_Title___ø",
    "add": "Legg til",
    "fields": "Felter",
    "noField": "Ingen felt",
    "visibility": "Synlig",
    "name": "å_Name__ø",
    "alias": "Alias",
    "actions": "å_Actions___ø"
  },
  "includeButton": {
    "include": "Inkluder"
  },
  "loadingShelter": {
    "loading": "Laster inn"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Ingen tjeneste funnet.",
    "unableConnectTo": "Kan ikke koble til",
    "invalidUrlTip": "URL-en du har angitt, er ugyldig eller ikke tilgjengelig."
  },
  "serviceBrowser": {
    "noGpFound": "Fant ingen geoprosesseringstjeneste.",
    "unableConnectTo": "Kan ikke koble til"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Fant ingen kart- eller featuretjeneste",
    "unableConnectTo": "Kan ikke koble til"
  },
  "basicServiceChooser": {
    "validate": "Valider",
    "example": "Eksempel",
    "set": "Angi"
  },
  "urlInput": {
    "invalidUrl": "Ugyldig URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ugyldig URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Legg til et filteruttrykk",
    "addSet": "Legg til et uttrykkssett",
    "matchMsg": "Hent geoobjekter i laget som samsvarer med ${any_or_all} av følgende uttrykk",
    "matchMsgSet": "${any_or_all} av de følgende uttrykkene i dette settet er sanne",
    "all": "Alle",
    "any": "Noen",
    "value": "Verdi",
    "field": "å_Field___ø",
    "unique": "Unike",
    "none": "Ingen",
    "and": "og",
    "valueTooltip": "Angi verdi",
    "fieldTooltip": "Velg fra eksisterende felt",
    "uniqueValueTooltip": "Velg blant unike verdier i det valgte feltet",
    "stringOperatorIs": "er",
    "stringOperatorIsNot": "er ikke",
    "stringOperatorStartsWith": "begynner på",
    "stringOperatorEndsWith": "slutter på",
    "stringOperatorContains": "inneholder",
    "stringOperatorDoesNotContain": "inneholder ikke",
    "stringOperatorIsBlank": "er tomt",
    "stringOperatorIsNotBlank": "er ikke tomt",
    "dateOperatorIsOn": "er den",
    "dateOperatorIsNotOn": "er ikke den",
    "dateOperatorIsBefore": "er før",
    "dateOperatorIsAfter": "er etter",
    "dateOperatorDays": "dagene",
    "dateOperatorWeeks": "ukene",
    "dateOperatorMonths": "månedene",
    "dateOperatorInTheLast": "i de/den siste",
    "dateOperatorNotInTheLast": "ikke i de/den siste",
    "dateOperatorIsBetween": "er mellom",
    "dateOperatorIsNotBetween": "er ikke mellom",
    "dateOperatorIsBlank": "er tomt",
    "dateOperatorIsNotBlank": "er ikke tomt",
    "numberOperatorIs": "er",
    "numberOperatorIsNot": "er ikke",
    "numberOperatorIsAtLeast": "er minst",
    "numberOperatorIsLessThan": "er mindre enn",
    "numberOperatorIsAtMost": "er maksimalt",
    "numberOperatorIsGreaterThan": "er større enn",
    "numberOperatorIsBetween": "er mellom",
    "numberOperatorIsNotBetween": "er ikke mellom",
    "numberOperatorIsBlank": "er tomt",
    "numberOperatorIsNotBlank": "er ikke tomt",
    "string": "Streng",
    "number": "Tall",
    "date": "Dato",
    "askForValues": "Spør om verdier",
    "prompt": "Spør",
    "hint": "Tips:",
    "error": {
      "invalidParams": "Ugyldige parametere.",
      "invalidUrl": "Ugyldig URL.",
      "noFilterFields": "Laget har ingen felter som kan brukes til filtrering.",
      "invalidSQL": "Ugyldig SQL-uttrykk.",
      "cantParseSQL": "Kan ikke analysere SQL-uttrykket."
    },
    "caseSensitive": "Skille mellom store og små bokstaver",
    "notSupportCaseSensitiveTip": "Administrerte tjenester støtter ikke spørringer som skiller mellom små og store bokstaver."
  },
  "featureLayerSource": {
    "layer": "Lag",
    "browse": "Bla gjennom",
    "selectFromMap": "Velg fra kart",
    "selectFromPortal": "Legg til fra Portal for ArcGIS",
    "addServiceUrl": "Legg til tjeneste-URL",
    "inputLayerUrl": "Angi kartlag-URL",
    "selectLayer": "Velg et geoobjektslag i gjeldende kart.",
    "chooseItem": "Velg et geoobjektslagelement.",
    "setServiceUrl": "Angi URL-adressen for feature- eller karttjeneste.",
    "selectFromOnline": "Legg til fra ArcGIS Online",
    "chooseLayer": "Velg et geoobjektslag."
  },
  "queryableLayerSource": {
    "layer": "å_Layer___ø",
    "browse": "Bla gjennom",
    "selectFromMap": "Velg fra kart",
    "selectFromPortal": "Legg til fra Portal for ArcGIS",
    "addServiceUrl": "Legg til tjeneste-URL",
    "inputLayerUrl": "Angi kartlag-URL",
    "selectLayer": "Velg et lag fra det gjeldende kartet.",
    "chooseItem": "Velg et element.",
    "setServiceUrl": "Angi URL-adressen til tjenesten.",
    "selectFromOnline": "Legg til fra ArcGIS Online",
    "chooseLayer": "Velg et lag."
  },
  "gpSource": {
    "selectFromPortal": "Legg til fra Portal for ArcGIS",
    "addServiceUrl": "Legg til tjeneste-URL",
    "selectFromOnline": "Legg til fra ArcGIS Online",
    "setServiceUrl": "Oppgi URL-en for geoprosesseringstjenesten.",
    "chooseItem": "Velg et element for geoprosesseringstjenesten.",
    "chooseTask": "Velg en geoprosesseringsoppgave."
  },
  "itemSelector": {
    "map": "å_Map__ø",
    "selectWebMap": "Velg webkart",
    "addMapFromOnlineOrPortal": "Finn og legg til et webkart som skal brukes i applikasjonen, fra ArcGIS Onlines offentlige ressurser eller ditt private innhold på ArcGIS Online eller Portal.",
    "searchMapName": "Søk etter kartnavn ...",
    "searchNone": "Vi finner ikke det du leter etter. Prøv på nytt.",
    "groups": "Grupper",
    "noneGroups": "Ingen grupper",
    "signInTip": "Påloggingsøkten har utløpt. Oppdater websiden for å logge på portalen din igjen.",
    "signIn": "Logg inn",
    "publicMap": "Felles",
    "myOrganization": "Min organisasjon",
    "myGroup": "Mine grupper",
    "myContent": "Mitt innhold",
    "count": "å_Count___ø",
    "fromPortal": "fra Portal",
    "fromOnline": "fra ArcGIS.com",
    "noneThumbnail": "Miniatyrbilde ikke tilgjengelig",
    "owner": "owner",
    "signInTo": "Logg inn på",
    "lastModified": "Sist endret",
    "moreDetails": "Flere detaljer"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Tjenesten støtter ikke spørringer."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Det er ingen aktuelle lag tilgjengelig i kartet."
  },
  "layerInfosMenu": {
    "titleBasemap": "Bakgrunnskart",
    "titleLayers": "Operative kartlag",
    "labelLayer": "Lagnavn",
    "itemZoomTo": "Zoom til",
    "itemTransparency": "Gjennomsiktighet",
    "itemTransparent": "Gjennomsiktig",
    "itemOpaque": "Ugjennomsiktig",
    "itemMoveUp": "Flytt opp",
    "itemMoveDown": "Flytt ned",
    "itemDesc": "Beskrivelse",
    "itemDownload": "Last ned",
    "itemToAttributeTable": "Åpne attributtabell"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: Leseren støtter ikke filleser-API",
    "readError": "Kan ikke lese filen.",
    "unknowError": "kan ikke fullføre operasjonene",
    "invalidType": "Ugyldig filtype.",
    "cropImage": "å_Crop Image____ø",
    "exceed": "Filstørrelsen må ikke overskride 1 024 kB",
    "enableFlash": "TODO: aktiver flash.",
    "cropWaining": "Velg et bilde som er minst ${width} x ${height} piksler.",
    "toolTip": "Resultatet blir best hvis bildet er ${width} piksler bredt og ${height} piksler høyt. Andre størrelser må justeres for at de skal passe. Godkjente bildeformater er: PNG, GIF og JPEG."
  },
  "simpleTable": {
    "moveUp": "Flytt opp",
    "moveDown": "Flytt ned",
    "deleteRow": "Slett",
    "edit": "Rediger"
  },
  "urlParams": {
    "invalidToken": "Ugyldig token",
    "validateTokenError": "Ugyldig token eller nettverksfeil"
  },
  "exportTo": {
    "exportTo": "Eksporter",
    "toCSV": "Eksporter til CSV-fil",
    "toFeatureCollection": "Eksporter til geoobjektssamling",
    "toGeoJSON": "Eksporter til GeoJSON"
  },
  "appState": {
    "title": "å_App State____ø",
    "restoreMap": "Klikk for å gjenopprette kartutstrekningen og synligheten for lagene der du slapp."
  },
  "featureActions": {
    "ZoomTo": "å_Zoom to___ø",
    "PanTo": "å_Pan to___ø",
    "Flash": "å_Flash___ø",
    "ShowPopup": "å_Show Pop-up____ø",
    "CreateLayer": "å_Create Layer_____ø",
    "ShowStatistics": "å_Statistics_____ø...",
    "ClearSelection": "å_Clear Selection______ø",
    "ExportToCSV": "å_Export to CSV file______ø",
    "ExportToFeatureCollection": "å_Export to Feature Collection_________ø",
    "ExportToGeoJSON": "å_Export to GeoJSON______ø"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "å_Related layer_____ø",
    "selectedFeatures": "å_Selected features______ø",
    "drawShapesTip": "å_Draw shapes to select features__________ø",
    "pleaseDrawShapesTip": "å_Please draw shapes to select features____________ø",
    "allFeaturesTip": "å_All features in the layer_________ø",
    "selectFeaturesOrDrawShapesTip": "å_Please use selected features in this layer or draw shapes on map to limit features__________________________ø."
  },
  "searchDistance": {
    "applySearchDistance": "å_Apply a search distance________ø",
    "applySearchDistanceToFeatures": "å_Apply a search distance to selected features______________ø"
  },
  "units": {
    "miles": "å_Miles___ø",
    "kilometers": "å_Kilometers____ø",
    "feet": "å_Feet__ø",
    "meters": "å_Meters___ø",
    "yards": "å_Yards___ø",
    "nauticalMiles": "å_Nautical Miles_____ø"
  },
  "featureSetChooser": {
    "select": "å_Select___ø",
    "dragBox": "å_Drag__ø",
    "dragMouse": "å_Darg the mouse_____ø",
    "selectByRectangle": "å_Select By Rectangle_______ø",
    "selectFeaturesTip": "å_Select features by dragging box around them on map________________ø",
    "newSelectionTip": "å_Create a new selection________ø",
    "addSelectionTip": "å_Add to the current selection_________ø",
    "removeSelectionTip": "å_Remove from the current selection___________ø",
    "selectFromCurrentSelectionTip": "å_Select from the current selection___________ø",
    "unselectAllSelectionTip": "å_Unselect all currently selected features_____________ø"
  },
  "widgetManager": {
    "createWidgetError": "å_Create widget error_______ø",
    "createWidgetSettingPageError": "å_Create widget setting page error___________ø",
    "loadWidgetResourceError": "å_Load widget resouce error_________ø"
  },
  "shareOptions": {
    "shareMap": "å_Choose who can view this app_________ø",
    "shareMapTips": "å_Your map is currentlt shared with these people_______________ø",
    "everyone": "å_everyone___ø",
    "theseGroups": "å_theseGroups____ø"
  },
  "shareLink": {
    "email": "å_email___ø",
    "shareEmail": "å_Email___ø",
    "facebook": "å_facebook___ø",
    "shareFacebook": "å_Facebook___ø",
    "twitter": "å_twitter___ø",
    "shareTwitter": "å_Twitter___ø",
    "googlePlus": "å_googlePlus____ø",
    "shareGooglePlus": "å_GooglePlus____ø",
    "EmbedTips": "å_Embed this scene in a website__________ø",
    "shareEmailTxt1": "å_Have a look at this Web Scene__________ø:",
    "shareEmailTxt2": "å_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ø.",
    "smallSize": "å_Small___ø",
    "mediumSize": "å_Medium___ø",
    "largeSize": "å_Large___ø",
    "customSize": "å_Custom___ø",
    "embed": "å_Embed this scene in a website__________ø",
    "more": "å_Embed Options_____ø",
    "changeShareSettings": "å_Change Share Settings_______ø",
    "shareLinkText": "å_Choose who can view Copy________ø",
    "linkOptions": "å_Link Options_____ø",
    "linkOptionsUrlParameters": "å_Select URL parameters included in the link______________ø",
    "currentMapExtent": "å_Current map extent______ø",
    "chooseCenterWithLevel": "å_Click the map to define the center of the map with scale level____________________ø",
    "chooseCenterWithScale": "å_Click the map to define the center of the map with map scale___________________ø",
    "findLocation": "å_Find the location or feature and zoom to it______________ø",
    "findLocation_inputPlaceholder": "å_Your place or feature_______ø",
    "queryFeature": "å_Query a feature and zoom to it__________ø",
    "addMarker": "å_Add a marker on the map________ø",
    "addMarker_titlePlaceholder": "å_Title of the marker pop-up_________ø",
    "addMarker_symbolURL": "å_Marker symbol URL______ø",
    "addMarker_label": "å_Marker label_____ø",
    "overwirteMobileLayout": "å_Overwrite default mobile layout__________ø",
    "language": "å_Set the app language_______ø",
    "auth": "å_Authenticate a user automatically___________ø",
    "linkPreview": "å_Link Preview_____ø",
    "useShortenLink": "å_Short Link____ø",
    "shareMapUrlExtent": "å_shareMapUrlExtent______ø"
  },
  "webSceneLoader": {
    "webglSupportTip": "å_3D web apps aren't supported in your browser_______________ø."
  }
});