define({
  "common": {
    "apply": "بيت_Apply___لاحقة",
    "ok": "موافق",
    "cancel": "إلغاء الأمر",
    "yes": "بيت_Yes__لاحقة",
    "no": "بيت_No__لاحقة",
    "next": "التالي",
    "back": "السابق",
    "selected": "بيت_selected___لاحقة",
    "name": "الاسم",
    "usage": "بيت_Usage___لاحقة",
    "settings": "بيت_Settings___لاحقة",
    "home": "بيت_Home__لاحقة",
    "link": "بيت_Link__لاحقة",
    "messages": "بيت_Messages___لاحقة",
    "outputs": "بيت_Outputs___لاحقة",
    "title": "العنوان",
    "thumbnail": "بيت_Thumbnail____لاحقة",
    "url": "بيت_URL__لاحقة",
    "actions": "الأفعال",
    "layer": "طبقة",
    "action": "بيت_Action___لاحقة",
    "input": "بيت_Input___لاحقة",
    "output": "بيت_Output___لاحقة",
    "type": "بيت_Type__لاحقة",
    "required": "بيت_Required___لاحقة",
    "options": "بيت_Options___لاحقة",
    "label": "لافتة التسمية",
    "tooltip": "بيت_Tooltip___لاحقة",
    "visible": "بيت_Visible___لاحقة",
    "symbol": "بيت_Symbol___لاحقة",
    "popup": "بيت_Popup___لاحقة",
    "upload": "بيت_Upload___لاحقة",
    "execute": "بيت_Execute___لاحقة",
    "help": "بيت_Help__لاحقة",
    "executing": "بيت_Executing____لاحقة",
    "clear": "مسح",
    "error": "بيت_Error___لاحقة",
    "zoomTo": "تكبير/تصغير إلى",
    "attribute": "بيت_Attribute____لاحقة",
    "exports": "بيت_Export___لاحقة",
    "check": "بيت_Check___لاحقة",
    "save": "بيت_Save__لاحقة",
    "close": "بيت_Close___لاحقة",
    "deleteText": "بيت_Delete___لاحقة",
    "map": "خريطة",
    "scene": "بيت_Scene___لاحقة",
    "reset": "بيت_Reset___لاحقة",
    "icon": "بيت_Icon__لاحقة",
    "share": "بيت_Share___لاحقة"
  },
  "errorCode": "كود",
  "errorMessage": "رسالة",
  "errorDetail": "تفاصيل",
  "widgetPlaceholderTooltip": "لتعينها، انتقل إلى عناصر واجهة الاستخدام وانقر على العناصر المتطابقة",
  "fieldStatistics": {
    "statistics": "بيت_Statistics____لاحقة",
    "field": "حقل",
    "count": "بيت_Number of Values______لاحقة",
    "sum": "بيت_Sum of Values_____لاحقة",
    "min": "بيت_Minimum___لاحقة",
    "max": "بيت_Maximum___لاحقة",
    "ave": "بيت_Average___لاحقة",
    "stddev": "بيت_Standard Deviation______لاحقة"
  },
  "symbolChooser": {
    "preview": "معاينة",
    "basic": "أساسي",
    "arrows": "الأسهم",
    "business": "أعمال تجارية",
    "cartographic": "رسم الخرائط",
    "nationalParkService": "خدمة المتنزه الوطني",
    "outdoorRecreation": "ترفيه خارجي",
    "peoplePlaces": "أماكن التجمعات",
    "safetyHealth": "الصحة العامة",
    "shapes": "الأشكال",
    "transportation": "نقل",
    "symbolSize": "حجم الرمز",
    "color": "لون",
    "alpha": "ألفا",
    "outlineColor": "اللون الأساسي",
    "outlineWidth": "العرض التفصيلي",
    "style": "نمط",
    "width": "العرض",
    "text": "النص",
    "fontColor": "لون الخط",
    "fontSize": "حجم الخط",
    "transparency": "معدل الشفافية:",
    "solid": "متصل",
    "dash": "شَرطَة",
    "dot": "نقطة",
    "dashDot": "شَرطَة ونقطة",
    "dashDotDot": "شَرطَة ونقطتين"
  },
  "transparency": {
    "opaque": "غير شفاف",
    "transparent": "شفاف"
  },
  "rendererChooser": {
    "domain": "مجال",
    "use": "استخدام",
    "singleSymbol": "رمز أحادي",
    "uniqueSymbol": "رموز فريدة",
    "color": "لون",
    "size": "الحجم",
    "toShow": "لإظهار",
    "colors": "ألوان",
    "classes": "تصنيفات",
    "symbolSize": "حجم الرمز",
    "addValue": "إضافة قيمة",
    "setDefaultSymbol": "تعيين الرمز الافتراضي",
    "defaultSymbol": "الرمز الافتراضي",
    "selectedSymbol": "الرمز المحدد",
    "value": "قيمة",
    "label": "بيت_Label___لاحقة",
    "range": "النطاق"
  },
  "drawBox": {
    "point": "نقطة",
    "line": "الخط",
    "polyline": "متعدد الخطوط",
    "freehandPolyline": "خط يدوي حر متعدد",
    "triangle": "مثلث",
    "extent": "المدى",
    "circle": "دائرة",
    "ellipse": "قطع ناقص",
    "polygon": "مضلع",
    "freehandPolygon": "مضلع مسوم بخط يدوي حر",
    "text": "النص",
    "clear": "بيت_Clear___لاحقة"
  },
  "popupConfig": {
    "title": "بيت_Title___لاحقة",
    "add": "إضافة",
    "fields": "حقول",
    "noField": "لا توجد حقول",
    "visibility": "مرئي",
    "name": "بيت_Name__لاحقة",
    "alias": "اسم مستعار",
    "actions": "بيت_Actions___لاحقة"
  },
  "includeButton": {
    "include": "تضمين"
  },
  "loadingShelter": {
    "loading": "تحميل"
  },
  "basicServiceBrowser": {
    "noServicesFound": "لا توجد خدمات",
    "unableConnectTo": "يتعذر الاتصال بـ",
    "invalidUrlTip": "عنوان URL الذي أدخلته غير صحيح أو يتعذر الوصول إليه."
  },
  "serviceBrowser": {
    "noGpFound": "لا توجد خدمة معالجة جغرافية.",
    "unableConnectTo": "يتعذر الاتصال بـ"
  },
  "layerServiceBrowser": {
    "noServicesFound": "لا توجد خدمة خريطة أو خدمة معالم",
    "unableConnectTo": "يتعذر الاتصال بـ"
  },
  "basicServiceChooser": {
    "validate": "تحقق",
    "example": "مثال",
    "set": "تعيين"
  },
  "urlInput": {
    "invalidUrl": "عنوان URL غير صحيح."
  },
  "urlComboBox": {
    "invalidUrl": "عنوان URL غير صحيح."
  },
  "filterBuilder": {
    "addAnotherExpression": "إضافة تعبير عامل تصفية",
    "addSet": "إضافة مجموعة التعبيرات",
    "matchMsg": "الحصول على المعالم في الطبقة التي تُطابق ${any_or_all} في التعبيرات التالية",
    "matchMsgSet": "${any_or_all} من التعبيرات التالية في هذه المجموعة صحيح",
    "all": "جميع",
    "any": "أي من",
    "value": "قيمة",
    "field": "بيت_Field___لاحقة",
    "unique": "فريد",
    "none": "بلا",
    "and": "و",
    "valueTooltip": "أدخل قيمة",
    "fieldTooltip": "اختيار من حقل حالي",
    "uniqueValueTooltip": "اختيار من قيم فريدة في حقل مُحدد",
    "stringOperatorIs": "هو",
    "stringOperatorIsNot": "ليس",
    "stringOperatorStartsWith": "البدء بـ",
    "stringOperatorEndsWith": "الانتهاء بـ",
    "stringOperatorContains": "يحتوي على",
    "stringOperatorDoesNotContain": "لا يحتوي على",
    "stringOperatorIsBlank": "فارغ",
    "stringOperatorIsNotBlank": "ليس فارغًا",
    "dateOperatorIsOn": "هو",
    "dateOperatorIsNotOn": "ليس",
    "dateOperatorIsBefore": "قبل",
    "dateOperatorIsAfter": "بعد",
    "dateOperatorDays": "يوم",
    "dateOperatorWeeks": "أسبوع",
    "dateOperatorMonths": "شهر",
    "dateOperatorInTheLast": "في آخر",
    "dateOperatorNotInTheLast": "ليس في الآخر",
    "dateOperatorIsBetween": "بين",
    "dateOperatorIsNotBetween": "ليس بين",
    "dateOperatorIsBlank": "فارغ",
    "dateOperatorIsNotBlank": "ليس فارغًا",
    "numberOperatorIs": "هو",
    "numberOperatorIsNot": "ليس",
    "numberOperatorIsAtLeast": "على الأقل",
    "numberOperatorIsLessThan": "أقل من",
    "numberOperatorIsAtMost": "في الغالب",
    "numberOperatorIsGreaterThan": "أكبر من",
    "numberOperatorIsBetween": "بين",
    "numberOperatorIsNotBetween": "ليس بين",
    "numberOperatorIsBlank": "فارغ",
    "numberOperatorIsNotBlank": "ليس فارغًا",
    "string": "سلسلة",
    "number": "عدد",
    "date": "التاريخ",
    "askForValues": "اسأل عن القيم",
    "prompt": "ترقية",
    "hint": "تلميح",
    "error": {
      "invalidParams": "معلمات غير صحيحة.",
      "invalidUrl": "عنوان URL غير صحيح.",
      "noFilterFields": "لا توجد حقول بالطبقة يمكن استخدامها للتصفية.",
      "invalidSQL": "تعبير SQL غير صحيح.",
      "cantParseSQL": "يتعذر توزيع تعبير SQL."
    },
    "caseSensitive": "تحسس حالة الأحرف",
    "notSupportCaseSensitiveTip": "الخدمات المستضافة لا تدعم الاستعلام الحساس للحالة."
  },
  "featureLayerSource": {
    "layer": "الطبقة",
    "browse": "استعراض",
    "selectFromMap": "تحديد من الخريطة",
    "selectFromPortal": "إضافة من Portal for ArcGIS",
    "addServiceUrl": "إضافة عنوان URL للخدمة",
    "inputLayerUrl": "إدخال عنوان URL للطبقة",
    "selectLayer": "تحديد طبقة معالم من الخريطة الحالية.",
    "chooseItem": "اختيار من عنصر طبقة معالم.",
    "setServiceUrl": "أدخل عنوان URL لخدمة المعالم أو خدمة الخريطة.",
    "selectFromOnline": "إضافة من ArcGIS Online",
    "chooseLayer": "اختر طبقة معلم."
  },
  "queryableLayerSource": {
    "layer": "بيت_Layer___لاحقة",
    "browse": "مربع حوار",
    "selectFromMap": "تحديد من الخريطة",
    "selectFromPortal": "إضافة من Portal for ArcGIS",
    "addServiceUrl": "إضافة عنوان URL للخدمة",
    "inputLayerUrl": "إدخال عنوان URL للطبقة",
    "selectLayer": "حدد طبقة من الخريطة الحالية.",
    "chooseItem": "اختر عنصر.",
    "setServiceUrl": "أدخل عنوان URL للخدمة.",
    "selectFromOnline": "إضافة من ArcGIS Online",
    "chooseLayer": "اختيار الطبقة"
  },
  "gpSource": {
    "selectFromPortal": "إضافة من Portal for ArcGIS",
    "addServiceUrl": "إضافة عنوان URL للخدمة",
    "selectFromOnline": "إضافة من ArcGIS Online",
    "setServiceUrl": "أدخل عنوان URL لخدمة المعالجة الجغرافية.",
    "chooseItem": "اختر عنصر خدمة المعالجة الجغرافية.",
    "chooseTask": "اختر مهمة المعالجة الجغرافية."
  },
  "itemSelector": {
    "map": "بيت_Map__لاحقة",
    "selectWebMap": "اختر خريطة الويب",
    "addMapFromOnlineOrPortal": "العثور على خريطة الويب وإضافتها للاستخدام في التطبيق من موارد ArcGIS Online العامة أو المحتويات الخاصة في ArcGIS Online أو البوابة الإلكترونية.",
    "searchMapName": "ابحث باستخدام اسم الخريطة...",
    "searchNone": "يتعذر إيجاد ما تبحث عنه. يرجى المحاولة مرة أخرى.",
    "groups": "مجموعات",
    "noneGroups": "لا توجد مجموعات",
    "signInTip": "انتهت صلاحية جلسة تسجيل الدخول، يرجى تنشيط المتصفح لتسجيل الدخول للمدخل مرة أخرى.",
    "signIn": "تسجيل الدخول",
    "publicMap": "عام",
    "myOrganization": "المنظمة",
    "myGroup": "المجموعات",
    "myContent": "المحتوى",
    "count": "بيت_Count___لاحقة",
    "fromPortal": "من البوابة الإلكترونية",
    "fromOnline": "من ArcGIS.com",
    "noneThumbnail": "الصورة المصغرة غير متاحة",
    "owner": "المالك",
    "signInTo": "تسجيل الدخول إلى",
    "lastModified": "آخر تعديل",
    "moreDetails": "المزيد من التفاصيل"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "الخدمة لا تدعم الاستعلام."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "لا تتوفر طبقة مناسبة داخل الخريطة."
  },
  "layerInfosMenu": {
    "titleBasemap": "خرائط الأساس",
    "titleLayers": "الطبقات التشغيلية",
    "labelLayer": "اسم الطبقة",
    "itemZoomTo": "تكبير إلى",
    "itemTransparency": "معدل الشفافية:",
    "itemTransparent": "شفاف",
    "itemOpaque": "غير شفاف",
    "itemMoveUp": "نقل لأعلى",
    "itemMoveDown": "نقل لأسفل",
    "itemDesc": "الوصف",
    "itemDownload": "تنزيل",
    "itemToAttributeTable": "فتح جدول البيانات الجدولية"
  },
  "imageChooser": {
    "unsupportReaderAPI": "قائمة المهام: المستعرض لا يدعم API لقارئ الملف",
    "readError": "فشل قراءة الملف.",
    "unknowError": "يتعذر إكمال العمليات",
    "invalidType": "نوع الملف غير صحيح.",
    "cropImage": "بيت_Crop Image____لاحقة",
    "exceed": "لا يجوز أن يتجاوز حجم الملف 1024 كيلوبايت",
    "enableFlash": "قائمة المهام: يرجى تمكين الفلاش.",
    "cropWaining": "يرجى اختيار صورة على الأقل ${عرض} x ${طول} بكسل.",
    "toolTip": "للحصول على أفضل نتيجة، ينبغي أن يكون حجم الصورة ${width} بيكسل وارتفاعها ${height} بيكسل. سيتم تعديل الأحجام الأخرى للملائمة. تنسيقات الصورة المقبولة هي PNG وGIF وJPEG."
  },
  "simpleTable": {
    "moveUp": "نقل لأعلى",
    "moveDown": "نقل لأسفل",
    "deleteRow": "حذف",
    "edit": "تحرير"
  },
  "urlParams": {
    "invalidToken": "رمز مميز غير صالح",
    "validateTokenError": "رمز مميز غير صحيح أو خطأ بالشبكة"
  },
  "exportTo": {
    "exportTo": "تصدير",
    "toCSV": "تصدير لملف CSV",
    "toFeatureCollection": "التصدير إلى مجموعة المعالم",
    "toGeoJSON": "التصدير إلى GeoJSON"
  },
  "appState": {
    "title": "بيت_App State____لاحقة",
    "restoreMap": "انقر لاستعادة مدى الخريطة ورؤية الطبقات حيث توقفت."
  },
  "featureActions": {
    "ZoomTo": "بيت_Zoom to___لاحقة",
    "PanTo": "بيت_Pan to___لاحقة",
    "Flash": "بيت_Flash___لاحقة",
    "ShowPopup": "بيت_Show Pop-up____لاحقة",
    "CreateLayer": "بيت_Create Layer_____لاحقة",
    "ShowStatistics": "بيت_Statistics_____لاحقة...",
    "ClearSelection": "بيت_Clear Selection______لاحقة",
    "ExportToCSV": "بيت_Export to CSV file______لاحقة",
    "ExportToFeatureCollection": "بيت_Export to Feature Collection_________لاحقة",
    "ExportToGeoJSON": "بيت_Export to GeoJSON______لاحقة"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "بيت_Related layer_____لاحقة",
    "selectedFeatures": "بيت_Selected features______لاحقة",
    "drawShapesTip": "بيت_Draw shapes to select features__________لاحقة",
    "pleaseDrawShapesTip": "بيت_Please draw shapes to select features____________لاحقة",
    "allFeaturesTip": "بيت_All features in the layer_________لاحقة",
    "selectFeaturesOrDrawShapesTip": "بيت_Please use selected features in this layer or draw shapes on map to limit features__________________________لاحقة."
  },
  "searchDistance": {
    "applySearchDistance": "بيت_Apply a search distance________لاحقة",
    "applySearchDistanceToFeatures": "بيت_Apply a search distance to selected features______________لاحقة"
  },
  "units": {
    "miles": "بيت_Miles___لاحقة",
    "kilometers": "بيت_Kilometers____لاحقة",
    "feet": "بيت_Feet__لاحقة",
    "meters": "بيت_Meters___لاحقة",
    "yards": "بيت_Yards___لاحقة",
    "nauticalMiles": "بيت_Nautical Miles_____لاحقة"
  },
  "featureSetChooser": {
    "select": "بيت_Select___لاحقة",
    "dragBox": "بيت_Drag__لاحقة",
    "dragMouse": "بيت_Darg the mouse_____لاحقة",
    "selectByRectangle": "بيت_Select By Rectangle_______لاحقة",
    "selectFeaturesTip": "بيت_Select features by dragging box around them on map________________لاحقة",
    "newSelectionTip": "بيت_Create a new selection________لاحقة",
    "addSelectionTip": "بيت_Add to the current selection_________لاحقة",
    "removeSelectionTip": "بيت_Remove from the current selection___________لاحقة",
    "selectFromCurrentSelectionTip": "بيت_Select from the current selection___________لاحقة",
    "unselectAllSelectionTip": "بيت_Unselect all currently selected features_____________لاحقة"
  },
  "widgetManager": {
    "createWidgetError": "بيت_Create widget error_______لاحقة",
    "createWidgetSettingPageError": "بيت_Create widget setting page error___________لاحقة",
    "loadWidgetResourceError": "بيت_Load widget resouce error_________لاحقة"
  },
  "shareOptions": {
    "shareMap": "بيت_Choose who can view this app_________لاحقة",
    "shareMapTips": "بيت_Your map is currentlt shared with these people_______________لاحقة",
    "everyone": "بيت_everyone___لاحقة",
    "theseGroups": "بيت_theseGroups____لاحقة"
  },
  "shareLink": {
    "email": "بيت_email___لاحقة",
    "shareEmail": "بيت_Email___لاحقة",
    "facebook": "بيت_facebook___لاحقة",
    "shareFacebook": "بيت_Facebook___لاحقة",
    "twitter": "بيت_twitter___لاحقة",
    "shareTwitter": "بيت_Twitter___لاحقة",
    "googlePlus": "بيت_googlePlus____لاحقة",
    "shareGooglePlus": "بيت_GooglePlus____لاحقة",
    "EmbedTips": "بيت_Embed this scene in a website__________لاحقة",
    "shareEmailTxt1": "بيت_Have a look at this Web Scene__________لاحقة:",
    "shareEmailTxt2": "بيت_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________لاحقة.",
    "smallSize": "بيت_Small___لاحقة",
    "mediumSize": "بيت_Medium___لاحقة",
    "largeSize": "بيت_Large___لاحقة",
    "customSize": "بيت_Custom___لاحقة",
    "embed": "بيت_Embed this scene in a website__________لاحقة",
    "more": "بيت_Embed Options_____لاحقة",
    "changeShareSettings": "بيت_Change Share Settings_______لاحقة",
    "shareLinkText": "بيت_Choose who can view Copy________لاحقة",
    "linkOptions": "بيت_Link Options_____لاحقة",
    "linkOptionsUrlParameters": "بيت_Select URL parameters included in the link______________لاحقة",
    "currentMapExtent": "بيت_Current map extent______لاحقة",
    "chooseCenterWithLevel": "بيت_Click the map to define the center of the map with scale level____________________لاحقة",
    "chooseCenterWithScale": "بيت_Click the map to define the center of the map with map scale___________________لاحقة",
    "findLocation": "بيت_Find the location or feature and zoom to it______________لاحقة",
    "findLocation_inputPlaceholder": "بيت_Your place or feature_______لاحقة",
    "queryFeature": "بيت_Query a feature and zoom to it__________لاحقة",
    "addMarker": "بيت_Add a marker on the map________لاحقة",
    "addMarker_titlePlaceholder": "بيت_Title of the marker pop-up_________لاحقة",
    "addMarker_symbolURL": "بيت_Marker symbol URL______لاحقة",
    "addMarker_label": "بيت_Marker label_____لاحقة",
    "overwirteMobileLayout": "بيت_Overwrite default mobile layout__________لاحقة",
    "language": "بيت_Set the app language_______لاحقة",
    "auth": "بيت_Authenticate a user automatically___________لاحقة",
    "linkPreview": "بيت_Link Preview_____لاحقة",
    "useShortenLink": "بيت_Short Link____لاحقة",
    "shareMapUrlExtent": "بيت_shareMapUrlExtent______لاحقة"
  },
  "webSceneLoader": {
    "webglSupportTip": "بيت_3D web apps aren't supported in your browser_______________لاحقة."
  }
});