define({
  "_widgetLabel": "טבלת מאפיינים",
  "_featureAction_ShowRelatedRecords": "כן_Show Related Records_______ש",
  "_featureAction_ViewInTable": "כן_View in Attribute Table________ש",
  "ok": "אישור",
  "cancel": "ביטול",
  "unsupportQueryWarning": "השכבה צריכה לתמוך בהפעלת שאילתא לצורך הצגה בוידג'ט 'טבלת מאפיינים'. ודא שיכולת השאילתא בשירות מופעלת.",
  "exportMessage": "האם ליצא את הנתונים לקובץ CSV?",
  "exportFiles": "ייצא ל- CSV",
  "exportSelected": "ייצא בחירה ל-CSV",
  "exportAll": "ייצא הכול ל-CSV",
  "options": "אפשרויות",
  "zoomto": "התמקד אל",
  "highlight": "הדגש גרפיקה",
  "selectAll": "בחר רשומות בכל הדפים",
  "selectPage": "בחר רשומות בדף הנוכחי",
  "clearSelection": "נקה בחירה",
  "filter": "פילטר",
  "setFilterTip": "הגדר בבקשה סינון תקין.",
  "noFilterTip": "מבלי להגדיר ביטוי לסינון, שאילתה זו תציג את כל הישויות במקור הנתונים שצוין.",
  "filterByExtent": "סינון לפי תיחום המפה",
  "showSelectedRecords": "הצג רשומות שנבחרו",
  "showAllRecords": "הצג את כל הרשומות",
  "showRelatedRecords": "הצג רשומות קשורות",
  "noRelatedRecords": "לא נמצאו רשומות מקושרות",
  "refresh": "רענן",
  "features": "יישויות",
  "selected": "נבחרים",
  "transparent": "מצב שקיפות",
  "indicate": "מקם בחירה",
  "columns": "הצג/הסתר עמודות",
  "selectionSymbol": "סמל לבחירה",
  "closeMessage": "הסתר טבלה (הרחב אותה שוב מהתחתית)",
  "dataNotAvailable": "נתונים לא זמינים!<br>לחץ [רענן] על הכפתור כדי לנסות שנית.",
  "openTableTip": "פתח טבלת מאפיינים",
  "closeTableTip": "הסתר טבלת מאפיינים",
  "sortAsc": "כן_Sort Ascending_____ש",
  "sortDes": "כן_Sort Descending______ש",
  "statistics": "כן_Statistics____ש"
});