define({
  "common": {
    "apply": "Ĳ_Apply___ä",
    "ok": "OK",
    "cancel": "Annuleren",
    "yes": "Ĳ_Yes__ä",
    "no": "Ĳ_No__ä",
    "next": "Volgende",
    "back": "Vorige",
    "selected": "Ĳ_selected___ä",
    "name": "Naam",
    "usage": "Ĳ_Usage___ä",
    "settings": "Ĳ_Settings___ä",
    "home": "Ĳ_Home__ä",
    "link": "Ĳ_Link__ä",
    "messages": "Ĳ_Messages___ä",
    "outputs": "Ĳ_Outputs___ä",
    "title": "Titel",
    "thumbnail": "Ĳ_Thumbnail____ä",
    "url": "Ĳ_URL__ä",
    "actions": "Acties",
    "layer": "Kaartlaag",
    "action": "Ĳ_Action___ä",
    "input": "Ĳ_Input___ä",
    "output": "Ĳ_Output___ä",
    "type": "Ĳ_Type__ä",
    "required": "Ĳ_Required___ä",
    "options": "Ĳ_Options___ä",
    "label": "Label",
    "tooltip": "Ĳ_Tooltip___ä",
    "visible": "Ĳ_Visible___ä",
    "symbol": "Ĳ_Symbol___ä",
    "popup": "Ĳ_Popup___ä",
    "upload": "Ĳ_Upload___ä",
    "execute": "Ĳ_Execute___ä",
    "help": "Ĳ_Help__ä",
    "executing": "Ĳ_Executing____ä",
    "clear": "Wissen",
    "error": "Ĳ_Error___ä",
    "zoomTo": "Zoomen naar",
    "attribute": "Ĳ_Attribute____ä",
    "exports": "Ĳ_Export___ä",
    "check": "Ĳ_Check___ä",
    "save": "Ĳ_Save__ä",
    "close": "Ĳ_Close___ä",
    "deleteText": "Ĳ_Delete___ä",
    "map": "Kaart",
    "scene": "Ĳ_Scene___ä",
    "reset": "Ĳ_Reset___ä",
    "icon": "Ĳ_Icon__ä",
    "share": "Ĳ_Share___ä"
  },
  "errorCode": "Code",
  "errorMessage": "Bericht",
  "errorDetail": "Detail",
  "widgetPlaceholderTooltip": "Om dit in te stellen, gaat u naar Widgets en klikt u op de overeenkomende tijdelijke aanduiding",
  "fieldStatistics": {
    "statistics": "Ĳ_Statistics____ä",
    "field": "Veld",
    "count": "Ĳ_Number of Values______ä",
    "sum": "Ĳ_Sum of Values_____ä",
    "min": "Ĳ_Minimum___ä",
    "max": "Ĳ_Maximum___ä",
    "ave": "Ĳ_Average___ä",
    "stddev": "Ĳ_Standard Deviation______ä"
  },
  "symbolChooser": {
    "preview": "Voorbeeld",
    "basic": "Eenvoudig",
    "arrows": "Pijlen",
    "business": "Economie",
    "cartographic": "Cartografisch",
    "nationalParkService": "National Park Service",
    "outdoorRecreation": "Recreatie in openlucht",
    "peoplePlaces": "Openbare plaatsen",
    "safetyHealth": "Veiligheid en gezondheid",
    "shapes": "Vormen",
    "transportation": "Vervoer",
    "symbolSize": "Symboolgrootte",
    "color": "Kleur",
    "alpha": "Alpha",
    "outlineColor": "Kleur omtreklijn",
    "outlineWidth": "Breedte omtreklijn",
    "style": "Stijl",
    "width": "Breedte",
    "text": "Tekst",
    "fontColor": "Tekstkleur",
    "fontSize": "Tekengrootte",
    "transparency": "Transparant",
    "solid": "Ononderbroken",
    "dash": "Streep",
    "dot": "Punt",
    "dashDot": "Streep punt",
    "dashDotDot": "Streep punt punt"
  },
  "transparency": {
    "opaque": "Niet transparant",
    "transparent": "Transparant"
  },
  "rendererChooser": {
    "domain": "Domein",
    "use": "Gebruiken",
    "singleSymbol": "Eén symbool",
    "uniqueSymbol": "Unieke symbolen",
    "color": "Kleur",
    "size": "Grootte",
    "toShow": "Om weer te geven",
    "colors": "Kleuren",
    "classes": "Klassen",
    "symbolSize": "Symboolgrootte",
    "addValue": "Waarde toevoegen",
    "setDefaultSymbol": "Standaardsymbool instellen",
    "defaultSymbol": "Standaard symbool",
    "selectedSymbol": "Geselecteerd symbool",
    "value": "Waarde",
    "label": "Ĳ_Label___ä",
    "range": "Bereik"
  },
  "drawBox": {
    "point": "Punt",
    "line": "Lijn",
    "polyline": "Polylijn",
    "freehandPolyline": "Polylijn in vrije stijl",
    "triangle": "Driehoek",
    "extent": "Extent",
    "circle": "Cirkel",
    "ellipse": "Ellips",
    "polygon": "Polygoon",
    "freehandPolygon": "Vlak in vrije stijl",
    "text": "Tekst",
    "clear": "Ĳ_Clear___ä"
  },
  "popupConfig": {
    "title": "Ĳ_Title___ä",
    "add": "Toevoegen",
    "fields": "Velden",
    "noField": "Geen veld",
    "visibility": "Zichtbaar",
    "name": "Ĳ_Name__ä",
    "alias": "Alias",
    "actions": "Ĳ_Actions___ä"
  },
  "includeButton": {
    "include": "Opnemen"
  },
  "loadingShelter": {
    "loading": "Laden"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Er zijn geen services gevonden.",
    "unableConnectTo": "Kan geen verbinding maken met",
    "invalidUrlTip": "De URL die u hebt ingevoerd, is ongeldig of ontoegankelijk."
  },
  "serviceBrowser": {
    "noGpFound": "Er zijn geen geoprocessingservices gevonden.",
    "unableConnectTo": "Kan geen verbinding maken met"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Er zijn geen mapservices of featureservices gevonden",
    "unableConnectTo": "Kan geen verbinding maken met"
  },
  "basicServiceChooser": {
    "validate": "Valideren",
    "example": "Voorbeeld",
    "set": "Instellen"
  },
  "urlInput": {
    "invalidUrl": "Ongeldige URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ongeldige URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Een filterexpressie toevoegen",
    "addSet": "Een expressieset toevoegen",
    "matchMsg": "Objecten in de kaartlaag ophalen die overeenkomen met ${any_or_all} van de volgende expressies",
    "matchMsgSet": "${any_or_all} van de volgende expressies in deze set zijn waar",
    "all": "Alle",
    "any": "Eén",
    "value": "Waarde",
    "field": "Ĳ_Field___ä",
    "unique": "Uniek",
    "none": "Geen",
    "and": "en",
    "valueTooltip": "Waarde invoeren",
    "fieldTooltip": "Keuze maken uit bestaand veld",
    "uniqueValueTooltip": "Keuze maken uit unieke waarden in geselecteerd veld",
    "stringOperatorIs": "is",
    "stringOperatorIsNot": "is niet",
    "stringOperatorStartsWith": "begint met",
    "stringOperatorEndsWith": "eindigt met",
    "stringOperatorContains": "bevat",
    "stringOperatorDoesNotContain": "bevat niet",
    "stringOperatorIsBlank": "is leeg",
    "stringOperatorIsNotBlank": "is niet leeg",
    "dateOperatorIsOn": "is op",
    "dateOperatorIsNotOn": "is niet op",
    "dateOperatorIsBefore": "is voor",
    "dateOperatorIsAfter": "is na",
    "dateOperatorDays": "dagen",
    "dateOperatorWeeks": "weken",
    "dateOperatorMonths": "maanden",
    "dateOperatorInTheLast": "in de afgelopen",
    "dateOperatorNotInTheLast": "niet in de afgelopen",
    "dateOperatorIsBetween": "is tussen",
    "dateOperatorIsNotBetween": "is niet tussen",
    "dateOperatorIsBlank": "is leeg",
    "dateOperatorIsNotBlank": "is niet leeg",
    "numberOperatorIs": "is",
    "numberOperatorIsNot": "is niet",
    "numberOperatorIsAtLeast": "is minimaal",
    "numberOperatorIsLessThan": "is minder dan",
    "numberOperatorIsAtMost": "is maximaal",
    "numberOperatorIsGreaterThan": "is meer dan",
    "numberOperatorIsBetween": "is tussen",
    "numberOperatorIsNotBetween": "is niet tussen",
    "numberOperatorIsBlank": "is leeg",
    "numberOperatorIsNotBlank": "is niet leeg",
    "string": "Tekenreeks",
    "number": "Nummer",
    "date": "Datum",
    "askForValues": "Vragen om waarden",
    "prompt": "Prompt",
    "hint": "Tip",
    "error": {
      "invalidParams": "Ongeldige parameters.",
      "invalidUrl": "Ongeldige URL.",
      "noFilterFields": "De kaartlaag heeft geen velden die kunnen worden gebruikt om te filteren.",
      "invalidSQL": "Ongeldige SQL-expressie.",
      "cantParseSQL": "Kan de SQL-expressie niet parseren."
    },
    "caseSensitive": "Hoofdletter gevoelig",
    "notSupportCaseSensitiveTip": "Hosted services ondersteunen geen hoofdlettergevoelige query."
  },
  "featureLayerSource": {
    "layer": "Kaartlaag",
    "browse": "Bladeren",
    "selectFromMap": "Selecteren in kaart",
    "selectFromPortal": "Toevoegen vanuit Portal for ArcGIS",
    "addServiceUrl": "Service-URL toevoegen",
    "inputLayerUrl": "URL van invoerlaag",
    "selectLayer": "Selecteer een objectlaag in de huidige kaart.",
    "chooseItem": "Kies een objectlaagitem.",
    "setServiceUrl": "Voer de URL van de featureservice of mapservice in.",
    "selectFromOnline": "Toevoegen vanuit ArcGIS Online",
    "chooseLayer": "Kies een objectlaag."
  },
  "queryableLayerSource": {
    "layer": "Ĳ_Layer___ä",
    "browse": "Bladeren",
    "selectFromMap": "Selecteren in kaart",
    "selectFromPortal": "Toevoegen vanuit Portal for ArcGIS",
    "addServiceUrl": "Service-URL toevoegen",
    "inputLayerUrl": "URL van invoerlaag",
    "selectLayer": "Selecteer een laag van huidige kaart.",
    "chooseItem": "Kies een item.",
    "setServiceUrl": "Voer de URL van de service in.",
    "selectFromOnline": "Toevoegen vanuit ArcGIS Online",
    "chooseLayer": "Kies een laag."
  },
  "gpSource": {
    "selectFromPortal": "Toevoegen vanuit Portal for ArcGIS",
    "addServiceUrl": "Service-URL toevoegen",
    "selectFromOnline": "Toevoegen vanuit ArcGIS Online",
    "setServiceUrl": "Voer de URL van de geoprocessingservice in.",
    "chooseItem": "Kies een geoprocessingservice-item.",
    "chooseTask": "Kies een geoprocessingtaak."
  },
  "itemSelector": {
    "map": "Ĳ_Map__ä",
    "selectWebMap": "Webmap kiezen",
    "addMapFromOnlineOrPortal": "Zoek en voeg een webmap toe in de applicatie vanaf openbare ArcGIS Online-bronnen of uw privécontent in ArcGIS Online of Portal.",
    "searchMapName": "Zoeken op naam van kaart...",
    "searchNone": "We hebben niet gevonden wat u zocht. Probeer opnieuw.",
    "groups": "Groepen",
    "noneGroups": "Geen groepen",
    "signInTip": "Uw sessie is afgelopen. Vernieuw uw browser om u opnieuw aan te melden voor uw portaal.",
    "signIn": "Aanmelden",
    "publicMap": "Openbaar",
    "myOrganization": "Mijn Organisatie",
    "myGroup": "Mijn Groepen",
    "myContent": "Mijn Content",
    "count": "Ĳ_Count___ä",
    "fromPortal": "vanaf Portaal",
    "fromOnline": "vanaf ArcGIS.com",
    "noneThumbnail": "Thumbnail niet beschikbaar",
    "owner": "eigenaar",
    "signInTo": "Meld u aan bij",
    "lastModified": "Laatst gewijzigd",
    "moreDetails": "Meer details"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "De service ondersteunt geen query's."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Er is geen geschikte laag beschikbaar in de kaart."
  },
  "layerInfosMenu": {
    "titleBasemap": "Basiskaarten",
    "titleLayers": "Operationele lagen",
    "labelLayer": "Laagnaam",
    "itemZoomTo": "Zoomen naar",
    "itemTransparency": "Transparant",
    "itemTransparent": "Transparant",
    "itemOpaque": "Niet transparant",
    "itemMoveUp": "Naar boven verplaatsen",
    "itemMoveDown": "Naar beneden verplaatsen",
    "itemDesc": "Beschrijving",
    "itemDownload": "Downloaden",
    "itemToAttributeTable": "Attribuuttabel openen"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TAAK: De browser biedt geen ondersteuning voor bestandslezer-API",
    "readError": "Kan het bestand niet lezen.",
    "unknowError": "kan de bewerkingen niet voltooien",
    "invalidType": "Ongeldig bestandstype.",
    "cropImage": "Ĳ_Crop Image____ä",
    "exceed": "Bestandsgrootte mag niet groter zijn dan 1024 KB",
    "enableFlash": "TAAK: schakel Flash in.",
    "cropWaining": "Kies een foto die minstens ${breedte}x ${hoogte} pixels is.",
    "toolTip": "Voor de beste weergave moet de afbeelding ${width} pixels breed en ${height} pixels hoog zijn. Andere formaten worden passend gemaakt. Aanvaardbare afbeeldingsindelingen zijn: PNG, GIF en JPEG."
  },
  "simpleTable": {
    "moveUp": "Naar boven verplaatsen",
    "moveDown": "Naar beneden verplaatsen",
    "deleteRow": "Verwijderen",
    "edit": "Bewerken"
  },
  "urlParams": {
    "invalidToken": "Ongeldige token",
    "validateTokenError": "Ongeldige token of Netwerkfout"
  },
  "exportTo": {
    "exportTo": "Exporteren",
    "toCSV": "Exporteren naar CSV-bestand",
    "toFeatureCollection": "Exporteren naar Feature Collection",
    "toGeoJSON": "Exporteren naar GeoJSON"
  },
  "appState": {
    "title": "Ĳ_App State____ä",
    "restoreMap": "Klik om de extent van de kaart en de zichtbaarheid van de lagen te herstellen waar u bent gebleven."
  },
  "featureActions": {
    "ZoomTo": "Ĳ_Zoom to___ä",
    "PanTo": "Ĳ_Pan to___ä",
    "Flash": "Ĳ_Flash___ä",
    "ShowPopup": "Ĳ_Show Pop-up____ä",
    "CreateLayer": "Ĳ_Create Layer_____ä",
    "ShowStatistics": "Ĳ_Statistics_____ä...",
    "ClearSelection": "Ĳ_Clear Selection______ä",
    "ExportToCSV": "Ĳ_Export to CSV file______ä",
    "ExportToFeatureCollection": "Ĳ_Export to Feature Collection_________ä",
    "ExportToGeoJSON": "Ĳ_Export to GeoJSON______ä"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Ĳ_Related layer_____ä",
    "selectedFeatures": "Ĳ_Selected features______ä",
    "drawShapesTip": "Ĳ_Draw shapes to select features__________ä",
    "pleaseDrawShapesTip": "Ĳ_Please draw shapes to select features____________ä",
    "allFeaturesTip": "Ĳ_All features in the layer_________ä",
    "selectFeaturesOrDrawShapesTip": "Ĳ_Please use selected features in this layer or draw shapes on map to limit features__________________________ä."
  },
  "searchDistance": {
    "applySearchDistance": "Ĳ_Apply a search distance________ä",
    "applySearchDistanceToFeatures": "Ĳ_Apply a search distance to selected features______________ä"
  },
  "units": {
    "miles": "Ĳ_Miles___ä",
    "kilometers": "Ĳ_Kilometers____ä",
    "feet": "Ĳ_Feet__ä",
    "meters": "Ĳ_Meters___ä",
    "yards": "Ĳ_Yards___ä",
    "nauticalMiles": "Ĳ_Nautical Miles_____ä"
  },
  "featureSetChooser": {
    "select": "Ĳ_Select___ä",
    "dragBox": "Ĳ_Drag__ä",
    "dragMouse": "Ĳ_Darg the mouse_____ä",
    "selectByRectangle": "Ĳ_Select By Rectangle_______ä",
    "selectFeaturesTip": "Ĳ_Select features by dragging box around them on map________________ä",
    "newSelectionTip": "Ĳ_Create a new selection________ä",
    "addSelectionTip": "Ĳ_Add to the current selection_________ä",
    "removeSelectionTip": "Ĳ_Remove from the current selection___________ä",
    "selectFromCurrentSelectionTip": "Ĳ_Select from the current selection___________ä",
    "unselectAllSelectionTip": "Ĳ_Unselect all currently selected features_____________ä"
  },
  "widgetManager": {
    "createWidgetError": "Ĳ_Create widget error_______ä",
    "createWidgetSettingPageError": "Ĳ_Create widget setting page error___________ä",
    "loadWidgetResourceError": "Ĳ_Load widget resouce error_________ä"
  },
  "shareOptions": {
    "shareMap": "Ĳ_Choose who can view this app_________ä",
    "shareMapTips": "Ĳ_Your map is currentlt shared with these people_______________ä",
    "everyone": "Ĳ_everyone___ä",
    "theseGroups": "Ĳ_theseGroups____ä"
  },
  "shareLink": {
    "email": "Ĳ_email___ä",
    "shareEmail": "Ĳ_Email___ä",
    "facebook": "Ĳ_facebook___ä",
    "shareFacebook": "Ĳ_Facebook___ä",
    "twitter": "Ĳ_twitter___ä",
    "shareTwitter": "Ĳ_Twitter___ä",
    "googlePlus": "Ĳ_googlePlus____ä",
    "shareGooglePlus": "Ĳ_GooglePlus____ä",
    "EmbedTips": "Ĳ_Embed this scene in a website__________ä",
    "shareEmailTxt1": "Ĳ_Have a look at this Web Scene__________ä:",
    "shareEmailTxt2": "Ĳ_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ä.",
    "smallSize": "Ĳ_Small___ä",
    "mediumSize": "Ĳ_Medium___ä",
    "largeSize": "Ĳ_Large___ä",
    "customSize": "Ĳ_Custom___ä",
    "embed": "Ĳ_Embed this scene in a website__________ä",
    "more": "Ĳ_Embed Options_____ä",
    "changeShareSettings": "Ĳ_Change Share Settings_______ä",
    "shareLinkText": "Ĳ_Choose who can view Copy________ä",
    "linkOptions": "Ĳ_Link Options_____ä",
    "linkOptionsUrlParameters": "Ĳ_Select URL parameters included in the link______________ä",
    "currentMapExtent": "Ĳ_Current map extent______ä",
    "chooseCenterWithLevel": "Ĳ_Click the map to define the center of the map with scale level____________________ä",
    "chooseCenterWithScale": "Ĳ_Click the map to define the center of the map with map scale___________________ä",
    "findLocation": "Ĳ_Find the location or feature and zoom to it______________ä",
    "findLocation_inputPlaceholder": "Ĳ_Your place or feature_______ä",
    "queryFeature": "Ĳ_Query a feature and zoom to it__________ä",
    "addMarker": "Ĳ_Add a marker on the map________ä",
    "addMarker_titlePlaceholder": "Ĳ_Title of the marker pop-up_________ä",
    "addMarker_symbolURL": "Ĳ_Marker symbol URL______ä",
    "addMarker_label": "Ĳ_Marker label_____ä",
    "overwirteMobileLayout": "Ĳ_Overwrite default mobile layout__________ä",
    "language": "Ĳ_Set the app language_______ä",
    "auth": "Ĳ_Authenticate a user automatically___________ä",
    "linkPreview": "Ĳ_Link Preview_____ä",
    "useShortenLink": "Ĳ_Short Link____ä",
    "shareMapUrlExtent": "Ĳ_shareMapUrlExtent______ä"
  },
  "webSceneLoader": {
    "webglSupportTip": "Ĳ_3D web apps aren't supported in your browser_______________ä."
  }
});