define({
  "common": {
    "apply": "Š_Apply___ä",
    "ok": "OK",
    "cancel": "Tühista",
    "yes": "Š_Yes__ä",
    "no": "Š_No__ä",
    "next": "Järgmine",
    "back": "Tagasi",
    "selected": "Š_selected___ä",
    "name": "Nimi",
    "usage": "Š_Usage___ä",
    "settings": "Š_Settings___ä",
    "home": "Š_Home__ä",
    "link": "Š_Link__ä",
    "messages": "Š_Messages___ä",
    "outputs": "Š_Outputs___ä",
    "title": "Pealkiri",
    "thumbnail": "Š_Thumbnail____ä",
    "url": "Š_URL__ä",
    "actions": "Tegevused",
    "layer": "Kiht",
    "action": "Š_Action___ä",
    "input": "Š_Input___ä",
    "output": "Š_Output___ä",
    "type": "Š_Type__ä",
    "required": "Š_Required___ä",
    "options": "Š_Options___ä",
    "label": "Märgis",
    "tooltip": "Š_Tooltip___ä",
    "visible": "Š_Visible___ä",
    "symbol": "Š_Symbol___ä",
    "popup": "Š_Popup___ä",
    "upload": "Š_Upload___ä",
    "execute": "Š_Execute___ä",
    "help": "Š_Help__ä",
    "executing": "Š_Executing____ä",
    "clear": "Puhasta",
    "error": "Š_Error___ä",
    "zoomTo": "Suumi",
    "attribute": "Š_Attribute____ä",
    "exports": "Š_Export___ä",
    "check": "Š_Check___ä",
    "save": "Š_Save__ä",
    "close": "Š_Close___ä",
    "deleteText": "Š_Delete___ä",
    "map": "Kaart",
    "scene": "Š_Scene___ä",
    "reset": "Š_Reset___ä",
    "icon": "Š_Icon__ä",
    "share": "Š_Share___ä"
  },
  "errorCode": "Kood",
  "errorMessage": "Sõnum",
  "errorDetail": "Detail",
  "widgetPlaceholderTooltip": "Seadistamiseks valige Vidinad ning klikkige vastavat kohatäidet",
  "fieldStatistics": {
    "statistics": "Š_Statistics____ä",
    "field": "Väli",
    "count": "Š_Number of Values______ä",
    "sum": "Š_Sum of Values_____ä",
    "min": "Š_Minimum___ä",
    "max": "Š_Maximum___ä",
    "ave": "Š_Average___ä",
    "stddev": "Š_Standard Deviation______ä"
  },
  "symbolChooser": {
    "preview": "Eelvaade",
    "basic": "Esmane",
    "arrows": "Nooled",
    "business": "Äriettevõtted",
    "cartographic": "Kartograafia",
    "nationalParkService": "Rahvuspargi teenus",
    "outdoorRecreation": "Rekreatsioon",
    "peoplePlaces": "Inimeste asukohad",
    "safetyHealth": "Tervishoid",
    "shapes": "Kujundid",
    "transportation": "Transport",
    "symbolSize": "Sümboli suurus",
    "color": "Värv",
    "alpha": "Alfa",
    "outlineColor": "Äärejoone värv",
    "outlineWidth": "Äärejoone laius",
    "style": "Stiil",
    "width": "Laius",
    "text": "Tekst",
    "fontColor": "Fondi värv",
    "fontSize": "Fondi suurus",
    "transparency": "Läbipaistvus",
    "solid": "Pidev",
    "dash": "Katkendlik",
    "dot": "Punktiir",
    "dashDot": "Katkendlik punktiga",
    "dashDotDot": "Katkendlik kahe punktiga"
  },
  "transparency": {
    "opaque": "Läbipaistmatu",
    "transparent": "Läbipaistev"
  },
  "rendererChooser": {
    "domain": "Domeen",
    "use": "Kasutus",
    "singleSymbol": "Üks sümbol",
    "uniqueSymbol": "Unikaalne sümbol",
    "color": "Värv",
    "size": "Suurus",
    "toShow": "Näita",
    "colors": "Värvid",
    "classes": "Klassid",
    "symbolSize": "Sümboli suurus",
    "addValue": "Lisa väärtus",
    "setDefaultSymbol": "Määra vaikesümbol",
    "defaultSymbol": "Vaikesümbol",
    "selectedSymbol": "Valitud sümbol",
    "value": "Väärtus",
    "label": "Š_Label___ä",
    "range": "Ulatus"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Joon",
    "polyline": "Murdjoon",
    "freehandPolyline": "Vabakäeline murdjoon",
    "triangle": "Kolmnurk",
    "extent": "Kuvaulatus",
    "circle": "Ring",
    "ellipse": "Ellips",
    "polygon": "Pind",
    "freehandPolygon": "Vabakäeline pind",
    "text": "Tekst",
    "clear": "Š_Clear___ä"
  },
  "popupConfig": {
    "title": "Š_Title___ä",
    "add": "Lisa",
    "fields": "Väljad",
    "noField": "Väli puudub",
    "visibility": "Nähtav",
    "name": "Š_Name__ä",
    "alias": "Alias",
    "actions": "Š_Actions___ä"
  },
  "includeButton": {
    "include": "Kaasatud"
  },
  "loadingShelter": {
    "loading": "Laen"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Teenuseid ei leitud.",
    "unableConnectTo": "Ei õnnestu luua ühendust",
    "invalidUrlTip": "Sisestatud URL ei sobi või pole kättesaadav."
  },
  "serviceBrowser": {
    "noGpFound": "Geotöötluse teenuseid ei leitud.",
    "unableConnectTo": "Ei õnnestu luua ühendust"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Kaardi- või objektiteenuseid ei leitud",
    "unableConnectTo": "Ei õnnestu luua ühendust"
  },
  "basicServiceChooser": {
    "validate": "Valideeri",
    "example": "Näide",
    "set": "Määra"
  },
  "urlInput": {
    "invalidUrl": "Vigane URL."
  },
  "urlComboBox": {
    "invalidUrl": "Vigane URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Lisa filtriavaldis",
    "addSet": "Lisa avaldise kirjeldus.",
    "matchMsg": "Too kihi objektid, millega ühtivad ${any_or_all} järgmised avaldised",
    "matchMsgSet": "${any_or_all} järgmistest avaldistest on tõesed",
    "all": "Kõik",
    "any": "Mõni",
    "value": "Väärtus",
    "field": "Š_Field___ä",
    "unique": "Unikaalne",
    "none": "Pole",
    "and": "ja",
    "valueTooltip": "Sisesta väärtus",
    "fieldTooltip": "Vali olemasolevast väljast",
    "uniqueValueTooltip": "Vali valitud välja unikaalsetest väärtustest",
    "stringOperatorIs": "on",
    "stringOperatorIsNot": "ei ole",
    "stringOperatorStartsWith": "algab",
    "stringOperatorEndsWith": "lõpeb",
    "stringOperatorContains": "sisaldab",
    "stringOperatorDoesNotContain": "ei sisalda",
    "stringOperatorIsBlank": "on tühi",
    "stringOperatorIsNotBlank": "ei ole tühi",
    "dateOperatorIsOn": "on",
    "dateOperatorIsNotOn": "ei ole",
    "dateOperatorIsBefore": "on enne",
    "dateOperatorIsAfter": "on pärast",
    "dateOperatorDays": "päeva",
    "dateOperatorWeeks": "nädalat",
    "dateOperatorMonths": "kuud",
    "dateOperatorInTheLast": "viimases",
    "dateOperatorNotInTheLast": "mitte viimases",
    "dateOperatorIsBetween": "on vahemikus",
    "dateOperatorIsNotBetween": "ei ole vahemikus",
    "dateOperatorIsBlank": "on tühi",
    "dateOperatorIsNotBlank": "ei ole tühi",
    "numberOperatorIs": "on",
    "numberOperatorIsNot": "ei ole",
    "numberOperatorIsAtLeast": "on vähemalt",
    "numberOperatorIsLessThan": "on väiksem kui",
    "numberOperatorIsAtMost": "on kõige",
    "numberOperatorIsGreaterThan": "on suurem kui",
    "numberOperatorIsBetween": "on vahemikus",
    "numberOperatorIsNotBetween": "ei ole vahemikus",
    "numberOperatorIsBlank": "on tühi",
    "numberOperatorIsNotBlank": "ei ole tühi",
    "string": "String",
    "number": "Number",
    "date": "Kuupäev",
    "askForValues": "Küsi väärtustest",
    "prompt": "Kuvatav kirje",
    "hint": "Vihje",
    "error": {
      "invalidParams": "Vigased parameetrid.",
      "invalidUrl": "Vigane URL.",
      "noFilterFields": "Kihil puuduvad väljad, mida saaks filtreerimiseks kasutada.",
      "invalidSQL": "Vigane SQL-avaldis.",
      "cantParseSQL": "SQL-avaldise parsimine ei õnnestu."
    },
    "caseSensitive": "Tõstutundlik",
    "notSupportCaseSensitiveTip": "Majutatud teenused ei toeta tõstutundlikke päringuid."
  },
  "featureLayerSource": {
    "layer": "Kiht",
    "browse": "Sirvi",
    "selectFromMap": "Vali kaardilt",
    "selectFromPortal": "Lisa Portal for ArcGIS-ist",
    "addServiceUrl": "Lisa teenuse URL",
    "inputLayerUrl": "Sisendkihi URL",
    "selectLayer": "Vali praeguse kaardi objektikiht.",
    "chooseItem": "Vali objektikihi sisu.",
    "setServiceUrl": "Sisesta objekti- või kaarditeenuse URL.",
    "selectFromOnline": "Lisa ArcGIS Online’ist",
    "chooseLayer": "Valige objektikiht."
  },
  "queryableLayerSource": {
    "layer": "Š_Layer___ä",
    "browse": "Sirvi",
    "selectFromMap": "Vali kaardilt",
    "selectFromPortal": "Lisa Portal for ArcGIS-ist",
    "addServiceUrl": "Lisa teenuse URL",
    "inputLayerUrl": "Sisendkihi URL",
    "selectLayer": "Valige kiht praeguselt kaardilt.",
    "chooseItem": "Valige sisuüksus.",
    "setServiceUrl": "Sisestage teenuse URL.",
    "selectFromOnline": "Lisa ArcGIS Online’ist",
    "chooseLayer": "Vali kiht."
  },
  "gpSource": {
    "selectFromPortal": "Lisa Portal for ArcGIS-ist",
    "addServiceUrl": "Lisa teenuse URL",
    "selectFromOnline": "Lisa ArcGIS Online’ist",
    "setServiceUrl": "Sisestage geotöötlusteenuse URL.",
    "chooseItem": "Valige geotöötlusteenuse objekt.",
    "chooseTask": "Valige geotöötluse ülesanne."
  },
  "itemSelector": {
    "map": "Š_Map__ä",
    "selectWebMap": "Vali veebikaart",
    "addMapFromOnlineOrPortal": "Saate rakenduses veebikaarti otsida ja selle lisada ArcGIS Online’i avalike ressursside kaudu või ArcGIS Online’i või Portali isikliku sisu kaudu.",
    "searchMapName": "Otsi kaardi nime järgi...",
    "searchNone": "Me ei leidnud seda, mida otsisite. Proovige uuesti.",
    "groups": "Grupid",
    "noneGroups": "Gruppe ei ole",
    "signInTip": "Teie sisselogimise seanss on aegunud, portaali uuesti sisse logimiseks värskendage brauserit.",
    "signIn": "Logi sisse",
    "publicMap": "Avalik",
    "myOrganization": "Minu organisatsioon",
    "myGroup": "Minu grupid",
    "myContent": "Minu sisu",
    "count": "Š_Count___ä",
    "fromPortal": "portaalist",
    "fromOnline": "veebilehelt ArcGIS.com",
    "noneThumbnail": "Pisipilt ei ole saadaval",
    "owner": "omanik",
    "signInTo": "Logi sisse",
    "lastModified": "Viimati muudetud",
    "moreDetails": "Rohkem infot"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Teenus ei toeta päringut."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Kaardi jaoks pole saadaval ühtegi sobivat kihti."
  },
  "layerInfosMenu": {
    "titleBasemap": "Aluskaardid",
    "titleLayers": "Töökihid",
    "labelLayer": "Kihi nimi",
    "itemZoomTo": "Suumi",
    "itemTransparency": "Läbipaistvus",
    "itemTransparent": "Läbipaistev",
    "itemOpaque": "Läbipaistmatu",
    "itemMoveUp": "Liiguta ülespoole",
    "itemMoveDown": "Liiguta allapoole",
    "itemDesc": "Kirjeldus",
    "itemDownload": "Laadi alla",
    "itemToAttributeTable": "Ava atribuuditabel"
  },
  "imageChooser": {
    "unsupportReaderAPI": "MÄRKUS. Brauser ei toeta faililugemise liidest.",
    "readError": "Faili lugemine nurjus.",
    "unknowError": "toiminguid ei saanud lõpule viia",
    "invalidType": "Sobimatut tüüpi fail",
    "cropImage": "Š_Crop Image____ä",
    "exceed": "Faili maht võib olla kuni 1024 KB.",
    "enableFlash": "Märkus. Lubage Flash.",
    "cropWaining": "Palun valige foto, mille mõõdud on vähemalt ${width} x ${height} pikslit.",
    "toolTip": "Parima tulemuse saamiseks peaks pildi laius olema ${width} pikslit ning kõrgus ${height} pikslit. Muud suurused kohandatakse parajaks. Sobivad pildiformaadid on PNG, GIF ja JPEG."
  },
  "simpleTable": {
    "moveUp": "Liiguta ülespoole",
    "moveDown": "Liiguta allapoole",
    "deleteRow": "Kustuta",
    "edit": "Muuda"
  },
  "urlParams": {
    "invalidToken": "Kehtetu võti",
    "validateTokenError": "Kehtetu võti või võrgu tõrge"
  },
  "exportTo": {
    "exportTo": "Ekspordi",
    "toCSV": "Ekspordi CSV failiks",
    "toFeatureCollection": "Eksport objektide kogumisse",
    "toGeoJSON": "Eksport GeoJSON formaati"
  },
  "appState": {
    "title": "Š_App State____ä",
    "restoreMap": "Klõpsake kaardi ulatuse ja kihtide nähtavuse taastamiseks poolelijäänud kohas."
  },
  "featureActions": {
    "ZoomTo": "Š_Zoom to___ä",
    "PanTo": "Š_Pan to___ä",
    "Flash": "Š_Flash___ä",
    "ShowPopup": "Š_Show Pop-up____ä",
    "CreateLayer": "Š_Create Layer_____ä",
    "ShowStatistics": "Š_Statistics_____ä...",
    "ClearSelection": "Š_Clear Selection______ä",
    "ExportToCSV": "Š_Export to CSV file______ä",
    "ExportToFeatureCollection": "Š_Export to Feature Collection_________ä",
    "ExportToGeoJSON": "Š_Export to GeoJSON______ä"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Š_Related layer_____ä",
    "selectedFeatures": "Š_Selected features______ä",
    "drawShapesTip": "Š_Draw shapes to select features__________ä",
    "pleaseDrawShapesTip": "Š_Please draw shapes to select features____________ä",
    "allFeaturesTip": "Š_All features in the layer_________ä",
    "selectFeaturesOrDrawShapesTip": "Š_Please use selected features in this layer or draw shapes on map to limit features__________________________ä."
  },
  "searchDistance": {
    "applySearchDistance": "Š_Apply a search distance________ä",
    "applySearchDistanceToFeatures": "Š_Apply a search distance to selected features______________ä"
  },
  "units": {
    "miles": "Š_Miles___ä",
    "kilometers": "Š_Kilometers____ä",
    "feet": "Š_Feet__ä",
    "meters": "Š_Meters___ä",
    "yards": "Š_Yards___ä",
    "nauticalMiles": "Š_Nautical Miles_____ä"
  },
  "featureSetChooser": {
    "select": "Š_Select___ä",
    "dragBox": "Š_Drag__ä",
    "dragMouse": "Š_Darg the mouse_____ä",
    "selectByRectangle": "Š_Select By Rectangle_______ä",
    "selectFeaturesTip": "Š_Select features by dragging box around them on map________________ä",
    "newSelectionTip": "Š_Create a new selection________ä",
    "addSelectionTip": "Š_Add to the current selection_________ä",
    "removeSelectionTip": "Š_Remove from the current selection___________ä",
    "selectFromCurrentSelectionTip": "Š_Select from the current selection___________ä",
    "unselectAllSelectionTip": "Š_Unselect all currently selected features_____________ä"
  },
  "widgetManager": {
    "createWidgetError": "Š_Create widget error_______ä",
    "createWidgetSettingPageError": "Š_Create widget setting page error___________ä",
    "loadWidgetResourceError": "Š_Load widget resouce error_________ä"
  },
  "shareOptions": {
    "shareMap": "Š_Choose who can view this app_________ä",
    "shareMapTips": "Š_Your map is currentlt shared with these people_______________ä",
    "everyone": "Š_everyone___ä",
    "theseGroups": "Š_theseGroups____ä"
  },
  "shareLink": {
    "email": "Š_email___ä",
    "shareEmail": "Š_Email___ä",
    "facebook": "Š_facebook___ä",
    "shareFacebook": "Š_Facebook___ä",
    "twitter": "Š_twitter___ä",
    "shareTwitter": "Š_Twitter___ä",
    "googlePlus": "Š_googlePlus____ä",
    "shareGooglePlus": "Š_GooglePlus____ä",
    "EmbedTips": "Š_Embed this scene in a website__________ä",
    "shareEmailTxt1": "Š_Have a look at this Web Scene__________ä:",
    "shareEmailTxt2": "Š_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ä.",
    "smallSize": "Š_Small___ä",
    "mediumSize": "Š_Medium___ä",
    "largeSize": "Š_Large___ä",
    "customSize": "Š_Custom___ä",
    "embed": "Š_Embed this scene in a website__________ä",
    "more": "Š_Embed Options_____ä",
    "changeShareSettings": "Š_Change Share Settings_______ä",
    "shareLinkText": "Š_Choose who can view Copy________ä",
    "linkOptions": "Š_Link Options_____ä",
    "linkOptionsUrlParameters": "Š_Select URL parameters included in the link______________ä",
    "currentMapExtent": "Š_Current map extent______ä",
    "chooseCenterWithLevel": "Š_Click the map to define the center of the map with scale level____________________ä",
    "chooseCenterWithScale": "Š_Click the map to define the center of the map with map scale___________________ä",
    "findLocation": "Š_Find the location or feature and zoom to it______________ä",
    "findLocation_inputPlaceholder": "Š_Your place or feature_______ä",
    "queryFeature": "Š_Query a feature and zoom to it__________ä",
    "addMarker": "Š_Add a marker on the map________ä",
    "addMarker_titlePlaceholder": "Š_Title of the marker pop-up_________ä",
    "addMarker_symbolURL": "Š_Marker symbol URL______ä",
    "addMarker_label": "Š_Marker label_____ä",
    "overwirteMobileLayout": "Š_Overwrite default mobile layout__________ä",
    "language": "Š_Set the app language_______ä",
    "auth": "Š_Authenticate a user automatically___________ä",
    "linkPreview": "Š_Link Preview_____ä",
    "useShortenLink": "Š_Short Link____ä",
    "shareMapUrlExtent": "Š_shareMapUrlExtent______ä"
  },
  "webSceneLoader": {
    "webglSupportTip": "Š_3D web apps aren't supported in your browser_______________ä."
  }
});