define({
  "common": {
    "apply": "ä_Apply___Ü",
    "ok": "OK",
    "cancel": "Abbrechen",
    "yes": "ä_Yes__Ü",
    "no": "ä_No__Ü",
    "next": "Weiter",
    "back": "Zurück",
    "selected": "ä_selected___Ü",
    "name": "Name",
    "usage": "ä_Usage___Ü",
    "settings": "ä_Settings___Ü",
    "home": "ä_Home__Ü",
    "link": "ä_Link__Ü",
    "messages": "ä_Messages___Ü",
    "outputs": "ä_Outputs___Ü",
    "title": "Titel",
    "thumbnail": "ä_Thumbnail____Ü",
    "url": "ä_URL__Ü",
    "actions": "Aktionen",
    "layer": "Layer",
    "action": "ä_Action___Ü",
    "input": "ä_Input___Ü",
    "output": "ä_Output___Ü",
    "type": "ä_Type__Ü",
    "required": "ä_Required___Ü",
    "options": "ä_Options___Ü",
    "label": "Beschriftung",
    "tooltip": "ä_Tooltip___Ü",
    "visible": "ä_Visible___Ü",
    "symbol": "ä_Symbol___Ü",
    "popup": "ä_Popup___Ü",
    "upload": "ä_Upload___Ü",
    "execute": "ä_Execute___Ü",
    "help": "ä_Help__Ü",
    "executing": "ä_Executing____Ü",
    "clear": "Löschen",
    "error": "ä_Error___Ü",
    "zoomTo": "Zoomen auf",
    "attribute": "ä_Attribute____Ü",
    "exports": "ä_Export___Ü",
    "check": "ä_Check___Ü",
    "save": "ä_Save__Ü",
    "close": "ä_Close___Ü",
    "deleteText": "ä_Delete___Ü",
    "map": "Karte",
    "scene": "ä_Scene___Ü",
    "reset": "ä_Reset___Ü",
    "icon": "ä_Icon__Ü",
    "share": "ä_Share___Ü"
  },
  "errorCode": "Code",
  "errorMessage": "Meldung",
  "errorDetail": "Detail",
  "widgetPlaceholderTooltip": "Zum Einrichten zu Widgets wechseln und auf den entsprechenden Platzhalter klicken",
  "fieldStatistics": {
    "statistics": "ä_Statistics____Ü",
    "field": "Feld",
    "count": "ä_Number of Values______Ü",
    "sum": "ä_Sum of Values_____Ü",
    "min": "ä_Minimum___Ü",
    "max": "ä_Maximum___Ü",
    "ave": "ä_Average___Ü",
    "stddev": "ä_Standard Deviation______Ü"
  },
  "symbolChooser": {
    "preview": "Vorschau",
    "basic": "Anfänger",
    "arrows": "Pfeile",
    "business": "Gewerbe",
    "cartographic": "Kartografisch",
    "nationalParkService": "National Park Service",
    "outdoorRecreation": "Erholung im Freien",
    "peoplePlaces": "Öffentliche Plätze",
    "safetyHealth": "Sicherheit und Gesundheit",
    "shapes": "Shapes",
    "transportation": "Verkehr",
    "symbolSize": "Symbolgröße",
    "color": "Farbe",
    "alpha": "Alpha",
    "outlineColor": "Umrissfarbe",
    "outlineWidth": "Umrissbreite",
    "style": "Style",
    "width": "Breite",
    "text": "Text",
    "fontColor": "Schriftfarbe",
    "fontSize": "Schriftgröße",
    "transparency": "Transparenz",
    "solid": "Durchgezogen",
    "dash": "Gestrichelt",
    "dot": "Punkt",
    "dashDot": "Strich-Punkt",
    "dashDotDot": "Strich-Punkt-Punkt"
  },
  "transparency": {
    "opaque": "Nicht transparent",
    "transparent": "Transparent"
  },
  "rendererChooser": {
    "domain": "Domäne",
    "use": "Verwenden",
    "singleSymbol": "Ein Symbol",
    "uniqueSymbol": "Einzelsymbole",
    "color": "Farbe",
    "size": "Größe",
    "toShow": "Anzeigen",
    "colors": "Farben",
    "classes": "Klassen",
    "symbolSize": "Symbolgröße",
    "addValue": "Wert hinzufügen",
    "setDefaultSymbol": "Standardsymbol festlegen",
    "defaultSymbol": "Standardsymbol",
    "selectedSymbol": "Ausgewähltes Symbol",
    "value": "Wert",
    "label": "ä_Label___Ü",
    "range": "Bereich"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linie",
    "polyline": "Polylinie",
    "freehandPolyline": "Freihand-Polylinie",
    "triangle": "Dreieck",
    "extent": "Ausdehnung",
    "circle": "Kreis",
    "ellipse": "Ellipse",
    "polygon": "Polygon",
    "freehandPolygon": "Freihand-Polygon",
    "text": "Text",
    "clear": "ä_Clear___Ü"
  },
  "popupConfig": {
    "title": "ä_Title___Ü",
    "add": "Hinzufügen",
    "fields": "Felder",
    "noField": "Kein Feld",
    "visibility": "Sichtbar",
    "name": "ä_Name__Ü",
    "alias": "Alias",
    "actions": "ä_Actions___Ü"
  },
  "includeButton": {
    "include": "Einbinden"
  },
  "loadingShelter": {
    "loading": "Wird geladen"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Keinen Service gefunden.",
    "unableConnectTo": "Verbindung kann nicht hergestellt werden",
    "invalidUrlTip": "Die eingegebene URL ist ungültig oder es kann nicht darauf zugegriffen werden."
  },
  "serviceBrowser": {
    "noGpFound": "Keinen Geoverarbeitungsservice gefunden.",
    "unableConnectTo": "Verbindung kann nicht hergestellt werden"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Keinen Kartenservice oder Feature-Service gefunden",
    "unableConnectTo": "Verbindung kann nicht hergestellt werden"
  },
  "basicServiceChooser": {
    "validate": "Überprüfen",
    "example": "Beispiel",
    "set": "Festlegen"
  },
  "urlInput": {
    "invalidUrl": "Ungültige URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ungültige URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Filterausdruck hinzufügen",
    "addSet": "Eine Gruppe von Ausdrücken hinzufügen",
    "matchMsg": "Features im Layer abrufen, bei denen ${any_or_all} der folgenden Ausdrücke zutreffen",
    "matchMsgSet": "${any_or_all} der folgenden Ausdrücke dieser Abfrage erfüllen die Bedingung",
    "all": "Alle",
    "any": "Einige",
    "value": "Wert",
    "field": "ä_Field___Ü",
    "unique": "Eindeutig",
    "none": "Keine",
    "and": "und",
    "valueTooltip": "Wert eingeben",
    "fieldTooltip": "Aus vorhandenem Feld auswählen",
    "uniqueValueTooltip": "Aus eindeutigen Werten im ausgewählten Feld auswählen",
    "stringOperatorIs": "ist",
    "stringOperatorIsNot": "ist nicht",
    "stringOperatorStartsWith": "beginnt mit",
    "stringOperatorEndsWith": "endet mit",
    "stringOperatorContains": "enthält",
    "stringOperatorDoesNotContain": "enthält nicht",
    "stringOperatorIsBlank": "ist leer",
    "stringOperatorIsNotBlank": "ist nicht leer",
    "dateOperatorIsOn": "ist am",
    "dateOperatorIsNotOn": "ist nicht am",
    "dateOperatorIsBefore": "ist vor",
    "dateOperatorIsAfter": "ist nach",
    "dateOperatorDays": "Tagen",
    "dateOperatorWeeks": "Wochen",
    "dateOperatorMonths": "Monate",
    "dateOperatorInTheLast": "in den letzten",
    "dateOperatorNotInTheLast": "nicht in den letzten",
    "dateOperatorIsBetween": "liegt zwischen",
    "dateOperatorIsNotBetween": "liegt nicht zwischen",
    "dateOperatorIsBlank": "ist leer",
    "dateOperatorIsNotBlank": "ist nicht leer",
    "numberOperatorIs": "ist",
    "numberOperatorIsNot": "ist nicht",
    "numberOperatorIsAtLeast": "ist mindestens",
    "numberOperatorIsLessThan": "ist kleiner als",
    "numberOperatorIsAtMost": "ist höchstens",
    "numberOperatorIsGreaterThan": "ist größer als",
    "numberOperatorIsBetween": "liegt zwischen",
    "numberOperatorIsNotBetween": "liegt nicht zwischen",
    "numberOperatorIsBlank": "ist leer",
    "numberOperatorIsNotBlank": "ist nicht leer",
    "string": "String",
    "number": "Zahl",
    "date": "Datum",
    "askForValues": "Werte abfragen",
    "prompt": "Eingabeaufforderung",
    "hint": "Hinweis",
    "error": {
      "invalidParams": "Ungültige Parameter.",
      "invalidUrl": "Ungültige URL.",
      "noFilterFields": "Der Layer verfügt über keine Felder, die gefiltert werden können.",
      "invalidSQL": "Ungültiger SQL-Ausdruck.",
      "cantParseSQL": "SQL-Ausdruck kann nicht geparst werden."
    },
    "caseSensitive": "Groß-/Kleinschreibung beachten",
    "notSupportCaseSensitiveTip": "Gehostete Services unterstützen keine Abfragen, bei denen zwischen Groß- und Kleinschreibung unterschieden wird."
  },
  "featureLayerSource": {
    "layer": "Layer",
    "browse": "Durchsuchen",
    "selectFromMap": "Aus Karte auswählen",
    "selectFromPortal": "Aus Portal for ArcGIS hinzufügen",
    "addServiceUrl": "Service-URL hinzufügen",
    "inputLayerUrl": "Eingabe-Layer-URL",
    "selectLayer": "Feature-Layer aus aktueller Karte auswählen.",
    "chooseItem": "Ein Feature-Layer-Element auswählen.",
    "setServiceUrl": "Geben Sie die URL des Feature-Service oder des Kartenservice ein.",
    "selectFromOnline": "Aus ArcGIS Online hinzufügen",
    "chooseLayer": "Wählen Sie einen Feature-Layer aus."
  },
  "queryableLayerSource": {
    "layer": "ä_Layer___Ü",
    "browse": "Durchsuchen",
    "selectFromMap": "Aus Karte auswählen",
    "selectFromPortal": "Aus Portal for ArcGIS hinzufügen",
    "addServiceUrl": "Service-URL hinzufügen",
    "inputLayerUrl": "Eingabe-Layer-URL",
    "selectLayer": "Wählen Sie einen Layer aus der aktuellen Karte aus.",
    "chooseItem": "Wählen Sie ein Element aus.",
    "setServiceUrl": "Geben Sie die URL des Service ein.",
    "selectFromOnline": "Aus ArcGIS Online hinzufügen",
    "chooseLayer": "Wählen Sie einen Layer aus."
  },
  "gpSource": {
    "selectFromPortal": "Aus Portal for ArcGIS hinzufügen",
    "addServiceUrl": "Service-URL hinzufügen",
    "selectFromOnline": "Aus ArcGIS Online hinzufügen",
    "setServiceUrl": "Geben Sie die URL des Geoverarbeitungsservice an.",
    "chooseItem": "Wählen Sie ein Geoverarbeitungsserviceelement aus.",
    "chooseTask": "Wählen Sie einen Geoverarbeitungs-Task aus."
  },
  "itemSelector": {
    "map": "ä_Map__Ü",
    "selectWebMap": "Webkarte auswählen",
    "addMapFromOnlineOrPortal": "Suchen Sie in der Anwendung eine Webkarte in den öffentlichen ArcGIS Online-Ressourcen oder Ihren privaten Inhalten in ArcGIS Online oder Portal und fügen Sie sie hinzu.",
    "searchMapName": "Nach Kartenname suchen...",
    "searchNone": "Die gesuchten Informationen konnten nicht gefunden werden. Versuchen Sie es erneut.",
    "groups": "Gruppen",
    "noneGroups": "Keine Gruppen",
    "signInTip": "Ihre Anmeldesitzung ist abgelaufen. Aktualisieren Sie Ihren Browser, um sich erneut bei Ihrem Portal anzumelden.",
    "signIn": "Anmelden",
    "publicMap": "Öffentlichkeit",
    "myOrganization": "Eigene Organisation",
    "myGroup": "Eigene Gruppen",
    "myContent": "Eigene Inhalte",
    "count": "ä_Count___Ü",
    "fromPortal": "aus Portal",
    "fromOnline": "aus ArcGIS.com",
    "noneThumbnail": "Miniaturansicht nicht verfügbar",
    "owner": "Besitzer",
    "signInTo": "Melden Sie sich an bei",
    "lastModified": "Zuletzt geändert",
    "moreDetails": "Mehr Details"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Der Service unterstützt keine Abfragen."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "In der Karte ist kein geeigneter Layer verfügbar."
  },
  "layerInfosMenu": {
    "titleBasemap": "Grundkarten",
    "titleLayers": "Operationale Layer",
    "labelLayer": "Layer-Name",
    "itemZoomTo": "Zoomen auf",
    "itemTransparency": "Transparenz",
    "itemTransparent": "Transparent",
    "itemOpaque": "Nicht transparent",
    "itemMoveUp": "Nach oben verschieben",
    "itemMoveDown": "Nach unten verschieben",
    "itemDesc": "Beschreibung",
    "itemDownload": "Herunterladen",
    "itemToAttributeTable": "Attributtabelle öffnen"
  },
  "imageChooser": {
    "unsupportReaderAPI": "ZU ERLEDIGEN: Der Browser unterstützt die Datei-Reader-API nicht",
    "readError": "Die Datei kann nicht gelesen werden.",
    "unknowError": "Vorgänge können nicht abgeschlossen werden",
    "invalidType": "Ungültiger Dateityp.",
    "cropImage": "ä_Crop Image____Ü",
    "exceed": "Dateigröße darf 1024 KB nicht überschreiten",
    "enableFlash": "ZU ERLEDIGEN: Flash aktivieren.",
    "cropWaining": "Wählen Sie ein Foto mit einem Format von mindestens ${width} x ${height} Pixel aus.",
    "toolTip": "Optimale Ergebnisse erzielen Sie mit einer Bildgröße von ${width} x ${height} Pixel (Breite x Höhe). Andere Größen werden angepasst. Zulässige Bildformate sind: PNG, GIF und JPEG."
  },
  "simpleTable": {
    "moveUp": "Nach oben verschieben",
    "moveDown": "Nach unten verschieben",
    "deleteRow": "Löschen",
    "edit": "Bearbeiten"
  },
  "urlParams": {
    "invalidToken": "Ungültiges Token",
    "validateTokenError": "Ungültiges Token oder Netzwerkfehler"
  },
  "exportTo": {
    "exportTo": "Exportieren",
    "toCSV": "In CSV-Datei exportieren",
    "toFeatureCollection": "In Feature-Sammlung exportieren",
    "toGeoJSON": "In GeoJSON exportieren"
  },
  "appState": {
    "title": "ä_App State____Ü",
    "restoreMap": "Klicken Sie, um den zuvor erreichten Status der Kartenausdehnung und der Layer-Sichtbarkeit wiederherzustellen."
  },
  "featureActions": {
    "ZoomTo": "ä_Zoom to___Ü",
    "PanTo": "ä_Pan to___Ü",
    "Flash": "ä_Flash___Ü",
    "ShowPopup": "ä_Show Pop-up____Ü",
    "CreateLayer": "ä_Create Layer_____Ü",
    "ShowStatistics": "ä_Statistics_____Ü...",
    "ClearSelection": "ä_Clear Selection______Ü",
    "ExportToCSV": "ä_Export to CSV file______Ü",
    "ExportToFeatureCollection": "ä_Export to Feature Collection_________Ü",
    "ExportToGeoJSON": "ä_Export to GeoJSON______Ü"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ä_Related layer_____Ü",
    "selectedFeatures": "ä_Selected features______Ü",
    "drawShapesTip": "ä_Draw shapes to select features__________Ü",
    "pleaseDrawShapesTip": "ä_Please draw shapes to select features____________Ü",
    "allFeaturesTip": "ä_All features in the layer_________Ü",
    "selectFeaturesOrDrawShapesTip": "ä_Please use selected features in this layer or draw shapes on map to limit features__________________________Ü."
  },
  "searchDistance": {
    "applySearchDistance": "ä_Apply a search distance________Ü",
    "applySearchDistanceToFeatures": "ä_Apply a search distance to selected features______________Ü"
  },
  "units": {
    "miles": "ä_Miles___Ü",
    "kilometers": "ä_Kilometers____Ü",
    "feet": "ä_Feet__Ü",
    "meters": "ä_Meters___Ü",
    "yards": "ä_Yards___Ü",
    "nauticalMiles": "ä_Nautical Miles_____Ü"
  },
  "featureSetChooser": {
    "select": "ä_Select___Ü",
    "dragBox": "ä_Drag__Ü",
    "dragMouse": "ä_Darg the mouse_____Ü",
    "selectByRectangle": "ä_Select By Rectangle_______Ü",
    "selectFeaturesTip": "ä_Select features by dragging box around them on map________________Ü",
    "newSelectionTip": "ä_Create a new selection________Ü",
    "addSelectionTip": "ä_Add to the current selection_________Ü",
    "removeSelectionTip": "ä_Remove from the current selection___________Ü",
    "selectFromCurrentSelectionTip": "ä_Select from the current selection___________Ü",
    "unselectAllSelectionTip": "ä_Unselect all currently selected features_____________Ü"
  },
  "widgetManager": {
    "createWidgetError": "ä_Create widget error_______Ü",
    "createWidgetSettingPageError": "ä_Create widget setting page error___________Ü",
    "loadWidgetResourceError": "ä_Load widget resouce error_________Ü"
  },
  "shareOptions": {
    "shareMap": "ä_Choose who can view this app_________Ü",
    "shareMapTips": "ä_Your map is currentlt shared with these people_______________Ü",
    "everyone": "ä_everyone___Ü",
    "theseGroups": "ä_theseGroups____Ü"
  },
  "shareLink": {
    "email": "ä_email___Ü",
    "shareEmail": "ä_Email___Ü",
    "facebook": "ä_facebook___Ü",
    "shareFacebook": "ä_Facebook___Ü",
    "twitter": "ä_twitter___Ü",
    "shareTwitter": "ä_Twitter___Ü",
    "googlePlus": "ä_googlePlus____Ü",
    "shareGooglePlus": "ä_GooglePlus____Ü",
    "EmbedTips": "ä_Embed this scene in a website__________Ü",
    "shareEmailTxt1": "ä_Have a look at this Web Scene__________Ü:",
    "shareEmailTxt2": "ä_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________Ü.",
    "smallSize": "ä_Small___Ü",
    "mediumSize": "ä_Medium___Ü",
    "largeSize": "ä_Large___Ü",
    "customSize": "ä_Custom___Ü",
    "embed": "ä_Embed this scene in a website__________Ü",
    "more": "ä_Embed Options_____Ü",
    "changeShareSettings": "ä_Change Share Settings_______Ü",
    "shareLinkText": "ä_Choose who can view Copy________Ü",
    "linkOptions": "ä_Link Options_____Ü",
    "linkOptionsUrlParameters": "ä_Select URL parameters included in the link______________Ü",
    "currentMapExtent": "ä_Current map extent______Ü",
    "chooseCenterWithLevel": "ä_Click the map to define the center of the map with scale level____________________Ü",
    "chooseCenterWithScale": "ä_Click the map to define the center of the map with map scale___________________Ü",
    "findLocation": "ä_Find the location or feature and zoom to it______________Ü",
    "findLocation_inputPlaceholder": "ä_Your place or feature_______Ü",
    "queryFeature": "ä_Query a feature and zoom to it__________Ü",
    "addMarker": "ä_Add a marker on the map________Ü",
    "addMarker_titlePlaceholder": "ä_Title of the marker pop-up_________Ü",
    "addMarker_symbolURL": "ä_Marker symbol URL______Ü",
    "addMarker_label": "ä_Marker label_____Ü",
    "overwirteMobileLayout": "ä_Overwrite default mobile layout__________Ü",
    "language": "ä_Set the app language_______Ü",
    "auth": "ä_Authenticate a user automatically___________Ü",
    "linkPreview": "ä_Link Preview_____Ü",
    "useShortenLink": "ä_Short Link____Ü",
    "shareMapUrlExtent": "ä_shareMapUrlExtent______Ü"
  },
  "webSceneLoader": {
    "webglSupportTip": "ä_3D web apps aren't supported in your browser_______________Ü."
  }
});