define({
  "common": {
    "apply": "須_Apply___鷗",
    "ok": "OK",
    "cancel": "キャンセル",
    "yes": "須_Yes__鷗",
    "no": "須_No__鷗",
    "next": "次へ",
    "back": "戻る",
    "selected": "須_selected___鷗",
    "name": "名前",
    "usage": "須_Usage___鷗",
    "settings": "須_Settings___鷗",
    "home": "須_Home__鷗",
    "link": "須_Link__鷗",
    "messages": "須_Messages___鷗",
    "outputs": "須_Outputs___鷗",
    "title": "タイトル",
    "thumbnail": "須_Thumbnail____鷗",
    "url": "須_URL__鷗",
    "actions": "アクション",
    "layer": "レイヤー",
    "action": "須_Action___鷗",
    "input": "須_Input___鷗",
    "output": "須_Output___鷗",
    "type": "須_Type__鷗",
    "required": "須_Required___鷗",
    "options": "須_Options___鷗",
    "label": "ラベル",
    "tooltip": "須_Tooltip___鷗",
    "visible": "須_Visible___鷗",
    "symbol": "須_Symbol___鷗",
    "popup": "須_Popup___鷗",
    "upload": "須_Upload___鷗",
    "execute": "須_Execute___鷗",
    "help": "須_Help__鷗",
    "executing": "須_Executing____鷗",
    "clear": "消去",
    "error": "須_Error___鷗",
    "zoomTo": "ズーム",
    "attribute": "須_Attribute____鷗",
    "exports": "須_Export___鷗",
    "check": "須_Check___鷗",
    "save": "須_Save__鷗",
    "close": "須_Close___鷗",
    "deleteText": "須_Delete___鷗",
    "map": "マップ",
    "scene": "須_Scene___鷗",
    "reset": "須_Reset___鷗",
    "icon": "須_Icon__鷗",
    "share": "須_Share___鷗"
  },
  "errorCode": "コード",
  "errorMessage": "メッセージ",
  "errorDetail": "詳細",
  "widgetPlaceholderTooltip": "これを設定するには、ウィジェットに移動して、対応するプレースホルダーをクリックします",
  "fieldStatistics": {
    "statistics": "須_Statistics____鷗",
    "field": "フィールド",
    "count": "須_Number of Values______鷗",
    "sum": "須_Sum of Values_____鷗",
    "min": "須_Minimum___鷗",
    "max": "須_Maximum___鷗",
    "ave": "須_Average___鷗",
    "stddev": "須_Standard Deviation______鷗"
  },
  "symbolChooser": {
    "preview": "プレビュー",
    "basic": "基本",
    "arrows": "矢印",
    "business": "ビジネス",
    "cartographic": "カートグラフィック",
    "nationalParkService": "アメリカ国立公園",
    "outdoorRecreation": "野外レクリエーション",
    "peoplePlaces": "人と場所",
    "safetyHealth": "安全と衛生",
    "shapes": "形状",
    "transportation": "交通",
    "symbolSize": "シンボル サイズ",
    "color": "色",
    "alpha": "透過",
    "outlineColor": "アウトライン色",
    "outlineWidth": "アウトライン幅",
    "style": "スタイル",
    "width": "幅",
    "text": "テキスト",
    "fontColor": "フォントの色",
    "fontSize": "フォント サイズ",
    "transparency": "透過表示",
    "solid": "実線",
    "dash": "破線",
    "dot": "点線",
    "dashDot": "1 点鎖線",
    "dashDotDot": "2 点鎖線"
  },
  "transparency": {
    "opaque": "不透明",
    "transparent": "透明"
  },
  "rendererChooser": {
    "domain": "ドメイン",
    "use": "使用",
    "singleSymbol": "単一シンボル",
    "uniqueSymbol": "個別値シンボル",
    "color": "色",
    "size": "サイズ",
    "toShow": "表示",
    "colors": "色",
    "classes": "等級",
    "symbolSize": "シンボル サイズ",
    "addValue": "値の追加",
    "setDefaultSymbol": "デフォルト シンボルの設定",
    "defaultSymbol": "デフォルト シンボル",
    "selectedSymbol": "選択時のシンボル",
    "value": "値",
    "label": "須_Label___鷗",
    "range": "範囲"
  },
  "drawBox": {
    "point": "ポイント",
    "line": "ライン",
    "polyline": "ポリライン",
    "freehandPolyline": "フリーハンド ポリライン",
    "triangle": "三角形",
    "extent": "範囲",
    "circle": "円",
    "ellipse": "楕円",
    "polygon": "ポリゴン",
    "freehandPolygon": "フリーハンド ポリゴン",
    "text": "テキスト",
    "clear": "須_Clear___鷗"
  },
  "popupConfig": {
    "title": "須_Title___鷗",
    "add": "追加",
    "fields": "フィールド",
    "noField": "フィールドがありません",
    "visibility": "表示",
    "name": "須_Name__鷗",
    "alias": "エイリアス",
    "actions": "須_Actions___鷗"
  },
  "includeButton": {
    "include": "含む"
  },
  "loadingShelter": {
    "loading": "読み込んでいます"
  },
  "basicServiceBrowser": {
    "noServicesFound": "サービスが見つかりませんでした。",
    "unableConnectTo": "次に接続できません:",
    "invalidUrlTip": "入力した URL は無効であるか、アクセスできません。"
  },
  "serviceBrowser": {
    "noGpFound": "ジオプロセシング サービスが見つかりませんでした。",
    "unableConnectTo": "次に接続できません:"
  },
  "layerServiceBrowser": {
    "noServicesFound": "マップ サービスまたはフィーチャ サービスが見つかりませんでした",
    "unableConnectTo": "次に接続できません:"
  },
  "basicServiceChooser": {
    "validate": "整合チェック",
    "example": "例",
    "set": "設定"
  },
  "urlInput": {
    "invalidUrl": "無効な URL です。"
  },
  "urlComboBox": {
    "invalidUrl": "無効な URL です。"
  },
  "filterBuilder": {
    "addAnotherExpression": "フィルターの条件式を追加",
    "addSet": "式セットの追加",
    "matchMsg": "次の条件式の ${any_or_all} に一致するレイヤーのフィーチャを取得",
    "matchMsgSet": "このセットの次の条件式の${any_or_all}に当てはまります。",
    "all": "すべて",
    "any": "一部",
    "value": "値",
    "field": "須_Field___鷗",
    "unique": "個別値",
    "none": "なし",
    "and": "かつ",
    "valueTooltip": "値の入力",
    "fieldTooltip": "既存のフィールドから選択",
    "uniqueValueTooltip": "選択されたフィールドの個別値から選択",
    "stringOperatorIs": "に等しい",
    "stringOperatorIsNot": "に等しくない",
    "stringOperatorStartsWith": "で始まる",
    "stringOperatorEndsWith": "で終わる",
    "stringOperatorContains": "を含む",
    "stringOperatorDoesNotContain": "を含まない",
    "stringOperatorIsBlank": "空である",
    "stringOperatorIsNotBlank": "空でない",
    "dateOperatorIsOn": "である",
    "dateOperatorIsNotOn": "でない",
    "dateOperatorIsBefore": "より前である",
    "dateOperatorIsAfter": "より後である",
    "dateOperatorDays": "日",
    "dateOperatorWeeks": "週",
    "dateOperatorMonths": "月",
    "dateOperatorInTheLast": "以内である",
    "dateOperatorNotInTheLast": "以内でない",
    "dateOperatorIsBetween": "の間にある",
    "dateOperatorIsNotBetween": "の間にない",
    "dateOperatorIsBlank": "空である",
    "dateOperatorIsNotBlank": "空でない",
    "numberOperatorIs": "に等しい",
    "numberOperatorIsNot": "に等しくない",
    "numberOperatorIsAtLeast": "以上",
    "numberOperatorIsLessThan": "より小さい",
    "numberOperatorIsAtMost": "以下",
    "numberOperatorIsGreaterThan": "より大きい",
    "numberOperatorIsBetween": "の間にある",
    "numberOperatorIsNotBetween": "の間にない",
    "numberOperatorIsBlank": "空である",
    "numberOperatorIsNotBlank": "空でない",
    "string": "文字列",
    "number": "数値",
    "date": "日付",
    "askForValues": "値の確認",
    "prompt": "プロンプト",
    "hint": "ヒント",
    "error": {
      "invalidParams": "無効なパラメーターです。",
      "invalidUrl": "無効な URL です。",
      "noFilterFields": "レイヤーには、フィルターに使用できるフィールドがありません。",
      "invalidSQL": "無効な SQL 式です。",
      "cantParseSQL": "SQL 式を解析できません。"
    },
    "caseSensitive": "大文字/小文字を区別します",
    "notSupportCaseSensitiveTip": "ホスト サービスでは、大文字/小文字を区別するクエリはサポートされていません。"
  },
  "featureLayerSource": {
    "layer": "レイヤー",
    "browse": "参照",
    "selectFromMap": "マップから選択",
    "selectFromPortal": "Portal for ArcGIS から追加",
    "addServiceUrl": "サービス URL を追加",
    "inputLayerUrl": "レイヤー URL を入力",
    "selectLayer": "現在のマップからフィーチャ レイヤーを選択",
    "chooseItem": "フィーチャ レイヤー アイテムを選択",
    "setServiceUrl": "フィーチャ サービスまたはマップ サービスの URL を入力",
    "selectFromOnline": "ArcGIS Online から追加",
    "chooseLayer": "フィーチャ レイヤーを選択します。"
  },
  "queryableLayerSource": {
    "layer": "須_Layer___鷗",
    "browse": "参照",
    "selectFromMap": "マップから選択",
    "selectFromPortal": "Portal for ArcGIS から追加",
    "addServiceUrl": "サービス URL の追加",
    "inputLayerUrl": "レイヤー URL を入力",
    "selectLayer": "現在のマップからレイヤーを選択します。",
    "chooseItem": "アイテムを選択します。",
    "setServiceUrl": "サービスの URL を入力します。",
    "selectFromOnline": "ArcGIS Online から追加",
    "chooseLayer": "レイヤーを選択します。"
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS から追加",
    "addServiceUrl": "サービス URL の追加",
    "selectFromOnline": "ArcGIS Online から追加",
    "setServiceUrl": "ジオプロセシング サービスの URL を入力します。",
    "chooseItem": "ジオプロセシング サービス アイテムを選択します。",
    "chooseTask": "ジオプロセシング タスクを選択します。"
  },
  "itemSelector": {
    "map": "須_Map__鷗",
    "selectWebMap": "Web マップの選択",
    "addMapFromOnlineOrPortal": "アプリケーションの Web マップを、ArcGIS Online のパブリック コンテンツから検索するか、ArcGIS Online または Portal のプライベート コンテンツから検索して追加します。",
    "searchMapName": "マップ名で検索...",
    "searchNone": "検索対象が見つかりませんでした。もう一度試してください。",
    "groups": "グループ",
    "noneGroups": "グループはありません",
    "signInTip": "ログイン セッションの期限が切れています。ブラウザーを更新して、ポータルにもう一度サイン インしてください。",
    "signIn": "サイン イン",
    "publicMap": "パブリック",
    "myOrganization": "組織",
    "myGroup": "マイ グループ",
    "myContent": "マイ コンテンツ",
    "count": "須_Count___鷗",
    "fromPortal": "ポータルから",
    "fromOnline": "ArcGIS.com から",
    "noneThumbnail": "サムネイルは使用できません",
    "owner": "所有者",
    "signInTo": "サイン イン",
    "lastModified": "最終更新日",
    "moreDetails": "詳細"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "サービスはクエリをサポートしていません。"
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "マップで利用できる適切なレイヤーがありません。"
  },
  "layerInfosMenu": {
    "titleBasemap": "ベースマップ",
    "titleLayers": "操作レイヤー",
    "labelLayer": "レイヤー名",
    "itemZoomTo": "ズーム",
    "itemTransparency": "透過表示",
    "itemTransparent": "透明",
    "itemOpaque": "不透明",
    "itemMoveUp": "上に移動",
    "itemMoveDown": "下に移動",
    "itemDesc": "説明",
    "itemDownload": "ダウンロード",
    "itemToAttributeTable": "属性テーブルを開く"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: ブラウザーはファイル リーダー API をサポートしていません",
    "readError": "ファイルの読み込みに失敗しました。",
    "unknowError": "操作を完了できません",
    "invalidType": "無効なファイル タイプです。",
    "cropImage": "須_Crop Image____鷗",
    "exceed": "ファイル サイズが 1024 KB を超えてはいけません。",
    "enableFlash": "TODO: フラッシュを有効にしてください。",
    "cropWaining": "少なくとも ${width} x ${height} ピクセルの写真を選択してください。",
    "toolTip": "一番見やすい画像サイズは、幅 ${width} ピクセル、高さ ${height} ピクセルです。その他のサイズでは自動的にサイズが調整されます。使用できる画像形式は、PNG、GIF、JPEG です。"
  },
  "simpleTable": {
    "moveUp": "上に移動",
    "moveDown": "下に移動",
    "deleteRow": "削除",
    "edit": "編集"
  },
  "urlParams": {
    "invalidToken": "無効なトークン",
    "validateTokenError": "無効なトークンまたはネットワーク エラー"
  },
  "exportTo": {
    "exportTo": "エクスポート",
    "toCSV": "CSV ファイルにエクスポート",
    "toFeatureCollection": "フィーチャ コレクションにエクスポート",
    "toGeoJSON": "GeoJSON にエクスポート"
  },
  "appState": {
    "title": "須_App State____鷗",
    "restoreMap": "クリックすると、マップ範囲およびオフにしていたレイヤーの表示設定を復元します。"
  },
  "featureActions": {
    "ZoomTo": "須_Zoom to___鷗",
    "PanTo": "須_Pan to___鷗",
    "Flash": "須_Flash___鷗",
    "ShowPopup": "須_Show Pop-up____鷗",
    "CreateLayer": "須_Create Layer_____鷗",
    "ShowStatistics": "須_Statistics_____鷗...",
    "ClearSelection": "須_Clear Selection______鷗",
    "ExportToCSV": "須_Export to CSV file______鷗",
    "ExportToFeatureCollection": "須_Export to Feature Collection_________鷗",
    "ExportToGeoJSON": "須_Export to GeoJSON______鷗"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "須_Related layer_____鷗",
    "selectedFeatures": "須_Selected features______鷗",
    "drawShapesTip": "須_Draw shapes to select features__________鷗",
    "pleaseDrawShapesTip": "須_Please draw shapes to select features____________鷗",
    "allFeaturesTip": "須_All features in the layer_________鷗",
    "selectFeaturesOrDrawShapesTip": "須_Please use selected features in this layer or draw shapes on map to limit features__________________________鷗."
  },
  "searchDistance": {
    "applySearchDistance": "須_Apply a search distance________鷗",
    "applySearchDistanceToFeatures": "須_Apply a search distance to selected features______________鷗"
  },
  "units": {
    "miles": "須_Miles___鷗",
    "kilometers": "須_Kilometers____鷗",
    "feet": "須_Feet__鷗",
    "meters": "須_Meters___鷗",
    "yards": "須_Yards___鷗",
    "nauticalMiles": "須_Nautical Miles_____鷗"
  },
  "featureSetChooser": {
    "select": "須_Select___鷗",
    "dragBox": "須_Drag__鷗",
    "dragMouse": "須_Darg the mouse_____鷗",
    "selectByRectangle": "須_Select By Rectangle_______鷗",
    "selectFeaturesTip": "須_Select features by dragging box around them on map________________鷗",
    "newSelectionTip": "須_Create a new selection________鷗",
    "addSelectionTip": "須_Add to the current selection_________鷗",
    "removeSelectionTip": "須_Remove from the current selection___________鷗",
    "selectFromCurrentSelectionTip": "須_Select from the current selection___________鷗",
    "unselectAllSelectionTip": "須_Unselect all currently selected features_____________鷗"
  },
  "widgetManager": {
    "createWidgetError": "須_Create widget error_______鷗",
    "createWidgetSettingPageError": "須_Create widget setting page error___________鷗",
    "loadWidgetResourceError": "須_Load widget resouce error_________鷗"
  },
  "shareOptions": {
    "shareMap": "須_Choose who can view this app_________鷗",
    "shareMapTips": "須_Your map is currentlt shared with these people_______________鷗",
    "everyone": "須_everyone___鷗",
    "theseGroups": "須_theseGroups____鷗"
  },
  "shareLink": {
    "email": "須_email___鷗",
    "shareEmail": "須_Email___鷗",
    "facebook": "須_facebook___鷗",
    "shareFacebook": "須_Facebook___鷗",
    "twitter": "須_twitter___鷗",
    "shareTwitter": "須_Twitter___鷗",
    "googlePlus": "須_googlePlus____鷗",
    "shareGooglePlus": "須_GooglePlus____鷗",
    "EmbedTips": "須_Embed this scene in a website__________鷗",
    "shareEmailTxt1": "須_Have a look at this Web Scene__________鷗:",
    "shareEmailTxt2": "須_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________鷗.",
    "smallSize": "須_Small___鷗",
    "mediumSize": "須_Medium___鷗",
    "largeSize": "須_Large___鷗",
    "customSize": "須_Custom___鷗",
    "embed": "須_Embed this scene in a website__________鷗",
    "more": "須_Embed Options_____鷗",
    "changeShareSettings": "須_Change Share Settings_______鷗",
    "shareLinkText": "須_Choose who can view Copy________鷗",
    "linkOptions": "須_Link Options_____鷗",
    "linkOptionsUrlParameters": "須_Select URL parameters included in the link______________鷗",
    "currentMapExtent": "須_Current map extent______鷗",
    "chooseCenterWithLevel": "須_Click the map to define the center of the map with scale level____________________鷗",
    "chooseCenterWithScale": "須_Click the map to define the center of the map with map scale___________________鷗",
    "findLocation": "須_Find the location or feature and zoom to it______________鷗",
    "findLocation_inputPlaceholder": "須_Your place or feature_______鷗",
    "queryFeature": "須_Query a feature and zoom to it__________鷗",
    "addMarker": "須_Add a marker on the map________鷗",
    "addMarker_titlePlaceholder": "須_Title of the marker pop-up_________鷗",
    "addMarker_symbolURL": "須_Marker symbol URL______鷗",
    "addMarker_label": "須_Marker label_____鷗",
    "overwirteMobileLayout": "須_Overwrite default mobile layout__________鷗",
    "language": "須_Set the app language_______鷗",
    "auth": "須_Authenticate a user automatically___________鷗",
    "linkPreview": "須_Link Preview_____鷗",
    "useShortenLink": "須_Short Link____鷗",
    "shareMapUrlExtent": "須_shareMapUrlExtent______鷗"
  },
  "webSceneLoader": {
    "webglSupportTip": "須_3D web apps aren't supported in your browser_______________鷗."
  }
});