define({
	addAChartSource: "Ř_Add a Chart Source_ů",
	sourceLabel: "Ř_Source label_ů",
	labelField: "Ř_Label field_ů",
	actions: "Ř_Actions_ů",
	hightLightColor: "Ř_Highlight color_ů",
	urlChartSource: "Ř_URL Chart Source_ů",
	layerChartSource: "Ř_Layer Chart Source_ů",
	searchUrl: "Ř_Search URL_ů",
	browse: "Ř_Browse_ů",
	layers: "Ř_Layers_ů",
	availableFields: "Ř_Available Fields_ů",
	charts: "Ř_Charts_ů",
	chartField: "Ř_Chart field_ů",
	description: "Ř_Description_ů",
	title: "Ř_Title_ů",
	type: "Ř_Type_ů",
	cancel: "Ř_Cancel_ů",
	addChartSource: "Ř_Add Chart Source_ů",
	updateChartSource: "Ř_Update Chart Source_ů",
	chartSources: "Ř_Chart Sources_ů",
	chartSource: "Ř_Chart Source_ů",
	general: "Ř_General_ů"
});