define({
	addAChartSource: "ø_Add a Chart Source_å",
	sourceLabel: "ø_Source label_å",
	labelField: "ø_Label field_å",
	actions: "ø_Actions_å",
	hightLightColor: "ø_Highlight color_å",
	urlChartSource: "ø_URL Chart Source_å",
	layerChartSource: "ø_Layer Chart Source_å",
	searchUrl: "ø_Search URL_å",
	browse: "ø_Browse_å",
	layers: "ø_Layers_å",
	availableFields: "ø_Available Fields_å",
	charts: "ø_Charts_å",
	chartField: "ø_Chart field_å",
	description: "ø_Description_å",
	title: "ø_Title_å",
	type: "ø_Type_å",
	cancel: "ø_Cancel_å",
	addChartSource: "ø_Add Chart Source_å",
	updateChartSource: "ø_Update Chart Source_å",
	chartSources: "ø_Chart Sources_å",
	chartSource: "ø_Chart Source_å",
	general: "ø_General_å"
});