define({
	root: {
		addAChartSource: "Add a Chart Source",
		sourceLabel: "Source label",
		labelField: "Label field",
		actions: "Actions",
		hightLightColor: "Highlight color",
		urlChartSource: "URL Chart Source",
		layerChartSource: "Layer Chart Source",
		searchUrl: "Search URL",
		browse: "Browse",
		layers: "Layers",
		availableFields: "Available Fields",
		charts: "Charts",
		chartField: "Chart field",
		description: "Description",
		title: "Title",
		type: "Type",
		cancel: "Cancel",
		addChartSource: "Add Chart Source",
		updateChartSource: "Update Chart Source",
		chartSources: "Chart Sources",
		chartSource: "Chart Source",
		general: "General",
		setSource: "Set Source",
		setSourceTip: "Please set chart source.",
		setLabelFieldTip: "Please select label field.",
		setMediaTip: "Please set a chart type at least."
	},
	"ar": false,
	"cs": false,
	"da": false,
	"de": false,
	"es": false,
	"et": false,
	"fi": false,
	"fr": false,
	"he": false,
	"it": false,
	"ja": false,
	"ko": false,
	"lt": false,
	"lv": false,
	"nb": false,
	"nl": false,
	"pl": false,
	"pt-BR": false,
	"pt-PT": false,
	"ro": false,
	"ru": false,
	"sv": false,
	"th": false,
	"tr": false,
	"zh-cn": true
});