define({
	addAChartSource: "á_Add a Chart Source_Ó",
	sourceLabel: "á_Source label_Ó",
	labelField: "á_Label field_Ó",
	actions: "á_Actions_Ó",
	hightLightColor: "á_Highlight color_Ó",
	urlChartSource: "á_URL Chart Source_Ó",
	layerChartSource: "á_Layer Chart Source_Ó",
	searchUrl: "á_Search URL_Ó",
	browse: "á_Browse_Ó",
	layers: "á_Layers_Ó",
	availableFields: "á_Available Fields_Ó",
	charts: "á_Charts_Ó",
	chartField: "á_Chart field_Ó",
	description: "á_Description_Ó",
	title: "á_Title_Ó",
	type: "á_Type_Ó",
	cancel: "á_Cancel_Ó",
	addChartSource: "á_Add Chart Source_Ó",
	updateChartSource: "á_Update Chart Source_Ó",
	chartSources: "á_Chart Sources_Ó",
	chartSource: "á_Chart Source_Ó",
	general: "á_General_Ó"
});