define({
  "common": {
    "apply": "æ_Apply___Â",
    "ok": "OK",
    "cancel": "Annuler",
    "yes": "æ_Yes__Â",
    "no": "æ_No__Â",
    "next": "Suivant",
    "back": "Retour",
    "selected": "æ_selected___Â",
    "name": "Nom",
    "usage": "æ_Usage___Â",
    "settings": "æ_Settings___Â",
    "home": "æ_Home__Â",
    "link": "æ_Link__Â",
    "messages": "æ_Messages___Â",
    "outputs": "æ_Outputs___Â",
    "title": "Titre",
    "thumbnail": "æ_Thumbnail____Â",
    "url": "æ_URL__Â",
    "actions": "Actions",
    "layer": "Couche",
    "action": "æ_Action___Â",
    "input": "æ_Input___Â",
    "output": "æ_Output___Â",
    "type": "æ_Type__Â",
    "required": "æ_Required___Â",
    "options": "æ_Options___Â",
    "label": "Etiquette",
    "tooltip": "æ_Tooltip___Â",
    "visible": "æ_Visible___Â",
    "symbol": "æ_Symbol___Â",
    "popup": "æ_Popup___Â",
    "upload": "æ_Upload___Â",
    "execute": "æ_Execute___Â",
    "help": "æ_Help__Â",
    "executing": "æ_Executing____Â",
    "clear": "Effacer",
    "error": "æ_Error___Â",
    "zoomTo": "Zoom",
    "attribute": "æ_Attribute____Â",
    "exports": "æ_Export___Â",
    "check": "æ_Check___Â",
    "save": "æ_Save__Â",
    "close": "æ_Close___Â",
    "deleteText": "æ_Delete___Â",
    "map": "Carte",
    "scene": "æ_Scene___Â",
    "reset": "æ_Reset___Â",
    "icon": "æ_Icon__Â",
    "share": "æ_Share___Â"
  },
  "errorCode": "Code",
  "errorMessage": "Message",
  "errorDetail": "Détail",
  "widgetPlaceholderTooltip": "Pour le configurer, accédez à Widgets et cliquez sur l’espace réservé correspondant",
  "fieldStatistics": {
    "statistics": "æ_Statistics____Â",
    "field": "Champ",
    "count": "æ_Number of Values______Â",
    "sum": "æ_Sum of Values_____Â",
    "min": "æ_Minimum___Â",
    "max": "æ_Maximum___Â",
    "ave": "æ_Average___Â",
    "stddev": "æ_Standard Deviation______Â"
  },
  "symbolChooser": {
    "preview": "Aperçu",
    "basic": "De base",
    "arrows": "Flèches",
    "business": "Entreprises",
    "cartographic": "Cartographie",
    "nationalParkService": "Service des parcs nationaux",
    "outdoorRecreation": "Activités de plein air",
    "peoplePlaces": "Personnes Lieux",
    "safetyHealth": "Sécurité Santé",
    "shapes": "Formes",
    "transportation": "Transports",
    "symbolSize": "Taille du symbole",
    "color": "Couleur",
    "alpha": "Alpha",
    "outlineColor": "Couleur du contour",
    "outlineWidth": "Largeur du contour",
    "style": "Style",
    "width": "Largeur",
    "text": "Texte",
    "fontColor": "Couleur de police",
    "fontSize": "Taille de police",
    "transparency": "Transparence",
    "solid": "Plein",
    "dash": "Tiret",
    "dot": "Point",
    "dashDot": "Tiret-point",
    "dashDotDot": "Tiret-point-point"
  },
  "transparency": {
    "opaque": "Opaque",
    "transparent": "Transparent"
  },
  "rendererChooser": {
    "domain": "Domaine",
    "use": "Utiliser",
    "singleSymbol": "Un seul symbole",
    "uniqueSymbol": "Des symboles uniques",
    "color": "Couleur",
    "size": "Taille",
    "toShow": "A afficher",
    "colors": "Couleurs",
    "classes": "Classes",
    "symbolSize": "Taille du symbole",
    "addValue": "Ajouter une valeur",
    "setDefaultSymbol": "Définir le symbole par défaut",
    "defaultSymbol": "Symbole par défaut",
    "selectedSymbol": "Symbole sélectionné",
    "value": "Valeur",
    "label": "æ_Label___Â",
    "range": "Plage"
  },
  "drawBox": {
    "point": "Point",
    "line": "Ligne",
    "polyline": "Polyligne",
    "freehandPolyline": "Polyligne à main levée",
    "triangle": "Triangle",
    "extent": "Etendue",
    "circle": "Cercle",
    "ellipse": "Ellipse",
    "polygon": "Polygone",
    "freehandPolygon": "Polygone à main levée",
    "text": "Texte",
    "clear": "æ_Clear___Â"
  },
  "popupConfig": {
    "title": "æ_Title___Â",
    "add": "Ajouter",
    "fields": "Champs",
    "noField": "Aucun champ",
    "visibility": "Visible",
    "name": "æ_Name__Â",
    "alias": "Alias",
    "actions": "æ_Actions___Â"
  },
  "includeButton": {
    "include": "Ajouter"
  },
  "loadingShelter": {
    "loading": "Chargement en cours"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Aucun service n’a été trouvé.",
    "unableConnectTo": "Connexion impossible à",
    "invalidUrlTip": "L'URL que vous avez saisie est incorrecte ou inaccessible."
  },
  "serviceBrowser": {
    "noGpFound": "Aucun service de géotraitement n’a été trouvé.",
    "unableConnectTo": "Connexion impossible à"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Aucun service de carte ou service d’entités n’a été trouvé",
    "unableConnectTo": "Connexion impossible à"
  },
  "basicServiceChooser": {
    "validate": "Valider",
    "example": "Exemple",
    "set": "Définir"
  },
  "urlInput": {
    "invalidUrl": "URL non valide."
  },
  "urlComboBox": {
    "invalidUrl": "URL non valide."
  },
  "filterBuilder": {
    "addAnotherExpression": "Ajouter une expression de filtre",
    "addSet": "Ajouter un jeu d’expressions",
    "matchMsg": "Obtenir les entités de la couche qui correspondent à ${any_or_all} des expressions suivantes",
    "matchMsgSet": "${any_or_all} des expressions suivantes dans ce jeu sont vraies",
    "all": "Tout",
    "any": "Certaines",
    "value": "Valeur",
    "field": "æ_Field___Â",
    "unique": "Unique",
    "none": "Aucun",
    "and": "et",
    "valueTooltip": "Entrer une valeur",
    "fieldTooltip": "Choisissez dans le champ existant",
    "uniqueValueTooltip": "Choisissez une des valeurs uniques dans le champ sélectionné",
    "stringOperatorIs": "est",
    "stringOperatorIsNot": "n'est pas",
    "stringOperatorStartsWith": "commence par",
    "stringOperatorEndsWith": "se termine par",
    "stringOperatorContains": "contient",
    "stringOperatorDoesNotContain": "ne contient pas",
    "stringOperatorIsBlank": "est vide",
    "stringOperatorIsNotBlank": "n'est pas vide",
    "dateOperatorIsOn": "est le",
    "dateOperatorIsNotOn": "n'est pas le",
    "dateOperatorIsBefore": "est avant",
    "dateOperatorIsAfter": "est après",
    "dateOperatorDays": "jours",
    "dateOperatorWeeks": "semaines",
    "dateOperatorMonths": "mois",
    "dateOperatorInTheLast": "au cours des derniers",
    "dateOperatorNotInTheLast": "pas au cours des derniers",
    "dateOperatorIsBetween": "est entre",
    "dateOperatorIsNotBetween": "n'est pas entre",
    "dateOperatorIsBlank": "est vide",
    "dateOperatorIsNotBlank": "n'est pas vide",
    "numberOperatorIs": "est",
    "numberOperatorIsNot": "n'est pas",
    "numberOperatorIsAtLeast": "est au moins",
    "numberOperatorIsLessThan": "est inférieur à",
    "numberOperatorIsAtMost": "est au plus",
    "numberOperatorIsGreaterThan": "est supérieur à",
    "numberOperatorIsBetween": "est entre",
    "numberOperatorIsNotBetween": "n'est pas entre",
    "numberOperatorIsBlank": "est vide",
    "numberOperatorIsNotBlank": "n'est pas vide",
    "string": "Chaîne",
    "number": "Nombre",
    "date": "Date",
    "askForValues": "Demander des valeurs",
    "prompt": "Invite",
    "hint": "Astuce",
    "error": {
      "invalidParams": "Paramètres non valides.",
      "invalidUrl": "URL non valide.",
      "noFilterFields": "La couche ne possède aucun champ pouvant être utilisé pour le filtrage.",
      "invalidSQL": "Expression SQL non valide.",
      "cantParseSQL": "Impossible d’analyser l’expression SQL."
    },
    "caseSensitive": "Respecter la casse",
    "notSupportCaseSensitiveTip": "Les services hébergés ne prennent pas en charge les requêtes respectant la casse."
  },
  "featureLayerSource": {
    "layer": "Couche",
    "browse": "Parcourir",
    "selectFromMap": "Sélectionner dans la carte",
    "selectFromPortal": "Ajouter depuis Portal for ArcGIS",
    "addServiceUrl": "Ajouter une URL de service",
    "inputLayerUrl": "URL de la couche en entrée",
    "selectLayer": "Sélectionnez une couche d’entités dans la carte actuelle.",
    "chooseItem": "Choisissez un élément de couche d’entités.",
    "setServiceUrl": "Entrez l’URL du service d’entités ou du service de carte.",
    "selectFromOnline": "Ajouter depuis ArcGIS Online",
    "chooseLayer": "Choisissez une couche d’entités."
  },
  "queryableLayerSource": {
    "layer": "æ_Layer___Â",
    "browse": "Parcourir",
    "selectFromMap": "Sélectionner dans la carte",
    "selectFromPortal": "Ajouter depuis Portal for ArcGIS",
    "addServiceUrl": "Ajouter une URL de service",
    "inputLayerUrl": "URL de la couche en entrée",
    "selectLayer": "Sélectionnez une couche dans la carte actuelle.",
    "chooseItem": "Choisissez un élément.",
    "setServiceUrl": "Saisissez l'URL du service.",
    "selectFromOnline": "Ajouter depuis ArcGIS Online",
    "chooseLayer": "Choisissez une couche."
  },
  "gpSource": {
    "selectFromPortal": "Ajouter depuis Portal for ArcGIS",
    "addServiceUrl": "Ajouter une URL de service",
    "selectFromOnline": "Ajouter depuis ArcGIS Online",
    "setServiceUrl": "Saisissez l'URL du service de géotraitement.",
    "chooseItem": "Choisissez un élément de service de géotraitement.",
    "chooseTask": "Choisissez une tâche de géotraitement."
  },
  "itemSelector": {
    "map": "æ_Map__Â",
    "selectWebMap": "Choisir une carte Web",
    "addMapFromOnlineOrPortal": "Recherchez et ajoutez une carte Web dans l'application à partir des ressources publiques d'ArcGIS Online ou de votre contenu privé dans ArcGIS Online ou Portal for ArcGIS.",
    "searchMapName": "Rechercher par nom de carte...",
    "searchNone": "Votre recherche n’a pas abouti. Réessayez.",
    "groups": "Groupes",
    "noneGroups": "Aucun groupe",
    "signInTip": "Votre session de connexion a expiré. Actualisez votre navigateur pour vous reconnecter à votre portail.",
    "signIn": "Se connecter",
    "publicMap": "Public",
    "myOrganization": "Organisation",
    "myGroup": "Mes groupes",
    "myContent": "Contenus",
    "count": "æ_Count___Â",
    "fromPortal": "depuis le portail",
    "fromOnline": "depuis ArcGIS.com",
    "noneThumbnail": "Miniature indisponible",
    "owner": "propriétaire",
    "signInTo": "Se connecter à",
    "lastModified": "Dernière modification",
    "moreDetails": "Plus de détails"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Le service ne prend pas en charge l'interrogation."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Aucune couche appropriée n'est disponible sur la carte."
  },
  "layerInfosMenu": {
    "titleBasemap": "Fonds de carte",
    "titleLayers": "Couches opérationnelles",
    "labelLayer": "Nom de la couche",
    "itemZoomTo": "Zoom",
    "itemTransparency": "Transparence",
    "itemTransparent": "Transparent",
    "itemOpaque": "Opaque",
    "itemMoveUp": "Monter",
    "itemMoveDown": "Descendre",
    "itemDesc": "Description",
    "itemDownload": "Télécharger",
    "itemToAttributeTable": "Ouvrir la table attributaire"
  },
  "imageChooser": {
    "unsupportReaderAPI": "A FAIRE : le navigateur ne prend pas en charge l'API du lecteur de fichiers",
    "readError": "Echec de la lecture du fichier.",
    "unknowError": "impossible d'exécuter les opérations",
    "invalidType": "Type de fichier non valide.",
    "cropImage": "æ_Crop Image____Â",
    "exceed": "La taille du fichier ne peut pas dépasser 1 024 Ko",
    "enableFlash": "A FAIRE : activez Flash.",
    "cropWaining": "Choisissez une photo d'au moins ${width} x ${height} pixels.",
    "toolTip": "Pour optimiser les résultats, l'image doit être de ${width} pixels en largeur sur ${height} pixels en hauteur. Les autres tailles sont ajustées en conséquence. Les formats d'image acceptables sont : PNG, GIF et JPEG."
  },
  "simpleTable": {
    "moveUp": "Monter",
    "moveDown": "Descendre",
    "deleteRow": "Supprimer",
    "edit": "Modifier"
  },
  "urlParams": {
    "invalidToken": "Jeton non valide",
    "validateTokenError": "Jeton non valide ou erreur réseau"
  },
  "exportTo": {
    "exportTo": "Exporter",
    "toCSV": "Exporter vers un fichier CSV",
    "toFeatureCollection": "Exporter vers la collection d'entités",
    "toGeoJSON": "Exporter vers GeoJSON"
  },
  "appState": {
    "title": "æ_App State____Â",
    "restoreMap": "Cliquez pour restaurer l’étendue de la carte et la visibilité des couches là où vous en étiez resté."
  },
  "featureActions": {
    "ZoomTo": "æ_Zoom to___Â",
    "PanTo": "æ_Pan to___Â",
    "Flash": "æ_Flash___Â",
    "ShowPopup": "æ_Show Pop-up____Â",
    "CreateLayer": "æ_Create Layer_____Â",
    "ShowStatistics": "æ_Statistics_____Â...",
    "ClearSelection": "æ_Clear Selection______Â",
    "ExportToCSV": "æ_Export to CSV file______Â",
    "ExportToFeatureCollection": "æ_Export to Feature Collection_________Â",
    "ExportToGeoJSON": "æ_Export to GeoJSON______Â"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "æ_Related layer_____Â",
    "selectedFeatures": "æ_Selected features______Â",
    "drawShapesTip": "æ_Draw shapes to select features__________Â",
    "pleaseDrawShapesTip": "æ_Please draw shapes to select features____________Â",
    "allFeaturesTip": "æ_All features in the layer_________Â",
    "selectFeaturesOrDrawShapesTip": "æ_Please use selected features in this layer or draw shapes on map to limit features__________________________Â."
  },
  "searchDistance": {
    "applySearchDistance": "æ_Apply a search distance________Â",
    "applySearchDistanceToFeatures": "æ_Apply a search distance to selected features______________Â"
  },
  "units": {
    "miles": "æ_Miles___Â",
    "kilometers": "æ_Kilometers____Â",
    "feet": "æ_Feet__Â",
    "meters": "æ_Meters___Â",
    "yards": "æ_Yards___Â",
    "nauticalMiles": "æ_Nautical Miles_____Â"
  },
  "featureSetChooser": {
    "select": "æ_Select___Â",
    "dragBox": "æ_Drag__Â",
    "dragMouse": "æ_Darg the mouse_____Â",
    "selectByRectangle": "æ_Select By Rectangle_______Â",
    "selectFeaturesTip": "æ_Select features by dragging box around them on map________________Â",
    "newSelectionTip": "æ_Create a new selection________Â",
    "addSelectionTip": "æ_Add to the current selection_________Â",
    "removeSelectionTip": "æ_Remove from the current selection___________Â",
    "selectFromCurrentSelectionTip": "æ_Select from the current selection___________Â",
    "unselectAllSelectionTip": "æ_Unselect all currently selected features_____________Â"
  },
  "widgetManager": {
    "createWidgetError": "æ_Create widget error_______Â",
    "createWidgetSettingPageError": "æ_Create widget setting page error___________Â",
    "loadWidgetResourceError": "æ_Load widget resouce error_________Â"
  },
  "shareOptions": {
    "shareMap": "æ_Choose who can view this app_________Â",
    "shareMapTips": "æ_Your map is currentlt shared with these people_______________Â",
    "everyone": "æ_everyone___Â",
    "theseGroups": "æ_theseGroups____Â"
  },
  "shareLink": {
    "email": "æ_email___Â",
    "shareEmail": "æ_Email___Â",
    "facebook": "æ_facebook___Â",
    "shareFacebook": "æ_Facebook___Â",
    "twitter": "æ_twitter___Â",
    "shareTwitter": "æ_Twitter___Â",
    "googlePlus": "æ_googlePlus____Â",
    "shareGooglePlus": "æ_GooglePlus____Â",
    "EmbedTips": "æ_Embed this scene in a website__________Â",
    "shareEmailTxt1": "æ_Have a look at this Web Scene__________Â:",
    "shareEmailTxt2": "æ_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________Â.",
    "smallSize": "æ_Small___Â",
    "mediumSize": "æ_Medium___Â",
    "largeSize": "æ_Large___Â",
    "customSize": "æ_Custom___Â",
    "embed": "æ_Embed this scene in a website__________Â",
    "more": "æ_Embed Options_____Â",
    "changeShareSettings": "æ_Change Share Settings_______Â",
    "shareLinkText": "æ_Choose who can view Copy________Â",
    "linkOptions": "æ_Link Options_____Â",
    "linkOptionsUrlParameters": "æ_Select URL parameters included in the link______________Â",
    "currentMapExtent": "æ_Current map extent______Â",
    "chooseCenterWithLevel": "æ_Click the map to define the center of the map with scale level____________________Â",
    "chooseCenterWithScale": "æ_Click the map to define the center of the map with map scale___________________Â",
    "findLocation": "æ_Find the location or feature and zoom to it______________Â",
    "findLocation_inputPlaceholder": "æ_Your place or feature_______Â",
    "queryFeature": "æ_Query a feature and zoom to it__________Â",
    "addMarker": "æ_Add a marker on the map________Â",
    "addMarker_titlePlaceholder": "æ_Title of the marker pop-up_________Â",
    "addMarker_symbolURL": "æ_Marker symbol URL______Â",
    "addMarker_label": "æ_Marker label_____Â",
    "overwirteMobileLayout": "æ_Overwrite default mobile layout__________Â",
    "language": "æ_Set the app language_______Â",
    "auth": "æ_Authenticate a user automatically___________Â",
    "linkPreview": "æ_Link Preview_____Â",
    "useShortenLink": "æ_Short Link____Â",
    "shareMapUrlExtent": "æ_shareMapUrlExtent______Â"
  },
  "webSceneLoader": {
    "webglSupportTip": "æ_3D web apps aren't supported in your browser_______________Â."
  }
});