define({
  "common": {
    "apply": "ķ_Apply___ū",
    "ok": "Labi",
    "cancel": "Atcelt",
    "yes": "ķ_Yes__ū",
    "no": "ķ_No__ū",
    "next": "Tālāk",
    "back": "Atpakaļ",
    "selected": "ķ_selected___ū",
    "name": "Nosaukums",
    "usage": "ķ_Usage___ū",
    "settings": "ķ_Settings___ū",
    "home": "ķ_Home__ū",
    "link": "ķ_Link__ū",
    "messages": "ķ_Messages___ū",
    "outputs": "ķ_Outputs___ū",
    "title": "Nosaukums",
    "thumbnail": "ķ_Thumbnail____ū",
    "url": "ķ_URL__ū",
    "actions": "Darbības",
    "layer": "Slānis",
    "action": "ķ_Action___ū",
    "input": "ķ_Input___ū",
    "output": "ķ_Output___ū",
    "type": "ķ_Type__ū",
    "required": "ķ_Required___ū",
    "options": "ķ_Options___ū",
    "label": "Kartes teksts",
    "tooltip": "ķ_Tooltip___ū",
    "visible": "ķ_Visible___ū",
    "symbol": "ķ_Symbol___ū",
    "popup": "ķ_Popup___ū",
    "upload": "ķ_Upload___ū",
    "execute": "ķ_Execute___ū",
    "help": "ķ_Help__ū",
    "executing": "ķ_Executing____ū",
    "clear": "Notīrīt",
    "error": "ķ_Error___ū",
    "zoomTo": "Pietuvināt",
    "attribute": "ķ_Attribute____ū",
    "exports": "ķ_Export___ū",
    "check": "ķ_Check___ū",
    "save": "ķ_Save__ū",
    "close": "ķ_Close___ū",
    "deleteText": "ķ_Delete___ū",
    "map": "Karte",
    "scene": "ķ_Scene___ū",
    "reset": "ķ_Reset___ū",
    "icon": "ķ_Icon__ū",
    "share": "ķ_Share___ū"
  },
  "errorCode": "Kods",
  "errorMessage": "Ziņojums",
  "errorDetail": "Detalizēta informācija",
  "widgetPlaceholderTooltip": "Lai to iestatītu, pārejiet uz sadaļu Logrīki un noklikšķiniet uz atbilstošā viettura",
  "fieldStatistics": {
    "statistics": "ķ_Statistics____ū",
    "field": "Lauks",
    "count": "ķ_Number of Values______ū",
    "sum": "ķ_Sum of Values_____ū",
    "min": "ķ_Minimum___ū",
    "max": "ķ_Maximum___ū",
    "ave": "ķ_Average___ū",
    "stddev": "ķ_Standard Deviation______ū"
  },
  "symbolChooser": {
    "preview": "Priekšskatījums",
    "basic": "Pamata",
    "arrows": "Bultiņas",
    "business": "Bizness",
    "cartographic": "Kartogrāfisks",
    "nationalParkService": "Nacionālo parku pakalpojums",
    "outdoorRecreation": "Aktīvā atpūta",
    "peoplePlaces": "Personu vietas",
    "safetyHealth": "Drošība un veselība",
    "shapes": "Formas",
    "transportation": "Transports",
    "symbolSize": "Simbola lielums",
    "color": "Krāsa",
    "alpha": "Alfa",
    "outlineColor": "Kontūras krāsa",
    "outlineWidth": "Kontūras platums",
    "style": "Stils",
    "width": "Platums",
    "text": "Teksts",
    "fontColor": "Fonta krāsa",
    "fontSize": "Fonta lielums",
    "transparency": "Caurspīdīgums",
    "solid": "Tīrtoņa",
    "dash": "Svītra",
    "dot": "Punkts",
    "dashDot": "Svītra punkts",
    "dashDotDot": "Svītra punkts punkts"
  },
  "transparency": {
    "opaque": "Necaurredzams",
    "transparent": "Caurspīdīgs"
  },
  "rendererChooser": {
    "domain": "Domēns",
    "use": "Lietot",
    "singleSymbol": "Atsevišķs simbols",
    "uniqueSymbol": "Unikāli simboli",
    "color": "Krāsa",
    "size": "Lielums",
    "toShow": "Lai rādītu",
    "colors": "Krāsas",
    "classes": "Klases",
    "symbolSize": "Simbola lielums",
    "addValue": "Pievienot vērtību",
    "setDefaultSymbol": "Iestatīt noklusējuma simbolu",
    "defaultSymbol": "Noklusējuma simbols",
    "selectedSymbol": "Atlasītais simbols",
    "value": "Vērtība",
    "label": "ķ_Label___ū",
    "range": "Diapazons"
  },
  "drawBox": {
    "point": "Virsotne",
    "line": "Līnija",
    "polyline": "Līnija",
    "freehandPolyline": "Brīvrokas līnija",
    "triangle": "Trīsstūris",
    "extent": "Pārklājums",
    "circle": "Aplis",
    "ellipse": "Elipse",
    "polygon": "Laukums",
    "freehandPolygon": "Brīvrokas laukums",
    "text": "Teksts",
    "clear": "ķ_Clear___ū"
  },
  "popupConfig": {
    "title": "ķ_Title___ū",
    "add": "Pievienot",
    "fields": "Lauki",
    "noField": "Nav lauka",
    "visibility": "Redzams",
    "name": "ķ_Name__ū",
    "alias": "Aizstājvārds",
    "actions": "ķ_Actions___ū"
  },
  "includeButton": {
    "include": "Iekļaut"
  },
  "loadingShelter": {
    "loading": "Ielādē"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nav atrasts neviens pakalpojums.",
    "unableConnectTo": "Nevar izveidot savienojumu ar",
    "invalidUrlTip": "Jūsu ievadītais URL nav derīgs vai tam nevar piekļūt."
  },
  "serviceBrowser": {
    "noGpFound": "Nav atrasts neviens ģeodatu apstrādes pakalpojums.",
    "unableConnectTo": "Nevar izveidot savienojumu ar"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nav atrasts neviens karšu serviss vai elementu serviss",
    "unableConnectTo": "Nevar izveidot savienojumu ar"
  },
  "basicServiceChooser": {
    "validate": "Pārbaudīt",
    "example": "Piemērs",
    "set": "Kopa"
  },
  "urlInput": {
    "invalidUrl": "Nederīgs URL."
  },
  "urlComboBox": {
    "invalidUrl": "Nederīgs URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Pievienot filtra izteiksmi",
    "addSet": "Pievienot izteiksmju kopu",
    "matchMsg": "Iegūt slāņa elementus, kas atbilst ${any_or_all} no šādām izteiksmēm",
    "matchMsgSet": "${any_or_all} no šādām izteiksmēm šajā kopā ir patiesi",
    "all": "Visi",
    "any": "Jebkurš",
    "value": "Vērtība",
    "field": "ķ_Field___ū",
    "unique": "Unikāls",
    "none": "Nav",
    "and": "un",
    "valueTooltip": "Ievadiet vērtību",
    "fieldTooltip": "Izmeklēt no esošajiem laukiem",
    "uniqueValueTooltip": "Izmeklēt unikālas vērtības no izvēlētā lauka",
    "stringOperatorIs": "ir",
    "stringOperatorIsNot": "nav",
    "stringOperatorStartsWith": "sākas ar",
    "stringOperatorEndsWith": "beidzas ar",
    "stringOperatorContains": "ietver",
    "stringOperatorDoesNotContain": "neietver",
    "stringOperatorIsBlank": "ir tukšs",
    "stringOperatorIsNotBlank": "nav tukšs",
    "dateOperatorIsOn": "ir šajā datumā",
    "dateOperatorIsNotOn": "nav šajā datumā",
    "dateOperatorIsBefore": "ir pirms",
    "dateOperatorIsAfter": "ir pēc",
    "dateOperatorDays": "dienas",
    "dateOperatorWeeks": "nedēļas",
    "dateOperatorMonths": "mēneši",
    "dateOperatorInTheLast": "pagātnē",
    "dateOperatorNotInTheLast": "nav pagātnē",
    "dateOperatorIsBetween": "ir starp",
    "dateOperatorIsNotBetween": "nav starp",
    "dateOperatorIsBlank": "ir tukšs",
    "dateOperatorIsNotBlank": "nav tukšs",
    "numberOperatorIs": "ir",
    "numberOperatorIsNot": "nav",
    "numberOperatorIsAtLeast": "ir vismaz",
    "numberOperatorIsLessThan": "ir mazāks nekā",
    "numberOperatorIsAtMost": "ir visvairāk",
    "numberOperatorIsGreaterThan": "ir lielāks nekā",
    "numberOperatorIsBetween": "ir starp",
    "numberOperatorIsNotBetween": "nav starp",
    "numberOperatorIsBlank": "ir tukšs",
    "numberOperatorIsNotBlank": "nav tukšs",
    "string": "Virkne",
    "number": "Numurs",
    "date": "Datums",
    "askForValues": "Jautāt vērtības",
    "prompt": "Uzvedne",
    "hint": "Mājiens",
    "error": {
      "invalidParams": "Nederīgi parametri.",
      "invalidUrl": "Nederīgs URL.",
      "noFilterFields": "Slānī nav lauku, ko var izmantot filtram.",
      "invalidSQL": "Nederīga SQL izteiksme.",
      "cantParseSQL": "SQL izteiksmi nevar parsēt."
    },
    "caseSensitive": "Reģistrjutīgs",
    "notSupportCaseSensitiveTip": "Viesotie servisi neatbalsta reģistrjutīgu vaicājumu."
  },
  "featureLayerSource": {
    "layer": "Slānis",
    "browse": "Pārlūkot",
    "selectFromMap": "Izvēlēties no kartes",
    "selectFromPortal": "Pievienot no Portal for ArcGIS",
    "addServiceUrl": "Pievienot pakalpojuma vietrādi URL",
    "inputLayerUrl": "Ievadīt slāņa URL",
    "selectLayer": "Izvēlieties elementu slāni no pašreizējās kartes.",
    "chooseItem": "Izvēlieties elementu slāņa vienību.",
    "setServiceUrl": "Ievadiet elementu pakalpojuma vai kartes pakalpojuma vietrādi URL.",
    "selectFromOnline": "Pievienot no ArcGIS Online",
    "chooseLayer": "Izvēlieties elementu slāni."
  },
  "queryableLayerSource": {
    "layer": "ķ_Layer___ū",
    "browse": "Pārlūks",
    "selectFromMap": "Izvēlēties no kartes",
    "selectFromPortal": "Pievienot no Portal for ArcGIS",
    "addServiceUrl": "Pievienot pakalpojuma vietrādi URL",
    "inputLayerUrl": "Ievadīt slāņa URL",
    "selectLayer": "Atlasiet slāni no pašreizējās kartes.",
    "chooseItem": "Izvēlieties vienumu.",
    "setServiceUrl": "Ievadiet pakalpojuma URL.",
    "selectFromOnline": "Pievienot no ArcGIS Online",
    "chooseLayer": "Izvēlieties slāni."
  },
  "gpSource": {
    "selectFromPortal": "Pievienot no Portal for ArcGIS",
    "addServiceUrl": "Pievienot pakalpojuma vietrādi URL",
    "selectFromOnline": "Pievienot no ArcGIS Online",
    "setServiceUrl": "Ievadiet ģeogrāfisko datu apstrādes pakalpojuma vietrādi URL.",
    "chooseItem": "Izvēlieties ģeogrāfisko datu apstrādes pakalpojuma vienumu.",
    "chooseTask": "Izvēlieties ģeogrāfisko datu apstrādes uzdevumu."
  },
  "itemSelector": {
    "map": "ķ_Map__ū",
    "selectWebMap": "Izvēlieties web karti",
    "addMapFromOnlineOrPortal": "Atrodiet un pievienojiet web karti aplikācijā no ArcGIS Online publiskajiem resursiem vai sava privātā satura pakalpojumā ArcGIS Online vai Portal.",
    "searchMapName": "Meklēt pēc kartes nosaukuma...",
    "searchNone": "Neizdevās atrast to, ko meklējāt. Mēģiniet vēlreiz.",
    "groups": "Grupas",
    "noneGroups": "Nav grupu",
    "signInTip": "Jūsu pieteikšanās sesija ir beigusies; lai vēlreiz pierakstītos savā portālā, atsvaidziniet pārlūku.",
    "signIn": "Pierakstīties",
    "publicMap": "Publisks",
    "myOrganization": "Organizācija",
    "myGroup": "Manas Grupas",
    "myContent": "Mans saturs",
    "count": "ķ_Count___ū",
    "fromPortal": "no Portal",
    "fromOnline": "no ArcGIS.com",
    "noneThumbnail": "Sīktēls nav pieejams",
    "owner": "īpašnieks",
    "signInTo": "Pierakstīties",
    "lastModified": "Pēdējā modificēšana",
    "moreDetails": "Papildu detalizētā informācija"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Pakalpojums neatbalsta vaicājumu."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Kartē nav pieejams neviens piemērots slānis."
  },
  "layerInfosMenu": {
    "titleBasemap": "Pamatkartes",
    "titleLayers": "Operacionālie slāņi",
    "labelLayer": "Slāņa nosaukums",
    "itemZoomTo": "Pietuvināt",
    "itemTransparency": "Caurspīdīgums",
    "itemTransparent": "Caurspīdīgs",
    "itemOpaque": "Necaurredzams",
    "itemMoveUp": "Pārvietot uz augšu",
    "itemMoveDown": "Pārvietot uz leju",
    "itemDesc": "Apraksts",
    "itemDownload": "Lejupielāde",
    "itemToAttributeTable": "Atvērt atribūtu tabulu"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: pārlūks neatbalsta faila lasītāja API",
    "readError": "Neizdevās nolasīt failu.",
    "unknowError": "nevar pabeigt darbības",
    "invalidType": "Nederīgs faila tips.",
    "cropImage": "ķ_Crop Image____ū",
    "exceed": "Faila lielums nedrīkst pārsniegt 1024 KB",
    "enableFlash": "TODO: lūdzu, aktivizējiet flash.",
    "cropWaining": "Lūdzu, izvēlieties fotoattēlu, kura izmēri ir vismaz ${width} x ${height} pikseļi.",
    "toolTip": "Lai sasniegtu labākos rezultātus, attēla platumam jābūt ${width} pikseļiem un tā augstumam jābūt ${height} pikseļiem. Citi izmēri tiks pielāgoti, lai atbilstu. Akceptētie attēla formāti ir: PNG, GIF un JPEG."
  },
  "simpleTable": {
    "moveUp": "Pārvietot uz augšu",
    "moveDown": "Pārvietot uz leju",
    "deleteRow": "Dzēst",
    "edit": "Rediģēt"
  },
  "urlParams": {
    "invalidToken": "Nederīga pilnvara",
    "validateTokenError": "Nederīga pilnvara vai tīkla kļūda"
  },
  "exportTo": {
    "exportTo": "Eksportēt",
    "toCSV": "Eksports uz CSV failu",
    "toFeatureCollection": "Eksportēt uz elementu kolekciju",
    "toGeoJSON": "Eksportēt uz GeoJSON"
  },
  "appState": {
    "title": "ķ_App State____ū",
    "restoreMap": "Noklikšķiniet, lai atjaunotu kartes pārklājumu un slāņu redzamību kāda tā bija, kad pārtraucāt darbu."
  },
  "featureActions": {
    "ZoomTo": "ķ_Zoom to___ū",
    "PanTo": "ķ_Pan to___ū",
    "Flash": "ķ_Flash___ū",
    "ShowPopup": "ķ_Show Pop-up____ū",
    "CreateLayer": "ķ_Create Layer_____ū",
    "ShowStatistics": "ķ_Statistics_____ū...",
    "ClearSelection": "ķ_Clear Selection______ū",
    "ExportToCSV": "ķ_Export to CSV file______ū",
    "ExportToFeatureCollection": "ķ_Export to Feature Collection_________ū",
    "ExportToGeoJSON": "ķ_Export to GeoJSON______ū"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ķ_Related layer_____ū",
    "selectedFeatures": "ķ_Selected features______ū",
    "drawShapesTip": "ķ_Draw shapes to select features__________ū",
    "pleaseDrawShapesTip": "ķ_Please draw shapes to select features____________ū",
    "allFeaturesTip": "ķ_All features in the layer_________ū",
    "selectFeaturesOrDrawShapesTip": "ķ_Please use selected features in this layer or draw shapes on map to limit features__________________________ū."
  },
  "searchDistance": {
    "applySearchDistance": "ķ_Apply a search distance________ū",
    "applySearchDistanceToFeatures": "ķ_Apply a search distance to selected features______________ū"
  },
  "units": {
    "miles": "ķ_Miles___ū",
    "kilometers": "ķ_Kilometers____ū",
    "feet": "ķ_Feet__ū",
    "meters": "ķ_Meters___ū",
    "yards": "ķ_Yards___ū",
    "nauticalMiles": "ķ_Nautical Miles_____ū"
  },
  "featureSetChooser": {
    "select": "ķ_Select___ū",
    "dragBox": "ķ_Drag__ū",
    "dragMouse": "ķ_Darg the mouse_____ū",
    "selectByRectangle": "ķ_Select By Rectangle_______ū",
    "selectFeaturesTip": "ķ_Select features by dragging box around them on map________________ū",
    "newSelectionTip": "ķ_Create a new selection________ū",
    "addSelectionTip": "ķ_Add to the current selection_________ū",
    "removeSelectionTip": "ķ_Remove from the current selection___________ū",
    "selectFromCurrentSelectionTip": "ķ_Select from the current selection___________ū",
    "unselectAllSelectionTip": "ķ_Unselect all currently selected features_____________ū"
  },
  "widgetManager": {
    "createWidgetError": "ķ_Create widget error_______ū",
    "createWidgetSettingPageError": "ķ_Create widget setting page error___________ū",
    "loadWidgetResourceError": "ķ_Load widget resouce error_________ū"
  },
  "shareOptions": {
    "shareMap": "ķ_Choose who can view this app_________ū",
    "shareMapTips": "ķ_Your map is currentlt shared with these people_______________ū",
    "everyone": "ķ_everyone___ū",
    "theseGroups": "ķ_theseGroups____ū"
  },
  "shareLink": {
    "email": "ķ_email___ū",
    "shareEmail": "ķ_Email___ū",
    "facebook": "ķ_facebook___ū",
    "shareFacebook": "ķ_Facebook___ū",
    "twitter": "ķ_twitter___ū",
    "shareTwitter": "ķ_Twitter___ū",
    "googlePlus": "ķ_googlePlus____ū",
    "shareGooglePlus": "ķ_GooglePlus____ū",
    "EmbedTips": "ķ_Embed this scene in a website__________ū",
    "shareEmailTxt1": "ķ_Have a look at this Web Scene__________ū:",
    "shareEmailTxt2": "ķ_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ū.",
    "smallSize": "ķ_Small___ū",
    "mediumSize": "ķ_Medium___ū",
    "largeSize": "ķ_Large___ū",
    "customSize": "ķ_Custom___ū",
    "embed": "ķ_Embed this scene in a website__________ū",
    "more": "ķ_Embed Options_____ū",
    "changeShareSettings": "ķ_Change Share Settings_______ū",
    "shareLinkText": "ķ_Choose who can view Copy________ū",
    "linkOptions": "ķ_Link Options_____ū",
    "linkOptionsUrlParameters": "ķ_Select URL parameters included in the link______________ū",
    "currentMapExtent": "ķ_Current map extent______ū",
    "chooseCenterWithLevel": "ķ_Click the map to define the center of the map with scale level____________________ū",
    "chooseCenterWithScale": "ķ_Click the map to define the center of the map with map scale___________________ū",
    "findLocation": "ķ_Find the location or feature and zoom to it______________ū",
    "findLocation_inputPlaceholder": "ķ_Your place or feature_______ū",
    "queryFeature": "ķ_Query a feature and zoom to it__________ū",
    "addMarker": "ķ_Add a marker on the map________ū",
    "addMarker_titlePlaceholder": "ķ_Title of the marker pop-up_________ū",
    "addMarker_symbolURL": "ķ_Marker symbol URL______ū",
    "addMarker_label": "ķ_Marker label_____ū",
    "overwirteMobileLayout": "ķ_Overwrite default mobile layout__________ū",
    "language": "ķ_Set the app language_______ū",
    "auth": "ķ_Authenticate a user automatically___________ū",
    "linkPreview": "ķ_Link Preview_____ū",
    "useShortenLink": "ķ_Short Link____ū",
    "shareMapUrlExtent": "ķ_shareMapUrlExtent______ū"
  },
  "webSceneLoader": {
    "webglSupportTip": "ķ_3D web apps aren't supported in your browser_______________ū."
  }
});