define({
	addAChartSource: "ķ_Add a Chart Source_ū",
	sourceLabel: "ķ_Source label_ū",
	labelField: "ķ_Label field_ū",
	actions: "ķ_Actions_ū",
	hightLightColor: "ķ_Highlight color_ū",
	urlChartSource: "ķ_URL Chart Source_ū",
	layerChartSource: "ķ_Layer Chart Source_ū",
	searchUrl: "ķ_Search URL_ū",
	browse: "ķ_Browse_ū",
	layers: "ķ_Layers_ū",
	availableFields: "ķ_Available Fields_ū",
	charts: "ķ_Charts_ū",
	chartField: "ķ_Chart field_ū",
	description: "ķ_Description_ū",
	title: "ķ_Title_ū",
	type: "ķ_Type_ū",
	cancel: "ķ_Cancel_ū",
	addChartSource: "ķ_Add Chart Source_ū",
	updateChartSource: "ķ_Update Chart Source_ū",
	chartSources: "ķ_Chart Sources_ū",
	chartSource: "ķ_Chart Source_ū",
	general: "ķ_General_ū"
});