define({
  "common": {
    "apply": "Đ_Apply___ớ",
    "ok": "OK",
    "cancel": "Hủy",
    "yes": "Đ_Yes__ớ",
    "no": "Đ_No__ớ",
    "next": "Tiếp",
    "back": "Quay lại",
    "selected": "Đ_selected___ớ",
    "name": "Tên",
    "usage": "Đ_Usage___ớ",
    "settings": "Đ_Settings___ớ",
    "home": "Đ_Home__ớ",
    "link": "Đ_Link__ớ",
    "messages": "Đ_Messages___ớ",
    "outputs": "Đ_Outputs___ớ",
    "title": "Tiêu đề",
    "thumbnail": "Đ_Thumbnail____ớ",
    "url": "Đ_URL__ớ",
    "actions": "Các hành động",
    "layer": "Lớp",
    "action": "Đ_Action___ớ",
    "input": "Đ_Input___ớ",
    "output": "Đ_Output___ớ",
    "type": "Đ_Type__ớ",
    "required": "Đ_Required___ớ",
    "options": "Đ_Options___ớ",
    "label": "Nhãn",
    "tooltip": "Đ_Tooltip___ớ",
    "visible": "Đ_Visible___ớ",
    "symbol": "Đ_Symbol___ớ",
    "popup": "Đ_Popup___ớ",
    "upload": "Đ_Upload___ớ",
    "execute": "Đ_Execute___ớ",
    "help": "Đ_Help__ớ",
    "executing": "Đ_Executing____ớ",
    "clear": "Xóa",
    "error": "Đ_Error___ớ",
    "zoomTo": "Phóng tới",
    "attribute": "Đ_Attribute____ớ",
    "exports": "Đ_Export___ớ",
    "check": "Đ_Check___ớ",
    "save": "Đ_Save__ớ",
    "close": "Đ_Close___ớ",
    "deleteText": "Đ_Delete___ớ",
    "map": "Bản đồ",
    "scene": "Đ_Scene___ớ",
    "reset": "Đ_Reset___ớ",
    "icon": "Đ_Icon__ớ",
    "share": "Đ_Share___ớ"
  },
  "errorCode": "Mã",
  "errorMessage": "Thông báo",
  "errorDetail": "Chi tiết",
  "widgetPlaceholderTooltip": "Để thiết lập, đi tới Tiện ích và bấm vào trình giữ chỗ tương ứng",
  "fieldStatistics": {
    "statistics": "Đ_Statistics____ớ",
    "field": "Trường",
    "count": "Đ_Number of Values______ớ",
    "sum": "Đ_Sum of Values_____ớ",
    "min": "Đ_Minimum___ớ",
    "max": "Đ_Maximum___ớ",
    "ave": "Đ_Average___ớ",
    "stddev": "Đ_Standard Deviation______ớ"
  },
  "symbolChooser": {
    "preview": "Xem trước",
    "basic": "Cơ bản",
    "arrows": "Mũi tên",
    "business": "Kinh doanh",
    "cartographic": "Bản đồ",
    "nationalParkService": "Cục Công viên Quốc gia",
    "outdoorRecreation": "Giải trí Ngoài trời",
    "peoplePlaces": "Địa điểm Con người",
    "safetyHealth": "Sức khỏe An toàn",
    "shapes": "Các hình dạng",
    "transportation": "Giao thông Vận tải",
    "symbolSize": "Kích cỡ Ký hiệu",
    "color": "Màu sắc",
    "alpha": "Alpha",
    "outlineColor": "Màu Đường viền",
    "outlineWidth": "Độ rộng Đường viền",
    "style": "Kiểu",
    "width": "Chiều rộng",
    "text": "Văn bản",
    "fontColor": "Màu Phông chữ",
    "fontSize": "Cỡ Chữ",
    "transparency": "Độ trong suốt",
    "solid": "Đậm",
    "dash": "Gạch",
    "dot": "Chấm",
    "dashDot": "Chấm Gạch",
    "dashDotDot": "Gạch Chấm Chấm"
  },
  "transparency": {
    "opaque": "Độ mờ",
    "transparent": "Độ trong suốt"
  },
  "rendererChooser": {
    "domain": "Miền",
    "use": "Sử dụng",
    "singleSymbol": "Một Ký hiệu Đơn",
    "uniqueSymbol": "Ký hiệu theo Loại đối tượng",
    "color": "Màu sắc",
    "size": "Kích cỡ",
    "toShow": "Để Hiển thị",
    "colors": "Màu sắc",
    "classes": "Các lớp",
    "symbolSize": "Kích cỡ Ký hiệu",
    "addValue": "Thêm Giá trị",
    "setDefaultSymbol": "Thiết lập Ký hiệu Mặc định",
    "defaultSymbol": "Ký hiệu Mặc định",
    "selectedSymbol": "Ký hiệu Đã chọn",
    "value": "Giá trị",
    "label": "Đ_Label___ớ",
    "range": "Phạm vi"
  },
  "drawBox": {
    "point": "Điểm",
    "line": "Đường",
    "polyline": "Đa tuyến",
    "freehandPolyline": "Đa tuyến vẽ tự do",
    "triangle": "Hình tam giác",
    "extent": "Phạm vi",
    "circle": "Hình tròn",
    "ellipse": "Hình Elip",
    "polygon": "Vùng",
    "freehandPolygon": "Vùng vẽ bằng tay",
    "text": "Văn bản",
    "clear": "Đ_Clear___ớ"
  },
  "popupConfig": {
    "title": "Đ_Title___ớ",
    "add": "Thêm",
    "fields": "Trường",
    "noField": "Không có trường nào",
    "visibility": "Hiển thị",
    "name": "Đ_Name__ớ",
    "alias": "Bí danh",
    "actions": "Đ_Actions___ớ"
  },
  "includeButton": {
    "include": "Bao gồm"
  },
  "loadingShelter": {
    "loading": "Đang tải"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Không tìm thấy dịch vụ nào.",
    "unableConnectTo": "Không thể kết nối với",
    "invalidUrlTip": "URL bạn vừa nhập không hợp lệ hoặc không thể truy cập được."
  },
  "serviceBrowser": {
    "noGpFound": "Không tìm thấy dịch vụ địa xử lý nào.",
    "unableConnectTo": "Không thể kết nối với"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Không tìm thấy dịch vụ bản đồ hoặc dịch vụ đối tượng nào",
    "unableConnectTo": "Không thể kết nối với"
  },
  "basicServiceChooser": {
    "validate": "Xác minh",
    "example": "Ví dụ",
    "set": "Thiết lập"
  },
  "urlInput": {
    "invalidUrl": "Url không hợp lệ."
  },
  "urlComboBox": {
    "invalidUrl": "Url không hợp lệ."
  },
  "filterBuilder": {
    "addAnotherExpression": "Thêm biểu thức lọc",
    "addSet": "Thêm tập hợp biểu thức",
    "matchMsg": "Lấy các đối tượng trong lớp trùng khớp với ${any_or_all} các biểu thức sau",
    "matchMsgSet": "${any_or_all} của các biểu thức sau trong tập hợp này là đúng",
    "all": "Tất cả",
    "any": "Bất kỳ",
    "value": "Giá trị",
    "field": "Đ_Field___ớ",
    "unique": "Duy nhất",
    "none": "Không có",
    "and": "và",
    "valueTooltip": "Nhập vào giá trị",
    "fieldTooltip": "Chọn từ trường hiện có",
    "uniqueValueTooltip": "Lấy từ các giá trị duy nhất trong trường được chọn",
    "stringOperatorIs": "là",
    "stringOperatorIsNot": "không phải là",
    "stringOperatorStartsWith": "bắt đầu với",
    "stringOperatorEndsWith": "kết thúc với",
    "stringOperatorContains": "chứa",
    "stringOperatorDoesNotContain": "không chứa",
    "stringOperatorIsBlank": "trống",
    "stringOperatorIsNotBlank": "không trống",
    "dateOperatorIsOn": "vào ngày",
    "dateOperatorIsNotOn": "không vào ngày",
    "dateOperatorIsBefore": "trước",
    "dateOperatorIsAfter": "sau",
    "dateOperatorDays": "ngày",
    "dateOperatorWeeks": "tuần",
    "dateOperatorMonths": "tháng",
    "dateOperatorInTheLast": "trong ngày cuối",
    "dateOperatorNotInTheLast": "không phải cuối cùng",
    "dateOperatorIsBetween": "ở giữa",
    "dateOperatorIsNotBetween": "không ở giữa",
    "dateOperatorIsBlank": "trống",
    "dateOperatorIsNotBlank": "không trống",
    "numberOperatorIs": "là",
    "numberOperatorIsNot": "không phải là",
    "numberOperatorIsAtLeast": "tối thiểu",
    "numberOperatorIsLessThan": "ít hơn",
    "numberOperatorIsAtMost": "tối đa",
    "numberOperatorIsGreaterThan": "nhiều hơn",
    "numberOperatorIsBetween": "ở giữa",
    "numberOperatorIsNotBetween": "không ở giữa",
    "numberOperatorIsBlank": "trống",
    "numberOperatorIsNotBlank": "không trống",
    "string": "String",
    "number": "Số",
    "date": "Ngày",
    "askForValues": "Yêu cầu các giá trị",
    "prompt": "Lời nhắc",
    "hint": "Gợi ý",
    "error": {
      "invalidParams": "Tham số không hợp lệ.",
      "invalidUrl": "Url không hợp lệ.",
      "noFilterFields": "Lớp không có trường nào có thể dùng để lọc.",
      "invalidSQL": "Biểu thức SQL không hợp lệ.",
      "cantParseSQL": "Không thể phân tích biểu thức SQL."
    },
    "caseSensitive": "Phân biệt chữ hoa chữ thường",
    "notSupportCaseSensitiveTip": "Dịch vụ được lưu trữ không hỗ trợ truy vấn phân biệt chữ hoa chữ thường."
  },
  "featureLayerSource": {
    "layer": "Lớp",
    "browse": "Duyệt",
    "selectFromMap": "Chọn từ Bản đồ",
    "selectFromPortal": "Thêm từ Portal for ArcGIS",
    "addServiceUrl": "Thêm URL Dịch vụ",
    "inputLayerUrl": "URL Lớp Đầu vào",
    "selectLayer": "Chọn một lớp đối tượng từ bản đồ hiện tại.",
    "chooseItem": "Chọn một mục lớp đối tượng.",
    "setServiceUrl": "Nhập URL của dịch vụ đối tượng hoặc dịch vụ bản đồ.",
    "selectFromOnline": "Thêm từ ArcGIS Online",
    "chooseLayer": "Chọn một lớp đối tượng."
  },
  "queryableLayerSource": {
    "layer": "Đ_Layer___ớ",
    "browse": "Duyệt",
    "selectFromMap": "Chọn từ Bản đồ",
    "selectFromPortal": "Thêm từ Portal for ArcGIS",
    "addServiceUrl": "Thêm URL Dịch vụ",
    "inputLayerUrl": "URL Lớp Đầu vào",
    "selectLayer": "Chọn một lớp từ bản đồ hiện tại.",
    "chooseItem": "Chọn một mục.",
    "setServiceUrl": "Nhập URL của dịch vụ.",
    "selectFromOnline": "Thêm từ ArcGIS Online",
    "chooseLayer": "Chọn lớp."
  },
  "gpSource": {
    "selectFromPortal": "Thêm từ Portal for ArcGIS",
    "addServiceUrl": "Thêm URL Dịch vụ",
    "selectFromOnline": "Thêm từ ArcGIS Online",
    "setServiceUrl": "Nhập URL của dịch vụ địa xử lý.",
    "chooseItem": "Chọn một mục dịch vụ địa xử lý.",
    "chooseTask": "Chọn một tác vụ địa xử lý."
  },
  "itemSelector": {
    "map": "Đ_Map__ớ",
    "selectWebMap": "Chọn Bản đồ Web",
    "addMapFromOnlineOrPortal": "Tìm và thêm bản đồ web trong ứng dụng từ các tài nguyên công khai của ArcGIS Online hoặc nội dung riêng tư của bạn trong ArcGIS Online hoặc Portal.",
    "searchMapName": "Tìm kiếm theo tên bản đồ...",
    "searchNone": "Chúng tôi không thể tìm thấy nội dung bạn đang tìm kiếm. Vui lòng thử lại.",
    "groups": "Nhóm",
    "noneGroups": "Không có nhóm nào",
    "signInTip": "Lần đăng nhập của bạn đã hết hạn, vui lòng làm mới trình duyệt để đăng nhập lại vào cổng thông tin.",
    "signIn": "Đăng nhập",
    "publicMap": "Công khai",
    "myOrganization": "Tổ chức của tôi",
    "myGroup": "Nhóm của tôi",
    "myContent": "Nội dung của tôi",
    "count": "Đ_Count___ớ",
    "fromPortal": "từ Cổng thông tin",
    "fromOnline": "từ ArcGIS.com",
    "noneThumbnail": "Hình thu nhỏ không khả dụng",
    "owner": "chủ sở hữu",
    "signInTo": "Đăng nhập vào",
    "lastModified": "Chỉnh sửa lần cuối",
    "moreDetails": "Thêm chi tiết"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Dịch vụ không hỗ trợ truy vấn."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Không có lớp thích hợp nào trong bản đồ."
  },
  "layerInfosMenu": {
    "titleBasemap": "Bản đồ nền",
    "titleLayers": "Các lớp hoạt động",
    "labelLayer": "Tên lớp",
    "itemZoomTo": "Phóng tới",
    "itemTransparency": "Độ trong suốt",
    "itemTransparent": "Độ trong suốt",
    "itemOpaque": "Độ mờ",
    "itemMoveUp": "Di chuyển lên trên",
    "itemMoveDown": "Di chuyển xuống dưới",
    "itemDesc": "Mô tả",
    "itemDownload": "Tải xuống",
    "itemToAttributeTable": "Mở Bảng Thuộc tính"
  },
  "imageChooser": {
    "unsupportReaderAPI": "CẦN LÀM: Trình duyệt này không hỗ trợ API bộ đọc tệp",
    "readError": "Không thể đọc tệp.",
    "unknowError": "không thể hoàn thành hoạt động",
    "invalidType": "Loại tệp không hợp lệ.",
    "cropImage": "Đ_Crop Image____ớ",
    "exceed": "Kích cỡ tệp không được vượt quá 1024 KB",
    "enableFlash": "CẦN LÀM: vui lòng bật flash.",
    "cropWaining": "Vui lòng chọn ảnh có kích thước tối thiểu ${width} x ${height} pixel.",
    "toolTip": "Để có kết quả tốt nhất, hình ảnh phải rộng ${width} pixel và cao ${height} pixel. Các kích cỡ khác sẽ được điều chỉnh cho phù hợp. Các định dạng hình ảnh được chấp nhận là: PNG, GIF và JPEG."
  },
  "simpleTable": {
    "moveUp": "Di chuyển lên trên",
    "moveDown": "Di chuyển xuống dưới",
    "deleteRow": "Xóa",
    "edit": "Chỉnh sửa"
  },
  "urlParams": {
    "invalidToken": "Mã token không hợp lệ",
    "validateTokenError": "Mã token không hợp lệ hoặc lỗi Mạng"
  },
  "exportTo": {
    "exportTo": "Xuất",
    "toCSV": "Xuất ra tệp CSV",
    "toFeatureCollection": "Xuất ra Bộ sưu tập Đối tượng",
    "toGeoJSON": "Xuất ra GeoJSON"
  },
  "appState": {
    "title": "Đ_App State____ớ",
    "restoreMap": "Bấm vào để khôi phục khả năng hiển thị của phạm vi bản đồ và các lớp khi bạn rời đi."
  },
  "featureActions": {
    "ZoomTo": "Đ_Zoom to___ớ",
    "PanTo": "Đ_Pan to___ớ",
    "Flash": "Đ_Flash___ớ",
    "ShowPopup": "Đ_Show Pop-up____ớ",
    "CreateLayer": "Đ_Create Layer_____ớ",
    "ShowStatistics": "Đ_Statistics_____ớ...",
    "ClearSelection": "Đ_Clear Selection______ớ",
    "ExportToCSV": "Đ_Export to CSV file______ớ",
    "ExportToFeatureCollection": "Đ_Export to Feature Collection_________ớ",
    "ExportToGeoJSON": "Đ_Export to GeoJSON______ớ"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Đ_Related layer_____ớ",
    "selectedFeatures": "Đ_Selected features______ớ",
    "drawShapesTip": "Đ_Draw shapes to select features__________ớ",
    "pleaseDrawShapesTip": "Đ_Please draw shapes to select features____________ớ",
    "allFeaturesTip": "Đ_All features in the layer_________ớ",
    "selectFeaturesOrDrawShapesTip": "Đ_Please use selected features in this layer or draw shapes on map to limit features__________________________ớ."
  },
  "searchDistance": {
    "applySearchDistance": "Đ_Apply a search distance________ớ",
    "applySearchDistanceToFeatures": "Đ_Apply a search distance to selected features______________ớ"
  },
  "units": {
    "miles": "Đ_Miles___ớ",
    "kilometers": "Đ_Kilometers____ớ",
    "feet": "Đ_Feet__ớ",
    "meters": "Đ_Meters___ớ",
    "yards": "Đ_Yards___ớ",
    "nauticalMiles": "Đ_Nautical Miles_____ớ"
  },
  "featureSetChooser": {
    "select": "Đ_Select___ớ",
    "dragBox": "Đ_Drag__ớ",
    "dragMouse": "Đ_Darg the mouse_____ớ",
    "selectByRectangle": "Đ_Select By Rectangle_______ớ",
    "selectFeaturesTip": "Đ_Select features by dragging box around them on map________________ớ",
    "newSelectionTip": "Đ_Create a new selection________ớ",
    "addSelectionTip": "Đ_Add to the current selection_________ớ",
    "removeSelectionTip": "Đ_Remove from the current selection___________ớ",
    "selectFromCurrentSelectionTip": "Đ_Select from the current selection___________ớ",
    "unselectAllSelectionTip": "Đ_Unselect all currently selected features_____________ớ"
  },
  "widgetManager": {
    "createWidgetError": "Đ_Create widget error_______ớ",
    "createWidgetSettingPageError": "Đ_Create widget setting page error___________ớ",
    "loadWidgetResourceError": "Đ_Load widget resouce error_________ớ"
  },
  "shareOptions": {
    "shareMap": "Đ_Choose who can view this app_________ớ",
    "shareMapTips": "Đ_Your map is currentlt shared with these people_______________ớ",
    "everyone": "Đ_everyone___ớ",
    "theseGroups": "Đ_theseGroups____ớ"
  },
  "shareLink": {
    "email": "Đ_email___ớ",
    "shareEmail": "Đ_Email___ớ",
    "facebook": "Đ_facebook___ớ",
    "shareFacebook": "Đ_Facebook___ớ",
    "twitter": "Đ_twitter___ớ",
    "shareTwitter": "Đ_Twitter___ớ",
    "googlePlus": "Đ_googlePlus____ớ",
    "shareGooglePlus": "Đ_GooglePlus____ớ",
    "EmbedTips": "Đ_Embed this scene in a website__________ớ",
    "shareEmailTxt1": "Đ_Have a look at this Web Scene__________ớ:",
    "shareEmailTxt2": "Đ_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ớ.",
    "smallSize": "Đ_Small___ớ",
    "mediumSize": "Đ_Medium___ớ",
    "largeSize": "Đ_Large___ớ",
    "customSize": "Đ_Custom___ớ",
    "embed": "Đ_Embed this scene in a website__________ớ",
    "more": "Đ_Embed Options_____ớ",
    "changeShareSettings": "Đ_Change Share Settings_______ớ",
    "shareLinkText": "Đ_Choose who can view Copy________ớ",
    "linkOptions": "Đ_Link Options_____ớ",
    "linkOptionsUrlParameters": "Đ_Select URL parameters included in the link______________ớ",
    "currentMapExtent": "Đ_Current map extent______ớ",
    "chooseCenterWithLevel": "Đ_Click the map to define the center of the map with scale level____________________ớ",
    "chooseCenterWithScale": "Đ_Click the map to define the center of the map with map scale___________________ớ",
    "findLocation": "Đ_Find the location or feature and zoom to it______________ớ",
    "findLocation_inputPlaceholder": "Đ_Your place or feature_______ớ",
    "queryFeature": "Đ_Query a feature and zoom to it__________ớ",
    "addMarker": "Đ_Add a marker on the map________ớ",
    "addMarker_titlePlaceholder": "Đ_Title of the marker pop-up_________ớ",
    "addMarker_symbolURL": "Đ_Marker symbol URL______ớ",
    "addMarker_label": "Đ_Marker label_____ớ",
    "overwirteMobileLayout": "Đ_Overwrite default mobile layout__________ớ",
    "language": "Đ_Set the app language_______ớ",
    "auth": "Đ_Authenticate a user automatically___________ớ",
    "linkPreview": "Đ_Link Preview_____ớ",
    "useShortenLink": "Đ_Short Link____ớ",
    "shareMapUrlExtent": "Đ_shareMapUrlExtent______ớ"
  },
  "webSceneLoader": {
    "webglSupportTip": "Đ_3D web apps aren't supported in your browser_______________ớ."
  }
});