define({
  "common": {
    "apply": "Đ_Apply___ớ",
    "ok": "ΟΚ",
    "cancel": "Ακύρωση",
    "yes": "Đ_Yes__ớ",
    "no": "Đ_No__ớ",
    "next": "Επόμενο",
    "back": "Πίσω",
    "selected": "Đ_selected___ớ",
    "name": "Όνομα",
    "usage": "Đ_Usage___ớ",
    "settings": "Đ_Settings___ớ",
    "home": "Đ_Home__ớ",
    "link": "Đ_Link__ớ",
    "messages": "Đ_Messages___ớ",
    "outputs": "Đ_Outputs___ớ",
    "title": "Τίτλος",
    "thumbnail": "Đ_Thumbnail____ớ",
    "url": "Đ_URL__ớ",
    "actions": "Ενέργειες",
    "layer": "Θεματικό Επίπεδο",
    "action": "Đ_Action___ớ",
    "input": "Đ_Input___ớ",
    "output": "Đ_Output___ớ",
    "type": "Đ_Type__ớ",
    "required": "Đ_Required___ớ",
    "options": "Đ_Options___ớ",
    "label": "Ετικέτα",
    "tooltip": "Đ_Tooltip___ớ",
    "visible": "Đ_Visible___ớ",
    "symbol": "Đ_Symbol___ớ",
    "popup": "Đ_Popup___ớ",
    "upload": "Đ_Upload___ớ",
    "execute": "Đ_Execute___ớ",
    "help": "Đ_Help__ớ",
    "executing": "Đ_Executing____ớ",
    "clear": "Απαλοιφή",
    "error": "Đ_Error___ớ",
    "zoomTo": "Εστίαση",
    "attribute": "Đ_Attribute____ớ",
    "exports": "Đ_Export___ớ",
    "check": "Đ_Check___ớ",
    "save": "Đ_Save__ớ",
    "close": "Đ_Close___ớ",
    "deleteText": "Đ_Delete___ớ",
    "map": "Χάρτης",
    "scene": "Đ_Scene___ớ",
    "reset": "Đ_Reset___ớ",
    "icon": "Đ_Icon__ớ",
    "share": "Đ_Share___ớ"
  },
  "errorCode": "Κωδικός",
  "errorMessage": "Μήνυμα",
  "errorDetail": "Λεπτομέρεια",
  "widgetPlaceholderTooltip": "Για να το ρυθμίσετε, μεταβείτε στα Widget και κάντε κλικ στο αντίστοιχο σύμβολο",
  "fieldStatistics": {
    "statistics": "Đ_Statistics____ớ",
    "field": "Πεδίο",
    "count": "Đ_Number of Values______ớ",
    "sum": "Đ_Sum of Values_____ớ",
    "min": "Đ_Minimum___ớ",
    "max": "Đ_Maximum___ớ",
    "ave": "Đ_Average___ớ",
    "stddev": "Đ_Standard Deviation______ớ"
  },
  "symbolChooser": {
    "preview": "Προεπισκόπηση",
    "basic": "Βασικά",
    "arrows": "Βέλη",
    "business": "Επιχείρηση",
    "cartographic": "Χαρτογραφικά",
    "nationalParkService": "Εθνική Υπηρεσία Πάρκων",
    "outdoorRecreation": "Υπαίθριες δραστηριότητες αναψυχής",
    "peoplePlaces": "Άνθρωποι και μέρη",
    "safetyHealth": "Ασφάλεια - Υγεία",
    "shapes": "Σχήματα",
    "transportation": "Μεταφορές",
    "symbolSize": "Μέγεθος συμβόλου",
    "color": "Χρώμα",
    "alpha": "Άλφα",
    "outlineColor": "Χρώμα περιγράμματος",
    "outlineWidth": "Πλάτος περιγράμματος",
    "style": "Στυλ",
    "width": "Πλάτος",
    "text": "Κείμενο",
    "fontColor": "Χρώμα γραμματοσειράς",
    "fontSize": "Μέγεθος γραμματοσειράς",
    "transparency": "Διαφάνεια",
    "solid": "Συμπαγές",
    "dash": "Παύλα",
    "dot": "Τελεία",
    "dashDot": "Παύλα τελεία",
    "dashDotDot": "Παύλα τελεία τελεία"
  },
  "transparency": {
    "opaque": "Αδιαφανές",
    "transparent": "Διαφανές"
  },
  "rendererChooser": {
    "domain": "Τομέας",
    "use": "Χρήση",
    "singleSymbol": "Ένα μόνο σύμβολο",
    "uniqueSymbol": "Μοναδικά σύμβολα",
    "color": "Χρώμα",
    "size": "Μέγεθος",
    "toShow": "Για εμφάνιση",
    "colors": "Χρώματα",
    "classes": "Κλάσεις",
    "symbolSize": "Μέγεθος συμβόλου",
    "addValue": "Προσθήκη τιμής",
    "setDefaultSymbol": "Ορισμός προκαθορισμένου συμβόλου",
    "defaultSymbol": "Προκαθορισμένο σύμβολο",
    "selectedSymbol": "Επιλεγμένο σύμβολο",
    "value": "Τιμή",
    "label": "Đ_Label___ớ",
    "range": "Εύρος"
  },
  "drawBox": {
    "point": "Σημείο",
    "line": "Γραμμή",
    "polyline": "Γραμμή πολλαπλών τμημάτων",
    "freehandPolyline": "Γραμμή ελεύθερης σχεδίασης",
    "triangle": "Τρίγωνο",
    "extent": "Έκταση",
    "circle": "Κύκλος",
    "ellipse": "Έλλειψη",
    "polygon": "Πολύγωνο",
    "freehandPolygon": "Πολύγωνο ελεύθερης σχεδίασης",
    "text": "Κείμενο",
    "clear": "Đ_Clear___ớ"
  },
  "popupConfig": {
    "title": "Đ_Title___ớ",
    "add": "Προσθήκη",
    "fields": "Πεδία",
    "noField": "Χωρίς πεδίο",
    "visibility": "Ορατό",
    "name": "Đ_Name__ớ",
    "alias": "Ψευδώνυμο",
    "actions": "Đ_Actions___ớ"
  },
  "includeButton": {
    "include": "Συμπερίληψη"
  },
  "loadingShelter": {
    "loading": "Φόρτωση"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Δεν εντοπίστηκε υπηρεσία.",
    "unableConnectTo": "Δεν ήταν δυνατή η σύνδεση σε",
    "invalidUrlTip": "Το URL που εισαγάγατε δεν είναι έγκυρο ή δεν είναι προσβάσιμο."
  },
  "serviceBrowser": {
    "noGpFound": "Δεν εντοπίστηκε geoprocessing service.",
    "unableConnectTo": "Δεν ήταν δυνατή η σύνδεση σε"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Δεν εντοπίστηκε map service ή feature service",
    "unableConnectTo": "Δεν ήταν δυνατή η σύνδεση σε"
  },
  "basicServiceChooser": {
    "validate": "Επικύρωση",
    "example": "Παράδειγμα",
    "set": "Ορισμός"
  },
  "urlInput": {
    "invalidUrl": "Μη έγκυρο URL."
  },
  "urlComboBox": {
    "invalidUrl": "Μη έγκυρο URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Προσθήκη έκφρασης φίλτρου",
    "addSet": "Προσθήκη συνόλου εκφράσεων",
    "matchMsg": "Βρείτε τα στοιχρία του θεματικού επιπέδου που συμφωνούν με ${any_or_all} τις παρακάτω εκφράσεις",
    "matchMsgSet": "${any_or_all} από τις παρακάτω εκφράσεις σε αυτό το σύνολο έχουν τιμή true",
    "all": "Όλες",
    "any": "Κάποιες",
    "value": "Τιμή",
    "field": "Đ_Field___ớ",
    "unique": "Μοναδικό",
    "none": "Κανένα",
    "and": "και",
    "valueTooltip": "Εισαγωγή τιμής",
    "fieldTooltip": "Επιλογή από υπάρχον πεδίο",
    "uniqueValueTooltip": "Επιλογή από μοναδικές τιμές σε επιλεγμένο πεδίο",
    "stringOperatorIs": "είναι",
    "stringOperatorIsNot": "δεν είναι",
    "stringOperatorStartsWith": "ξεκινάει με",
    "stringOperatorEndsWith": "τελειώνει με",
    "stringOperatorContains": "περιέχει",
    "stringOperatorDoesNotContain": "δεν περιέχει",
    "stringOperatorIsBlank": "είναι κενό",
    "stringOperatorIsNotBlank": "δεν είναι κενό",
    "dateOperatorIsOn": "είναι στις",
    "dateOperatorIsNotOn": "δεν είναι στις",
    "dateOperatorIsBefore": "είναι πριν από",
    "dateOperatorIsAfter": "είναι μετά από",
    "dateOperatorDays": "ημέρες",
    "dateOperatorWeeks": "εβδομάδες",
    "dateOperatorMonths": "μήνες",
    "dateOperatorInTheLast": "τους τελευταίους/τις τελευταίες",
    "dateOperatorNotInTheLast": "όχι τους τελευταίους/τις τελευταίες",
    "dateOperatorIsBetween": "είναι μεταξύ",
    "dateOperatorIsNotBetween": "δεν είναι μεταξύ",
    "dateOperatorIsBlank": "είναι κενό",
    "dateOperatorIsNotBlank": "δεν είναι κενό",
    "numberOperatorIs": "είναι",
    "numberOperatorIsNot": "δεν είναι",
    "numberOperatorIsAtLeast": "είναι τουλάχιστον",
    "numberOperatorIsLessThan": "είναι λιγότερο από",
    "numberOperatorIsAtMost": "είναι το πολύ",
    "numberOperatorIsGreaterThan": "είναι μεγαλύτερο από",
    "numberOperatorIsBetween": "είναι μεταξύ",
    "numberOperatorIsNotBetween": "δεν είναι μεταξύ",
    "numberOperatorIsBlank": "είναι κενό",
    "numberOperatorIsNotBlank": "δεν είναι κενό",
    "string": "Συμβολοσειρά",
    "number": "Αριθμός",
    "date": "Ημερομηνία",
    "askForValues": "Εισαγωγή τιμών από το χρήστη",
    "prompt": "Κείμενο εμφάνισης",
    "hint": "Κείμενο υπόδειξης",
    "error": {
      "invalidParams": "Μη έγκυρες παράμετροι.",
      "invalidUrl": "Μη έγκυρο URL.",
      "noFilterFields": "Το θεματικό επίπεδο δεν διαθέτει πεδία που μπορούν να χρησιμοποιηθούν για φίλτρο.",
      "invalidSQL": "Μη έγκυρη έκφραση SQL.",
      "cantParseSQL": "Δεν είναι δυνατή η ανάλυση της έκφρασης SQL."
    },
    "caseSensitive": "Διάκριση πεζών-κεφαλαίων",
    "notSupportCaseSensitiveTip": "Οι hosted υπηρεσίες δεν υποστηρίζουν ερωτήματα με διάκριση πεζών-κεφαλαίων."
  },
  "featureLayerSource": {
    "layer": "Θεματικό επίπεδο",
    "browse": "Περιήγηση",
    "selectFromMap": "Επιλογή από το χάρτη",
    "selectFromPortal": "Προσθήκη από το Portal for ArcGIS",
    "addServiceUrl": "Προσθήκη Service URL",
    "inputLayerUrl": "URL θεματικού επιπέδου εισόδου",
    "selectLayer": "Επιλέξτε ένα feature layer από τον τρέχοντα χάρτη.",
    "chooseItem": "Επιλέξτε ένα αντικείμενο τύπου feature layer.",
    "setServiceUrl": "Καταχωρίστε το URL του feature service ή του map service.",
    "selectFromOnline": "Προσθήκη από το ArcGIS Online",
    "chooseLayer": "Επιλέξτε ένα feature layer."
  },
  "queryableLayerSource": {
    "layer": "Đ_Layer___ớ",
    "browse": "Αναζήτηση",
    "selectFromMap": "Επιλογή από το χάρτη",
    "selectFromPortal": "Προσθήκη από το Portal for ArcGIS",
    "addServiceUrl": "Προσθήκη Service URL",
    "inputLayerUrl": "URL θεματικού επιπέδου εισόδου",
    "selectLayer": "Επιλέξτε θεματικό επίπεδο από τον τρέχοντα χάρτη.",
    "chooseItem": "Διαλέξτε ένα αντικείμενο.",
    "setServiceUrl": "Καταχωρίστε το URL της υπηρεσίας.",
    "selectFromOnline": "Προσθήκη από το ArcGIS Online",
    "chooseLayer": "Διαλέξτε θεματικό επίπεδο."
  },
  "gpSource": {
    "selectFromPortal": "Προσθήκη από το Portal for ArcGIS",
    "addServiceUrl": "Προσθήκη URL υπηρεσίας",
    "selectFromOnline": "Προσθήκη από το ArcGIS Online",
    "setServiceUrl": "Καταχωρίστε το URL του geoprocessing service.",
    "chooseItem": "Επιλέξτε ένα αντικείμενο τύπου geoprocessing service.",
    "chooseTask": "Επιλέξτε μια εργασία γεωεπεξεργασίας."
  },
  "itemSelector": {
    "map": "Đ_Map__ớ",
    "selectWebMap": "Επιλογή Web χάρτη",
    "addMapFromOnlineOrPortal": "Εντοπίστε και προσθέστε έναν web χάρτη στην εφαρμογή από τους δημόσιους πόρους του ArcGIS Online ή από το ιδιωτικό σας περιεχόμενο στο ArcGIS Online ή το Portal.",
    "searchMapName": "Αναζήτηση ανά όνομα χάρτη...",
    "searchNone": "Δεν ήταν δυνατή η εύρεση του στοιχείου που αναζητήσατε. Προσπαθήστε ξανά.",
    "groups": "Ομάδες",
    "noneGroups": "Δεν υπάρχουν ομάδες",
    "signInTip": "Η περίοδος λειτουργίας έχει λήξει, ανανεώστε το πρόγραμμα περιήγησης για να συνδεθείτε ξανά στην πύλη σας.",
    "signIn": "Είσοδος",
    "publicMap": "Δημόσιο περιεχόμενο",
    "myOrganization": "Ο Οργανισμός μου",
    "myGroup": "Οι Ομάδες μου",
    "myContent": "Το Περιεχόμενό μου",
    "count": "Đ_Count___ớ",
    "fromPortal": "από το Portal",
    "fromOnline": "από το ArcGIS.com",
    "noneThumbnail": "Δεν υπάρχουν διαθέσιμες μικρογραφίες",
    "owner": "κάτοχος",
    "signInTo": "Είσοδος σε",
    "lastModified": "Τελευταία τροποποίηση",
    "moreDetails": "Περισσότερες λεπτομέρειες"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Η υπηρεσία δεν υποστηρίζει ερωτήματα."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Δεν υπάρχει κατάλληλο θεματικό επίπεδο, διαθέσιμο στο χάρτη."
  },
  "layerInfosMenu": {
    "titleBasemap": "Υπόβαθρα",
    "titleLayers": "Επιχειρησιακά επίπεδα",
    "labelLayer": "Όνομα θεματικού επιπέδου",
    "itemZoomTo": "Εστίαση",
    "itemTransparency": "Διαφάνεια",
    "itemTransparent": "Διαφανές",
    "itemOpaque": "Αδιαφανές",
    "itemMoveUp": "Μετακίνηση προς τα επάνω",
    "itemMoveDown": "Μετακίνηση προς τα κάτω",
    "itemDesc": "Περιγραφή",
    "itemDownload": "Λήψη",
    "itemToAttributeTable": "Άνοιγμα Πίνακα Περιγραφικών Γνωρισμάτων"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: Το πρόγραμμα περιήγησης δεν υποστηρίζει το API του προγράμματος ανάγνωσης αρχείων",
    "readError": "Απέτυχε η ανάγνωση του αρχείου.",
    "unknowError": "δεν είναι δυνατή η ολοκλήρωση ενεργειών",
    "invalidType": "Μη έγκυρος τύπος αρχείου.",
    "cropImage": "Đ_Crop Image____ớ",
    "exceed": "Το μέγεθος αρχείου δεν μπορεί να υπερβαίνει τα 1024 KB",
    "enableFlash": "TODO: ενεργοποιήστε το flash.",
    "cropWaining": "Διαλέξτε μια φωτογραφία με διαστάσεις τουλάχιστον ${πλάτος} x ${ύψος} pixel.",
    "toolTip": "Για το καλύτερο αποτέλεσμα, η εικόνα πρέπει να έχει πλάτος ${width} pixel και ύψος ${height} pixel. Τα άλλα μεγέθη θα προσαρμοστούν αναλόγως για σωστή εμφάνιση. Οι αποδεκτοι μορφότυποι εικόνας είναι οι εξής: PNG, GIF και JPEG."
  },
  "simpleTable": {
    "moveUp": "Μετακίνηση προς τα επάνω",
    "moveDown": "Μετακίνηση προς τα κάτω",
    "deleteRow": "Διαγραφή",
    "edit": "Επεξεργασία"
  },
  "urlParams": {
    "invalidToken": "Μη έγκυρο διακριτικό",
    "validateTokenError": "Το διακριτικό δεν είναι έγκυρο ή παρουσιάστηκε σφάλμα δικτύου"
  },
  "exportTo": {
    "exportTo": "Εξαγωγή",
    "toCSV": "Εξαγωγή σε αρχείο CSV",
    "toFeatureCollection": "Εξαγωγή σε Feature Collection",
    "toGeoJSON": "Εξαγωγή σε GeoJSON"
  },
  "appState": {
    "title": "Đ_App State____ớ",
    "restoreMap": "Κάντε κλικ για να επαναφέρετε την έκταση του χάρτη και την ορατότητα των θεματικών επιπέδων στο σημείο που σταματήσατε."
  },
  "featureActions": {
    "ZoomTo": "Đ_Zoom to___ớ",
    "PanTo": "Đ_Pan to___ớ",
    "Flash": "Đ_Flash___ớ",
    "ShowPopup": "Đ_Show Pop-up____ớ",
    "CreateLayer": "Đ_Create Layer_____ớ",
    "ShowStatistics": "Đ_Statistics_____ớ...",
    "ClearSelection": "Đ_Clear Selection______ớ",
    "ExportToCSV": "Đ_Export to CSV file______ớ",
    "ExportToFeatureCollection": "Đ_Export to Feature Collection_________ớ",
    "ExportToGeoJSON": "Đ_Export to GeoJSON______ớ"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Đ_Related layer_____ớ",
    "selectedFeatures": "Đ_Selected features______ớ",
    "drawShapesTip": "Đ_Draw shapes to select features__________ớ",
    "pleaseDrawShapesTip": "Đ_Please draw shapes to select features____________ớ",
    "allFeaturesTip": "Đ_All features in the layer_________ớ",
    "selectFeaturesOrDrawShapesTip": "Đ_Please use selected features in this layer or draw shapes on map to limit features__________________________ớ."
  },
  "searchDistance": {
    "applySearchDistance": "Đ_Apply a search distance________ớ",
    "applySearchDistanceToFeatures": "Đ_Apply a search distance to selected features______________ớ"
  },
  "units": {
    "miles": "Đ_Miles___ớ",
    "kilometers": "Đ_Kilometers____ớ",
    "feet": "Đ_Feet__ớ",
    "meters": "Đ_Meters___ớ",
    "yards": "Đ_Yards___ớ",
    "nauticalMiles": "Đ_Nautical Miles_____ớ"
  },
  "featureSetChooser": {
    "select": "Đ_Select___ớ",
    "dragBox": "Đ_Drag__ớ",
    "dragMouse": "Đ_Darg the mouse_____ớ",
    "selectByRectangle": "Đ_Select By Rectangle_______ớ",
    "selectFeaturesTip": "Đ_Select features by dragging box around them on map________________ớ",
    "newSelectionTip": "Đ_Create a new selection________ớ",
    "addSelectionTip": "Đ_Add to the current selection_________ớ",
    "removeSelectionTip": "Đ_Remove from the current selection___________ớ",
    "selectFromCurrentSelectionTip": "Đ_Select from the current selection___________ớ",
    "unselectAllSelectionTip": "Đ_Unselect all currently selected features_____________ớ"
  },
  "widgetManager": {
    "createWidgetError": "Đ_Create widget error_______ớ",
    "createWidgetSettingPageError": "Đ_Create widget setting page error___________ớ",
    "loadWidgetResourceError": "Đ_Load widget resouce error_________ớ"
  },
  "shareOptions": {
    "shareMap": "Đ_Choose who can view this app_________ớ",
    "shareMapTips": "Đ_Your map is currentlt shared with these people_______________ớ",
    "everyone": "Đ_everyone___ớ",
    "theseGroups": "Đ_theseGroups____ớ"
  },
  "shareLink": {
    "email": "Đ_email___ớ",
    "shareEmail": "Đ_Email___ớ",
    "facebook": "Đ_facebook___ớ",
    "shareFacebook": "Đ_Facebook___ớ",
    "twitter": "Đ_twitter___ớ",
    "shareTwitter": "Đ_Twitter___ớ",
    "googlePlus": "Đ_googlePlus____ớ",
    "shareGooglePlus": "Đ_GooglePlus____ớ",
    "EmbedTips": "Đ_Embed this scene in a website__________ớ",
    "shareEmailTxt1": "Đ_Have a look at this Web Scene__________ớ:",
    "shareEmailTxt2": "Đ_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ớ.",
    "smallSize": "Đ_Small___ớ",
    "mediumSize": "Đ_Medium___ớ",
    "largeSize": "Đ_Large___ớ",
    "customSize": "Đ_Custom___ớ",
    "embed": "Đ_Embed this scene in a website__________ớ",
    "more": "Đ_Embed Options_____ớ",
    "changeShareSettings": "Đ_Change Share Settings_______ớ",
    "shareLinkText": "Đ_Choose who can view Copy________ớ",
    "linkOptions": "Đ_Link Options_____ớ",
    "linkOptionsUrlParameters": "Đ_Select URL parameters included in the link______________ớ",
    "currentMapExtent": "Đ_Current map extent______ớ",
    "chooseCenterWithLevel": "Đ_Click the map to define the center of the map with scale level____________________ớ",
    "chooseCenterWithScale": "Đ_Click the map to define the center of the map with map scale___________________ớ",
    "findLocation": "Đ_Find the location or feature and zoom to it______________ớ",
    "findLocation_inputPlaceholder": "Đ_Your place or feature_______ớ",
    "queryFeature": "Đ_Query a feature and zoom to it__________ớ",
    "addMarker": "Đ_Add a marker on the map________ớ",
    "addMarker_titlePlaceholder": "Đ_Title of the marker pop-up_________ớ",
    "addMarker_symbolURL": "Đ_Marker symbol URL______ớ",
    "addMarker_label": "Đ_Marker label_____ớ",
    "overwirteMobileLayout": "Đ_Overwrite default mobile layout__________ớ",
    "language": "Đ_Set the app language_______ớ",
    "auth": "Đ_Authenticate a user automatically___________ớ",
    "linkPreview": "Đ_Link Preview_____ớ",
    "useShortenLink": "Đ_Short Link____ớ",
    "shareMapUrlExtent": "Đ_shareMapUrlExtent______ớ"
  },
  "webSceneLoader": {
    "webglSupportTip": "Đ_3D web apps aren't supported in your browser_______________ớ."
  }
});