define({
    root: ({
        configError: "Widget is not properly configured",
        flagHeading: "Add Flags",
        barrierHeading: "Add Barriers",
        traceButtonValue: "Run Trace",
        clearButtonValue: "Clear",
        resultPanelhading: "Results",
        GPExecutionFailed: "The trace could not be completed, please try again",
        skipThisAsset: "Skip This Asset",
        saveTolayerButtonValue: "Save To Layer",
        exportTolayerButtonValue: "Export To Layer",
        lblExportToCSV: "Export to CSV",
        lblSaveToLayer: "Save To Layer",
        backButtonValue: "Back",
        highlightOnMapTooltip: "Highlight on map",
        outageAreaValue: "Outage Area",
        lblOutageAreaStartDate: "Start Date",
        lblOutageAreaStartTime: "Start Time",
        lblOutageAreaEndDate: "Outage End Date",
        lblOutageAreaEndTime: "Outage End Time",
        lblOutageAreaType: "Outage Type",
        lblCustOutOfService: "Cust out of service",
        lblNoOfValves: "Number of valves",
        lblNumberOfHydrants: "Number of Hydrants",
        lblSaveButtonValue: "Save",
        valvesValue: "Valves",
        hydrantsValue: "Hydrants",
        customersValue: "Customers",
        typePlanned: "Planned",
        typeUnPlanned: "Unplanned",
        checkBoxValves: "Valves",
        checkBoxHydrants: "Hydrants",
        checkBoxCustomers: "Customers",
        btnSaveExportToLayer: "Save",
        outageTypePlanned: "Planned",
        outageTypeUnPlanned: "Unplanned",
        NoOf: "No. of ",
        summaryPanel: "Output Summary",
        skipLocaton: "Skip the location",
        outageAreaLabel: "Outage Area",
        saveToLayerSuccess: "Save To Layer is successfully completed",
        NoLayerForSaveToLayer: "No Layer selected",
        ExportToCSVtooltip: "Export To CSV",
        exportToCSVSuccess: "Export To CSV is successfully completed",
        exportToCSVFailure:"Unable to perform Export to csv operation",
        noLayerSelectedForExportToCSV:"No Layer is selected",
        saveToLayertoolTip: "Save To Layer",
        unableToSaveLayer:"Unable to Save some of the layers"
    })
});
