define({
	addAChartSource: "ł_Add a Chart Source_ą",
	sourceLabel: "ł_Source label_ą",
	labelField: "ł_Label field_ą",
	actions: "ł_Actions_ą",
	hightLightColor: "ł_Highlight color_ą",
	urlChartSource: "ł_URL Chart Source_ą",
	layerChartSource: "ł_Layer Chart Source_ą",
	searchUrl: "ł_Search URL_ą",
	browse: "ł_Browse_ą",
	layers: "ł_Layers_ą",
	availableFields: "ł_Available Fields_ą",
	charts: "ł_Charts_ą",
	chartField: "ł_Chart field_ą",
	description: "ł_Description_ą",
	title: "ł_Title_ą",
	type: "ł_Type_ą",
	cancel: "ł_Cancel_ą",
	addChartSource: "ł_Add Chart Source_ą",
	updateChartSource: "ł_Update Chart Source_ą",
	chartSources: "ł_Chart Sources_ą",
	chartSource: "ł_Chart Source_ą",
	general: "ł_General_ą"
});