define({
  "common": {
    "apply": "試_Apply___驗",
    "ok": "確定",
    "cancel": "取消",
    "yes": "試_Yes__驗",
    "no": "試_No__驗",
    "next": "下一步",
    "back": "上一步",
    "selected": "試_selected___驗",
    "name": "名稱",
    "usage": "試_Usage___驗",
    "settings": "試_Settings___驗",
    "home": "試_Home__驗",
    "link": "試_Link__驗",
    "messages": "試_Messages___驗",
    "outputs": "試_Outputs___驗",
    "title": "標題",
    "thumbnail": "試_Thumbnail____驗",
    "url": "試_URL__驗",
    "actions": "操作",
    "layer": "圖層",
    "action": "試_Action___驗",
    "input": "試_Input___驗",
    "output": "試_Output___驗",
    "type": "試_Type__驗",
    "required": "試_Required___驗",
    "options": "試_Options___驗",
    "label": "標籤",
    "tooltip": "試_Tooltip___驗",
    "visible": "試_Visible___驗",
    "symbol": "試_Symbol___驗",
    "popup": "試_Popup___驗",
    "upload": "試_Upload___驗",
    "execute": "試_Execute___驗",
    "help": "試_Help__驗",
    "executing": "試_Executing____驗",
    "clear": "清除",
    "error": "試_Error___驗",
    "zoomTo": "縮放至",
    "attribute": "試_Attribute____驗",
    "exports": "試_Export___驗",
    "check": "試_Check___驗",
    "save": "試_Save__驗",
    "close": "試_Close___驗",
    "deleteText": "試_Delete___驗",
    "map": "地圖",
    "scene": "試_Scene___驗",
    "reset": "試_Reset___驗",
    "icon": "試_Icon__驗",
    "share": "試_Share___驗"
  },
  "errorCode": "代碼",
  "errorMessage": "訊息",
  "errorDetail": "詳細資訊",
  "widgetPlaceholderTooltip": "要進行設置，請轉到 widget 並按一下相應占位符",
  "fieldStatistics": {
    "statistics": "試_Statistics____驗",
    "field": "欄位",
    "count": "試_Number of Values______驗",
    "sum": "試_Sum of Values_____驗",
    "min": "試_Minimum___驗",
    "max": "試_Maximum___驗",
    "ave": "試_Average___驗",
    "stddev": "試_Standard Deviation______驗"
  },
  "symbolChooser": {
    "preview": "預覽",
    "basic": "Basic",
    "arrows": "箭頭",
    "business": "商業",
    "cartographic": "製圖",
    "nationalParkService": "國家公園管理局",
    "outdoorRecreation": "戶外娛樂",
    "peoplePlaces": "人員位置",
    "safetyHealth": "安全健康",
    "shapes": "形狀",
    "transportation": "交通運輸",
    "symbolSize": "符號大小",
    "color": "顏色",
    "alpha": "Alpha",
    "outlineColor": "輪廓顏色",
    "outlineWidth": "輪廓寬度",
    "style": "樣式",
    "width": "寬度",
    "text": "文字",
    "fontColor": "字型顏色",
    "fontSize": "字型大小",
    "transparency": "透明度",
    "solid": "實線",
    "dash": "虛線",
    "dot": "點",
    "dashDot": "虛線",
    "dashDotDot": "虛線點點"
  },
  "transparency": {
    "opaque": "不透明",
    "transparent": "透明"
  },
  "rendererChooser": {
    "domain": "領域",
    "use": "使用",
    "singleSymbol": "單一符號",
    "uniqueSymbol": "唯一符號",
    "color": "顏色",
    "size": "大小",
    "toShow": "顯示",
    "colors": "顏色",
    "classes": "類別",
    "symbolSize": "符號大小",
    "addValue": "新增值",
    "setDefaultSymbol": "設定預設符號",
    "defaultSymbol": "預設符號",
    "selectedSymbol": "所選符號",
    "value": "值",
    "label": "試_Label___驗",
    "range": "範圍"
  },
  "drawBox": {
    "point": "點",
    "line": "線",
    "polyline": "折線",
    "freehandPolyline": "手繪折線",
    "triangle": "三角形",
    "extent": "範圍",
    "circle": "圓形",
    "ellipse": "橢圓",
    "polygon": "面",
    "freehandPolygon": "手繪面",
    "text": "文字",
    "clear": "試_Clear___驗"
  },
  "popupConfig": {
    "title": "試_Title___驗",
    "add": "新增",
    "fields": "欄位",
    "noField": "無欄位",
    "visibility": "可見",
    "name": "試_Name__驗",
    "alias": "別名",
    "actions": "試_Actions___驗"
  },
  "includeButton": {
    "include": "包含"
  },
  "loadingShelter": {
    "loading": "正在載入"
  },
  "basicServiceBrowser": {
    "noServicesFound": "找不到任何服務。",
    "unableConnectTo": "無法連接至",
    "invalidUrlTip": "您輸入的 URL 無效或不可存取。"
  },
  "serviceBrowser": {
    "noGpFound": "未找到任何地理處理服務。",
    "unableConnectTo": "無法連接至"
  },
  "layerServiceBrowser": {
    "noServicesFound": "未找到任何地圖服務或圖徵服務",
    "unableConnectTo": "無法連接至"
  },
  "basicServiceChooser": {
    "validate": "驗證",
    "example": "範例",
    "set": "設置"
  },
  "urlInput": {
    "invalidUrl": "URL 無效。"
  },
  "urlComboBox": {
    "invalidUrl": "URL 無效。"
  },
  "filterBuilder": {
    "addAnotherExpression": "新增篩選表達式",
    "addSet": "新增表達式集合",
    "matchMsg": "取得圖層中與以下 ${any_or_all} 表達式相符的圖徵",
    "matchMsgSet": "此集合中的以下 ${any_or_all} 表達式為 true",
    "all": "全部",
    "any": "任意",
    "value": "值",
    "field": "試_Field___驗",
    "unique": "唯一",
    "none": "無",
    "and": "與",
    "valueTooltip": "輸入值",
    "fieldTooltip": "從現有欄位中選擇",
    "uniqueValueTooltip": "從所選欄位的唯一值中選擇",
    "stringOperatorIs": "等於",
    "stringOperatorIsNot": "不等於",
    "stringOperatorStartsWith": "開頭是",
    "stringOperatorEndsWith": "結尾是",
    "stringOperatorContains": "包含",
    "stringOperatorDoesNotContain": "不包含",
    "stringOperatorIsBlank": "為空",
    "stringOperatorIsNotBlank": "不為空",
    "dateOperatorIsOn": "在",
    "dateOperatorIsNotOn": "不在",
    "dateOperatorIsBefore": "早於",
    "dateOperatorIsAfter": "晚於",
    "dateOperatorDays": "天",
    "dateOperatorWeeks": "週",
    "dateOperatorMonths": "月",
    "dateOperatorInTheLast": "最後",
    "dateOperatorNotInTheLast": "不是最後",
    "dateOperatorIsBetween": "介於",
    "dateOperatorIsNotBetween": "不介於",
    "dateOperatorIsBlank": "為空",
    "dateOperatorIsNotBlank": "不為空",
    "numberOperatorIs": "等於",
    "numberOperatorIsNot": "不等於",
    "numberOperatorIsAtLeast": "最小為",
    "numberOperatorIsLessThan": "小於",
    "numberOperatorIsAtMost": "最大為",
    "numberOperatorIsGreaterThan": "大於",
    "numberOperatorIsBetween": "介於",
    "numberOperatorIsNotBetween": "不介於",
    "numberOperatorIsBlank": "為空",
    "numberOperatorIsNotBlank": "不為空",
    "string": "字串",
    "number": "編號",
    "date": "日期",
    "askForValues": "請求值",
    "prompt": "提示",
    "hint": "提示",
    "error": {
      "invalidParams": "無效的參數。",
      "invalidUrl": "無效的 URL。",
      "noFilterFields": "圖層不包含可用於篩選的欄位。",
      "invalidSQL": "SQL 表達式無效。",
      "cantParseSQL": "無法解析 SQL 表達式。"
    },
    "caseSensitive": "區分大小寫",
    "notSupportCaseSensitiveTip": "託管的服務不支援區分大小寫的查詢。"
  },
  "featureLayerSource": {
    "layer": "圖層",
    "browse": "瀏覽",
    "selectFromMap": "從地圖中選擇",
    "selectFromPortal": "從 Portal for ArcGIS 新增",
    "addServiceUrl": "新增服務 URL",
    "inputLayerUrl": "輸入圖層 URL",
    "selectLayer": "從目前地圖中選擇圖徵圖層。",
    "chooseItem": "選擇圖徵圖層項目。",
    "setServiceUrl": "輸入圖徵服務 URL 或地圖服務。",
    "selectFromOnline": "從 ArcGIS Online 新增",
    "chooseLayer": "選擇圖徵圖層。"
  },
  "queryableLayerSource": {
    "layer": "試_Layer___驗",
    "browse": "瀏覽",
    "selectFromMap": "從地圖中選擇",
    "selectFromPortal": "從 Portal for ArcGIS 新增",
    "addServiceUrl": "新增服務 URL",
    "inputLayerUrl": "輸入圖層 URL",
    "selectLayer": "從目前地圖中選擇圖層。",
    "chooseItem": "選擇項目。",
    "setServiceUrl": "輸入服務的 URL。",
    "selectFromOnline": "從 ArcGIS Online 新增",
    "chooseLayer": "選擇圖層。"
  },
  "gpSource": {
    "selectFromPortal": "從 Portal for ArcGIS 新增",
    "addServiceUrl": "新增服務 URL",
    "selectFromOnline": "從 ArcGIS Online 新增",
    "setServiceUrl": "輸入地理處理服務的 URL。",
    "chooseItem": "選擇地理處理服務項目。",
    "chooseTask": "選擇地理處理任務。"
  },
  "itemSelector": {
    "map": "試_Map__驗",
    "selectWebMap": "選擇 Web 地圖",
    "addMapFromOnlineOrPortal": "從 ArcGIS Online 公用資源或 ArcGIS Online 或 Portal 私有內容中尋找，並新增應用程式中的 Web 地圖。",
    "searchMapName": "按地圖名稱搜尋...",
    "searchNone": "無法找到您正在尋找的內容。請重試。",
    "groups": "群組",
    "noneGroups": "無任何群組",
    "signInTip": "登入工作階段已逾時，請重新整理瀏覽器以重新登入入口網站。",
    "signIn": "登入",
    "publicMap": "公用",
    "myOrganization": "我的組織",
    "myGroup": "我的群組",
    "myContent": "我的內容",
    "count": "試_Count___驗",
    "fromPortal": "從入口網站",
    "fromOnline": "從 ArcGIS.com",
    "noneThumbnail": "縮圖無法使用",
    "owner": "擁有者",
    "signInTo": "登入到",
    "lastModified": "上次修改時間",
    "moreDetails": "更多詳細資訊"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "服務不支援查詢。"
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "地圖中不存在可用的相應圖層。"
  },
  "layerInfosMenu": {
    "titleBasemap": "底圖",
    "titleLayers": "操作圖層",
    "labelLayer": "圖層名稱",
    "itemZoomTo": "縮放至",
    "itemTransparency": "透明度",
    "itemTransparent": "透明",
    "itemOpaque": "不透明",
    "itemMoveUp": "上移",
    "itemMoveDown": "下移",
    "itemDesc": "描述",
    "itemDownload": "下載",
    "itemToAttributeTable": "打開屬性表"
  },
  "imageChooser": {
    "unsupportReaderAPI": "待辦：瀏覽器不支援 FileReader API",
    "readError": "讀取檔案失敗。",
    "unknowError": "無法完成操作",
    "invalidType": "無效的檔案類型。",
    "cropImage": "試_Crop Image____驗",
    "exceed": "檔案大小不得超過 1024 KB",
    "enableFlash": "待辦：請啟用閃爍。",
    "cropWaining": "請選擇至少擁有 ${width} x ${height} 像素的照片。",
    "toolTip": "為獲得最佳效果，圖片的寬度應為 ${width} 像素，高度應為 ${height} 像素。其他大小將調整為適應此大小。可接受的圖片格式包括: PNG、GIF 和 JPEG。"
  },
  "simpleTable": {
    "moveUp": "上移",
    "moveDown": "下移",
    "deleteRow": "刪除",
    "edit": "編輯"
  },
  "urlParams": {
    "invalidToken": "權杖無效",
    "validateTokenError": "權杖無效或網路錯誤"
  },
  "exportTo": {
    "exportTo": "匯出",
    "toCSV": "匯出到 CSV 檔案",
    "toFeatureCollection": "匯出至圖徵集合",
    "toGeoJSON": "匯出至 GeoJSON"
  },
  "appState": {
    "title": "試_App State____驗",
    "restoreMap": "按一下以還原離開時的地圖範圍和圖層可見度。"
  },
  "featureActions": {
    "ZoomTo": "試_Zoom to___驗",
    "PanTo": "試_Pan to___驗",
    "Flash": "試_Flash___驗",
    "ShowPopup": "試_Show Pop-up____驗",
    "CreateLayer": "試_Create Layer_____驗",
    "ShowStatistics": "試_Statistics_____驗...",
    "ClearSelection": "試_Clear Selection______驗",
    "ExportToCSV": "試_Export to CSV file______驗",
    "ExportToFeatureCollection": "試_Export to Feature Collection_________驗",
    "ExportToGeoJSON": "試_Export to GeoJSON______驗"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "試_Related layer_____驗",
    "selectedFeatures": "試_Selected features______驗",
    "drawShapesTip": "試_Draw shapes to select features__________驗",
    "pleaseDrawShapesTip": "試_Please draw shapes to select features____________驗",
    "allFeaturesTip": "試_All features in the layer_________驗",
    "selectFeaturesOrDrawShapesTip": "試_Please use selected features in this layer or draw shapes on map to limit features__________________________驗."
  },
  "searchDistance": {
    "applySearchDistance": "試_Apply a search distance________驗",
    "applySearchDistanceToFeatures": "試_Apply a search distance to selected features______________驗"
  },
  "units": {
    "miles": "試_Miles___驗",
    "kilometers": "試_Kilometers____驗",
    "feet": "試_Feet__驗",
    "meters": "試_Meters___驗",
    "yards": "試_Yards___驗",
    "nauticalMiles": "試_Nautical Miles_____驗"
  },
  "featureSetChooser": {
    "select": "試_Select___驗",
    "dragBox": "試_Drag__驗",
    "dragMouse": "試_Darg the mouse_____驗",
    "selectByRectangle": "試_Select By Rectangle_______驗",
    "selectFeaturesTip": "試_Select features by dragging box around them on map________________驗",
    "newSelectionTip": "試_Create a new selection________驗",
    "addSelectionTip": "試_Add to the current selection_________驗",
    "removeSelectionTip": "試_Remove from the current selection___________驗",
    "selectFromCurrentSelectionTip": "試_Select from the current selection___________驗",
    "unselectAllSelectionTip": "試_Unselect all currently selected features_____________驗"
  },
  "widgetManager": {
    "createWidgetError": "試_Create widget error_______驗",
    "createWidgetSettingPageError": "試_Create widget setting page error___________驗",
    "loadWidgetResourceError": "試_Load widget resouce error_________驗"
  },
  "shareOptions": {
    "shareMap": "試_Choose who can view this app_________驗",
    "shareMapTips": "試_Your map is currentlt shared with these people_______________驗",
    "everyone": "試_everyone___驗",
    "theseGroups": "試_theseGroups____驗"
  },
  "shareLink": {
    "email": "試_email___驗",
    "shareEmail": "試_Email___驗",
    "facebook": "試_facebook___驗",
    "shareFacebook": "試_Facebook___驗",
    "twitter": "試_twitter___驗",
    "shareTwitter": "試_Twitter___驗",
    "googlePlus": "試_googlePlus____驗",
    "shareGooglePlus": "試_GooglePlus____驗",
    "EmbedTips": "試_Embed this scene in a website__________驗",
    "shareEmailTxt1": "試_Have a look at this Web Scene__________驗:",
    "shareEmailTxt2": "試_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________驗.",
    "smallSize": "試_Small___驗",
    "mediumSize": "試_Medium___驗",
    "largeSize": "試_Large___驗",
    "customSize": "試_Custom___驗",
    "embed": "試_Embed this scene in a website__________驗",
    "more": "試_Embed Options_____驗",
    "changeShareSettings": "試_Change Share Settings_______驗",
    "shareLinkText": "試_Choose who can view Copy________驗",
    "linkOptions": "試_Link Options_____驗",
    "linkOptionsUrlParameters": "試_Select URL parameters included in the link______________驗",
    "currentMapExtent": "試_Current map extent______驗",
    "chooseCenterWithLevel": "試_Click the map to define the center of the map with scale level____________________驗",
    "chooseCenterWithScale": "試_Click the map to define the center of the map with map scale___________________驗",
    "findLocation": "試_Find the location or feature and zoom to it______________驗",
    "findLocation_inputPlaceholder": "試_Your place or feature_______驗",
    "queryFeature": "試_Query a feature and zoom to it__________驗",
    "addMarker": "試_Add a marker on the map________驗",
    "addMarker_titlePlaceholder": "試_Title of the marker pop-up_________驗",
    "addMarker_symbolURL": "試_Marker symbol URL______驗",
    "addMarker_label": "試_Marker label_____驗",
    "overwirteMobileLayout": "試_Overwrite default mobile layout__________驗",
    "language": "試_Set the app language_______驗",
    "auth": "試_Authenticate a user automatically___________驗",
    "linkPreview": "試_Link Preview_____驗",
    "useShortenLink": "試_Short Link____驗",
    "shareMapUrlExtent": "試_shareMapUrlExtent______驗"
  },
  "webSceneLoader": {
    "webglSupportTip": "試_3D web apps aren't supported in your browser_______________驗."
  }
});