define({
  "common": {
    "apply": "试_Apply___验",
    "ok": "确定",
    "cancel": "取消",
    "yes": "试_Yes__验",
    "no": "试_No__验",
    "next": "下一步",
    "back": "返回",
    "selected": "试_selected___验",
    "name": "名称",
    "usage": "试_Usage___验",
    "settings": "试_Settings___验",
    "home": "试_Home__验",
    "link": "试_Link__验",
    "messages": "试_Messages___验",
    "outputs": "试_Outputs___验",
    "title": "标题",
    "thumbnail": "试_Thumbnail____验",
    "url": "试_URL__验",
    "actions": "操作",
    "layer": "图层",
    "action": "试_Action___验",
    "input": "试_Input___验",
    "output": "试_Output___验",
    "type": "试_Type__验",
    "required": "试_Required___验",
    "options": "试_Options___验",
    "label": "标注",
    "tooltip": "试_Tooltip___验",
    "visible": "试_Visible___验",
    "symbol": "试_Symbol___验",
    "popup": "试_Popup___验",
    "upload": "试_Upload___验",
    "execute": "试_Execute___验",
    "help": "试_Help__验",
    "executing": "试_Executing____验",
    "clear": "清除",
    "error": "试_Error___验",
    "zoomTo": "缩放至",
    "attribute": "试_Attribute____验",
    "exports": "试_Export___验",
    "check": "试_Check___验",
    "save": "试_Save__验",
    "close": "试_Close___验",
    "deleteText": "试_Delete___验",
    "map": "地图",
    "scene": "试_Scene___验",
    "reset": "试_Reset___验",
    "icon": "试_Icon__验",
    "share": "试_Share___验"
  },
  "errorCode": "代码",
  "errorMessage": "消息",
  "errorDetail": "详细信息",
  "widgetPlaceholderTooltip": "要进行设置，请转到微件并单击相应占位控件",
  "fieldStatistics": {
    "statistics": "试_Statistics____验",
    "field": "字段",
    "count": "试_Number of Values______验",
    "sum": "试_Sum of Values_____验",
    "min": "试_Minimum___验",
    "max": "试_Maximum___验",
    "ave": "试_Average___验",
    "stddev": "试_Standard Deviation______验"
  },
  "symbolChooser": {
    "preview": "预览",
    "basic": "基本形状",
    "arrows": "箭头",
    "business": "商业",
    "cartographic": "制图",
    "nationalParkService": "国家公园管理局",
    "outdoorRecreation": "户外娱乐",
    "peoplePlaces": "人员位置",
    "safetyHealth": "安全健康",
    "shapes": "形状",
    "transportation": "交通运输",
    "symbolSize": "符号大小",
    "color": "颜色",
    "alpha": "透明度",
    "outlineColor": "轮廓颜色",
    "outlineWidth": "轮廓宽度",
    "style": "样式",
    "width": "宽度",
    "text": "文本",
    "fontColor": "字体颜色",
    "fontSize": "字号",
    "transparency": "透明度",
    "solid": "实线",
    "dash": "虚线",
    "dot": "点",
    "dashDot": "点划线",
    "dashDotDot": "双点划线"
  },
  "transparency": {
    "opaque": "不透明",
    "transparent": "透明"
  },
  "rendererChooser": {
    "domain": "属性域",
    "use": "使用",
    "singleSymbol": "单一符号",
    "uniqueSymbol": "唯一符号",
    "color": "颜色",
    "size": "大小",
    "toShow": "显示",
    "colors": "颜色",
    "classes": "类别",
    "symbolSize": "符号大小",
    "addValue": "添加值",
    "setDefaultSymbol": "设置默认符号",
    "defaultSymbol": "默认符号",
    "selectedSymbol": "所选符号",
    "value": "值",
    "label": "试_Label___验",
    "range": "范围"
  },
  "drawBox": {
    "point": "点",
    "line": "线",
    "polyline": "折线",
    "freehandPolyline": "手绘折线",
    "triangle": "三角形",
    "extent": "矩形",
    "circle": "圆形",
    "ellipse": "椭圆",
    "polygon": "面",
    "freehandPolygon": "手绘面",
    "text": "文本",
    "clear": "试_Clear___验"
  },
  "popupConfig": {
    "title": "试_Title___验",
    "add": "添加",
    "fields": "字段",
    "noField": "无字段",
    "visibility": "可见",
    "name": "试_Name__验",
    "alias": "别名",
    "actions": "试_Actions___验"
  },
  "includeButton": {
    "include": "包含"
  },
  "loadingShelter": {
    "loading": "正在加载"
  },
  "basicServiceBrowser": {
    "noServicesFound": "未找到任何服务。",
    "unableConnectTo": "无法连接至",
    "invalidUrlTip": "您输入的 URL 无效或不可访问。"
  },
  "serviceBrowser": {
    "noGpFound": "未找到任何地理处理服务。",
    "unableConnectTo": "无法连接至"
  },
  "layerServiceBrowser": {
    "noServicesFound": "未找到任何地图服务或要素服务",
    "unableConnectTo": "无法连接至"
  },
  "basicServiceChooser": {
    "validate": "验证",
    "example": "示例",
    "set": "集合"
  },
  "urlInput": {
    "invalidUrl": "URL 无效。"
  },
  "urlComboBox": {
    "invalidUrl": "URL 无效。"
  },
  "filterBuilder": {
    "addAnotherExpression": "添加过滤表达式",
    "addSet": "添加表达式集合",
    "matchMsg": "获取图层中与以下 ${any_or_all} 表达式相匹配的要素",
    "matchMsgSet": "此集合中的以下 ${any_or_all} 表达式为 true",
    "all": "全部",
    "any": "任一",
    "value": "值",
    "field": "试_Field___验",
    "unique": "唯一值",
    "none": "无",
    "and": "和",
    "valueTooltip": "输入值",
    "fieldTooltip": "从现有字段中选择",
    "uniqueValueTooltip": "从所选字段的唯一值中选择",
    "stringOperatorIs": "等于",
    "stringOperatorIsNot": "不等于",
    "stringOperatorStartsWith": "开头是",
    "stringOperatorEndsWith": "结尾是",
    "stringOperatorContains": "包含",
    "stringOperatorDoesNotContain": "不包含",
    "stringOperatorIsBlank": "为空",
    "stringOperatorIsNotBlank": "不为空",
    "dateOperatorIsOn": "在",
    "dateOperatorIsNotOn": "不在",
    "dateOperatorIsBefore": "早于",
    "dateOperatorIsAfter": "晚于",
    "dateOperatorDays": "天",
    "dateOperatorWeeks": "周",
    "dateOperatorMonths": "月",
    "dateOperatorInTheLast": "最后",
    "dateOperatorNotInTheLast": "不是最后",
    "dateOperatorIsBetween": "介于",
    "dateOperatorIsNotBetween": "不介于",
    "dateOperatorIsBlank": "为空",
    "dateOperatorIsNotBlank": "不为空",
    "numberOperatorIs": "等于",
    "numberOperatorIsNot": "不等于",
    "numberOperatorIsAtLeast": "最小为",
    "numberOperatorIsLessThan": "小于",
    "numberOperatorIsAtMost": "最大为",
    "numberOperatorIsGreaterThan": "大于",
    "numberOperatorIsBetween": "介于",
    "numberOperatorIsNotBetween": "不介于",
    "numberOperatorIsBlank": "为空",
    "numberOperatorIsNotBlank": "不为空",
    "string": "字符串型",
    "number": "数值",
    "date": "日期",
    "askForValues": "请求值",
    "prompt": "提示",
    "hint": "提示",
    "error": {
      "invalidParams": "参数无效。",
      "invalidUrl": "URL 无效。",
      "noFilterFields": "图层不包含可用于过滤的字段。",
      "invalidSQL": "SQL 表达式无效。",
      "cantParseSQL": "无法解析 SQL 表达式。"
    },
    "caseSensitive": "区分大小写",
    "notSupportCaseSensitiveTip": "托管的服务不支持区分大小写的查询。"
  },
  "featureLayerSource": {
    "layer": "图层",
    "browse": "浏览",
    "selectFromMap": "从地图中选择",
    "selectFromPortal": "从 Portal for ArcGIS 添加",
    "addServiceUrl": "添加服务 URL",
    "inputLayerUrl": "输入图层 URL",
    "selectLayer": "从当前地图中选择要素图层。",
    "chooseItem": "选择要素图层项目。",
    "setServiceUrl": "输入要素服务 URL 或地图服务。",
    "selectFromOnline": "从 ArcGIS Online 添加",
    "chooseLayer": "选择要素图层。"
  },
  "queryableLayerSource": {
    "layer": "试_Layer___验",
    "browse": "浏览",
    "selectFromMap": "从地图中选择",
    "selectFromPortal": "从 Portal for ArcGIS 添加",
    "addServiceUrl": "添加服务 URL",
    "inputLayerUrl": "输入图层 URL",
    "selectLayer": "从当前地图中选择图层。",
    "chooseItem": "选择项目。",
    "setServiceUrl": "输入服务的 URL。",
    "selectFromOnline": "从 ArcGIS Online 添加",
    "chooseLayer": "选择图层。"
  },
  "gpSource": {
    "selectFromPortal": "从 Portal for ArcGIS 添加",
    "addServiceUrl": "添加服务 URL",
    "selectFromOnline": "从 ArcGIS Online 添加",
    "setServiceUrl": "输入地理处理服务的 URL。",
    "chooseItem": "选择地理处理服务项目。",
    "chooseTask": "选择地理处理任务。"
  },
  "itemSelector": {
    "map": "试_Map__验",
    "selectWebMap": "选择 Web 地图",
    "addMapFromOnlineOrPortal": "从 ArcGIS Online 公共资源或 ArcGIS Online 或 Portal 私有内容中查找并添加应用程序中的 Web 地图。",
    "searchMapName": "按地图名称搜索...",
    "searchNone": "无法找到您正在查找的内容。请重试。",
    "groups": "群组",
    "noneGroups": "无任何群组",
    "signInTip": "登录会话已过期，请刷新浏览器以重新登录门户。",
    "signIn": "登录",
    "publicMap": "公共",
    "myOrganization": "我的组织",
    "myGroup": "我的组",
    "myContent": "我的内容",
    "count": "试_Count___验",
    "fromPortal": "从 Portal",
    "fromOnline": "从 ArcGIS.com",
    "noneThumbnail": "缩略图不可用",
    "owner": "所有者",
    "signInTo": "登录到",
    "lastModified": "上次修改时间",
    "moreDetails": "更多详细信息"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "服务不支持查询。"
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "地图中不存在可用的相应图层。"
  },
  "layerInfosMenu": {
    "titleBasemap": "底图",
    "titleLayers": "业务图层",
    "labelLayer": "图层名称",
    "itemZoomTo": "缩放至",
    "itemTransparency": "透明度",
    "itemTransparent": "透明",
    "itemOpaque": "不透明",
    "itemMoveUp": "上移",
    "itemMoveDown": "下移",
    "itemDesc": "描述",
    "itemDownload": "下载",
    "itemToAttributeTable": "打开属性表"
  },
  "imageChooser": {
    "unsupportReaderAPI": "注释: 浏览器不支持 FileReader API",
    "readError": "读取文件失败。",
    "unknowError": "无法完成操作",
    "invalidType": "无效的文件类型。",
    "cropImage": "试_Crop Image____验",
    "exceed": "文件大小不得超过 1024 KB",
    "enableFlash": "需执行的操作: 请启用闪烁。",
    "cropWaining": "请选择至少拥有 ${width} x ${height} 像素的照片。",
    "toolTip": "为获得最佳效果，图像的宽度应为 ${width} 像素，高度应为 ${height} 像素。其他大小将调整为适应此大小。可接受的图像格式包括: PNG、GIF 和 JPEG。"
  },
  "simpleTable": {
    "moveUp": "上移",
    "moveDown": "下移",
    "deleteRow": "删除",
    "edit": "编辑"
  },
  "urlParams": {
    "invalidToken": "无效令牌",
    "validateTokenError": "无效令牌或网络错误"
  },
  "exportTo": {
    "exportTo": "导出",
    "toCSV": "导出到 CSV 文件",
    "toFeatureCollection": "导出至要素集合",
    "toGeoJSON": "导出至 GeoJSON"
  },
  "appState": {
    "title": "试_App State____验",
    "restoreMap": "单击以恢复之前停止的地图范围和图层可见性。"
  },
  "featureActions": {
    "ZoomTo": "试_Zoom to___验",
    "PanTo": "试_Pan to___验",
    "Flash": "试_Flash___验",
    "ShowPopup": "试_Show Pop-up____验",
    "CreateLayer": "试_Create Layer_____验",
    "ShowStatistics": "试_Statistics_____验...",
    "ClearSelection": "试_Clear Selection______验",
    "ExportToCSV": "试_Export to CSV file______验",
    "ExportToFeatureCollection": "试_Export to Feature Collection_________验",
    "ExportToGeoJSON": "试_Export to GeoJSON______验"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "试_Related layer_____验",
    "selectedFeatures": "试_Selected features______验",
    "drawShapesTip": "试_Draw shapes to select features__________验",
    "pleaseDrawShapesTip": "试_Please draw shapes to select features____________验",
    "allFeaturesTip": "试_All features in the layer_________验",
    "selectFeaturesOrDrawShapesTip": "试_Please use selected features in this layer or draw shapes on map to limit features__________________________验."
  },
  "searchDistance": {
    "applySearchDistance": "试_Apply a search distance________验",
    "applySearchDistanceToFeatures": "试_Apply a search distance to selected features______________验"
  },
  "units": {
    "miles": "试_Miles___验",
    "kilometers": "试_Kilometers____验",
    "feet": "试_Feet__验",
    "meters": "试_Meters___验",
    "yards": "试_Yards___验",
    "nauticalMiles": "试_Nautical Miles_____验"
  },
  "featureSetChooser": {
    "select": "试_Select___验",
    "dragBox": "试_Drag__验",
    "dragMouse": "试_Darg the mouse_____验",
    "selectByRectangle": "试_Select By Rectangle_______验",
    "selectFeaturesTip": "试_Select features by dragging box around them on map________________验",
    "newSelectionTip": "试_Create a new selection________验",
    "addSelectionTip": "试_Add to the current selection_________验",
    "removeSelectionTip": "试_Remove from the current selection___________验",
    "selectFromCurrentSelectionTip": "试_Select from the current selection___________验",
    "unselectAllSelectionTip": "试_Unselect all currently selected features_____________验"
  },
  "widgetManager": {
    "createWidgetError": "试_Create widget error_______验",
    "createWidgetSettingPageError": "试_Create widget setting page error___________验",
    "loadWidgetResourceError": "试_Load widget resouce error_________验"
  },
  "shareOptions": {
    "shareMap": "试_Choose who can view this app_________验",
    "shareMapTips": "试_Your map is currentlt shared with these people_______________验",
    "everyone": "试_everyone___验",
    "theseGroups": "试_theseGroups____验"
  },
  "shareLink": {
    "email": "试_email___验",
    "shareEmail": "试_Email___验",
    "facebook": "试_facebook___验",
    "shareFacebook": "试_Facebook___验",
    "twitter": "试_twitter___验",
    "shareTwitter": "试_Twitter___验",
    "googlePlus": "试_googlePlus____验",
    "shareGooglePlus": "试_GooglePlus____验",
    "EmbedTips": "试_Embed this scene in a website__________验",
    "shareEmailTxt1": "试_Have a look at this Web Scene__________验:",
    "shareEmailTxt2": "试_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________验.",
    "smallSize": "试_Small___验",
    "mediumSize": "试_Medium___验",
    "largeSize": "试_Large___验",
    "customSize": "试_Custom___验",
    "embed": "试_Embed this scene in a website__________验",
    "more": "试_Embed Options_____验",
    "changeShareSettings": "试_Change Share Settings_______验",
    "shareLinkText": "试_Choose who can view Copy________验",
    "linkOptions": "试_Link Options_____验",
    "linkOptionsUrlParameters": "试_Select URL parameters included in the link______________验",
    "currentMapExtent": "试_Current map extent______验",
    "chooseCenterWithLevel": "试_Click the map to define the center of the map with scale level____________________验",
    "chooseCenterWithScale": "试_Click the map to define the center of the map with map scale___________________验",
    "findLocation": "试_Find the location or feature and zoom to it______________验",
    "findLocation_inputPlaceholder": "试_Your place or feature_______验",
    "queryFeature": "试_Query a feature and zoom to it__________验",
    "addMarker": "试_Add a marker on the map________验",
    "addMarker_titlePlaceholder": "试_Title of the marker pop-up_________验",
    "addMarker_symbolURL": "试_Marker symbol URL______验",
    "addMarker_label": "试_Marker label_____验",
    "overwirteMobileLayout": "试_Overwrite default mobile layout__________验",
    "language": "试_Set the app language_______验",
    "auth": "试_Authenticate a user automatically___________验",
    "linkPreview": "试_Link Preview_____验",
    "useShortenLink": "试_Short Link____验",
    "shareMapUrlExtent": "试_shareMapUrlExtent______验"
  },
  "webSceneLoader": {
    "webglSupportTip": "试_3D web apps aren't supported in your browser_______________验."
  }
});