define({
	addAChartSource: "Į_Add a Chart Source_š",
	sourceLabel: "Į_Source label_š",
	labelField: "Į_Label field_š",
	actions: "Į_Actions_š",
	hightLightColor: "Į_Highlight color_š",
	urlChartSource: "Į_URL Chart Source_š",
	layerChartSource: "Į_Layer Chart Source_š",
	searchUrl: "Į_Search URL_š",
	browse: "Į_Browse_š",
	layers: "Į_Layers_š",
	availableFields: "Į_Available Fields_š",
	charts: "Į_Charts_š",
	chartField: "Į_Chart field_š",
	description: "Į_Description_š",
	title: "Į_Title_š",
	type: "Į_Type_š",
	cancel: "Į_Cancel_š",
	addChartSource: "Į_Add Chart Source_š",
	updateChartSource: "Į_Update Chart Source_š",
	chartSources: "Į_Chart Sources_š",
	chartSource: "Į_Chart Source_š",
	general: "Į_General_š"
});