define({
  "_widgetLabel": "Attributtabell",
  "_featureAction_ShowRelatedRecords": "Å_Show Related Records_______ö",
  "_featureAction_ViewInTable": "Å_View in Attribute Table________ö",
  "ok": "OK",
  "cancel": "Avbryt",
  "unsupportQueryWarning": "Lagret måste ha stöd för frågeåtgärden för att visas i widgeten Attributtabell. Kontrollera att frågefunktionen i tjänsten är påslagen.",
  "exportMessage": "Exportera data till CSV-fil?",
  "exportFiles": "Exportera till CSV",
  "exportSelected": "Exportera markering till CSV",
  "exportAll": "Exportera allt till CSV",
  "options": "Alternativ",
  "zoomto": "Zooma till",
  "highlight": "Markera grafik",
  "selectAll": "Välj poster på alla sidor",
  "selectPage": "Välj poster på aktuell sida",
  "clearSelection": "Rensa val",
  "filter": "Filter",
  "setFilterTip": "Ange filtret korrekt.",
  "noFilterTip": "Om inget filteruttryck definierats visar denna frågeuppgift en lista med alla geoobjekt i den angivna datakällan.",
  "filterByExtent": "Filtrera efter kartutbredning",
  "showSelectedRecords": "Visa markerade poster",
  "showAllRecords": "Visa alla poster",
  "showRelatedRecords": "Visa relaterade poster",
  "noRelatedRecords": "Inga relaterade poster hittades",
  "refresh": "Uppdatera",
  "features": "geoobjekt",
  "selected": "valt",
  "transparent": "Transparent läge",
  "indicate": "Hitta val",
  "columns": "Visa/dölj kolumner",
  "selectionSymbol": "Markeringssymbol",
  "closeMessage": "Dölj tabell (expandera den igen från nederkanten)",
  "dataNotAvailable": "Data är inte tillgängliga!<br>Klicka på [Uppdatera] för att försöka igen.",
  "openTableTip": "Öppna attributtabell",
  "closeTableTip": "Dölj attributtabell",
  "sortAsc": "Å_Sort Ascending_____ö",
  "sortDes": "Å_Sort Descending______ö",
  "statistics": "Å_Statistics____ö"
});