define({
	addAChartSource: "Ж_Add a Chart Source_Я",
	sourceLabel: "Ж_Source label_Я",
	labelField: "Ж_Label field_Я",
	actions: "Ж_Actions_Я",
	hightLightColor: "Ж_Highlight color_Я",
	urlChartSource: "Ж_URL Chart Source_Я",
	layerChartSource: "Ж_Layer Chart Source_Я",
	searchUrl: "Ж_Search URL_Я",
	browse: "Ж_Browse_Я",
	layers: "Ж_Layers_Я",
	availableFields: "Ж_Available Fields_Я",
	charts: "Ж_Charts_Я",
	chartField: "Ж_Chart field_Я",
	description: "Ж_Description_Я",
	title: "Ж_Title_Я",
	type: "Ж_Type_Я",
	cancel: "Ж_Cancel_Я",
	addChartSource: "Ж_Add Chart Source_Я",
	updateChartSource: "Ж_Update Chart Source_Я",
	chartSources: "Ж_Chart Sources_Я",
	chartSource: "Ж_Chart Source_Я",
	general: "Ж_General_Я"
});