define({
  "common": {
    "apply": "Ж_Apply___Я",
    "ok": "OK",
    "cancel": "Отмена",
    "yes": "Ж_Yes__Я",
    "no": "Ж_No__Я",
    "next": "Далее",
    "back": "Назад",
    "selected": "Ж_selected___Я",
    "name": "Имя",
    "usage": "Ж_Usage___Я",
    "settings": "Ж_Settings___Я",
    "home": "Ж_Home__Я",
    "link": "Ж_Link__Я",
    "messages": "Ж_Messages___Я",
    "outputs": "Ж_Outputs___Я",
    "title": "Заголовок",
    "thumbnail": "Ж_Thumbnail____Я",
    "url": "Ж_URL__Я",
    "actions": "Действия",
    "layer": "Слой",
    "action": "Ж_Action___Я",
    "input": "Ж_Input___Я",
    "output": "Ж_Output___Я",
    "type": "Ж_Type__Я",
    "required": "Ж_Required___Я",
    "options": "Ж_Options___Я",
    "label": "Надпись",
    "tooltip": "Ж_Tooltip___Я",
    "visible": "Ж_Visible___Я",
    "symbol": "Ж_Symbol___Я",
    "popup": "Ж_Popup___Я",
    "upload": "Ж_Upload___Я",
    "execute": "Ж_Execute___Я",
    "help": "Ж_Help__Я",
    "executing": "Ж_Executing____Я",
    "clear": "Очистить",
    "error": "Ж_Error___Я",
    "zoomTo": "Приблизить к",
    "attribute": "Ж_Attribute____Я",
    "exports": "Ж_Export___Я",
    "check": "Ж_Check___Я",
    "save": "Ж_Save__Я",
    "close": "Ж_Close___Я",
    "deleteText": "Ж_Delete___Я",
    "map": "Карта",
    "scene": "Ж_Scene___Я",
    "reset": "Ж_Reset___Я",
    "icon": "Ж_Icon__Я",
    "share": "Ж_Share___Я"
  },
  "errorCode": "Код",
  "errorMessage": "Сообщение",
  "errorDetail": "Подробности",
  "widgetPlaceholderTooltip": "Чтобы настроить его, перейдите в Виджеты и щелкните соответствующий ограничитель",
  "fieldStatistics": {
    "statistics": "Ж_Statistics____Я",
    "field": "Поле",
    "count": "Ж_Number of Values______Я",
    "sum": "Ж_Sum of Values_____Я",
    "min": "Ж_Minimum___Я",
    "max": "Ж_Maximum___Я",
    "ave": "Ж_Average___Я",
    "stddev": "Ж_Standard Deviation______Я"
  },
  "symbolChooser": {
    "preview": "Просмотр",
    "basic": "Базовый",
    "arrows": "Стрелки",
    "business": "Бизнес",
    "cartographic": "Картография",
    "nationalParkService": "Служба национальных парков",
    "outdoorRecreation": "Отдых на свежем воздухе",
    "peoplePlaces": "Общественные места",
    "safetyHealth": "Безопасность, здоровье",
    "shapes": "Формы",
    "transportation": "Транспорт",
    "symbolSize": "Размер символа",
    "color": "Цвет",
    "alpha": "Альфа",
    "outlineColor": "Цвет контура",
    "outlineWidth": "Ширина контура",
    "style": "Стиль",
    "width": "Ширина",
    "text": "Текст",
    "fontColor": "Цвет шрифта",
    "fontSize": "Размер шрифта",
    "transparency": "Прозрачность",
    "solid": "Заливка",
    "dash": "Тире",
    "dot": "Точка",
    "dashDot": "Тире-точка",
    "dashDotDot": "Тире-точка-точка"
  },
  "transparency": {
    "opaque": "Непрозрачный",
    "transparent": "Прозрачный"
  },
  "rendererChooser": {
    "domain": "Домен",
    "use": "Использовать",
    "singleSymbol": "Единый символ",
    "uniqueSymbol": "Уникальные символы",
    "color": "Цвет",
    "size": "Размер",
    "toShow": "Отображать",
    "colors": "Цвета",
    "classes": "Классы",
    "symbolSize": "Размер символа",
    "addValue": "Добавить значение",
    "setDefaultSymbol": "Настроить символ по умолчанию",
    "defaultSymbol": "Символ по умолчанию",
    "selectedSymbol": "Выбранный символ",
    "value": "Значение",
    "label": "Ж_Label___Я",
    "range": "Диапазон"
  },
  "drawBox": {
    "point": "Точка",
    "line": "Линия",
    "polyline": "Линия",
    "freehandPolyline": "Линия произвольной формы",
    "triangle": "Треугольник",
    "extent": "Экстент",
    "circle": "Круг",
    "ellipse": "Эллипс",
    "polygon": "Полигон",
    "freehandPolygon": "Полигон произвольной формы",
    "text": "Текст",
    "clear": "Ж_Clear___Я"
  },
  "popupConfig": {
    "title": "Ж_Title___Я",
    "add": "Добавить",
    "fields": "Поля",
    "noField": "Нет поля",
    "visibility": "Видимый",
    "name": "Ж_Name__Я",
    "alias": "Псевдоним",
    "actions": "Ж_Actions___Я"
  },
  "includeButton": {
    "include": "Включить"
  },
  "loadingShelter": {
    "loading": "Загрузка"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Сервисы не были найдены.",
    "unableConnectTo": "Не удается подключиться к",
    "invalidUrlTip": "Введенный URL-адрес недопустим или недоступен."
  },
  "serviceBrowser": {
    "noGpFound": "Сервисы геообработки не найдены.",
    "unableConnectTo": "Не удается подключиться к"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Картографические сервисы или сервисы пространственных объектов не найдены",
    "unableConnectTo": "Не удается подключиться к"
  },
  "basicServiceChooser": {
    "validate": "Проверить",
    "example": "Пример",
    "set": "Задать"
  },
  "urlInput": {
    "invalidUrl": "Недопустимый URL-адрес."
  },
  "urlComboBox": {
    "invalidUrl": "Недопустимый URL-адрес."
  },
  "filterBuilder": {
    "addAnotherExpression": "Добавить выражение фильтра",
    "addSet": "Добавить набор выражений",
    "matchMsg": "Получить объекты слоя, которые соответствуют ${any_or_all} из следующих выражений",
    "matchMsgSet": "${any_or_all} из следующих выражений в этом наборе равно true",
    "all": "все",
    "any": "Любые",
    "value": "Значение",
    "field": "Ж_Field___Я",
    "unique": "Уникальное",
    "none": "Нет",
    "and": "и",
    "valueTooltip": "Введите значение",
    "fieldTooltip": "Выбрать из существующего поля",
    "uniqueValueTooltip": "Выбрать из уникальных значений в выбранном поле",
    "stringOperatorIs": "соответствует",
    "stringOperatorIsNot": "не соответствует",
    "stringOperatorStartsWith": "начинается с",
    "stringOperatorEndsWith": "заканчивается",
    "stringOperatorContains": "содержит",
    "stringOperatorDoesNotContain": "не содержит",
    "stringOperatorIsBlank": "является пустым",
    "stringOperatorIsNotBlank": "не является пустым",
    "dateOperatorIsOn": "соответствует",
    "dateOperatorIsNotOn": "не соответствует",
    "dateOperatorIsBefore": "перед",
    "dateOperatorIsAfter": "после",
    "dateOperatorDays": "дней",
    "dateOperatorWeeks": "недель",
    "dateOperatorMonths": "месяцев",
    "dateOperatorInTheLast": "в последние",
    "dateOperatorNotInTheLast": "не в последние",
    "dateOperatorIsBetween": "между",
    "dateOperatorIsNotBetween": "не между",
    "dateOperatorIsBlank": "является пустым",
    "dateOperatorIsNotBlank": "не является пустым",
    "numberOperatorIs": "соответствует",
    "numberOperatorIsNot": "не соответствует",
    "numberOperatorIsAtLeast": "больше или равно",
    "numberOperatorIsLessThan": "меньше чем",
    "numberOperatorIsAtMost": "меньше или равно",
    "numberOperatorIsGreaterThan": "больше чем",
    "numberOperatorIsBetween": "между",
    "numberOperatorIsNotBetween": "не между",
    "numberOperatorIsBlank": "является пустым",
    "numberOperatorIsNotBlank": "не является пустым",
    "string": "Строка",
    "number": "Число",
    "date": "Дата",
    "askForValues": "Запросить значения",
    "prompt": "Рекомендация",
    "hint": "Подсказка",
    "error": {
      "invalidParams": "Некорректные параметры.",
      "invalidUrl": "Недопустимый URL-адрес.",
      "noFilterFields": "Слой не имеет полей, которые могут использоваться для фильтрации.",
      "invalidSQL": "Некорректное sql выражение.",
      "cantParseSQL": "Не возможно разобрать sql выражение."
    },
    "caseSensitive": "Учитывать регистр",
    "notSupportCaseSensitiveTip": "Опубликованные сервисы не поддерживают запрос с чувствительностью к регистру."
  },
  "featureLayerSource": {
    "layer": "Слой",
    "browse": "Обзор",
    "selectFromMap": "Выбрать с карты",
    "selectFromPortal": "Добавить с Portal for ArcGIS",
    "addServiceUrl": "Добавить URL-адрес сервиса",
    "inputLayerUrl": "URL-адрес входного слоя",
    "selectLayer": "Выбрать слой объектов на текущей карте.",
    "chooseItem": "Выбрать элемент слоя объектов.",
    "setServiceUrl": "Введите URL-адрес сервиса объектов или картографического сервиса.",
    "selectFromOnline": "Добавить с ArcGIS Online",
    "chooseLayer": "Выберите векторный слой."
  },
  "queryableLayerSource": {
    "layer": "Ж_Layer___Я",
    "browse": "Обзор",
    "selectFromMap": "Выбрать с карты",
    "selectFromPortal": "Добавить с Portal for ArcGIS",
    "addServiceUrl": "Добавить URL-адрес сервиса",
    "inputLayerUrl": "URL-адрес входного слоя",
    "selectLayer": "Выбрать слой из текущей карты.",
    "chooseItem": "Выбрать элемент.",
    "setServiceUrl": "Ввести URL сервиса.",
    "selectFromOnline": "Добавить с ArcGIS Online",
    "chooseLayer": "Выбор слоя."
  },
  "gpSource": {
    "selectFromPortal": "Добавить с Portal for ArcGIS",
    "addServiceUrl": "Добавить URL сервиса",
    "selectFromOnline": "Добавить с ArcGIS Online",
    "setServiceUrl": "Введите URL-адрес сервиса геообработки.",
    "chooseItem": "Выберите элемент сервиса геообработки.",
    "chooseTask": "Выберите задачу геообработки."
  },
  "itemSelector": {
    "map": "Ж_Map__Я",
    "selectWebMap": "Выбрать веб-карту",
    "addMapFromOnlineOrPortal": "Найти и добавить в приложение веб-карты из открытых ресурсов ArcGIS Online или собственных частных ресурсов ArcGIS Online или Portal.",
    "searchMapName": "Поиск по названию карты...",
    "searchNone": "Мы не смогли найти то, что вы искали. Пожалуйста, попробуйте снова.",
    "groups": "Группы",
    "noneGroups": "Нет групп",
    "signInTip": "Ваш сеанс работы под данной учетной записью истек, обновите свой браузер, чтобы войти в портал снова.",
    "signIn": "Войти",
    "publicMap": "Для всех",
    "myOrganization": "Моя организация",
    "myGroup": "Мои группы",
    "myContent": "Мои ресурсы",
    "count": "Ж_Count___Я",
    "fromPortal": "из Portal",
    "fromOnline": "из ArcGIS.com",
    "noneThumbnail": "Образец недоступен",
    "owner": "владелец",
    "signInTo": "Войти в",
    "lastModified": "Последние изменения",
    "moreDetails": "Подробнее"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Сервис не поддерживает запросы."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "На карте нет доступного подходящего слоя."
  },
  "layerInfosMenu": {
    "titleBasemap": "Базовые карты",
    "titleLayers": "Рабочие слои",
    "labelLayer": "Имя слоя",
    "itemZoomTo": "Приблизить к",
    "itemTransparency": "Прозрачность",
    "itemTransparent": "Прозрачный",
    "itemOpaque": "Непрозрачный",
    "itemMoveUp": "Выше",
    "itemMoveDown": "Ниже",
    "itemDesc": "Описание",
    "itemDownload": "Загрузить",
    "itemToAttributeTable": "Открыть таблицу атрибутов"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: Браузер не поддерживает API чтения файлов",
    "readError": "Не удалось считать файл.",
    "unknowError": "невозможно завершить операции",
    "invalidType": "Недопустимый тип файла.",
    "cropImage": "Ж_Crop Image____Я",
    "exceed": "Размер файла не может превышать 1024 КБ",
    "enableFlash": "TODO: включите флеш.",
    "cropWaining": "Выберите фото размером как минимум ${width} x ${height} пикселов.",
    "toolTip": "Для получения наилучших результатов, изображение должно быть ${width} пикселов шириной и ${height} пикселов высотой. Изображения других размеров будут настроены. Допустимые форматы изображений: PNG, GIF и JPEG."
  },
  "simpleTable": {
    "moveUp": "Выше",
    "moveDown": "Ниже",
    "deleteRow": "Удалить",
    "edit": "Редактировать"
  },
  "urlParams": {
    "invalidToken": "Неверный токен",
    "validateTokenError": "Недопустимый токен или ошибка сети"
  },
  "exportTo": {
    "exportTo": "Экспорт",
    "toCSV": "Экспорт в файл CSV",
    "toFeatureCollection": "Экспорт в Коллекцию объектов",
    "toGeoJSON": "Экспорт в GeoJSON"
  },
  "appState": {
    "title": "Ж_App State____Я",
    "restoreMap": "Щелкните, чтобы сохранить заново экстент карты и видимость слоев в том виде, в котором вы их оставляете."
  },
  "featureActions": {
    "ZoomTo": "Ж_Zoom to___Я",
    "PanTo": "Ж_Pan to___Я",
    "Flash": "Ж_Flash___Я",
    "ShowPopup": "Ж_Show Pop-up____Я",
    "CreateLayer": "Ж_Create Layer_____Я",
    "ShowStatistics": "Ж_Statistics_____Я...",
    "ClearSelection": "Ж_Clear Selection______Я",
    "ExportToCSV": "Ж_Export to CSV file______Я",
    "ExportToFeatureCollection": "Ж_Export to Feature Collection_________Я",
    "ExportToGeoJSON": "Ж_Export to GeoJSON______Я"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Ж_Related layer_____Я",
    "selectedFeatures": "Ж_Selected features______Я",
    "drawShapesTip": "Ж_Draw shapes to select features__________Я",
    "pleaseDrawShapesTip": "Ж_Please draw shapes to select features____________Я",
    "allFeaturesTip": "Ж_All features in the layer_________Я",
    "selectFeaturesOrDrawShapesTip": "Ж_Please use selected features in this layer or draw shapes on map to limit features__________________________Я."
  },
  "searchDistance": {
    "applySearchDistance": "Ж_Apply a search distance________Я",
    "applySearchDistanceToFeatures": "Ж_Apply a search distance to selected features______________Я"
  },
  "units": {
    "miles": "Ж_Miles___Я",
    "kilometers": "Ж_Kilometers____Я",
    "feet": "Ж_Feet__Я",
    "meters": "Ж_Meters___Я",
    "yards": "Ж_Yards___Я",
    "nauticalMiles": "Ж_Nautical Miles_____Я"
  },
  "featureSetChooser": {
    "select": "Ж_Select___Я",
    "dragBox": "Ж_Drag__Я",
    "dragMouse": "Ж_Darg the mouse_____Я",
    "selectByRectangle": "Ж_Select By Rectangle_______Я",
    "selectFeaturesTip": "Ж_Select features by dragging box around them on map________________Я",
    "newSelectionTip": "Ж_Create a new selection________Я",
    "addSelectionTip": "Ж_Add to the current selection_________Я",
    "removeSelectionTip": "Ж_Remove from the current selection___________Я",
    "selectFromCurrentSelectionTip": "Ж_Select from the current selection___________Я",
    "unselectAllSelectionTip": "Ж_Unselect all currently selected features_____________Я"
  },
  "widgetManager": {
    "createWidgetError": "Ж_Create widget error_______Я",
    "createWidgetSettingPageError": "Ж_Create widget setting page error___________Я",
    "loadWidgetResourceError": "Ж_Load widget resouce error_________Я"
  },
  "shareOptions": {
    "shareMap": "Ж_Choose who can view this app_________Я",
    "shareMapTips": "Ж_Your map is currentlt shared with these people_______________Я",
    "everyone": "Ж_everyone___Я",
    "theseGroups": "Ж_theseGroups____Я"
  },
  "shareLink": {
    "email": "Ж_email___Я",
    "shareEmail": "Ж_Email___Я",
    "facebook": "Ж_facebook___Я",
    "shareFacebook": "Ж_Facebook___Я",
    "twitter": "Ж_twitter___Я",
    "shareTwitter": "Ж_Twitter___Я",
    "googlePlus": "Ж_googlePlus____Я",
    "shareGooglePlus": "Ж_GooglePlus____Я",
    "EmbedTips": "Ж_Embed this scene in a website__________Я",
    "shareEmailTxt1": "Ж_Have a look at this Web Scene__________Я:",
    "shareEmailTxt2": "Ж_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________Я.",
    "smallSize": "Ж_Small___Я",
    "mediumSize": "Ж_Medium___Я",
    "largeSize": "Ж_Large___Я",
    "customSize": "Ж_Custom___Я",
    "embed": "Ж_Embed this scene in a website__________Я",
    "more": "Ж_Embed Options_____Я",
    "changeShareSettings": "Ж_Change Share Settings_______Я",
    "shareLinkText": "Ж_Choose who can view Copy________Я",
    "linkOptions": "Ж_Link Options_____Я",
    "linkOptionsUrlParameters": "Ж_Select URL parameters included in the link______________Я",
    "currentMapExtent": "Ж_Current map extent______Я",
    "chooseCenterWithLevel": "Ж_Click the map to define the center of the map with scale level____________________Я",
    "chooseCenterWithScale": "Ж_Click the map to define the center of the map with map scale___________________Я",
    "findLocation": "Ж_Find the location or feature and zoom to it______________Я",
    "findLocation_inputPlaceholder": "Ж_Your place or feature_______Я",
    "queryFeature": "Ж_Query a feature and zoom to it__________Я",
    "addMarker": "Ж_Add a marker on the map________Я",
    "addMarker_titlePlaceholder": "Ж_Title of the marker pop-up_________Я",
    "addMarker_symbolURL": "Ж_Marker symbol URL______Я",
    "addMarker_label": "Ж_Marker label_____Я",
    "overwirteMobileLayout": "Ж_Overwrite default mobile layout__________Я",
    "language": "Ж_Set the app language_______Я",
    "auth": "Ж_Authenticate a user automatically___________Я",
    "linkPreview": "Ж_Link Preview_____Я",
    "useShortenLink": "Ж_Short Link____Я",
    "shareMapUrlExtent": "Ж_shareMapUrlExtent______Я"
  },
  "webSceneLoader": {
    "webglSupportTip": "Ж_3D web apps aren't supported in your browser_______________Я."
  }
});