define({
  "common": {
    "apply": "ł_Apply___ą",
    "ok": "OK",
    "cancel": "Anuluj",
    "yes": "ł_Yes__ą",
    "no": "ł_No__ą",
    "next": "Dalej",
    "back": "Wstecz",
    "selected": "ł_selected___ą",
    "name": "Nazwa",
    "usage": "ł_Usage___ą",
    "settings": "ł_Settings___ą",
    "home": "ł_Home__ą",
    "link": "ł_Link__ą",
    "messages": "ł_Messages___ą",
    "outputs": "ł_Outputs___ą",
    "title": "Tytuł",
    "thumbnail": "ł_Thumbnail____ą",
    "url": "ł_URL__ą",
    "actions": "Operacje",
    "layer": "Warstwa",
    "action": "ł_Action___ą",
    "input": "ł_Input___ą",
    "output": "ł_Output___ą",
    "type": "ł_Type__ą",
    "required": "ł_Required___ą",
    "options": "ł_Options___ą",
    "label": "Etykieta",
    "tooltip": "ł_Tooltip___ą",
    "visible": "ł_Visible___ą",
    "symbol": "ł_Symbol___ą",
    "popup": "ł_Popup___ą",
    "upload": "ł_Upload___ą",
    "execute": "ł_Execute___ą",
    "help": "ł_Help__ą",
    "executing": "ł_Executing____ą",
    "clear": "Wyczyść",
    "error": "ł_Error___ą",
    "zoomTo": "Powiększ do",
    "attribute": "ł_Attribute____ą",
    "exports": "ł_Export___ą",
    "check": "ł_Check___ą",
    "save": "ł_Save__ą",
    "close": "ł_Close___ą",
    "deleteText": "ł_Delete___ą",
    "map": "Mapa",
    "scene": "ł_Scene___ą",
    "reset": "ł_Reset___ą",
    "icon": "ł_Icon__ą",
    "share": "ł_Share___ą"
  },
  "errorCode": "Kod",
  "errorMessage": "Komunikat",
  "errorDetail": "Szczegóły",
  "widgetPlaceholderTooltip": "Aby skonfigurować ten element, przejdź do ekranu Widżety i kliknij odpowiedni symbol zastępczy",
  "fieldStatistics": {
    "statistics": "ł_Statistics____ą",
    "field": "Pole",
    "count": "ł_Number of Values______ą",
    "sum": "ł_Sum of Values_____ą",
    "min": "ł_Minimum___ą",
    "max": "ł_Maximum___ą",
    "ave": "ł_Average___ą",
    "stddev": "ł_Standard Deviation______ą"
  },
  "symbolChooser": {
    "preview": "Podgląd",
    "basic": "Podstawowy",
    "arrows": "Strzałki",
    "business": "Biznes",
    "cartographic": "Kartograficzny",
    "nationalParkService": "Służba Parków Narodowych",
    "outdoorRecreation": "Rekreacja na świeżym powietrzu",
    "peoplePlaces": "Ludzie i miejsca",
    "safetyHealth": "Higiena i bezpieczeństwo",
    "shapes": "Kształty",
    "transportation": "Transport",
    "symbolSize": "Rozmiar symbolu",
    "color": "Kolor",
    "alpha": "Alfa",
    "outlineColor": "Kolor obrysu",
    "outlineWidth": "Szerokość obrysu",
    "style": "Styl",
    "width": "Szerokość",
    "text": "Tekst",
    "fontColor": "Kolor czcionki",
    "fontSize": "Rozmiar czcionki",
    "transparency": "Przezroczystość",
    "solid": "Pełna",
    "dash": "Przerywana",
    "dot": "Kropka",
    "dashDot": "Kreska-kropka",
    "dashDotDot": "Kreska-kropka-kropka"
  },
  "transparency": {
    "opaque": "Nieprzezroczysty",
    "transparent": "Przezroczysty"
  },
  "rendererChooser": {
    "domain": "Domena",
    "use": "Użyj",
    "singleSymbol": "Pojedynczy symbol",
    "uniqueSymbol": "Symbole unikalne",
    "color": "Kolor",
    "size": "Rozmiar",
    "toShow": "Do wyświetlenia",
    "colors": "Kolory",
    "classes": "Klasy",
    "symbolSize": "Rozmiar symbolu",
    "addValue": "Dodaj wartość",
    "setDefaultSymbol": "Ustaw symbol domyślny",
    "defaultSymbol": "Domyślny symbol",
    "selectedSymbol": "Wybrany symbol",
    "value": "Wartość",
    "label": "ł_Label___ą",
    "range": "Zakres"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linia",
    "polyline": "Polilinia",
    "freehandPolyline": "Dowolna polilinia",
    "triangle": "Trójkąt",
    "extent": "Zasięg",
    "circle": "Koło",
    "ellipse": "Elipsa",
    "polygon": "Poligon",
    "freehandPolygon": "Dowolny poligon",
    "text": "Tekst",
    "clear": "ł_Clear___ą"
  },
  "popupConfig": {
    "title": "ł_Title___ą",
    "add": "Dodaj",
    "fields": "Pola",
    "noField": "Brak pola",
    "visibility": "Widoczne",
    "name": "ł_Name__ą",
    "alias": "Alias",
    "actions": "ł_Actions___ą"
  },
  "includeButton": {
    "include": "Dodaj"
  },
  "loadingShelter": {
    "loading": "Wczytywanie"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nie odnaleziono żadnej usługi.",
    "unableConnectTo": "Nie można nawiązać połączenia z",
    "invalidUrlTip": "Wprowadzony adres URL jest nieprawidłowy lub nieosiągalny."
  },
  "serviceBrowser": {
    "noGpFound": "Nie odnaleziono żadnej usługi geoprzetwarzania.",
    "unableConnectTo": "Nie można nawiązać połączenia z"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nie znaleziono żadnych usług mapowych ani obiektowych.",
    "unableConnectTo": "Nie można nawiązać połączenia z"
  },
  "basicServiceChooser": {
    "validate": "Sprawdź poprawność",
    "example": "Przykład",
    "set": "Ustaw"
  },
  "urlInput": {
    "invalidUrl": "Nieprawidłowy adres URL"
  },
  "urlComboBox": {
    "invalidUrl": "Nieprawidłowy adres URL"
  },
  "filterBuilder": {
    "addAnotherExpression": "Dodaj wyrażenie filtru",
    "addSet": "Dodaj zestaw wyrażenia",
    "matchMsg": "Pobierz z warstwy obiekty, które spełniają ${any_or_all} następujące wyrażenia",
    "matchMsgSet": "${any_or_all} następujące wyrażenia z tego zestawu są prawdziwe",
    "all": "Wszystkie",
    "any": "Dowolne",
    "value": "Wartość",
    "field": "ł_Field___ą",
    "unique": "Unikalne",
    "none": "Brak",
    "and": "i",
    "valueTooltip": "Wprowadź wartość",
    "fieldTooltip": "Wybierz z istniejącego pola",
    "uniqueValueTooltip": "Wybierz spośród unikalnych wartości w wybranym polu",
    "stringOperatorIs": "wynosi",
    "stringOperatorIsNot": "nie równa się",
    "stringOperatorStartsWith": "zaczyna się od",
    "stringOperatorEndsWith": "kończy się na",
    "stringOperatorContains": "zawiera",
    "stringOperatorDoesNotContain": "nie zawiera",
    "stringOperatorIsBlank": "jest puste",
    "stringOperatorIsNotBlank": "nie jest puste",
    "dateOperatorIsOn": "jest w dniu",
    "dateOperatorIsNotOn": "nie jest w dniu",
    "dateOperatorIsBefore": "jest przed",
    "dateOperatorIsAfter": "jest po",
    "dateOperatorDays": "dni",
    "dateOperatorWeeks": "tygodni",
    "dateOperatorMonths": "miesięcy",
    "dateOperatorInTheLast": "w ciągu ostatnich",
    "dateOperatorNotInTheLast": "nie w ciągu ostatnich",
    "dateOperatorIsBetween": "jest pomiędzy",
    "dateOperatorIsNotBetween": "nie jest pomiędzy",
    "dateOperatorIsBlank": "jest puste",
    "dateOperatorIsNotBlank": "nie jest puste",
    "numberOperatorIs": "wynosi",
    "numberOperatorIsNot": "nie równa się",
    "numberOperatorIsAtLeast": "równa się co najmniej",
    "numberOperatorIsLessThan": "jest mniejsze niż",
    "numberOperatorIsAtMost": "równa się maksymalnie",
    "numberOperatorIsGreaterThan": "jest większe niż",
    "numberOperatorIsBetween": "jest pomiędzy",
    "numberOperatorIsNotBetween": "nie jest pomiędzy",
    "numberOperatorIsBlank": "jest puste",
    "numberOperatorIsNotBlank": "nie jest puste",
    "string": "Tekst",
    "number": "Liczba",
    "date": "Data",
    "askForValues": "Pytaj o wartości",
    "prompt": "Monit",
    "hint": "Wskazówka",
    "error": {
      "invalidParams": "Nieprawidłowe parametry",
      "invalidUrl": "Nieprawidłowy adres URL",
      "noFilterFields": "Warstwa nie zawiera pól, które można zastosować w filtrze.",
      "invalidSQL": "Nieprawidłowe wyrażenie SQL",
      "cantParseSQL": "Nie można przeanalizować wyrażenia SQL."
    },
    "caseSensitive": "Uwzględnia wielkość liter",
    "notSupportCaseSensitiveTip": "Hostowane usługi nie obsługują zapytań rozróżniających wielkość liter."
  },
  "featureLayerSource": {
    "layer": "Warstwa",
    "browse": "Przeglądaj",
    "selectFromMap": "Wybierz na mapie",
    "selectFromPortal": "Dodaj z witryny Portal for ArcGIS",
    "addServiceUrl": "Dodaj adres URL usługi",
    "inputLayerUrl": "Adres URL warstwy wejściowej",
    "selectLayer": "Zaznacz na bieżącej mapie warstwę obiektów.",
    "chooseItem": "Wybierz atrybut warstwy obiektów.",
    "setServiceUrl": "Wprowadź adres URL usługi obiektowej lub mapowej.",
    "selectFromOnline": "Dodaj z usługi ArcGIS Online",
    "chooseLayer": "Wybierz warstwę obiektów."
  },
  "queryableLayerSource": {
    "layer": "ł_Layer___ą",
    "browse": "Przeglądaj",
    "selectFromMap": "Wybierz na mapie",
    "selectFromPortal": "Dodaj z witryny Portal for ArcGIS",
    "addServiceUrl": "Dodaj adres URL usługi",
    "inputLayerUrl": "Adres URL warstwy wejściowej",
    "selectLayer": "Wybierz na bieżącej mapie warstwę.",
    "chooseItem": "Wybierz element.",
    "setServiceUrl": "Wpisz adres URL usługi.",
    "selectFromOnline": "Dodaj z usługi ArcGIS Online",
    "chooseLayer": "Wybierz warstwę."
  },
  "gpSource": {
    "selectFromPortal": "Dodaj z witryny Portal for ArcGIS",
    "addServiceUrl": "Dodaj adres URL usługi",
    "selectFromOnline": "Dodaj z usługi ArcGIS Online",
    "setServiceUrl": "Wpisz adres URL usługi geoprzetwarzania.",
    "chooseItem": "Wybierz element będący usługą geoprzetwarzania.",
    "chooseTask": "Wybierz zadanie geoprzetwarzania."
  },
  "itemSelector": {
    "map": "ł_Map__ą",
    "selectWebMap": "Wybierz mapę internetową",
    "addMapFromOnlineOrPortal": "Wyszukaj mapę internetową spośród zasobów publicznych usługi cGIS Online bądź własnych, prywatnych zasobów serwisu ArcGIS Online lub Portal i dodaj ją do aplikacji.",
    "searchMapName": "Wyszukaj wg nazwy mapy...",
    "searchNone": "Nie można odnaleźć wyszukiwanego zasobu. Spróbuj ponownie.",
    "groups": "Grupy",
    "noneGroups": "Brak grup",
    "signInTip": "Twoja sesja logowania wygasła, odśwież widok w oknie przeglądarki, aby ponownie zalogować się do portalu.",
    "signIn": "Logowanie",
    "publicMap": "Publiczny",
    "myOrganization": "Moja instytucja",
    "myGroup": "Moje grupy",
    "myContent": "Moje zasoby",
    "count": "ł_Count___ą",
    "fromPortal": "z portalu",
    "fromOnline": "z serwisu ArcGIS.com",
    "noneThumbnail": "Miniatura jest niedostępna",
    "owner": "właściciel",
    "signInTo": "Zaloguj się do",
    "lastModified": "Ostatnia modyfikacja",
    "moreDetails": "Więcej szczegółów"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Usługa nie obsługuje wykonywania zapytań."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Mapa nie zawiera odpowiedniej warstwy."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mapy bazowe",
    "titleLayers": "Warstwy operacyjne",
    "labelLayer": "Nazwa warstwy tematycznej",
    "itemZoomTo": "Powiększ do",
    "itemTransparency": "Przezroczystość",
    "itemTransparent": "Przezroczysty",
    "itemOpaque": "Nieprzezroczysty",
    "itemMoveUp": "Przesuń w górę",
    "itemMoveDown": "Przesuń w dół",
    "itemDesc": "Opis",
    "itemDownload": "Pobierz",
    "itemToAttributeTable": "Otwórz tabelę atrybutów"
  },
  "imageChooser": {
    "unsupportReaderAPI": "DO OPRACOWANIA:  Przeglądarka nie obsługuje interfejsu API czytnika plików",
    "readError": "Nie można odczytać pliku.",
    "unknowError": "nie można zakończyć czynności",
    "invalidType": "Nieprawidłowy typ plików",
    "cropImage": "ł_Crop Image____ą",
    "exceed": "Rozmiar pliku nie może przekraczać 1024 KB",
    "enableFlash": "DO WYKONANIA: Włącz technologię Flash.",
    "cropWaining": "Proszę wybrać zdjęcie o minimalnych wymiarach ${width} x ${height} pikseli.",
    "toolTip": "W celu uzyskania najlepszych wyników obraz powinien mieć szerokość ${width} pikseli i wysokość ${height} pikseli.  Inne wielkości zostaną dopasowane.  Akceptowane formaty obrazów:  PNG, GIF i JPEG."
  },
  "simpleTable": {
    "moveUp": "Przesuń w górę",
    "moveDown": "Przesuń w dół",
    "deleteRow": "Usuń",
    "edit": "Edytuj"
  },
  "urlParams": {
    "invalidToken": "Niewłaściwy token",
    "validateTokenError": "Niewłaściwy token lub błąd sieciowy"
  },
  "exportTo": {
    "exportTo": "Eksportuj",
    "toCSV": "Eksportuj do pliku CSV",
    "toFeatureCollection": "Eksportuj do zbioru obiektów",
    "toGeoJSON": "Eksportuj do GeoJSON"
  },
  "appState": {
    "title": "ł_App State____ą",
    "restoreMap": "Kliknij, aby przywrócić zasięg mapy i widoczność warstw takie, jak w chwili pozostawienia."
  },
  "featureActions": {
    "ZoomTo": "ł_Zoom to___ą",
    "PanTo": "ł_Pan to___ą",
    "Flash": "ł_Flash___ą",
    "ShowPopup": "ł_Show Pop-up____ą",
    "CreateLayer": "ł_Create Layer_____ą",
    "ShowStatistics": "ł_Statistics_____ą...",
    "ClearSelection": "ł_Clear Selection______ą",
    "ExportToCSV": "ł_Export to CSV file______ą",
    "ExportToFeatureCollection": "ł_Export to Feature Collection_________ą",
    "ExportToGeoJSON": "ł_Export to GeoJSON______ą"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ł_Related layer_____ą",
    "selectedFeatures": "ł_Selected features______ą",
    "drawShapesTip": "ł_Draw shapes to select features__________ą",
    "pleaseDrawShapesTip": "ł_Please draw shapes to select features____________ą",
    "allFeaturesTip": "ł_All features in the layer_________ą",
    "selectFeaturesOrDrawShapesTip": "ł_Please use selected features in this layer or draw shapes on map to limit features__________________________ą."
  },
  "searchDistance": {
    "applySearchDistance": "ł_Apply a search distance________ą",
    "applySearchDistanceToFeatures": "ł_Apply a search distance to selected features______________ą"
  },
  "units": {
    "miles": "ł_Miles___ą",
    "kilometers": "ł_Kilometers____ą",
    "feet": "ł_Feet__ą",
    "meters": "ł_Meters___ą",
    "yards": "ł_Yards___ą",
    "nauticalMiles": "ł_Nautical Miles_____ą"
  },
  "featureSetChooser": {
    "select": "ł_Select___ą",
    "dragBox": "ł_Drag__ą",
    "dragMouse": "ł_Darg the mouse_____ą",
    "selectByRectangle": "ł_Select By Rectangle_______ą",
    "selectFeaturesTip": "ł_Select features by dragging box around them on map________________ą",
    "newSelectionTip": "ł_Create a new selection________ą",
    "addSelectionTip": "ł_Add to the current selection_________ą",
    "removeSelectionTip": "ł_Remove from the current selection___________ą",
    "selectFromCurrentSelectionTip": "ł_Select from the current selection___________ą",
    "unselectAllSelectionTip": "ł_Unselect all currently selected features_____________ą"
  },
  "widgetManager": {
    "createWidgetError": "ł_Create widget error_______ą",
    "createWidgetSettingPageError": "ł_Create widget setting page error___________ą",
    "loadWidgetResourceError": "ł_Load widget resouce error_________ą"
  },
  "shareOptions": {
    "shareMap": "ł_Choose who can view this app_________ą",
    "shareMapTips": "ł_Your map is currentlt shared with these people_______________ą",
    "everyone": "ł_everyone___ą",
    "theseGroups": "ł_theseGroups____ą"
  },
  "shareLink": {
    "email": "ł_email___ą",
    "shareEmail": "ł_Email___ą",
    "facebook": "ł_facebook___ą",
    "shareFacebook": "ł_Facebook___ą",
    "twitter": "ł_twitter___ą",
    "shareTwitter": "ł_Twitter___ą",
    "googlePlus": "ł_googlePlus____ą",
    "shareGooglePlus": "ł_GooglePlus____ą",
    "EmbedTips": "ł_Embed this scene in a website__________ą",
    "shareEmailTxt1": "ł_Have a look at this Web Scene__________ą:",
    "shareEmailTxt2": "ł_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ą.",
    "smallSize": "ł_Small___ą",
    "mediumSize": "ł_Medium___ą",
    "largeSize": "ł_Large___ą",
    "customSize": "ł_Custom___ą",
    "embed": "ł_Embed this scene in a website__________ą",
    "more": "ł_Embed Options_____ą",
    "changeShareSettings": "ł_Change Share Settings_______ą",
    "shareLinkText": "ł_Choose who can view Copy________ą",
    "linkOptions": "ł_Link Options_____ą",
    "linkOptionsUrlParameters": "ł_Select URL parameters included in the link______________ą",
    "currentMapExtent": "ł_Current map extent______ą",
    "chooseCenterWithLevel": "ł_Click the map to define the center of the map with scale level____________________ą",
    "chooseCenterWithScale": "ł_Click the map to define the center of the map with map scale___________________ą",
    "findLocation": "ł_Find the location or feature and zoom to it______________ą",
    "findLocation_inputPlaceholder": "ł_Your place or feature_______ą",
    "queryFeature": "ł_Query a feature and zoom to it__________ą",
    "addMarker": "ł_Add a marker on the map________ą",
    "addMarker_titlePlaceholder": "ł_Title of the marker pop-up_________ą",
    "addMarker_symbolURL": "ł_Marker symbol URL______ą",
    "addMarker_label": "ł_Marker label_____ą",
    "overwirteMobileLayout": "ł_Overwrite default mobile layout__________ą",
    "language": "ł_Set the app language_______ą",
    "auth": "ł_Authenticate a user automatically___________ą",
    "linkPreview": "ł_Link Preview_____ą",
    "useShortenLink": "ł_Short Link____ą",
    "shareMapUrlExtent": "ł_shareMapUrlExtent______ą"
  },
  "webSceneLoader": {
    "webglSupportTip": "ł_3D web apps aren't supported in your browser_______________ą."
  }
});