define({
	addAChartSource: "ã_Add a Chart Source_Ç",
	sourceLabel: "ã_Source label_Ç",
	labelField: "ã_Label field_Ç",
	actions: "ã_Actions_Ç",
	hightLightColor: "ã_Highlight color_Ç",
	urlChartSource: "ã_URL Chart Source_Ç",
	layerChartSource: "ã_Layer Chart Source_Ç",
	searchUrl: "ã_Search URL_Ç",
	browse: "ã_Browse_Ç",
	layers: "ã_Layers_Ç",
	availableFields: "ã_Available Fields_Ç",
	charts: "ã_Charts_Ç",
	chartField: "ã_Chart field_Ç",
	description: "ã_Description_Ç",
	title: "ã_Title_Ç",
	type: "ã_Type_Ç",
	cancel: "ã_Cancel_Ç",
	addChartSource: "ã_Add Chart Source_Ç",
	updateChartSource: "ã_Update Chart Source_Ç",
	chartSources: "ã_Chart Sources_Ç",
	chartSource: "ã_Chart Source_Ç",
	general: "ã_General_Ç"
});