define({
  "common": {
    "apply": "ı_Apply___İ",
    "ok": "Tamam",
    "cancel": "İptal",
    "yes": "ı_Yes__İ",
    "no": "ı_No__İ",
    "next": "İleri",
    "back": "Geri",
    "selected": "ı_selected___İ",
    "name": "Ad",
    "usage": "ı_Usage___İ",
    "settings": "ı_Settings___İ",
    "home": "ı_Home__İ",
    "link": "ı_Link__İ",
    "messages": "ı_Messages___İ",
    "outputs": "ı_Outputs___İ",
    "title": "Başlık",
    "thumbnail": "ı_Thumbnail____İ",
    "url": "ı_URL__İ",
    "actions": "İşlemler",
    "layer": "Katman",
    "action": "ı_Action___İ",
    "input": "ı_Input___İ",
    "output": "ı_Output___İ",
    "type": "ı_Type__İ",
    "required": "ı_Required___İ",
    "options": "ı_Options___İ",
    "label": "Etiket",
    "tooltip": "ı_Tooltip___İ",
    "visible": "ı_Visible___İ",
    "symbol": "ı_Symbol___İ",
    "popup": "ı_Popup___İ",
    "upload": "ı_Upload___İ",
    "execute": "ı_Execute___İ",
    "help": "ı_Help__İ",
    "executing": "ı_Executing____İ",
    "clear": "Temizle",
    "error": "ı_Error___İ",
    "zoomTo": "Yakınlaştır",
    "attribute": "ı_Attribute____İ",
    "exports": "ı_Export___İ",
    "check": "ı_Check___İ",
    "save": "ı_Save__İ",
    "close": "ı_Close___İ",
    "deleteText": "ı_Delete___İ",
    "map": "Harita",
    "scene": "ı_Scene___İ",
    "reset": "ı_Reset___İ",
    "icon": "ı_Icon__İ",
    "share": "ı_Share___İ"
  },
  "errorCode": "Kod",
  "errorMessage": "İleti",
  "errorDetail": "Ayrıntı",
  "widgetPlaceholderTooltip": "Ayarlamak için Araçlar'a gidin ve karşılık gelen yer tutucuyu tıklayın",
  "fieldStatistics": {
    "statistics": "ı_Statistics____İ",
    "field": "Alan",
    "count": "ı_Number of Values______İ",
    "sum": "ı_Sum of Values_____İ",
    "min": "ı_Minimum___İ",
    "max": "ı_Maximum___İ",
    "ave": "ı_Average___İ",
    "stddev": "ı_Standard Deviation______İ"
  },
  "symbolChooser": {
    "preview": "Önizleme",
    "basic": "Temel",
    "arrows": "Oklar",
    "business": "İş",
    "cartographic": "Kartografik",
    "nationalParkService": "Ulusal Park Hizmeti",
    "outdoorRecreation": "Açık Havada Dinlenme",
    "peoplePlaces": "İnsanların Bulunduğu Mekanlar",
    "safetyHealth": "Güvenlik Sağlık",
    "shapes": "Şekiller",
    "transportation": "Taşımacılık",
    "symbolSize": "Simge Boyutu",
    "color": "Renk",
    "alpha": "Alfa",
    "outlineColor": "Dış Çizgi Rengi",
    "outlineWidth": "Dış Çizgi Genişliği",
    "style": "Stil",
    "width": "Genişlik",
    "text": "Metin",
    "fontColor": "Yazı Tipi Rengi",
    "fontSize": "Yazı Tipi Boyutu",
    "transparency": "Saydamlık",
    "solid": "Dolu",
    "dash": "Tire",
    "dot": "Nokta",
    "dashDot": "Çizgi Nokta",
    "dashDotDot": "Çizgi Nokta Nokta"
  },
  "transparency": {
    "opaque": "Opak",
    "transparent": "Saydam"
  },
  "rendererChooser": {
    "domain": "Etki Alanı",
    "use": "Kullan",
    "singleSymbol": "Tek Bir Simge",
    "uniqueSymbol": "Özel Simgeler",
    "color": "Renk",
    "size": "Boyut",
    "toShow": "Gösterilecek",
    "colors": "Renkler",
    "classes": "Sınıflar",
    "symbolSize": "Simge Boyutu",
    "addValue": "Değer Ekle",
    "setDefaultSymbol": "Varsayılan Simgeyi Ayarla",
    "defaultSymbol": "Varsayılan Sembol",
    "selectedSymbol": "Seçili Simge",
    "value": "Değer",
    "label": "ı_Label___İ",
    "range": "Aralık"
  },
  "drawBox": {
    "point": "Nokta",
    "line": "Çizgi",
    "polyline": "Çoklu Çizgi",
    "freehandPolyline": "Serbest Çizim Çoklu Çizgi",
    "triangle": "Üçgen",
    "extent": "Yayılım",
    "circle": "Daire",
    "ellipse": "Elips",
    "polygon": "Alan",
    "freehandPolygon": "Serbest Çizim Alan",
    "text": "Metin",
    "clear": "ı_Clear___İ"
  },
  "popupConfig": {
    "title": "ı_Title___İ",
    "add": "Ekle",
    "fields": "Alanlar",
    "noField": "Alan Yok",
    "visibility": "Görünür",
    "name": "ı_Name__İ",
    "alias": "Diğer Ad",
    "actions": "ı_Actions___İ"
  },
  "includeButton": {
    "include": "Dahil Et"
  },
  "loadingShelter": {
    "loading": "Yükleniyor"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Servis bulunamadı.",
    "unableConnectTo": "Buraya bağlanılamıyor:",
    "invalidUrlTip": "Girdiğiniz URL geçersiz veya erişilemez."
  },
  "serviceBrowser": {
    "noGpFound": "Coğrafi işlem servisi bulunamadı.",
    "unableConnectTo": "Buraya bağlanılamıyor:"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Harita servisi ya da detay servisi bulunamadı",
    "unableConnectTo": "Buraya bağlanılamıyor:"
  },
  "basicServiceChooser": {
    "validate": "Doğrula",
    "example": "Örnek",
    "set": "Ayarla"
  },
  "urlInput": {
    "invalidUrl": "Geçersiz URL."
  },
  "urlComboBox": {
    "invalidUrl": "Geçersiz URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Bir filtre ifadesi ekle",
    "addSet": "İfade kümesi ekle",
    "matchMsg": "Katmanda, aşağıdaki ifadenin ${any_or_all} kadarı ile eşleşen detayları al",
    "matchMsgSet": "Bu setteki aşağıdaki ifadelerin ${any_or_all} doğru",
    "all": "Tümü",
    "any": "Bir Kısmı",
    "value": "Değer",
    "field": "ı_Field___İ",
    "unique": "Tek",
    "none": "Hiçbiri",
    "and": "ve",
    "valueTooltip": "Değer gir",
    "fieldTooltip": "Mevcut alandan seç",
    "uniqueValueTooltip": "Seçili alandaki tek değerlerden seç",
    "stringOperatorIs": "alanı şu olanlar",
    "stringOperatorIsNot": "alanı şu olmayanlar",
    "stringOperatorStartsWith": "alanı şununla başlayanlar",
    "stringOperatorEndsWith": "alanı şununla bitenler",
    "stringOperatorContains": "alanı şunu içerenler",
    "stringOperatorDoesNotContain": "alanı şunu içermeyenler",
    "stringOperatorIsBlank": "alanı boş olanlar",
    "stringOperatorIsNotBlank": "alanı boş olmayanlar",
    "dateOperatorIsOn": "alanı şu tarihte olanlar",
    "dateOperatorIsNotOn": "alanı şu tarihte olmayanlar",
    "dateOperatorIsBefore": "alanı şu tarihten önce olanlar",
    "dateOperatorIsAfter": "alanı şu tarihten sonra olanlar",
    "dateOperatorDays": "gün içinde",
    "dateOperatorWeeks": "hafta içinde",
    "dateOperatorMonths": "ay içinde",
    "dateOperatorInTheLast": "alanı son şu dönemde olanlar",
    "dateOperatorNotInTheLast": "alanı son şu dönemde olmayanlar",
    "dateOperatorIsBetween": "alanı şu tarihler arasında olanlar",
    "dateOperatorIsNotBetween": "alanı şu tarihler arasında olmayanlar",
    "dateOperatorIsBlank": "alanı boş olanlar",
    "dateOperatorIsNotBlank": "alanı boş olmayanlar",
    "numberOperatorIs": "alanı şu olanlar",
    "numberOperatorIsNot": "alanı şu olmayanlar",
    "numberOperatorIsAtLeast": "alanı en az şu olanlar",
    "numberOperatorIsLessThan": "alanı şundan küçük olanlar",
    "numberOperatorIsAtMost": "alanı en çok şu olanlar",
    "numberOperatorIsGreaterThan": "alanı şundan büyük olanlar",
    "numberOperatorIsBetween": "alanı şu tarihler arasında olanlar",
    "numberOperatorIsNotBetween": "alanı şu tarihler arasında olmayanlar",
    "numberOperatorIsBlank": "alanı boş olanlar",
    "numberOperatorIsNotBlank": "alanı boş olmayanlar",
    "string": "Dize",
    "number": "Rakam",
    "date": "Tarih",
    "askForValues": "Değer iste",
    "prompt": "İstem",
    "hint": "İpucu",
    "error": {
      "invalidParams": "Geçersiz parametreler.",
      "invalidUrl": "Geçersiz URL.",
      "noFilterFields": "Katmanın filtre için kullanılabilecek hiçbir alanı yok.",
      "invalidSQL": "Geçersiz SQL ifadesi.",
      "cantParseSQL": "SQL ifadesi ayrıştırılamadı."
    },
    "caseSensitive": "Büyük/Küçük Harf Duyarlı",
    "notSupportCaseSensitiveTip": "Barındırılan hizmetler büyük küçük harf duyarlı sorgulamayı desteklemez."
  },
  "featureLayerSource": {
    "layer": "Katman",
    "browse": "Gözat",
    "selectFromMap": "Haritadan seç",
    "selectFromPortal": "Portal for ArcGIS'ten ekle",
    "addServiceUrl": "Servis URL'si ekle",
    "inputLayerUrl": "Girdi Katmanı URL'si",
    "selectLayer": "Geçerli haritadan bir detay katmanı seçin.",
    "chooseItem": "Bir detay katmanı öğesi seçin.",
    "setServiceUrl": "Detay servisinin ya da harita servisinin URL'sini girin.",
    "selectFromOnline": "ArcGIS Online'dan Ekle",
    "chooseLayer": "Bir özellik katmanı seçin."
  },
  "queryableLayerSource": {
    "layer": "ı_Layer___İ",
    "browse": "...",
    "selectFromMap": "Haritadan seç",
    "selectFromPortal": "Portal for ArcGIS'ten ekle",
    "addServiceUrl": "Servis URL'si ekle",
    "inputLayerUrl": "Girdi Katmanı URL'si",
    "selectLayer": "Geçerli haritadan bir katman seçin.",
    "chooseItem": "Öğe seçin.",
    "setServiceUrl": "Hizmetin URL'sini girin.",
    "selectFromOnline": "ArcGIS Online'dan Ekle",
    "chooseLayer": "Katman seçmek için kullanılır."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS'ten ekle",
    "addServiceUrl": "Servis URL'si Ekle",
    "selectFromOnline": "ArcGIS Online'dan Ekle",
    "setServiceUrl": "Coğrafi işlem hizmetinin URL'sini girin.",
    "chooseItem": "Bir coğrafi işlem hizmet öğesi seçin.",
    "chooseTask": "Bir coğrafi işlem görevi seçin."
  },
  "itemSelector": {
    "map": "ı_Map__İ",
    "selectWebMap": "Web Haritası Seç",
    "addMapFromOnlineOrPortal": "ArcGIS Online genel kaynaklarından veya ArcGIS Online veya Portal'daki özel içeriğinizden gelen uygulamada bir web haritası bulun ve buraya ekleyin.",
    "searchMapName": "Harita adına göre ara...",
    "searchNone": "Aradığınızı bulamadık. Yeniden deneyin.",
    "groups": "Gruplar",
    "noneGroups": "Grup yok",
    "signInTip": "Oturumunuzun süresi doldu, portalınızda yeniden oturum açmak için tarayıcınızı yenileyin.",
    "signIn": "Hesabınıza",
    "publicMap": "Genel",
    "myOrganization": "Kuruluşum",
    "myGroup": "Gruplarım",
    "myContent": "İçeriğim",
    "count": "ı_Count___İ",
    "fromPortal": "Portal'dan",
    "fromOnline": "ArcGIS.com'dan",
    "noneThumbnail": "Küçük Resim Yok",
    "owner": "Sahibi",
    "signInTo": "Şurada oturum aç",
    "lastModified": "Son Değiştirme",
    "moreDetails": "Diğer Ayrıntılar"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Hizmet sorgulamayı desteklemiyor."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Haritada kullanılabilir uygun katman yok."
  },
  "layerInfosMenu": {
    "titleBasemap": "Altlık haritaları",
    "titleLayers": "Operasyonel Katmanlar",
    "labelLayer": "Katman Adı",
    "itemZoomTo": "Şuna Yakınlaştır",
    "itemTransparency": "Saydamlık",
    "itemTransparent": "Saydam",
    "itemOpaque": "Opak",
    "itemMoveUp": "Yukarı taşı",
    "itemMoveDown": "Aşağı taşı",
    "itemDesc": "Açıklama",
    "itemDownload": "İndir",
    "itemToAttributeTable": "Öznitelik Tablosunu Aç"
  },
  "imageChooser": {
    "unsupportReaderAPI": "YAPILACAK: Tarayıcı, dosya okuyucu API'sini desteklemiyor",
    "readError": "Dosya okunamadı.",
    "unknowError": "işlemler tamamlanamıyor",
    "invalidType": "Geçersiz dosya türü.",
    "cropImage": "ı_Crop Image____İ",
    "exceed": "Dosya boyutu 1024 KB'yi aşamaz",
    "enableFlash": "YAPILACAK: Flash'ı etkinleştirin.",
    "cropWaining": "Çözünürlüğü en az ${width} x ${height} piksel olan bir fotoğraf seçin.",
    "toolTip": "En iyi sonuç için görüntü ${width} piksel genişliğinde ve ${height} piksel yüksekliğinde olmalıdır. Diğer boyutlar sığacak şekilde ayarlanır. Kabul edilen görüntü biçimleri: PNG, GIF ve JPEG."
  },
  "simpleTable": {
    "moveUp": "Yukarı taşı",
    "moveDown": "Aşağı taşı",
    "deleteRow": "Sil",
    "edit": "Düzenle"
  },
  "urlParams": {
    "invalidToken": "Geçersiz belirteç",
    "validateTokenError": "Geçersiz belirteç veya Ağ hatası"
  },
  "exportTo": {
    "exportTo": "Dışa Aktar",
    "toCSV": "CSV dosyasına gönder",
    "toFeatureCollection": "Detay Koleksiyonuna Aktar",
    "toGeoJSON": "GeoJSON//'a Aktar"
  },
  "appState": {
    "title": "ı_App State____İ",
    "restoreMap": "Harita yayılımını ve katman görünürlüğünü bıraktığınız yerden geri yüklemek için tıklayın."
  },
  "featureActions": {
    "ZoomTo": "ı_Zoom to___İ",
    "PanTo": "ı_Pan to___İ",
    "Flash": "ı_Flash___İ",
    "ShowPopup": "ı_Show Pop-up____İ",
    "CreateLayer": "ı_Create Layer_____İ",
    "ShowStatistics": "ı_Statistics_____İ...",
    "ClearSelection": "ı_Clear Selection______İ",
    "ExportToCSV": "ı_Export to CSV file______İ",
    "ExportToFeatureCollection": "ı_Export to Feature Collection_________İ",
    "ExportToGeoJSON": "ı_Export to GeoJSON______İ"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ı_Related layer_____İ",
    "selectedFeatures": "ı_Selected features______İ",
    "drawShapesTip": "ı_Draw shapes to select features__________İ",
    "pleaseDrawShapesTip": "ı_Please draw shapes to select features____________İ",
    "allFeaturesTip": "ı_All features in the layer_________İ",
    "selectFeaturesOrDrawShapesTip": "ı_Please use selected features in this layer or draw shapes on map to limit features__________________________İ."
  },
  "searchDistance": {
    "applySearchDistance": "ı_Apply a search distance________İ",
    "applySearchDistanceToFeatures": "ı_Apply a search distance to selected features______________İ"
  },
  "units": {
    "miles": "ı_Miles___İ",
    "kilometers": "ı_Kilometers____İ",
    "feet": "ı_Feet__İ",
    "meters": "ı_Meters___İ",
    "yards": "ı_Yards___İ",
    "nauticalMiles": "ı_Nautical Miles_____İ"
  },
  "featureSetChooser": {
    "select": "ı_Select___İ",
    "dragBox": "ı_Drag__İ",
    "dragMouse": "ı_Darg the mouse_____İ",
    "selectByRectangle": "ı_Select By Rectangle_______İ",
    "selectFeaturesTip": "ı_Select features by dragging box around them on map________________İ",
    "newSelectionTip": "ı_Create a new selection________İ",
    "addSelectionTip": "ı_Add to the current selection_________İ",
    "removeSelectionTip": "ı_Remove from the current selection___________İ",
    "selectFromCurrentSelectionTip": "ı_Select from the current selection___________İ",
    "unselectAllSelectionTip": "ı_Unselect all currently selected features_____________İ"
  },
  "widgetManager": {
    "createWidgetError": "ı_Create widget error_______İ",
    "createWidgetSettingPageError": "ı_Create widget setting page error___________İ",
    "loadWidgetResourceError": "ı_Load widget resouce error_________İ"
  },
  "shareOptions": {
    "shareMap": "ı_Choose who can view this app_________İ",
    "shareMapTips": "ı_Your map is currentlt shared with these people_______________İ",
    "everyone": "ı_everyone___İ",
    "theseGroups": "ı_theseGroups____İ"
  },
  "shareLink": {
    "email": "ı_email___İ",
    "shareEmail": "ı_Email___İ",
    "facebook": "ı_facebook___İ",
    "shareFacebook": "ı_Facebook___İ",
    "twitter": "ı_twitter___İ",
    "shareTwitter": "ı_Twitter___İ",
    "googlePlus": "ı_googlePlus____İ",
    "shareGooglePlus": "ı_GooglePlus____İ",
    "EmbedTips": "ı_Embed this scene in a website__________İ",
    "shareEmailTxt1": "ı_Have a look at this Web Scene__________İ:",
    "shareEmailTxt2": "ı_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________İ.",
    "smallSize": "ı_Small___İ",
    "mediumSize": "ı_Medium___İ",
    "largeSize": "ı_Large___İ",
    "customSize": "ı_Custom___İ",
    "embed": "ı_Embed this scene in a website__________İ",
    "more": "ı_Embed Options_____İ",
    "changeShareSettings": "ı_Change Share Settings_______İ",
    "shareLinkText": "ı_Choose who can view Copy________İ",
    "linkOptions": "ı_Link Options_____İ",
    "linkOptionsUrlParameters": "ı_Select URL parameters included in the link______________İ",
    "currentMapExtent": "ı_Current map extent______İ",
    "chooseCenterWithLevel": "ı_Click the map to define the center of the map with scale level____________________İ",
    "chooseCenterWithScale": "ı_Click the map to define the center of the map with map scale___________________İ",
    "findLocation": "ı_Find the location or feature and zoom to it______________İ",
    "findLocation_inputPlaceholder": "ı_Your place or feature_______İ",
    "queryFeature": "ı_Query a feature and zoom to it__________İ",
    "addMarker": "ı_Add a marker on the map________İ",
    "addMarker_titlePlaceholder": "ı_Title of the marker pop-up_________İ",
    "addMarker_symbolURL": "ı_Marker symbol URL______İ",
    "addMarker_label": "ı_Marker label_____İ",
    "overwirteMobileLayout": "ı_Overwrite default mobile layout__________İ",
    "language": "ı_Set the app language_______İ",
    "auth": "ı_Authenticate a user automatically___________İ",
    "linkPreview": "ı_Link Preview_____İ",
    "useShortenLink": "ı_Short Link____İ",
    "shareMapUrlExtent": "ı_shareMapUrlExtent______İ"
  },
  "webSceneLoader": {
    "webglSupportTip": "ı_3D web apps aren't supported in your browser_______________İ."
  }
});