define({
  "common": {
    "apply": "ก้_Apply___ษฺ",
    "ok": "ตกลง",
    "cancel": "ยกเลิก",
    "yes": "ก้_Yes__ษฺ",
    "no": "ก้_No__ษฺ",
    "next": "ถัดไป",
    "back": "กลับ",
    "selected": "ก้_selected___ษฺ",
    "name": "ชื่อ",
    "usage": "ก้_Usage___ษฺ",
    "settings": "ก้_Settings___ษฺ",
    "home": "ก้_Home__ษฺ",
    "link": "ก้_Link__ษฺ",
    "messages": "ก้_Messages___ษฺ",
    "outputs": "ก้_Outputs___ษฺ",
    "title": "ชื่อ",
    "thumbnail": "ก้_Thumbnail____ษฺ",
    "url": "ก้_URL__ษฺ",
    "actions": "กระทำ",
    "layer": "ชั้นข้อมูล",
    "action": "ก้_Action___ษฺ",
    "input": "ก้_Input___ษฺ",
    "output": "ก้_Output___ษฺ",
    "type": "ก้_Type__ษฺ",
    "required": "ก้_Required___ษฺ",
    "options": "ก้_Options___ษฺ",
    "label": "ตัวอักษร",
    "tooltip": "ก้_Tooltip___ษฺ",
    "visible": "ก้_Visible___ษฺ",
    "symbol": "ก้_Symbol___ษฺ",
    "popup": "ก้_Popup___ษฺ",
    "upload": "ก้_Upload___ษฺ",
    "execute": "ก้_Execute___ษฺ",
    "help": "ก้_Help__ษฺ",
    "executing": "ก้_Executing____ษฺ",
    "clear": "ลบ",
    "error": "ก้_Error___ษฺ",
    "zoomTo": "ขยายไปยัง",
    "attribute": "ก้_Attribute____ษฺ",
    "exports": "ก้_Export___ษฺ",
    "check": "ก้_Check___ษฺ",
    "save": "ก้_Save__ษฺ",
    "close": "ก้_Close___ษฺ",
    "deleteText": "ก้_Delete___ษฺ",
    "map": "แผนที่",
    "scene": "ก้_Scene___ษฺ",
    "reset": "ก้_Reset___ษฺ",
    "icon": "ก้_Icon__ษฺ",
    "share": "ก้_Share___ษฺ"
  },
  "errorCode": "รหัส",
  "errorMessage": "ข้อความ",
  "errorDetail": "รายละเอียด",
  "widgetPlaceholderTooltip": "ทำการตั้งค่า ไปยัง widget และคลิกที่ตัวยืดร่วม",
  "fieldStatistics": {
    "statistics": "ก้_Statistics____ษฺ",
    "field": "คอลัมน์",
    "count": "ก้_Number of Values______ษฺ",
    "sum": "ก้_Sum of Values_____ษฺ",
    "min": "ก้_Minimum___ษฺ",
    "max": "ก้_Maximum___ษฺ",
    "ave": "ก้_Average___ษฺ",
    "stddev": "ก้_Standard Deviation______ษฺ"
  },
  "symbolChooser": {
    "preview": "ตัวอย่าง",
    "basic": "ระดับพื้นฐาน",
    "arrows": "ลูกศร",
    "business": "ธุรกิจ",
    "cartographic": "การทำแผนที่",
    "nationalParkService": "เซอร์วิสอุทยานแห่งชาติ",
    "outdoorRecreation": "กิจกรรมกลางแจ้ง",
    "peoplePlaces": "สถานที่บุคคล",
    "safetyHealth": "ความปลอดภัยด้านสุขภาพ",
    "shapes": "รูปร่าง",
    "transportation": "การคมนาคม",
    "symbolSize": "ขนาดสัญลักษณ์",
    "color": "สี",
    "alpha": "อัลฟ้า",
    "outlineColor": "สีของโครงร่าง",
    "outlineWidth": "ความกว้างโครงร่าง",
    "style": "สไตล์",
    "width": "ความกว้าง",
    "text": "ข้อความ",
    "fontColor": "สีตัวอักษร",
    "fontSize": "ขนาดตัวอักษร",
    "transparency": "ความโปร่งแสง",
    "solid": "สีเดียว",
    "dash": "-",
    "dot": ".",
    "dashDot": "-.",
    "dashDotDot": "-.."
  },
  "transparency": {
    "opaque": "ความทึบแสง",
    "transparent": "ความโปร่งแสง"
  },
  "rendererChooser": {
    "domain": "โดเมน",
    "use": "ใช้",
    "singleSymbol": "สัญลักษณ์เดี่ยว",
    "uniqueSymbol": "สัญลักษณ์ที่เป็นเอกลักษณ์",
    "color": "สี",
    "size": "ขนาด",
    "toShow": "แสดง",
    "colors": "สี",
    "classes": "ชั้น",
    "symbolSize": "ขนาดสัญลักษณ์",
    "addValue": "เพิ่มค่า",
    "setDefaultSymbol": "ตั้งค่าสัญลักษณ์ตั้งต้น",
    "defaultSymbol": "สัญลักษณ์ตั้งต้น",
    "selectedSymbol": "สัญลักษณ์ที่เลือก",
    "value": "ค่า",
    "label": "ก้_Label___ษฺ",
    "range": "ลำดับ"
  },
  "drawBox": {
    "point": "จุด",
    "line": "เส้น",
    "polyline": "เส้น",
    "freehandPolyline": "การวาดเส้นหลายเส้นด้วยมือเปล่า",
    "triangle": "สามเหลี่ยม",
    "extent": "ส่วนขยาย",
    "circle": "วงกลม",
    "ellipse": "วงรี",
    "polygon": "รูปปิด",
    "freehandPolygon": "การวาดรูปหลายเหลี่ยมด้วยมือเปล่า",
    "text": "ข้อความ",
    "clear": "ก้_Clear___ษฺ"
  },
  "popupConfig": {
    "title": "ก้_Title___ษฺ",
    "add": "เพิ่ม",
    "fields": "ฟิลด์",
    "noField": "ไม่มีฟิลด์",
    "visibility": "มองเห็น",
    "name": "ก้_Name__ษฺ",
    "alias": "นามแฝง",
    "actions": "ก้_Actions___ษฺ"
  },
  "includeButton": {
    "include": "รวมเข้ากับ"
  },
  "loadingShelter": {
    "loading": "กำลังโหลด"
  },
  "basicServiceBrowser": {
    "noServicesFound": "ไม่พบเซอร์วิสที่ค้นหา",
    "unableConnectTo": "ไม่สามารถเชื่อมต่อไปยัง",
    "invalidUrlTip": "URL ที่คุณป้อนไม่ถูกต้องหรือไม่สามารถเข้าถึง"
  },
  "serviceBrowser": {
    "noGpFound": "ไม่พบเซอร์วิสกระบวนการทางภูมิศาสตร์ที่ค้นหา",
    "unableConnectTo": "ไม่สามารถเชื่อมต่อไปยัง"
  },
  "layerServiceBrowser": {
    "noServicesFound": "ไม่พบแมพเซอร์วิสหรือฟีเจอร์เซอร์วิสที่ค้นหา",
    "unableConnectTo": "ไม่สามารถเชื่อมต่อไปยัง"
  },
  "basicServiceChooser": {
    "validate": "ตรวจสอบ",
    "example": "ตัวอย่าง",
    "set": "ตั้งค่า"
  },
  "urlInput": {
    "invalidUrl": "Url ไม่ถูกต้อง"
  },
  "urlComboBox": {
    "invalidUrl": "Url ไม่ถูกต้อง"
  },
  "filterBuilder": {
    "addAnotherExpression": "เพิ่มสูตรคำนวณในการกรอง",
    "addSet": "เพิ่มชุดการแสดง",
    "matchMsg": "แสดงฟีเจอร์ที่ในชั้นข้อมูลที่ตรงกัน ${any_or_all}ตามสูตรคำนวณต่อไปนี้",
    "matchMsgSet": "${any_or_all} ตามสูตรคำนวณนี้จะทำให้การตั้งค่าเป็นจริง",
    "all": "ทั้งหมด",
    "any": "ใดๆ",
    "value": "ค่า",
    "field": "ก้_Field___ษฺ",
    "unique": "เอกลักษณ์",
    "none": "ไม่มี",
    "and": "และ",
    "valueTooltip": "เพิ่มค่า",
    "fieldTooltip": "หยิบจากฟิลด์ที่มีอยู่",
    "uniqueValueTooltip": "หยิบจากค่าเอกลักษณ์ในฟิลด์ที่เลือก",
    "stringOperatorIs": "เป็น",
    "stringOperatorIsNot": "ไม่เป็น",
    "stringOperatorStartsWith": "เริ่มด้วย",
    "stringOperatorEndsWith": "จบด้วย",
    "stringOperatorContains": "รวมด้วย",
    "stringOperatorDoesNotContain": "ไม่รวมด้วย",
    "stringOperatorIsBlank": "ว่าง",
    "stringOperatorIsNotBlank": "ไม่ว่าง",
    "dateOperatorIsOn": "ที่อยู่บน",
    "dateOperatorIsNotOn": "ที่ไม่อยู่บน",
    "dateOperatorIsBefore": "แต่ก่อน",
    "dateOperatorIsAfter": "ที่หลัง",
    "dateOperatorDays": "วัน",
    "dateOperatorWeeks": "สัปดาห์",
    "dateOperatorMonths": "เดือน",
    "dateOperatorInTheLast": "ในที่สุด",
    "dateOperatorNotInTheLast": "ไม่ที่สุด",
    "dateOperatorIsBetween": "ระหว่าง",
    "dateOperatorIsNotBetween": "ไม่ระหว่าง",
    "dateOperatorIsBlank": "ว่าง",
    "dateOperatorIsNotBlank": "ไม่ว่าง",
    "numberOperatorIs": "เป็น",
    "numberOperatorIsNot": "ไม่เป็น",
    "numberOperatorIsAtLeast": "อย่างน้อย",
    "numberOperatorIsLessThan": "น้อยกว่า",
    "numberOperatorIsAtMost": "มาก",
    "numberOperatorIsGreaterThan": "มากกว่า",
    "numberOperatorIsBetween": "ระหว่าง",
    "numberOperatorIsNotBetween": "ไม่ระหว่าง",
    "numberOperatorIsBlank": "ว่าง",
    "numberOperatorIsNotBlank": "ไม่ว่าง",
    "string": "ตัวหนังสือ",
    "number": "จำนวน",
    "date": "วันที่",
    "askForValues": "สอบถามค่า",
    "prompt": "รวดเร็ว",
    "hint": "เปรียบเปรย",
    "error": {
      "invalidParams": "พารามิเตอร์ไม่ถูกต้อง",
      "invalidUrl": "Url ไม่ถูกต้อง",
      "noFilterFields": "ชั้นข้อมูลไม่มีฟิลด์ที่สามารถนำไปใช้กรองได้",
      "invalidSQL": "สูตรคำนวณ SQL ไม่ถูกต้อง",
      "cantParseSQL": "ไม่สามารถแยกสูตรคำนวณ SQL ได้"
    },
    "caseSensitive": "ตัวอักษรใหญ่หรือเล็กมีความสำคัญ",
    "notSupportCaseSensitiveTip": "บริการโฮสต์ข้อมูลไม่สนับสนุนการสอบถามเป็นกรณี ๆ"
  },
  "featureLayerSource": {
    "layer": "ชั้นข้อมูล",
    "browse": "เบราว์",
    "selectFromMap": "เลือกจากแผนที่",
    "selectFromPortal": "เพิ่มจาก Portal for ArcGIS",
    "addServiceUrl": "เพิ่ม URL เซอร์วิส",
    "inputLayerUrl": "นำเข้าชั้นข้อมูล URL",
    "selectLayer": "เลือกชั้นข้อมูลฟีเจอร์จากแผนที่ปัจจุบัน",
    "chooseItem": "เลือกขั้นข้อมูลฟีเจอร์",
    "setServiceUrl": "ตั้งค่าเซอร์วิส URL หรือเซอร์วิสแผนที่",
    "selectFromOnline": "เพิ่มจาก ArcGIS Online",
    "chooseLayer": "เลือกชั้นข้อมูลฟีเจอร์"
  },
  "queryableLayerSource": {
    "layer": "ก้_Layer___ษฺ",
    "browse": "ค้นหา",
    "selectFromMap": "เลือกจากแผนที่",
    "selectFromPortal": "เพิ่มจาก Portal for ArcGIS",
    "addServiceUrl": "เพิ่ม Service URL",
    "inputLayerUrl": "นำเข้าชั้นข้อมูล URL",
    "selectLayer": "เลือกชั้นข้อมูลจากแผนที่ปัจจุบัน",
    "chooseItem": "เลือกรายการ",
    "setServiceUrl": "ใส่  URL ของเซอร์วิส",
    "selectFromOnline": "เพิ่มจาก ArcGIS Online",
    "chooseLayer": "เลือกชั้นข้อมูล"
  },
  "gpSource": {
    "selectFromPortal": "เพิ่มจาก Portal for ArcGIS",
    "addServiceUrl": "เพิ่ม Service URL",
    "selectFromOnline": "เพิ่มจาก ArcGIS Online",
    "setServiceUrl": "กรอก URL ของ GeoProcessing Service",
    "chooseItem": "เลือกรายการข้อมูล GeoProcessing Service",
    "chooseTask": "เลือกรายการทำงานของ GeoProessing"
  },
  "itemSelector": {
    "map": "ก้_Map__ษฺ",
    "selectWebMap": "เลือกเว็บแมพ",
    "addMapFromOnlineOrPortal": "ค้นหาและเพิ่มเว็บแมพที่จะใช้ในแอพพลิเคชั่นจาก ArcGIS Online สำหรับแหล่งข้อมูลสาธารณะหรือเนื้อหาส่วนตัวที่อยู่ใน ArcGIS Online หรือในพอร์ทัล",
    "searchMapName": "ค้นหาจากชื่อแผนที่...",
    "searchNone": "เราไม่สามารถค้นหาในสิ่งที่คุณต้องการได้ โปรดลองอีกครั้งหนึ่ง",
    "groups": "กลุ่ม :",
    "noneGroups": "ไม่มีกลุ่ม",
    "signInTip": "การอยู่ในระบบของคุณหมดเวลาลงแล้ว โปรดรีเฟรชที่บราวเซอร์ใหม่อีกครั้งเพื่อทำการเข้าสู่ระบบพอร์ทัลของคุณอีกครั้ง",
    "signIn": "ลงชื่อเข้าใช้",
    "publicMap": "สาธารณะ",
    "myOrganization": "องค์กรของฉัน",
    "myGroup": "กลุ่มของฉัน",
    "myContent": "เนื้อหาของฉัน",
    "count": "ก้_Count___ษฺ",
    "fromPortal": "จากพอร์ทัล",
    "fromOnline": "จาก ArcGIS.com",
    "noneThumbnail": "รูปภาพขนาดเล็กไม่สามารถใช้งานได้",
    "owner": "เจ้าของ",
    "signInTo": "ลงชื่อเข้าใช้สู่",
    "lastModified": "แก้ไขครั้งสุดท้ายเมื่อ",
    "moreDetails": "รายละเอียดเพิ่มเติม"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Service นี้ไม่รองรับการคัดกรองข้อมูล"
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "ไม่มีชั้นข้อมูลการดำเนินการบนแผนที่"
  },
  "layerInfosMenu": {
    "titleBasemap": "แผนที่ฐาน",
    "titleLayers": "ชั้นข้อมูลซ้อนทับ",
    "labelLayer": "ชื่อชั้นข้อมูล",
    "itemZoomTo": "ขยายไปยัง",
    "itemTransparency": "ความโปร่งแสง",
    "itemTransparent": "ความโปร่งแสง",
    "itemOpaque": "ความทึบแสง",
    "itemMoveUp": "เลื่อนขึ้น",
    "itemMoveDown": "เลื่อนลง",
    "itemDesc": "คำอธิบาย",
    "itemDownload": "ดาวน์โหลด",
    "itemToAttributeTable": "เปิดตารางข้อมูลเชิงประกอบ"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: บราวเซอร์ไม่สนับสนุนตัวอ่านไฟล์ API",
    "readError": "การอ่านไฟล์ล้มเหลว",
    "unknowError": "ไม่สามารถดำเนินการได้อย่างสมบูรณ์",
    "invalidType": "ประเภทของไฟล์ไม่ถูกต้อง",
    "cropImage": "ก้_Crop Image____ษฺ",
    "exceed": "ขนาดไฟล์ห้ามเกิน 1024 KB",
    "enableFlash": "TODO: กรุณาเปิดการใช้งานแฟลช",
    "cropWaining": "กรุณาเลือกภาพที่อย่างน้อย ${width} x ${height} พิเซล",
    "toolTip": "เพื่อให้ได้ผลลัพธ์ที่ดีที่สุดควรจะเป็นภาพ ${width} พิกเซลกว้างโดย ${height} พิกเซลสูง ขนาดอื่น ๆ จะได้รับการปรับเปลี่ยนให้เหมาะสม รูปแบบภาพที่ยอมรับได้คือ: PNG, GIF และ JPEG"
  },
  "simpleTable": {
    "moveUp": "เลื่อนขึ้น",
    "moveDown": "เลื่อนลง",
    "deleteRow": "ลบทิ้ง",
    "edit": "แก้ไข"
  },
  "urlParams": {
    "invalidToken": "โทเค็นไม่ถูกต้อง",
    "validateTokenError": "โทเค็นไม่ถูกต้อง หรือข้อผิดพลาดของเครือข่าย"
  },
  "exportTo": {
    "exportTo": "ส่งออก",
    "toCSV": "นำออกเป็นไฟล์ CSV",
    "toFeatureCollection": "ส่งออกเป็น Feature Collection",
    "toGeoJSON": "ส่งออกเป็น GeoJSON"
  },
  "appState": {
    "title": "ก้_App State____ษฺ",
    "restoreMap": "คลิกเพื่อเรียกขอบเขตแผนที่และชั้นข้อมูลในการมองเห็น เมื่อคุณไม่ได้อยู่ที่หน้าต่างการทำงาน"
  },
  "featureActions": {
    "ZoomTo": "ก้_Zoom to___ษฺ",
    "PanTo": "ก้_Pan to___ษฺ",
    "Flash": "ก้_Flash___ษฺ",
    "ShowPopup": "ก้_Show Pop-up____ษฺ",
    "CreateLayer": "ก้_Create Layer_____ษฺ",
    "ShowStatistics": "ก้_Statistics_____ษฺ...",
    "ClearSelection": "ก้_Clear Selection______ษฺ",
    "ExportToCSV": "ก้_Export to CSV file______ษฺ",
    "ExportToFeatureCollection": "ก้_Export to Feature Collection_________ษฺ",
    "ExportToGeoJSON": "ก้_Export to GeoJSON______ษฺ"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ก้_Related layer_____ษฺ",
    "selectedFeatures": "ก้_Selected features______ษฺ",
    "drawShapesTip": "ก้_Draw shapes to select features__________ษฺ",
    "pleaseDrawShapesTip": "ก้_Please draw shapes to select features____________ษฺ",
    "allFeaturesTip": "ก้_All features in the layer_________ษฺ",
    "selectFeaturesOrDrawShapesTip": "ก้_Please use selected features in this layer or draw shapes on map to limit features__________________________ษฺ."
  },
  "searchDistance": {
    "applySearchDistance": "ก้_Apply a search distance________ษฺ",
    "applySearchDistanceToFeatures": "ก้_Apply a search distance to selected features______________ษฺ"
  },
  "units": {
    "miles": "ก้_Miles___ษฺ",
    "kilometers": "ก้_Kilometers____ษฺ",
    "feet": "ก้_Feet__ษฺ",
    "meters": "ก้_Meters___ษฺ",
    "yards": "ก้_Yards___ษฺ",
    "nauticalMiles": "ก้_Nautical Miles_____ษฺ"
  },
  "featureSetChooser": {
    "select": "ก้_Select___ษฺ",
    "dragBox": "ก้_Drag__ษฺ",
    "dragMouse": "ก้_Darg the mouse_____ษฺ",
    "selectByRectangle": "ก้_Select By Rectangle_______ษฺ",
    "selectFeaturesTip": "ก้_Select features by dragging box around them on map________________ษฺ",
    "newSelectionTip": "ก้_Create a new selection________ษฺ",
    "addSelectionTip": "ก้_Add to the current selection_________ษฺ",
    "removeSelectionTip": "ก้_Remove from the current selection___________ษฺ",
    "selectFromCurrentSelectionTip": "ก้_Select from the current selection___________ษฺ",
    "unselectAllSelectionTip": "ก้_Unselect all currently selected features_____________ษฺ"
  },
  "widgetManager": {
    "createWidgetError": "ก้_Create widget error_______ษฺ",
    "createWidgetSettingPageError": "ก้_Create widget setting page error___________ษฺ",
    "loadWidgetResourceError": "ก้_Load widget resouce error_________ษฺ"
  },
  "shareOptions": {
    "shareMap": "ก้_Choose who can view this app_________ษฺ",
    "shareMapTips": "ก้_Your map is currentlt shared with these people_______________ษฺ",
    "everyone": "ก้_everyone___ษฺ",
    "theseGroups": "ก้_theseGroups____ษฺ"
  },
  "shareLink": {
    "email": "ก้_email___ษฺ",
    "shareEmail": "ก้_Email___ษฺ",
    "facebook": "ก้_facebook___ษฺ",
    "shareFacebook": "ก้_Facebook___ษฺ",
    "twitter": "ก้_twitter___ษฺ",
    "shareTwitter": "ก้_Twitter___ษฺ",
    "googlePlus": "ก้_googlePlus____ษฺ",
    "shareGooglePlus": "ก้_GooglePlus____ษฺ",
    "EmbedTips": "ก้_Embed this scene in a website__________ษฺ",
    "shareEmailTxt1": "ก้_Have a look at this Web Scene__________ษฺ:",
    "shareEmailTxt2": "ก้_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ษฺ.",
    "smallSize": "ก้_Small___ษฺ",
    "mediumSize": "ก้_Medium___ษฺ",
    "largeSize": "ก้_Large___ษฺ",
    "customSize": "ก้_Custom___ษฺ",
    "embed": "ก้_Embed this scene in a website__________ษฺ",
    "more": "ก้_Embed Options_____ษฺ",
    "changeShareSettings": "ก้_Change Share Settings_______ษฺ",
    "shareLinkText": "ก้_Choose who can view Copy________ษฺ",
    "linkOptions": "ก้_Link Options_____ษฺ",
    "linkOptionsUrlParameters": "ก้_Select URL parameters included in the link______________ษฺ",
    "currentMapExtent": "ก้_Current map extent______ษฺ",
    "chooseCenterWithLevel": "ก้_Click the map to define the center of the map with scale level____________________ษฺ",
    "chooseCenterWithScale": "ก้_Click the map to define the center of the map with map scale___________________ษฺ",
    "findLocation": "ก้_Find the location or feature and zoom to it______________ษฺ",
    "findLocation_inputPlaceholder": "ก้_Your place or feature_______ษฺ",
    "queryFeature": "ก้_Query a feature and zoom to it__________ษฺ",
    "addMarker": "ก้_Add a marker on the map________ษฺ",
    "addMarker_titlePlaceholder": "ก้_Title of the marker pop-up_________ษฺ",
    "addMarker_symbolURL": "ก้_Marker symbol URL______ษฺ",
    "addMarker_label": "ก้_Marker label_____ษฺ",
    "overwirteMobileLayout": "ก้_Overwrite default mobile layout__________ษฺ",
    "language": "ก้_Set the app language_______ษฺ",
    "auth": "ก้_Authenticate a user automatically___________ษฺ",
    "linkPreview": "ก้_Link Preview_____ษฺ",
    "useShortenLink": "ก้_Short Link____ษฺ",
    "shareMapUrlExtent": "ก้_shareMapUrlExtent______ษฺ"
  },
  "webSceneLoader": {
    "webglSupportTip": "ก้_3D web apps aren't supported in your browser_______________ษฺ."
  }
});