define({
  "_widgetLabel": "Atributna tabela",
  "_featureAction_ShowRelatedRecords": "Č_Show Related Records_______ž",
  "_featureAction_ViewInTable": "Č_View in Attribute Table________ž",
  "ok": "U redu",
  "cancel": "Otkaži",
  "unsupportQueryWarning": "Sloj mora da podržava radnju upita da bi se prikazao u vidžetu „Atributna tabela“. Postarajte se da je mogućnost izvršavanja upita u servisu uključena.",
  "exportMessage": "Izvezi podatke u CSV datoteku?",
  "exportFiles": "Izvezi u CSV",
  "exportSelected": "Izvezi selektovano u CSV",
  "exportAll": "Izvezi sve stavke u CSV",
  "options": "Opcije",
  "zoomto": "Uveličaj na",
  "highlight": "Istakni grafiku",
  "selectAll": "Selektuj zapise na svim stranicama",
  "selectPage": "Selektuj zapise na trenutnoj stranici",
  "clearSelection": "Ukloni selekciju",
  "filter": "Filter",
  "setFilterTip": "Pravilno postavite filter.",
  "noFilterTip": "Bez definisanog izraza filtera, ovaj zadatak upita će izlistati sve geoobjekte u određenom izvoru podataka.",
  "filterByExtent": "Filtriraj po obuhvatu mape",
  "showSelectedRecords": "Pokaži selektovane zapise",
  "showAllRecords": "Pokaži sve zapise",
  "showRelatedRecords": "Pokaži povezane zapise",
  "noRelatedRecords": "Nema pronađenih povezanih zapisa",
  "refresh": "Osveži",
  "features": "geoobjekti",
  "selected": "selektovano",
  "transparent": "Režim prozirnosti",
  "indicate": "Lociraj selektovano",
  "columns": "Prikaži/sakrij kolone",
  "selectionSymbol": "Simbol selekcije",
  "closeMessage": "Sakrij tabelu (ponovo je proširi od dna)",
  "dataNotAvailable": "Podaci nisu dostupni!<br>Kliknite na dugme [Osveži] da biste ponovo pokušali.",
  "openTableTip": "Otvori atributnu tabelu",
  "closeTableTip": "Sakrij atributnu tabelu",
  "sortAsc": "Č_Sort Ascending_____ž",
  "sortDes": "Č_Sort Descending______ž",
  "statistics": "Č_Statistics____ž"
});