define({
  "common": {
    "apply": "Ă_Apply___ș",
    "ok": "OK",
    "cancel": "Anulare",
    "yes": "Ă_Yes__ș",
    "no": "Ă_No__ș",
    "next": "Următor",
    "back": "Înapoi",
    "selected": "Ă_selected___ș",
    "name": "Nume",
    "usage": "Ă_Usage___ș",
    "settings": "Ă_Settings___ș",
    "home": "Ă_Home__ș",
    "link": "Ă_Link__ș",
    "messages": "Ă_Messages___ș",
    "outputs": "Ă_Outputs___ș",
    "title": "Titlu",
    "thumbnail": "Ă_Thumbnail____ș",
    "url": "Ă_URL__ș",
    "actions": "Acţiuni",
    "layer": "Strat tematic",
    "action": "Ă_Action___ș",
    "input": "Ă_Input___ș",
    "output": "Ă_Output___ș",
    "type": "Ă_Type__ș",
    "required": "Ă_Required___ș",
    "options": "Ă_Options___ș",
    "label": "Etichetă",
    "tooltip": "Ă_Tooltip___ș",
    "visible": "Ă_Visible___ș",
    "symbol": "Ă_Symbol___ș",
    "popup": "Ă_Popup___ș",
    "upload": "Ă_Upload___ș",
    "execute": "Ă_Execute___ș",
    "help": "Ă_Help__ș",
    "executing": "Ă_Executing____ș",
    "clear": "Golire",
    "error": "Ă_Error___ș",
    "zoomTo": "Transfocare la",
    "attribute": "Ă_Attribute____ș",
    "exports": "Ă_Export___ș",
    "check": "Ă_Check___ș",
    "save": "Ă_Save__ș",
    "close": "Ă_Close___ș",
    "deleteText": "Ă_Delete___ș",
    "map": "Hartă",
    "scene": "Ă_Scene___ș",
    "reset": "Ă_Reset___ș",
    "icon": "Ă_Icon__ș",
    "share": "Ă_Share___ș"
  },
  "errorCode": "Cod",
  "errorMessage": "Mesaj",
  "errorDetail": "Detaliu",
  "widgetPlaceholderTooltip": "Pentru a-l configura, mergeţi la Widgeturi şi faceţi clic pe substituentul corespunzător",
  "fieldStatistics": {
    "statistics": "Ă_Statistics____ș",
    "field": "Câmp",
    "count": "Ă_Number of Values______ș",
    "sum": "Ă_Sum of Values_____ș",
    "min": "Ă_Minimum___ș",
    "max": "Ă_Maximum___ș",
    "ave": "Ă_Average___ș",
    "stddev": "Ă_Standard Deviation______ș"
  },
  "symbolChooser": {
    "preview": "Previzualizare",
    "basic": "De bază",
    "arrows": "Săgeţi",
    "business": "Afacere",
    "cartographic": "Cartografie",
    "nationalParkService": "Serviciul pentru parcuri naţionale",
    "outdoorRecreation": "Recreere în aer liber",
    "peoplePlaces": "Locaţii personale",
    "safetyHealth": "Siguranţă şi sănătate",
    "shapes": "Forme",
    "transportation": "Transport",
    "symbolSize": "Dimensiune simbol",
    "color": "Culoare",
    "alpha": "Alfa",
    "outlineColor": "Culoare contur",
    "outlineWidth": "Lăţime contur",
    "style": "Stil",
    "width": "Lăţime",
    "text": "Text",
    "fontColor": "Culoare font",
    "fontSize": "Dimensiune font",
    "transparency": "Transparenţă",
    "solid": "Continuu",
    "dash": "Linie",
    "dot": "Punct",
    "dashDot": "Linie punct",
    "dashDotDot": "Linie punct punct"
  },
  "transparency": {
    "opaque": "Opac",
    "transparent": "Transparent"
  },
  "rendererChooser": {
    "domain": "Domeniu",
    "use": "Utilizare",
    "singleSymbol": "Un singur simbol",
    "uniqueSymbol": "Simboluri unice",
    "color": "Culoare",
    "size": "Dimensiune",
    "toShow": "Pentru afişare",
    "colors": "Culori",
    "classes": "Clase",
    "symbolSize": "Dimensiune simbol",
    "addValue": "Adăugare valoare",
    "setDefaultSymbol": "Setare simbol implicit",
    "defaultSymbol": "Simbol implicit",
    "selectedSymbol": "Simbol selectat",
    "value": "Valoare",
    "label": "Ă_Label___ș",
    "range": "Distanţă"
  },
  "drawBox": {
    "point": "Punct",
    "line": "Linie",
    "polyline": "Linie poligonală",
    "freehandPolyline": "Linie poligonală trasată manual",
    "triangle": "Triunghi",
    "extent": "Extindere",
    "circle": "Cerc",
    "ellipse": "Elipsă",
    "polygon": "Poligon",
    "freehandPolygon": "Poligon trasat manual",
    "text": "Text",
    "clear": "Ă_Clear___ș"
  },
  "popupConfig": {
    "title": "Ă_Title___ș",
    "add": "Adăugare",
    "fields": "Câmpuri",
    "noField": "Niciun câmp",
    "visibility": "Vizibil",
    "name": "Ă_Name__ș",
    "alias": "Pseudonim",
    "actions": "Ă_Actions___ș"
  },
  "includeButton": {
    "include": "Includere"
  },
  "loadingShelter": {
    "loading": "Se încarcă"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nu a fost găsit niciun serviciu.",
    "unableConnectTo": "Nu se poate efectua conectarea la",
    "invalidUrlTip": "Adresa URL pe care aţi introdus-o este nevalidă sau inaccesibilă."
  },
  "serviceBrowser": {
    "noGpFound": "Nu a fost găsit niciun serviciu de geoprocesare.",
    "unableConnectTo": "Nu se poate efectua conectarea la"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nu a fost găsit niciun serviciu de hărţi sau serviciu de obiecte spaţiale",
    "unableConnectTo": "Nu se poate efectua conectarea la"
  },
  "basicServiceChooser": {
    "validate": "Validare",
    "example": "Exemplu",
    "set": "Setare"
  },
  "urlInput": {
    "invalidUrl": "URL nevalid."
  },
  "urlComboBox": {
    "invalidUrl": "URL nevalid."
  },
  "filterBuilder": {
    "addAnotherExpression": "Adăugare expresie de filtrare",
    "addSet": "Adăugare set pentru expresie",
    "matchMsg": "Obţinere obiecte spaţiale în stratul tematic care se potrivesc cu ${any_or_all} dintre următoarele expresii",
    "matchMsgSet": "${any_or_all} dintre următoarele expresii din acest set sunt adevărate",
    "all": "Toate",
    "any": "Oricare",
    "value": "Valoare",
    "field": "Ă_Field___ș",
    "unique": "Unice",
    "none": "Niciunul",
    "and": "şi",
    "valueTooltip": "Introducere valoare",
    "fieldTooltip": "Alegere din câmpul existent",
    "uniqueValueTooltip": "Alegeţi dintre valorile unice din câmpul selectat",
    "stringOperatorIs": "este",
    "stringOperatorIsNot": "nu este",
    "stringOperatorStartsWith": "începe cu",
    "stringOperatorEndsWith": "se termină cu",
    "stringOperatorContains": "conţine",
    "stringOperatorDoesNotContain": "nu conţine",
    "stringOperatorIsBlank": "este necompletat",
    "stringOperatorIsNotBlank": "nu este necompletat",
    "dateOperatorIsOn": "este pe",
    "dateOperatorIsNotOn": "nu este pe",
    "dateOperatorIsBefore": "este înainte de",
    "dateOperatorIsAfter": "este după",
    "dateOperatorDays": "zile",
    "dateOperatorWeeks": "săptămâni",
    "dateOperatorMonths": "luni",
    "dateOperatorInTheLast": "în ultimele",
    "dateOperatorNotInTheLast": "nu este în ultimele",
    "dateOperatorIsBetween": "este între",
    "dateOperatorIsNotBetween": "nu este între",
    "dateOperatorIsBlank": "este necompletat",
    "dateOperatorIsNotBlank": "nu este necompletat",
    "numberOperatorIs": "este",
    "numberOperatorIsNot": "nu este",
    "numberOperatorIsAtLeast": "este cel puţin",
    "numberOperatorIsLessThan": "este mai mică decât",
    "numberOperatorIsAtMost": "este cel mult",
    "numberOperatorIsGreaterThan": "este mai mare de",
    "numberOperatorIsBetween": "este între",
    "numberOperatorIsNotBetween": "nu este între",
    "numberOperatorIsBlank": "este necompletat",
    "numberOperatorIsNotBlank": "nu este necompletat",
    "string": "Şir",
    "number": "Număr",
    "date": "Dată",
    "askForValues": "Solicitare valori",
    "prompt": "Prompt",
    "hint": "Sugestie",
    "error": {
      "invalidParams": "Parametri nevalizi.",
      "invalidUrl": "URL nevalid.",
      "noFilterFields": "Stratul tematic nu conţine câmpuri ce pot fi folosite pentru filtru.",
      "invalidSQL": "Expresie SQL nevalidă.",
      "cantParseSQL": "Expresia SQL nu poate fi analizată."
    },
    "caseSensitive": "Sensibil la majuscule/minuscule",
    "notSupportCaseSensitiveTip": "Serviciile găzduite nu acceptă interogările care depind de majuscule/minuscule."
  },
  "featureLayerSource": {
    "layer": "Strat tematic",
    "browse": "Parcurgere",
    "selectFromMap": "Selectare din hartă",
    "selectFromPortal": "Adăugare din Portal for ArcGIS",
    "addServiceUrl": "Adăugare URL serviciu",
    "inputLayerUrl": "URL strat tematic de intrare",
    "selectLayer": "Selectaţi un strat tematic de obiecte spaţiale din harta actuală.",
    "chooseItem": "Selectaţi un element strat tematic de obiecte spaţiale.",
    "setServiceUrl": "Introduceţi adresa URL a serviciului de obiecte spaţiale sau a serviciului de hartă.",
    "selectFromOnline": "Adăugare din ArcGIS Online",
    "chooseLayer": "Selectaţi un strat tematic de obiecte spaţiale."
  },
  "queryableLayerSource": {
    "layer": "Ă_Layer___ș",
    "browse": "Parcurgere",
    "selectFromMap": "Selectare din hartă",
    "selectFromPortal": "Adăugare din Portal for ArcGIS",
    "addServiceUrl": "Adăugare URL serviciu",
    "inputLayerUrl": "URL strat tematic de intrare",
    "selectLayer": "Selectaţi un strat tematic din harta actuală.",
    "chooseItem": "Selectaţi un element.",
    "setServiceUrl": "Introduceţi adresa URL a serviciului.",
    "selectFromOnline": "Adăugare din ArcGIS Online",
    "chooseLayer": "Alegeţi un strat tematic."
  },
  "gpSource": {
    "selectFromPortal": "Adăugare din Portal for ArcGIS",
    "addServiceUrl": "Adăugare URL serviciu",
    "selectFromOnline": "Adăugare din ArcGIS Online",
    "setServiceUrl": "Introduceţi adresa URL a serviciului de geoprocesare.",
    "chooseItem": "Selectaţi un element de tip serviciu de geoprocesare.",
    "chooseTask": "Selectaţi o operaţie de geoprocesare."
  },
  "itemSelector": {
    "map": "Ă_Map__ș",
    "selectWebMap": "Selectare hartă Web",
    "addMapFromOnlineOrPortal": "Găsiţi şi adăugaţi o hartă web în aplicaţie din resurse ArcGIS Online publice sau din conţinutul dvs. privat din ArcGIS Online sau Portal.",
    "searchMapName": "Căutare după numele hărţii...",
    "searchNone": "Nu am putut găsi ceea ce căutaţi. Încercaţi din nou.",
    "groups": "Grupuri",
    "noneGroups": "Niciun grup",
    "signInTip": "Sesiunea de lucru autentificat a expirat; reîmprospătaţi browserul pentru a vă autentifica din nou în portal.",
    "signIn": "Autentificaţi-vă",
    "publicMap": "Public",
    "myOrganization": "Organizaţia mea",
    "myGroup": "Grupurile mele",
    "myContent": "Resursele mele",
    "count": "Ă_Count___ș",
    "fromPortal": "din Portal",
    "fromOnline": "din ArcGIS.com",
    "noneThumbnail": "Miniatură indisponibilă",
    "owner": "proprietar",
    "signInTo": "Autentificare la",
    "lastModified": "Ultima modificare",
    "moreDetails": "Mai multe detalii"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Serviciul nu permite interogări."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Nu există niciun strat tematic adecvat disponibil pe hartă."
  },
  "layerInfosMenu": {
    "titleBasemap": "Hărţi fundal",
    "titleLayers": "Straturi tematice operaţionale",
    "labelLayer": "Nume strat tematic",
    "itemZoomTo": "Transfocare la",
    "itemTransparency": "Transparenţă",
    "itemTransparent": "Transparent",
    "itemOpaque": "Opac",
    "itemMoveUp": "Deplasare în sus",
    "itemMoveDown": "Deplasare în jos",
    "itemDesc": "Descriere",
    "itemDownload": "Descărcare",
    "itemToAttributeTable": "Deschidere tabel de atribute"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Acţiune: Browserul nu suportă API-ul pentru citirea fişierului",
    "readError": "Nu s-a reuşit citirea fişierului.",
    "unknowError": "imposibil de finalizat operaţiunile",
    "invalidType": "Tip de fişier nevalid.",
    "cropImage": "Ă_Crop Image____ș",
    "exceed": "Dimensiunea fişierului nu poate depăşi 1024 KB",
    "enableFlash": "Acţiune: activaţi funcţia flash.",
    "cropWaining": "Alegeţi o fotografie cu dimensiunea de cel puţin ${width} x ${height} pixeli.",
    "toolTip": "Pentru cel mai bun rezultat, imaginea trebuie să aibă ${width} pixeli lăţime şi ${height} pixeli înălţime. Alte dimensiuni vor fi ajustate pentru a se încadra. Formatele de imagine acceptate sunt: PNG, GIF şi JPEG."
  },
  "simpleTable": {
    "moveUp": "Deplasare în sus",
    "moveDown": "Deplasare în jos",
    "deleteRow": "Ştergere",
    "edit": "Editare"
  },
  "urlParams": {
    "invalidToken": "Token nevalid",
    "validateTokenError": "Token nevalid sau eroare de reţea"
  },
  "exportTo": {
    "exportTo": "Export",
    "toCSV": "Export în fişier CSV",
    "toFeatureCollection": "Export către Colecția de obiecte spațiale",
    "toGeoJSON": "Export către GeoJSON"
  },
  "appState": {
    "title": "Ă_App State____ș",
    "restoreMap": "Apăsaţi pentru a restaura extinderea hărţii şi vizibilitatea straturilor tematice de unde aţi rămas."
  },
  "featureActions": {
    "ZoomTo": "Ă_Zoom to___ș",
    "PanTo": "Ă_Pan to___ș",
    "Flash": "Ă_Flash___ș",
    "ShowPopup": "Ă_Show Pop-up____ș",
    "CreateLayer": "Ă_Create Layer_____ș",
    "ShowStatistics": "Ă_Statistics_____ș...",
    "ClearSelection": "Ă_Clear Selection______ș",
    "ExportToCSV": "Ă_Export to CSV file______ș",
    "ExportToFeatureCollection": "Ă_Export to Feature Collection_________ș",
    "ExportToGeoJSON": "Ă_Export to GeoJSON______ș"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Ă_Related layer_____ș",
    "selectedFeatures": "Ă_Selected features______ș",
    "drawShapesTip": "Ă_Draw shapes to select features__________ș",
    "pleaseDrawShapesTip": "Ă_Please draw shapes to select features____________ș",
    "allFeaturesTip": "Ă_All features in the layer_________ș",
    "selectFeaturesOrDrawShapesTip": "Ă_Please use selected features in this layer or draw shapes on map to limit features__________________________ș."
  },
  "searchDistance": {
    "applySearchDistance": "Ă_Apply a search distance________ș",
    "applySearchDistanceToFeatures": "Ă_Apply a search distance to selected features______________ș"
  },
  "units": {
    "miles": "Ă_Miles___ș",
    "kilometers": "Ă_Kilometers____ș",
    "feet": "Ă_Feet__ș",
    "meters": "Ă_Meters___ș",
    "yards": "Ă_Yards___ș",
    "nauticalMiles": "Ă_Nautical Miles_____ș"
  },
  "featureSetChooser": {
    "select": "Ă_Select___ș",
    "dragBox": "Ă_Drag__ș",
    "dragMouse": "Ă_Darg the mouse_____ș",
    "selectByRectangle": "Ă_Select By Rectangle_______ș",
    "selectFeaturesTip": "Ă_Select features by dragging box around them on map________________ș",
    "newSelectionTip": "Ă_Create a new selection________ș",
    "addSelectionTip": "Ă_Add to the current selection_________ș",
    "removeSelectionTip": "Ă_Remove from the current selection___________ș",
    "selectFromCurrentSelectionTip": "Ă_Select from the current selection___________ș",
    "unselectAllSelectionTip": "Ă_Unselect all currently selected features_____________ș"
  },
  "widgetManager": {
    "createWidgetError": "Ă_Create widget error_______ș",
    "createWidgetSettingPageError": "Ă_Create widget setting page error___________ș",
    "loadWidgetResourceError": "Ă_Load widget resouce error_________ș"
  },
  "shareOptions": {
    "shareMap": "Ă_Choose who can view this app_________ș",
    "shareMapTips": "Ă_Your map is currentlt shared with these people_______________ș",
    "everyone": "Ă_everyone___ș",
    "theseGroups": "Ă_theseGroups____ș"
  },
  "shareLink": {
    "email": "Ă_email___ș",
    "shareEmail": "Ă_Email___ș",
    "facebook": "Ă_facebook___ș",
    "shareFacebook": "Ă_Facebook___ș",
    "twitter": "Ă_twitter___ș",
    "shareTwitter": "Ă_Twitter___ș",
    "googlePlus": "Ă_googlePlus____ș",
    "shareGooglePlus": "Ă_GooglePlus____ș",
    "EmbedTips": "Ă_Embed this scene in a website__________ș",
    "shareEmailTxt1": "Ă_Have a look at this Web Scene__________ș:",
    "shareEmailTxt2": "Ă_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________ș.",
    "smallSize": "Ă_Small___ș",
    "mediumSize": "Ă_Medium___ș",
    "largeSize": "Ă_Large___ș",
    "customSize": "Ă_Custom___ș",
    "embed": "Ă_Embed this scene in a website__________ș",
    "more": "Ă_Embed Options_____ș",
    "changeShareSettings": "Ă_Change Share Settings_______ș",
    "shareLinkText": "Ă_Choose who can view Copy________ș",
    "linkOptions": "Ă_Link Options_____ș",
    "linkOptionsUrlParameters": "Ă_Select URL parameters included in the link______________ș",
    "currentMapExtent": "Ă_Current map extent______ș",
    "chooseCenterWithLevel": "Ă_Click the map to define the center of the map with scale level____________________ș",
    "chooseCenterWithScale": "Ă_Click the map to define the center of the map with map scale___________________ș",
    "findLocation": "Ă_Find the location or feature and zoom to it______________ș",
    "findLocation_inputPlaceholder": "Ă_Your place or feature_______ș",
    "queryFeature": "Ă_Query a feature and zoom to it__________ș",
    "addMarker": "Ă_Add a marker on the map________ș",
    "addMarker_titlePlaceholder": "Ă_Title of the marker pop-up_________ș",
    "addMarker_symbolURL": "Ă_Marker symbol URL______ș",
    "addMarker_label": "Ă_Marker label_____ș",
    "overwirteMobileLayout": "Ă_Overwrite default mobile layout__________ș",
    "language": "Ă_Set the app language_______ș",
    "auth": "Ă_Authenticate a user automatically___________ș",
    "linkPreview": "Ă_Link Preview_____ș",
    "useShortenLink": "Ă_Short Link____ș",
    "shareMapUrlExtent": "Ă_shareMapUrlExtent______ș"
  },
  "webSceneLoader": {
    "webglSupportTip": "Ă_3D web apps aren't supported in your browser_______________ș."
  }
});