define({
  root: ({
    schemaMapping: "Schema Mapping",
    locationMapping: "Location Mapping",
    addToMap: "Add to map",
    submit: "Submit",
    clear: "Clear",
    schemaMappingInstructions: "Please drag/drop a CSV onto the map.\nThis widget will assist with processing the CSV data when it is made avalible.",
    loadWarning: "This widget requires a Feature Service datasource. Please configure the widget to define a datasource.",
    addressFieldLabel: "Address",
    useAddress: "Single Field Address",
    useMultiAddress: "Multi Field Address",
    xyFieldsLabelX: "X",
    xyFieldsLabelY: "Y",
    useXY: "X/Y Fields",
    saveError: "Error saving features.",
    noValue: "Select a Value",
    consumesCredits: "This tool consumes credits when used with the ArcGIS Online World Geocoding Service",
    address: "Address",
    city: "City",
    state: "State",
    zip: "Zip"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "hr": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sr": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});