define({
	addAChartSource: "ä_Add a Chart Source_Ü",
	sourceLabel: "ä_Source label_Ü",
	labelField: "ä_Label field_Ü",
	actions: "ä_Actions_Ü",
	hightLightColor: "ä_Highlight color_Ü",
	urlChartSource: "ä_URL Chart Source_Ü",
	layerChartSource: "ä_Layer Chart Source_Ü",
	searchUrl: "ä_Search URL_Ü",
	browse: "ä_Browse_Ü",
	layers: "ä_Layers_Ü",
	availableFields: "ä_Available Fields_Ü",
	charts: "ä_Charts_Ü",
	chartField: "ä_Chart field_Ü",
	description: "ä_Description_Ü",
	title: "ä_Title_Ü",
	type: "ä_Type_Ü",
	cancel: "ä_Cancel_Ü",
	addChartSource: "ä_Add Chart Source_Ü",
	updateChartSource: "ä_Update Chart Source_Ü",
	chartSources: "ä_Chart Sources_Ü",
	chartSource: "ä_Chart Source_Ü",
	general: "ä_General_Ü"
});