define({
  "common": {
    "apply": "ã_Apply___Ç",
    "ok": "Ok",
    "cancel": "Cancelar",
    "yes": "ã_Yes__Ç",
    "no": "ã_No__Ç",
    "next": "Seguinte",
    "back": "Regressar",
    "selected": "ã_selected___Ç",
    "name": "Nome",
    "usage": "ã_Usage___Ç",
    "settings": "ã_Settings___Ç",
    "home": "ã_Home__Ç",
    "link": "ã_Link__Ç",
    "messages": "ã_Messages___Ç",
    "outputs": "ã_Outputs___Ç",
    "title": "Título",
    "thumbnail": "ã_Thumbnail____Ç",
    "url": "ã_URL__Ç",
    "actions": "Ações",
    "layer": "Camada",
    "action": "ã_Action___Ç",
    "input": "ã_Input___Ç",
    "output": "ã_Output___Ç",
    "type": "ã_Type__Ç",
    "required": "ã_Required___Ç",
    "options": "ã_Options___Ç",
    "label": "Rótulo",
    "tooltip": "ã_Tooltip___Ç",
    "visible": "ã_Visible___Ç",
    "symbol": "ã_Symbol___Ç",
    "popup": "ã_Popup___Ç",
    "upload": "ã_Upload___Ç",
    "execute": "ã_Execute___Ç",
    "help": "ã_Help__Ç",
    "executing": "ã_Executing____Ç",
    "clear": "Limpar",
    "error": "ã_Error___Ç",
    "zoomTo": "Efectuar zoom para",
    "attribute": "ã_Attribute____Ç",
    "exports": "ã_Export___Ç",
    "check": "ã_Check___Ç",
    "save": "ã_Save__Ç",
    "close": "ã_Close___Ç",
    "deleteText": "ã_Delete___Ç",
    "map": "Mapa",
    "scene": "ã_Scene___Ç",
    "reset": "ã_Reset___Ç",
    "icon": "ã_Icon__Ç",
    "share": "ã_Share___Ç"
  },
  "errorCode": "Código",
  "errorMessage": "Mensagem",
  "errorDetail": "Detalhe",
  "widgetPlaceholderTooltip": "Para configurar, vá a Widgets e clique no placehorlder correspondente",
  "fieldStatistics": {
    "statistics": "ã_Statistics____Ç",
    "field": "Campo",
    "count": "ã_Number of Values______Ç",
    "sum": "ã_Sum of Values_____Ç",
    "min": "ã_Minimum___Ç",
    "max": "ã_Maximum___Ç",
    "ave": "ã_Average___Ç",
    "stddev": "ã_Standard Deviation______Ç"
  },
  "symbolChooser": {
    "preview": "Pré-Visualizar",
    "basic": "Básico",
    "arrows": "Setas",
    "business": "Negócio",
    "cartographic": "Cartográfico",
    "nationalParkService": "Serviço Parque Nacional",
    "outdoorRecreation": "Lazer Outdoor",
    "peoplePlaces": "Locais de Pessoas",
    "safetyHealth": "Segurança Saúde",
    "shapes": "Formas",
    "transportation": "Transportes",
    "symbolSize": "Tamanho de Símbolos",
    "color": "Cor",
    "alpha": "Alfa",
    "outlineColor": "Cor de Contorno",
    "outlineWidth": "Largura do Contorno",
    "style": "Estilo",
    "width": "Largura",
    "text": "Texto",
    "fontColor": "Cor da Letra",
    "fontSize": "Tamanho de letra",
    "transparency": "Transparência",
    "solid": "Sólido",
    "dash": "Traço",
    "dot": "Ponto",
    "dashDot": "Traço Ponto",
    "dashDotDot": "Traço Ponto Ponto"
  },
  "transparency": {
    "opaque": "Opaco",
    "transparent": "Transparente"
  },
  "rendererChooser": {
    "domain": "Domínio",
    "use": "Utilize",
    "singleSymbol": "Um Único Símbolo",
    "uniqueSymbol": "Símbolos Únicos",
    "color": "Cor",
    "size": "Tamanho",
    "toShow": "Para Exibir",
    "colors": "Cores",
    "classes": "Classes",
    "symbolSize": "Tamanho de Símbolos",
    "addValue": "Adicionar Valor",
    "setDefaultSymbol": "Definir Símbolo Padrão",
    "defaultSymbol": "Símbolo Padrão",
    "selectedSymbol": "Símbolo Selecionado",
    "value": "Valor",
    "label": "ã_Label___Ç",
    "range": "Intervalo"
  },
  "drawBox": {
    "point": "Ponto",
    "line": "Linha",
    "polyline": "Polilinha",
    "freehandPolyline": "Polilinha À Mão Livre",
    "triangle": "Triângulo",
    "extent": "Extensão",
    "circle": "Círculo",
    "ellipse": "Elipse",
    "polygon": "Polígono",
    "freehandPolygon": "Polígono À Mão Livre",
    "text": "Texto",
    "clear": "ã_Clear___Ç"
  },
  "popupConfig": {
    "title": "ã_Title___Ç",
    "add": "Adicionar",
    "fields": "Campos",
    "noField": "Sem Campo",
    "visibility": "Visível",
    "name": "ã_Name__Ç",
    "alias": "Nome Alternativo",
    "actions": "ã_Actions___Ç"
  },
  "includeButton": {
    "include": "Incluir"
  },
  "loadingShelter": {
    "loading": "A carregar"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Não foram encontrados serviços.",
    "unableConnectTo": "Impossível ligar a",
    "invalidUrlTip": "O URL que introduziu é inválido ou encontra-se inacessível."
  },
  "serviceBrowser": {
    "noGpFound": "Não foram encontrados serviços de geoprocessamento.",
    "unableConnectTo": "Impossível ligar a"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Não foram encontrados serviços MapServer ou FeatureServer",
    "unableConnectTo": "Impossível ligar a"
  },
  "basicServiceChooser": {
    "validate": "Validar",
    "example": "Exemplo",
    "set": "Definir"
  },
  "urlInput": {
    "invalidUrl": "Url inválido."
  },
  "urlComboBox": {
    "invalidUrl": "Url inválido."
  },
  "filterBuilder": {
    "addAnotherExpression": "Adicionar uma expressão de filtro",
    "addSet": "Adicionar uma expressão definida",
    "matchMsg": "Obter elementos na camada que correspondam a ${any_or_all} das expressões seguintes",
    "matchMsgSet": "${any_or_all} (d)as expressões seguintes neste conjunto são verdadeiras",
    "all": "Todas",
    "any": "Qualquer",
    "value": "Valor",
    "field": "ã_Field___Ç",
    "unique": "Único",
    "none": "Nenhum",
    "and": "e",
    "valueTooltip": "Introduzir valor",
    "fieldTooltip": "Escolher a partir de campo existente",
    "uniqueValueTooltip": "Escolher a partir de valores únicos no campo selecionado",
    "stringOperatorIs": "é",
    "stringOperatorIsNot": "não é",
    "stringOperatorStartsWith": "começa por",
    "stringOperatorEndsWith": "acaba em",
    "stringOperatorContains": "contém",
    "stringOperatorDoesNotContain": "não contém",
    "stringOperatorIsBlank": "está vazio",
    "stringOperatorIsNotBlank": "não está vazio",
    "dateOperatorIsOn": "é em",
    "dateOperatorIsNotOn": "não é em",
    "dateOperatorIsBefore": "é anterior a",
    "dateOperatorIsAfter": "é posterior a",
    "dateOperatorDays": "dias",
    "dateOperatorWeeks": "semanas",
    "dateOperatorMonths": "meses",
    "dateOperatorInTheLast": "nos(as) últimos(as)",
    "dateOperatorNotInTheLast": "não nos(as) últimos(as)",
    "dateOperatorIsBetween": "é entre",
    "dateOperatorIsNotBetween": "não é entre",
    "dateOperatorIsBlank": "está vazio",
    "dateOperatorIsNotBlank": "não está vazio",
    "numberOperatorIs": "é",
    "numberOperatorIsNot": "não é",
    "numberOperatorIsAtLeast": "é no mínimo",
    "numberOperatorIsLessThan": "é inferior a",
    "numberOperatorIsAtMost": "é no máximo",
    "numberOperatorIsGreaterThan": "é superior a",
    "numberOperatorIsBetween": "é entre",
    "numberOperatorIsNotBetween": "não é entre",
    "numberOperatorIsBlank": "está vazio",
    "numberOperatorIsNotBlank": "não está vazio",
    "string": "Texto",
    "number": "Número",
    "date": "Data",
    "askForValues": "Solicitar valores",
    "prompt": "Solicitação",
    "hint": "Dica",
    "error": {
      "invalidParams": "Parâmetros inválidos.",
      "invalidUrl": "Url inválido.",
      "noFilterFields": "A camada não tem quaisquer campos que possam ser utilizados para filtragem.",
      "invalidSQL": "Expressão sql inválida.",
      "cantParseSQL": "Impossível analisar a expressão sql."
    },
    "caseSensitive": "Diferencia Tamanho de Letra",
    "notSupportCaseSensitiveTip": "Os serviços alojados não suportam consultas que diferenciam maiúsculas de minúsculas."
  },
  "featureLayerSource": {
    "layer": "Camada",
    "browse": "Procurar",
    "selectFromMap": "Selecionar do Mapa",
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "inputLayerUrl": "Url da Camada de Entrada",
    "selectLayer": "Selecionar uma camada de elementos do mapa atual.",
    "chooseItem": "Escolher um item da camada de elementos.",
    "setServiceUrl": "Introduzir o URL do serviço de elementos ou serviço de mapa.",
    "selectFromOnline": "Adicionar de ArcGIS Online",
    "chooseLayer": "Escolha uma camada de elementos."
  },
  "queryableLayerSource": {
    "layer": "ã_Layer___Ç",
    "browse": "Procurar",
    "selectFromMap": "Selecionar do Mapa",
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "inputLayerUrl": "Url da Camada de Entrada",
    "selectLayer": "Seleccionar uma camada do mapa actual.",
    "chooseItem": "Escolher um item.",
    "setServiceUrl": "Introduza o URL do serviço.",
    "selectFromOnline": "Adicionar de ArcGIS Online",
    "chooseLayer": "Escolher uma camada."
  },
  "gpSource": {
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "selectFromOnline": "Adicionar de ArcGIS Online",
    "setServiceUrl": "Introduza o URL do serviço de geoprocessamento.",
    "chooseItem": "Escolha um item de serviço de geoprocessamento.",
    "chooseTask": "Escolha uma tarefa de geoprocessamento."
  },
  "itemSelector": {
    "map": "ã_Map__Ç",
    "selectWebMap": "Selecionar Mapa Web",
    "addMapFromOnlineOrPortal": "Encontre e adicione um mapa web na aplicação a partir dos recursos públicos ArcGIS Online ou do seu conteúdo privado, no ArcGIS Online ou no Portal.",
    "searchMapName": "Pesquisar por nome do mapa...",
    "searchNone": "Não conseguimos encontrar aquilo que procura. Por favor, tente outra pesquisa.",
    "groups": "Grupos",
    "noneGroups": "Sem grupos",
    "signInTip": "Por favor, inicie sessão para aceder ao seu conteúdo privado.",
    "signIn": "Iniciar sessão",
    "publicMap": "Público",
    "myOrganization": "A Organização",
    "myGroup": "Os Meus Grupos",
    "myContent": "O Meu Conteúdo",
    "count": "ã_Count___Ç",
    "fromPortal": "do Portal",
    "fromOnline": "de ArcGIS.com",
    "noneThumbnail": "Imagem Miniatura Indisponível",
    "owner": "proprietário",
    "signInTo": "Iniciar sessão em",
    "lastModified": "Última Modificação",
    "moreDetails": "Mais Detalhes"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "O serviço não suporta consultas."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Não existe uma camada apropriada disponível no mapa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mapas base",
    "titleLayers": "Camadas Operacionais",
    "labelLayer": "Nome da Camada",
    "itemZoomTo": "Efetuar zoom para",
    "itemTransparency": "Transparência",
    "itemTransparent": "Transparente",
    "itemOpaque": "Opaco",
    "itemMoveUp": "Mover para cima",
    "itemMoveDown": "Mover para baixo",
    "itemDesc": "Descrição",
    "itemDownload": "Descarregar",
    "itemToAttributeTable": "Abrir tabela de atributos"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: O navegador não suporta o API de leitor de ficheiros",
    "readError": "Falha ao ler o ficheiro.",
    "unknowError": "impossível completar operações",
    "invalidType": "Tipo de ficheiro inválido.",
    "cropImage": "ã_Crop Image____Ç",
    "exceed": "O tamanho do ficheiro não pode exceder 1024 KB",
    "enableFlash": "TODO: por favor, ative o flash.",
    "cropWaining": "Por favor escolha uma fotografa que tenha pelo menos ${width} x ${height} pixels.",
    "toolTip": "Para obter melhores resultados, a imagem deverá ter ${width} pixéis de largura por ${height} pixéis de altura. Outros tamanhos serão ajustados para caberem. Os formatos de imagem aceitáveis são: PNG, GIF e JPEG."
  },
  "simpleTable": {
    "moveUp": "Mover para cima",
    "moveDown": "Mover para baixo",
    "deleteRow": "Eliminar",
    "edit": "Editar"
  },
  "urlParams": {
    "invalidToken": "Token inválido",
    "validateTokenError": "Token inválido ou erro de Rede"
  },
  "exportTo": {
    "exportTo": "Exportar",
    "toCSV": "Exportar para ficheiro CSV",
    "toFeatureCollection": "Exportar para Coleção de Elementos",
    "toGeoJSON": "Exportar para GeoJSON"
  },
  "appState": {
    "title": "ã_App State____Ç",
    "restoreMap": "Clique para restaurar a extensão de mapa e camadas de visibilidade de onde saiu."
  },
  "featureActions": {
    "ZoomTo": "ã_Zoom to___Ç",
    "PanTo": "ã_Pan to___Ç",
    "Flash": "ã_Flash___Ç",
    "ShowPopup": "ã_Show Pop-up____Ç",
    "CreateLayer": "ã_Create Layer_____Ç",
    "ShowStatistics": "ã_Statistics_____Ç...",
    "ClearSelection": "ã_Clear Selection______Ç",
    "ExportToCSV": "ã_Export to CSV file______Ç",
    "ExportToFeatureCollection": "ã_Export to Feature Collection_________Ç",
    "ExportToGeoJSON": "ã_Export to GeoJSON______Ç"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ã_Related layer_____Ç",
    "selectedFeatures": "ã_Selected features______Ç",
    "drawShapesTip": "ã_Draw shapes to select features__________Ç",
    "pleaseDrawShapesTip": "ã_Please draw shapes to select features____________Ç",
    "allFeaturesTip": "ã_All features in the layer_________Ç",
    "selectFeaturesOrDrawShapesTip": "ã_Please use selected features in this layer or draw shapes on map to limit features__________________________Ç."
  },
  "searchDistance": {
    "applySearchDistance": "ã_Apply a search distance________Ç",
    "applySearchDistanceToFeatures": "ã_Apply a search distance to selected features______________Ç"
  },
  "units": {
    "miles": "ã_Miles___Ç",
    "kilometers": "ã_Kilometers____Ç",
    "feet": "ã_Feet__Ç",
    "meters": "ã_Meters___Ç",
    "yards": "ã_Yards___Ç",
    "nauticalMiles": "ã_Nautical Miles_____Ç"
  },
  "featureSetChooser": {
    "select": "ã_Select___Ç",
    "dragBox": "ã_Drag__Ç",
    "dragMouse": "ã_Darg the mouse_____Ç",
    "selectByRectangle": "ã_Select By Rectangle_______Ç",
    "selectFeaturesTip": "ã_Select features by dragging box around them on map________________Ç",
    "newSelectionTip": "ã_Create a new selection________Ç",
    "addSelectionTip": "ã_Add to the current selection_________Ç",
    "removeSelectionTip": "ã_Remove from the current selection___________Ç",
    "selectFromCurrentSelectionTip": "ã_Select from the current selection___________Ç",
    "unselectAllSelectionTip": "ã_Unselect all currently selected features_____________Ç"
  },
  "widgetManager": {
    "createWidgetError": "ã_Create widget error_______Ç",
    "createWidgetSettingPageError": "ã_Create widget setting page error___________Ç",
    "loadWidgetResourceError": "ã_Load widget resouce error_________Ç"
  },
  "shareOptions": {
    "shareMap": "ã_Choose who can view this app_________Ç",
    "shareMapTips": "ã_Your map is currentlt shared with these people_______________Ç",
    "everyone": "ã_everyone___Ç",
    "theseGroups": "ã_theseGroups____Ç"
  },
  "shareLink": {
    "email": "ã_email___Ç",
    "shareEmail": "ã_Email___Ç",
    "facebook": "ã_facebook___Ç",
    "shareFacebook": "ã_Facebook___Ç",
    "twitter": "ã_twitter___Ç",
    "shareTwitter": "ã_Twitter___Ç",
    "googlePlus": "ã_googlePlus____Ç",
    "shareGooglePlus": "ã_GooglePlus____Ç",
    "EmbedTips": "ã_Embed this scene in a website__________Ç",
    "shareEmailTxt1": "ã_Have a look at this Web Scene__________Ç:",
    "shareEmailTxt2": "ã_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________Ç.",
    "smallSize": "ã_Small___Ç",
    "mediumSize": "ã_Medium___Ç",
    "largeSize": "ã_Large___Ç",
    "customSize": "ã_Custom___Ç",
    "embed": "ã_Embed this scene in a website__________Ç",
    "more": "ã_Embed Options_____Ç",
    "changeShareSettings": "ã_Change Share Settings_______Ç",
    "shareLinkText": "ã_Choose who can view Copy________Ç",
    "linkOptions": "ã_Link Options_____Ç",
    "linkOptionsUrlParameters": "ã_Select URL parameters included in the link______________Ç",
    "currentMapExtent": "ã_Current map extent______Ç",
    "chooseCenterWithLevel": "ã_Click the map to define the center of the map with scale level____________________Ç",
    "chooseCenterWithScale": "ã_Click the map to define the center of the map with map scale___________________Ç",
    "findLocation": "ã_Find the location or feature and zoom to it______________Ç",
    "findLocation_inputPlaceholder": "ã_Your place or feature_______Ç",
    "queryFeature": "ã_Query a feature and zoom to it__________Ç",
    "addMarker": "ã_Add a marker on the map________Ç",
    "addMarker_titlePlaceholder": "ã_Title of the marker pop-up_________Ç",
    "addMarker_symbolURL": "ã_Marker symbol URL______Ç",
    "addMarker_label": "ã_Marker label_____Ç",
    "overwirteMobileLayout": "ã_Overwrite default mobile layout__________Ç",
    "language": "ã_Set the app language_______Ç",
    "auth": "ã_Authenticate a user automatically___________Ç",
    "linkPreview": "ã_Link Preview_____Ç",
    "useShortenLink": "ã_Short Link____Ç",
    "shareMapUrlExtent": "ã_shareMapUrlExtent______Ç"
  },
  "webSceneLoader": {
    "webglSupportTip": "ã_3D web apps aren't supported in your browser_______________Ç."
  }
});