define({
	addAChartSource: "Å_Add a Chart Source_ö",
	sourceLabel: "Å_Source label_ö",
	labelField: "Å_Label field_ö",
	actions: "Å_Actions_ö",
	hightLightColor: "Å_Highlight color_ö",
	urlChartSource: "Å_URL Chart Source_ö",
	layerChartSource: "Å_Layer Chart Source_ö",
	searchUrl: "Å_Search URL_ö",
	browse: "Å_Browse_ö",
	layers: "Å_Layers_ö",
	availableFields: "Å_Available Fields_ö",
	charts: "Å_Charts_ö",
	chartField: "Å_Chart field_ö",
	description: "Å_Description_ö",
	title: "Å_Title_ö",
	type: "Å_Type_ö",
	cancel: "Å_Cancel_ö",
	addChartSource: "Å_Add Chart Source_ö",
	updateChartSource: "Å_Update Chart Source_ö",
	chartSources: "Å_Chart Sources_ö",
	chartSource: "Å_Chart Source_ö",
	general: "Å_General_ö"
});