define({
  "common": {
    "apply": "á_Apply___Ó",
    "ok": "Aceptar",
    "cancel": "Cancelar",
    "yes": "á_Yes__Ó",
    "no": "á_No__Ó",
    "next": "Siguiente",
    "back": "Atrás",
    "selected": "á_selected___Ó",
    "name": "Nombre",
    "usage": "á_Usage___Ó",
    "settings": "á_Settings___Ó",
    "home": "á_Home__Ó",
    "link": "á_Link__Ó",
    "messages": "á_Messages___Ó",
    "outputs": "á_Outputs___Ó",
    "title": "Título",
    "thumbnail": "á_Thumbnail____Ó",
    "url": "á_URL__Ó",
    "actions": "Acciones",
    "layer": "Capa",
    "action": "á_Action___Ó",
    "input": "á_Input___Ó",
    "output": "á_Output___Ó",
    "type": "á_Type__Ó",
    "required": "á_Required___Ó",
    "options": "á_Options___Ó",
    "label": "Etiqueta",
    "tooltip": "á_Tooltip___Ó",
    "visible": "á_Visible___Ó",
    "symbol": "á_Symbol___Ó",
    "popup": "á_Popup___Ó",
    "upload": "á_Upload___Ó",
    "execute": "á_Execute___Ó",
    "help": "á_Help__Ó",
    "executing": "á_Executing____Ó",
    "clear": "Borrar",
    "error": "á_Error___Ó",
    "zoomTo": "Acercar",
    "attribute": "á_Attribute____Ó",
    "exports": "á_Export___Ó",
    "check": "á_Check___Ó",
    "save": "á_Save__Ó",
    "close": "á_Close___Ó",
    "deleteText": "á_Delete___Ó",
    "map": "Mapa",
    "scene": "á_Scene___Ó",
    "reset": "á_Reset___Ó",
    "icon": "á_Icon__Ó",
    "share": "á_Share___Ó"
  },
  "errorCode": "Código",
  "errorMessage": "Mensaje",
  "errorDetail": "Detalle",
  "widgetPlaceholderTooltip": "Para configurarlo, ve a Widgets y haz clic en el marcador de posición correspondiente",
  "fieldStatistics": {
    "statistics": "á_Statistics____Ó",
    "field": "Campo",
    "count": "á_Number of Values______Ó",
    "sum": "á_Sum of Values_____Ó",
    "min": "á_Minimum___Ó",
    "max": "á_Maximum___Ó",
    "ave": "á_Average___Ó",
    "stddev": "á_Standard Deviation______Ó"
  },
  "symbolChooser": {
    "preview": "Presentación preliminar",
    "basic": "Básico",
    "arrows": "Flechas",
    "business": "Empresa",
    "cartographic": "Cartográfico",
    "nationalParkService": "Servicio de Parque Nacional",
    "outdoorRecreation": "Entretenimiento al aire libre",
    "peoplePlaces": "Lugares y personas",
    "safetyHealth": "Seguridad y salud públicas",
    "shapes": "Formas",
    "transportation": "Transporte",
    "symbolSize": "Tamaño de símbolo",
    "color": "Color",
    "alpha": "Alfa",
    "outlineColor": "Color del contorno",
    "outlineWidth": "Ancho de contorno",
    "style": "Estilo",
    "width": "Ancho",
    "text": "Texto",
    "fontColor": "Color de fuente",
    "fontSize": "Tamaño de fuente",
    "transparency": "Transparencia",
    "solid": "Continuo",
    "dash": "Guion",
    "dot": "Punto",
    "dashDot": "Guion Punto",
    "dashDotDot": "Guion Punto Punto"
  },
  "transparency": {
    "opaque": "Opaco",
    "transparent": "Transparente"
  },
  "rendererChooser": {
    "domain": "Dominio",
    "use": "Usar",
    "singleSymbol": "Un símbolo único",
    "uniqueSymbol": "Símbolos únicos",
    "color": "Color",
    "size": "Tamaño",
    "toShow": "Mostrar",
    "colors": "Colores",
    "classes": "Clases",
    "symbolSize": "Tamaño de símbolo",
    "addValue": "Agregar valor",
    "setDefaultSymbol": "Establecer símbolo predeterminado",
    "defaultSymbol": "Símbolo predeterminado",
    "selectedSymbol": "Símbolo seleccionado",
    "value": "Valor",
    "label": "á_Label___Ó",
    "range": "Alcance"
  },
  "drawBox": {
    "point": "Punto",
    "line": "Línea",
    "polyline": "Polilínea",
    "freehandPolyline": "Polilínea a mano alzada",
    "triangle": "Triángulo",
    "extent": "Extensión",
    "circle": "Círculo",
    "ellipse": "Elipse",
    "polygon": "Polígono",
    "freehandPolygon": "Polígono a mano alzada",
    "text": "Texto",
    "clear": "á_Clear___Ó"
  },
  "popupConfig": {
    "title": "á_Title___Ó",
    "add": "Agregar",
    "fields": "Campos",
    "noField": "Sin campo",
    "visibility": "Visible",
    "name": "á_Name__Ó",
    "alias": "Alias",
    "actions": "á_Actions___Ó"
  },
  "includeButton": {
    "include": "Incluir"
  },
  "loadingShelter": {
    "loading": "Cargando"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Ningún servicio encontrado.",
    "unableConnectTo": "No se puede conectar a",
    "invalidUrlTip": "La URL que has introducido no es válida o no se puede acceder a ella."
  },
  "serviceBrowser": {
    "noGpFound": "Ningún servicio de geoprocesamiento encontrado.",
    "unableConnectTo": "No se puede conectar a"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Ningún servicio de mapas o entidades encontrado",
    "unableConnectTo": "No se puede conectar a"
  },
  "basicServiceChooser": {
    "validate": "Validar",
    "example": "Ejemplo",
    "set": "Establecer"
  },
  "urlInput": {
    "invalidUrl": "URL no válida."
  },
  "urlComboBox": {
    "invalidUrl": "URL no válida."
  },
  "filterBuilder": {
    "addAnotherExpression": "Agregar una expresión de filtro",
    "addSet": "Agregar un conjunto de expresiones",
    "matchMsg": "Obtener entidades de la capa que coincidan con ${any_or_all} de las expresiones siguientes",
    "matchMsgSet": "${any_or_all} de las expresiones siguientes de este conjunto son verdaderas",
    "all": "Todo",
    "any": "Cualquiera de",
    "value": "Valor",
    "field": "á_Field___Ó",
    "unique": "Único",
    "none": "Ninguno",
    "and": "y",
    "valueTooltip": "Introduce un valor",
    "fieldTooltip": "Seleccionar en un campo existente",
    "uniqueValueTooltip": "Seleccionar entre los valores únicos del campo seleccionado",
    "stringOperatorIs": "es",
    "stringOperatorIsNot": "no es",
    "stringOperatorStartsWith": "comienza por",
    "stringOperatorEndsWith": "termina en",
    "stringOperatorContains": "contiene",
    "stringOperatorDoesNotContain": "no contiene",
    "stringOperatorIsBlank": "está vacío",
    "stringOperatorIsNotBlank": "no está vacío",
    "dateOperatorIsOn": "es el",
    "dateOperatorIsNotOn": "no es el",
    "dateOperatorIsBefore": "es anterior a",
    "dateOperatorIsAfter": "es posterior a",
    "dateOperatorDays": "días",
    "dateOperatorWeeks": "semanas",
    "dateOperatorMonths": "meses",
    "dateOperatorInTheLast": "es el último",
    "dateOperatorNotInTheLast": "no es el último",
    "dateOperatorIsBetween": "está entre",
    "dateOperatorIsNotBetween": "no está entre",
    "dateOperatorIsBlank": "está vacío",
    "dateOperatorIsNotBlank": "no está vacío",
    "numberOperatorIs": "es",
    "numberOperatorIsNot": "no es",
    "numberOperatorIsAtLeast": "es como mínimo",
    "numberOperatorIsLessThan": "es menos que",
    "numberOperatorIsAtMost": "es como máximo",
    "numberOperatorIsGreaterThan": "es mayor que",
    "numberOperatorIsBetween": "está entre",
    "numberOperatorIsNotBetween": "no está entre",
    "numberOperatorIsBlank": "está vacío",
    "numberOperatorIsNotBlank": "no está vacío",
    "string": "Cadena de caracteres",
    "number": "Número",
    "date": "Fecha",
    "askForValues": "Pedir valores",
    "prompt": "Indicación",
    "hint": "Sugerencia",
    "error": {
      "invalidParams": "Parámetros no válidos.",
      "invalidUrl": "URL no válida.",
      "noFilterFields": "La capa no tiene ningún campo que se pueda utilizar para el filtro.",
      "invalidSQL": "Expresión SQL no válida.",
      "cantParseSQL": "No se puede analizar la expresión SQL."
    },
    "caseSensitive": "Distinguir mayúsculas de minúsculas",
    "notSupportCaseSensitiveTip": "Los servicios alojados no admiten consultas que distingan mayúsculas de minúsculas."
  },
  "featureLayerSource": {
    "layer": "Capa",
    "browse": "Examinar",
    "selectFromMap": "Seleccionar en el mapa",
    "selectFromPortal": "Agregar desde Portal for ArcGIS",
    "addServiceUrl": "Agregar URL de servicio",
    "inputLayerUrl": "Introducir URL de capa",
    "selectLayer": "Selecciona una capa de entidades en el mapa actual.",
    "chooseItem": "Elige un elemento de capa de entidades.",
    "setServiceUrl": "Introduce la dirección URL del servicio de entidades o servicio de mapa.",
    "selectFromOnline": "Agregar desde ArcGIS Online",
    "chooseLayer": "Elige una capa de entidades."
  },
  "queryableLayerSource": {
    "layer": "á_Layer___Ó",
    "browse": "Examinar",
    "selectFromMap": "Seleccionar en el mapa",
    "selectFromPortal": "Agregar desde Portal for ArcGIS",
    "addServiceUrl": "Agregar URL de servicio",
    "inputLayerUrl": "Introducir URL de capa",
    "selectLayer": "Selecciona una capa del mapa actual.",
    "chooseItem": "Selecciona un elemento.",
    "setServiceUrl": "Introduce la dirección URL del servicio.",
    "selectFromOnline": "Agregar desde ArcGIS Online",
    "chooseLayer": "Elegir una capa."
  },
  "gpSource": {
    "selectFromPortal": "Agregar desde Portal for ArcGIS",
    "addServiceUrl": "Agregar URL de servicio",
    "selectFromOnline": "Agregar desde ArcGIS Online",
    "setServiceUrl": "Introduce la URL del servicio de geoprocesamiento.",
    "chooseItem": "Elige un elemento de servicio de geoprocesamiento.",
    "chooseTask": "Elige una tarea de geoprocesamiento."
  },
  "itemSelector": {
    "map": "á_Map__Ó",
    "selectWebMap": "Elegir mapa web",
    "addMapFromOnlineOrPortal": "Busca y agrega un mapa web en la aplicación desde los recursos públicos de ArcGIS Online o tu contenido privado en ArcGIS Online o Portal.",
    "searchMapName": "Buscar por nombre de mapa...",
    "searchNone": "No hemos podido encontrar lo que buscas. Inténtalo de nuevo.",
    "groups": "Grupos",
    "noneGroups": "No hay grupos",
    "signInTip": "Tu inicio de sesión ha expirado, actualiza el navegador para iniciar sesión de nuevo en tu portal.",
    "signIn": "Iniciar sesión",
    "publicMap": "Público",
    "myOrganization": "Mi organización",
    "myGroup": "Mis grupos",
    "myContent": "Mi contenido",
    "count": "á_Count___Ó",
    "fromPortal": "desde Portal",
    "fromOnline": "desde ArcGIS.com",
    "noneThumbnail": "Miniatura no disponible",
    "owner": "propietario",
    "signInTo": "Iniciar sesión en",
    "lastModified": "Última modificación",
    "moreDetails": "Más detalles"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Este servicio no admite consultas."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "No hay ninguna capa adecuada disponible en el mapa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mapas base",
    "titleLayers": "Capas operativas",
    "labelLayer": "Nombre de capa",
    "itemZoomTo": "Acercar a",
    "itemTransparency": "Transparencia",
    "itemTransparent": "Transparente",
    "itemOpaque": "Opaco",
    "itemMoveUp": "Mover hacia arriba",
    "itemMoveDown": "Mover hacia abajo",
    "itemDesc": "Descripción",
    "itemDownload": "Descargar",
    "itemToAttributeTable": "Abrir tabla de atributos"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TAREA PENDIENTE: el navegador no admite la API del lector de archivos",
    "readError": "Error al leer el archivo.",
    "unknowError": "no se pueden completar las operaciones",
    "invalidType": "Tipo de archivo no válido.",
    "cropImage": "á_Crop Image____Ó",
    "exceed": "El tamaño de archivo no puede sobrepasar los 1024 KB",
    "enableFlash": "TAREA PENDIENTE: habilita flash.",
    "cropWaining": "Selecciona una foto que tenga por lo menos ${width} x ${height} píxeles.",
    "toolTip": "Para obtener el mejor resultado, la imagen debe tener ${width} píxeles de ancho y ${height} píxeles de alto. El resto de tamaños se adaptará a este tamaño. Los formatos de imagen válidos son: PNG, GIF y JPEG."
  },
  "simpleTable": {
    "moveUp": "Mover hacia arriba",
    "moveDown": "Mover hacia abajo",
    "deleteRow": "Eliminar",
    "edit": "Editar"
  },
  "urlParams": {
    "invalidToken": "Token no válido",
    "validateTokenError": "Token no válido o error de red"
  },
  "exportTo": {
    "exportTo": "Exportar",
    "toCSV": "Exportar a archivo CSV",
    "toFeatureCollection": "Exportar a un conjunto de entidades",
    "toGeoJSON": "Exportar a GeoJSON"
  },
  "appState": {
    "title": "á_App State____Ó",
    "restoreMap": "Haz clic para restaurar la extensión de mapa y la visibilidad de las capas donde lo dejaste."
  },
  "featureActions": {
    "ZoomTo": "á_Zoom to___Ó",
    "PanTo": "á_Pan to___Ó",
    "Flash": "á_Flash___Ó",
    "ShowPopup": "á_Show Pop-up____Ó",
    "CreateLayer": "á_Create Layer_____Ó",
    "ShowStatistics": "á_Statistics_____Ó...",
    "ClearSelection": "á_Clear Selection______Ó",
    "ExportToCSV": "á_Export to CSV file______Ó",
    "ExportToFeatureCollection": "á_Export to Feature Collection_________Ó",
    "ExportToGeoJSON": "á_Export to GeoJSON______Ó"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "á_Related layer_____Ó",
    "selectedFeatures": "á_Selected features______Ó",
    "drawShapesTip": "á_Draw shapes to select features__________Ó",
    "pleaseDrawShapesTip": "á_Please draw shapes to select features____________Ó",
    "allFeaturesTip": "á_All features in the layer_________Ó",
    "selectFeaturesOrDrawShapesTip": "á_Please use selected features in this layer or draw shapes on map to limit features__________________________Ó."
  },
  "searchDistance": {
    "applySearchDistance": "á_Apply a search distance________Ó",
    "applySearchDistanceToFeatures": "á_Apply a search distance to selected features______________Ó"
  },
  "units": {
    "miles": "á_Miles___Ó",
    "kilometers": "á_Kilometers____Ó",
    "feet": "á_Feet__Ó",
    "meters": "á_Meters___Ó",
    "yards": "á_Yards___Ó",
    "nauticalMiles": "á_Nautical Miles_____Ó"
  },
  "featureSetChooser": {
    "select": "á_Select___Ó",
    "dragBox": "á_Drag__Ó",
    "dragMouse": "á_Darg the mouse_____Ó",
    "selectByRectangle": "á_Select By Rectangle_______Ó",
    "selectFeaturesTip": "á_Select features by dragging box around them on map________________Ó",
    "newSelectionTip": "á_Create a new selection________Ó",
    "addSelectionTip": "á_Add to the current selection_________Ó",
    "removeSelectionTip": "á_Remove from the current selection___________Ó",
    "selectFromCurrentSelectionTip": "á_Select from the current selection___________Ó",
    "unselectAllSelectionTip": "á_Unselect all currently selected features_____________Ó"
  },
  "widgetManager": {
    "createWidgetError": "á_Create widget error_______Ó",
    "createWidgetSettingPageError": "á_Create widget setting page error___________Ó",
    "loadWidgetResourceError": "á_Load widget resouce error_________Ó"
  },
  "shareOptions": {
    "shareMap": "á_Choose who can view this app_________Ó",
    "shareMapTips": "á_Your map is currentlt shared with these people_______________Ó",
    "everyone": "á_everyone___Ó",
    "theseGroups": "á_theseGroups____Ó"
  },
  "shareLink": {
    "email": "á_email___Ó",
    "shareEmail": "á_Email___Ó",
    "facebook": "á_facebook___Ó",
    "shareFacebook": "á_Facebook___Ó",
    "twitter": "á_twitter___Ó",
    "shareTwitter": "á_Twitter___Ó",
    "googlePlus": "á_googlePlus____Ó",
    "shareGooglePlus": "á_GooglePlus____Ó",
    "EmbedTips": "á_Embed this scene in a website__________Ó",
    "shareEmailTxt1": "á_Have a look at this Web Scene__________Ó:",
    "shareEmailTxt2": "á_You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free__________________________________________Ó.",
    "smallSize": "á_Small___Ó",
    "mediumSize": "á_Medium___Ó",
    "largeSize": "á_Large___Ó",
    "customSize": "á_Custom___Ó",
    "embed": "á_Embed this scene in a website__________Ó",
    "more": "á_Embed Options_____Ó",
    "changeShareSettings": "á_Change Share Settings_______Ó",
    "shareLinkText": "á_Choose who can view Copy________Ó",
    "linkOptions": "á_Link Options_____Ó",
    "linkOptionsUrlParameters": "á_Select URL parameters included in the link______________Ó",
    "currentMapExtent": "á_Current map extent______Ó",
    "chooseCenterWithLevel": "á_Click the map to define the center of the map with scale level____________________Ó",
    "chooseCenterWithScale": "á_Click the map to define the center of the map with map scale___________________Ó",
    "findLocation": "á_Find the location or feature and zoom to it______________Ó",
    "findLocation_inputPlaceholder": "á_Your place or feature_______Ó",
    "queryFeature": "á_Query a feature and zoom to it__________Ó",
    "addMarker": "á_Add a marker on the map________Ó",
    "addMarker_titlePlaceholder": "á_Title of the marker pop-up_________Ó",
    "addMarker_symbolURL": "á_Marker symbol URL______Ó",
    "addMarker_label": "á_Marker label_____Ó",
    "overwirteMobileLayout": "á_Overwrite default mobile layout__________Ó",
    "language": "á_Set the app language_______Ó",
    "auth": "á_Authenticate a user automatically___________Ó",
    "linkPreview": "á_Link Preview_____Ó",
    "useShortenLink": "á_Short Link____Ó",
    "shareMapUrlExtent": "á_shareMapUrlExtent______Ó"
  },
  "webSceneLoader": {
    "webglSupportTip": "á_3D web apps aren't supported in your browser_______________Ó."
  }
});