define({
	addAChartSource: "Š_Add a Chart Source_ä",
	sourceLabel: "Š_Source label_ä",
	labelField: "Š_Label field_ä",
	actions: "Š_Actions_ä",
	hightLightColor: "Š_Highlight color_ä",
	urlChartSource: "Š_URL Chart Source_ä",
	layerChartSource: "Š_Layer Chart Source_ä",
	searchUrl: "Š_Search URL_ä",
	browse: "Š_Browse_ä",
	layers: "Š_Layers_ä",
	availableFields: "Š_Available Fields_ä",
	charts: "Š_Charts_ä",
	chartField: "Š_Chart field_ä",
	description: "Š_Description_ä",
	title: "Š_Title_ä",
	type: "Š_Type_ä",
	cancel: "Š_Cancel_ä",
	addChartSource: "Š_Add Chart Source_ä",
	updateChartSource: "Š_Update Chart Source_ä",
	chartSources: "Š_Chart Sources_ä",
	chartSource: "Š_Chart Source_ä",
	general: "Š_General_ä"
});