define({
	addAChartSource: "é_Add a Chart Source_È",
	sourceLabel: "é_Source label_È",
	labelField: "é_Label field_È",
	actions: "é_Actions_È",
	hightLightColor: "é_Highlight color_È",
	urlChartSource: "é_URL Chart Source_È",
	layerChartSource: "é_Layer Chart Source_È",
	searchUrl: "é_Search URL_È",
	browse: "é_Browse_È",
	layers: "é_Layers_È",
	availableFields: "é_Available Fields_È",
	charts: "é_Charts_È",
	chartField: "é_Chart field_È",
	description: "é_Description_È",
	title: "é_Title_È",
	type: "é_Type_È",
	cancel: "é_Cancel_È",
	addChartSource: "é_Add Chart Source_È",
	updateChartSource: "é_Update Chart Source_È",
	chartSources: "é_Chart Sources_È",
	chartSource: "é_Chart Source_È",
	general: "é_General_È"
});