define({
  "_widgetLabel": "Πίνακας Περιγραφικών Γνωρισμάτων",
  "_featureAction_ShowRelatedRecords": "Đ_Show Related Records_______ớ",
  "_featureAction_ViewInTable": "Đ_View in Attribute Table________ớ",
  "ok": "ΟΚ",
  "cancel": "Ακύρωση",
  "unsupportQueryWarning": "Το θεματικό επίπεδο πρέπει να υποστηρίζει τη λειτουργία δημιουργίας ερωτημάτων ώστε να εμφανίζεται στο widget Πίνακας Περιγραφικών Γνωρισμάτων. Βεβαιωθείτε ότι η δυνατότητα δημιουργίας ερωτημάτων είναι ενεργοποιημένη στην υπηρεσία.",
  "exportMessage": "Εξαγωγή δεδομένων σε αρχείο CSV;",
  "exportFiles": "Εξαγωγή σε CSV",
  "exportSelected": "Εξαγωγή επιλεγμένων σε CSV",
  "exportAll": "Εξαγωγή όλων σε CSV",
  "options": "Επιλογές",
  "zoomto": "Εστίαση",
  "highlight": "Επισήμανση γραφικών",
  "selectAll": "Επιλογή εγγραφών σε όλες τις σελίδες",
  "selectPage": "Επιλογή εγγραφών στην τρέχουσα σελίδα",
  "clearSelection": "Απαλοιφή επιλογής",
  "filter": "Φίλτρο",
  "setFilterTip": "Ορίστε σωστά το φίλτρο.",
  "noFilterTip": "Αν δεν καθοριστεί έκφραση για το φίλτρο, αυτό το ερώτημα θα συμπεριλάβει σε λίστα όλα τα στοιχεία από την καθορισμένη προέλευση δεδομένων.",
  "filterByExtent": "Φιλτράρισμα με την έκταση του χάρτη",
  "showSelectedRecords": "Εμφάνιση επιλεγμένων εγγραφών",
  "showAllRecords": "Εμφάνιση όλων των εγγραφών",
  "showRelatedRecords": "Εμφάνιση συσχετισμένων εγγραφών",
  "noRelatedRecords": "Δεν βρέθηκαν σχετικές εγγραφές",
  "refresh": "Ανανέωση",
  "features": "στοιχεία",
  "selected": "επιλεγμένα",
  "transparent": "Διαφάνεια",
  "indicate": "Εντοπισμός επιλογής",
  "columns": "Εμφάνιση/Απόκρυψη στηλών",
  "selectionSymbol": "Σύμβολο επιλογής",
  "closeMessage": "Απόκρυψη πίνακα (ανοίξτε τον ξανά από κάτω)",
  "dataNotAvailable": "Τα δεδομένα δεν είναι διαθέσιμα!<br>Κάντε κλικ στο κουμπί [Ανανέωση] και δοκιμάστε ξανά.",
  "openTableTip": "Άνοιγμα Πίνακα Περιγραφικών Γνωρισμάτων",
  "closeTableTip": "Απόκρυψη Πίνακα Περιγραφικών Γνωρισμάτων",
  "sortAsc": "Đ_Sort Ascending_____ớ",
  "sortDes": "Đ_Sort Descending______ớ",
  "statistics": "Đ_Statistics____ớ"
});