define({
	addAChartSource: "Ĳ_Add a Chart Source_ä",
	sourceLabel: "Ĳ_Source label_ä",
	labelField: "Ĳ_Label field_ä",
	actions: "Ĳ_Actions_ä",
	hightLightColor: "Ĳ_Highlight color_ä",
	urlChartSource: "Ĳ_URL Chart Source_ä",
	layerChartSource: "Ĳ_Layer Chart Source_ä",
	searchUrl: "Ĳ_Search URL_ä",
	browse: "Ĳ_Browse_ä",
	layers: "Ĳ_Layers_ä",
	availableFields: "Ĳ_Available Fields_ä",
	charts: "Ĳ_Charts_ä",
	chartField: "Ĳ_Chart field_ä",
	description: "Ĳ_Description_ä",
	title: "Ĳ_Title_ä",
	type: "Ĳ_Type_ä",
	cancel: "Ĳ_Cancel_ä",
	addChartSource: "Ĳ_Add Chart Source_ä",
	updateChartSource: "Ĳ_Update Chart Source_ä",
	chartSources: "Ĳ_Chart Sources_ä",
	chartSource: "Ĳ_Chart Source_ä",
	general: "Ĳ_General_ä"
});